### ISSUE TITLE
incomplete or wrong instruction

### ISSUE THREAD

**Issue by ferdiga** [OCA/OpenUpgrade#100]
https://doc.therp.nl/openupgrade/analyse.html says

---

On both instances, install a database without demo data and install the openupgrade_records module, which is included in the OpenUpgrade server distribution.

---

this does not work on v7 (and others) as 
server/openerp/openupgrade is missing and is not part of the module 

after manually copying this directory the module loads but does not generate records

solution
either move directory openupgrade to module openupgrade_records
(OR update documentation - not so good solution)

OR I miss understand
Set up two OpenUpgrade servers of subsequent OpenERP releases
- where do I get the OpenUpgrade Server for 7.0 ???
  I used a normal v7 server - as the OpenUpgrade Server has the v8 modules.
  I used https://github.com/OpenUpgrade/OpenUpgrade branch 8

**Comment by ferdiga** [comment]
is this the v7 server?
https://code.launchpad.net/~openupgrade-committers/openupgrade-server/7.0-update_module_coverage

**Comment by StefanRijnhart** [comment]
You can find v7 here: lp:openupgrade-server/7.0
