### ISSUE TITLE
Loose crm.stage migrating from v9 to v10

### ISSUE THREAD

**Issue by rafaelbn** [OCA/OpenUpgrade#1031]
Impacted versions: 9.0

Steps to reproduce:

In v9 you have crm.stage common to all Sales team
In v10 you have to define a crm.stage per sale team

Current behavior:

After migration some sales team have no stages and crm.leads have loosen them

Expected behavior:

After migration all crm.leads have the same stage as they have in v10

cc @tecnativa

**Comment by pedrobaeza** [comment]
Solved in #1033
