### ISSUE TITLE
[9.0] [stock] Migrate Pack Operation

### ISSUE THREAD

**Issue by mbaena** [OCA/OpenUpgrade#1034]
Should stock_pack_operation.product_qty be used instead of quant.qty?
https://github.com/mbaena/OpenUpgrade/commit/b807e0641235e3e91f469d868f63598a7590f8ba

**Comment by pedrobaeza** [comment]
What is the rationale behind this change? Have you found any problem with current form?

**Comment by mbaena** [comment]
stock.pack.operation.lot defines lots for product_qty in stock.pack.operation. The problem with current form: 2 stock.pack.operation and 2 stock_quant with the same lot will produce a cartesian product.

**Comment by pedrobaeza** [comment]
But that table doesn't exist on v8, so it's not possible to use it.

**Comment by mbaena** [comment]
Yes, lots are defined in stock.pack_operation in 8.0. But in 9.0 are refactored to stock.pack.operation.lot (without relation to stock_quant).

**Comment by pedrobaeza** [comment]
It's better that you propose the PR and then we talk there, as I'm seeing a different thing in the commit than what we are talking now. I close this meanwhile.
