### ISSUE TITLE
[10.0]some hr.Analytic.timesheet disappear

### ISSUE THREAD

**Issue by flotho** [OCA/OpenUpgrade#1036]
Hi,

I've migrated form 8.0 to 9.0 recently and I have some timesheet activities that has disappeared.
When going from the project => timesheet, only a few part of the time tracked are available.

Hopefully, everything keep tracked in account.analytic.line but what ccould be the reason why some hr.analytic move lines has disappeared?

**Comment by flotho** [comment]
Found,
Some analytic lines haven't got any project set even if the analytic account is linked to a project.
Maybe this PR https://github.com/OCA/OpenUpgrade/pull/944 could be improved in the method : https://github.com/Tecnativa/OpenUpgrade/blob/81302a8c04545d3240c673e1790c60dd705fa5c7/addons/hr_timesheet/migrations/10.0.1.0/post-migration.py#L45
Please consider that a timesheet could be linked to nothing except projetc. You could have neither task nor issue, just project informed.
regards

**Comment by pedrobaeza** [comment]
A project always have a linked analytic account, so the other seems to be incorrect data.

**Comment by pedrobaeza** [comment]
Closing as there's no answer
