### ISSUE TITLE
[9.0] Convert account.voucher to account.payment.

### ISSUE THREAD

**Issue by mvaled** [OCA/OpenUpgrade#1043]
Odoo 9 introduces a new model `account.payment`.  In Odoo 8, `account.voucher` allowed the user create the payment.  In fact, the button 'Register payment' created an `account.voucher`.  Since Odoo 9 it creates a `account.payment`.

The behavior of Odoo 9's `account.voucher` is more related to that of the invoices.  If you create a `account.voucher` (Sales receipt) with 'Pay later', it creates a journal entry equivalent to that of creating an invoice:

```
Account                    Debit                 Credit
--------------------       ----------------      --------------
Receivable                  $$$$
Sales                                                   $$$$
```

If the receipt is created with type 'Pay directly' the Receivable account is replaced by the Bank, but it still a sale.

So, I think we should *not* convert Odoo 8 vouchers to Odoo 9 voucher, but to payments.

cc: @hbrunn

**Comment by mvaled** [comment]
Hi @hbrunn,

I would like you to comment on this issue.

Best regards,
Manuel.

**Comment by JordiBForgeFlow** [comment]
Manuel, this is the behaviour of v8 to v9. Not sure why you're not seeing
this. We have made migrations where the vouchers are migrated into payments
successfully.

Perhaps you can be more specific on your use case.

**Comment by JordiBForgeFlow** [comment]
See
https://github.com/OCA/OpenUpgrade/blob/9.0/addons/account_voucher/migrations/9.0.1.0/post-migration.py

**Comment by mvaled** [comment]
@jbeficent You're 100% right! My bad.

I didn't read the code, but only the `openupgrade_analysis_work.txt` file and there I didn't see any mention of converting to `account_payment`.

Closing this.
