### ISSUE TITLE
[RFC] Detect removed noupdate records

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/OpenUpgrade#1046]
noupdate="1" records are not automatically removed on any update/migration, and they can be very harmful if they are for example record rules (example: https://github.com/OCA/OpenUpgrade/pull/848).

We should detect them and maybe automatically delete them. Ideal would be on OpenUpgrade itself, in a similar way we have made with binary stored as attachments: https://github.com/OCA/OpenUpgrade/pull/1013.

If not possible, then at least we can detect them in the `compare_noupdate_xml_records.py` script. There's a `<delete>` tag for XML that maybe we can use for automatic removal loading the XML file.

Opinions @StefanRijnhart @hbrunn @mreficent ?

**Comment by MiquelRForgeFlow** [comment]
I love automatic things :+1:

**Comment by pedrobaeza** [comment]
Any opinion/advice for implementing this?

**Comment by StefanRijnhart** [comment]
I'm all for reporting on the noupdate property in the analysis file (working on that now), but removing them by default would be unfortunate (for example, the default service product is in use by some of my customers, but it has been removed in Odoo 9.0).

**Comment by pedrobaeza** [comment]
OK, then let's go for the manual one. About the issue you mention, we can study it for solving all cases. Maybe an unlink encapsulated in a try... Can you open an issue for it?

**Comment by StefanRijnhart** [comment]
@pedrobaeza I am not particularly interested in automatic removal, so I won't open the issue.

**Comment by pedrobaeza** [comment]
Well I was talking about the concrete issue of the default service product, but if you have solved it...

**Comment by StefanRijnhart** [comment]
Oh, sorry I misunderstood. The service product will be kept exactly because it is a noupdate record. I gave it as an example why it might be a bad idea to delete such records by default when they are removed in a new Odoo release.

**Comment by StefanRijnhart** [comment]
Here is the analysis with checking for the noupdate property. Is that what you had in mind? https://github.com/StefanRijnhart/OpenUpgrade/commit/a524b8362ee9d1d548009b75d1e13bd6452403ef

**Comment by pedrobaeza** [comment]
Yeah, that's it! With that, we can see from the analysis file which records have to be taken into account. We still need to keep the script for getting the XML, but this way we can compare 2 ways. Thanks for that.

**Comment by StefanRijnhart** [comment]
Well, thanks for suggesting this feature. I will create a PR with this change as soon as the current analysis and framework PR's are merged.

**Comment by StefanRijnhart** [comment]
Closing as the related PR's have been merged.
