### ISSUE TITLE
[v10]replace message_follower_ids by message_partner_ids in ir_rules

### ISSUE THREAD

**Issue by flotho** [OCA/OpenUpgrade#1047]
New v10 coming from v8 => v9

Some rules are referencing message_follower_ids on sale.order, account.invoice etc...
Those fields usages have to be replaced by message_partner_ids.

**Comment by pedrobaeza** [comment]
Script https://github.com/OCA/OpenUpgrade/blob/10.0/scripts/compare_noupdate_xml_records.py should detect that changes. It had before #1045 a problem and didn't write the changes. Please check modules where this change should be done and check in #1042 how we did for loading these changes.
