### ISSUE TITLE
[10.0]Website image no more available for non authenticate users

### ISSUE THREAD

**Issue by flotho** [OCA/OpenUpgrade#1048]
Impacted versions: V10

Since I migrate from v8 to v10, all the images in the website part are no more available for non authenticated user. 
What's the correct way to give the read part to public users?

**Comment by hbrunn** [comment]
looks like you're missing https://github.com/OCA/OpenUpgrade/pull/1025

**Comment by flotho** [comment]
Great, my migration was previously done to this PR,

Thanks
