### ISSUE TITLE
[v10]Blog entries in website are "old" release

### ISSUE THREAD

**Issue by flotho** [OCA/OpenUpgrade#1049]
After a mrigration from v8=>v10 some parts of my blog entries have disappeared.
What could be the cause of this? 
How can I found the responsible of that?

regards

**Comment by pedrobaeza** [comment]
Sorry, you have to be more specific.

**Comment by flotho** [comment]
Hi @pedrobaeza , I found what's going on.
In v8 we have blog history and of course the version displayed in the web site is the most recent one.
In v10 history seems to have disappeared so that the content field still the first saved in the UI.

Could this issue be reopened?

regards

**Comment by pedrobaeza** [comment]
But I still don't get what's the problem.

**Comment by flotho** [comment]
the problem is that the openupgrade don't take the content of the latest history but the initial content set into the blog entry. The datas are consequently partial

**Comment by flotho** [comment]
IMO, we need to adapt the migration to check whether history is present and use the latest release to be updated in the blog post
