### ISSUE TITLE
[RFC] database size after upgrade and psql tools

### ISSUE THREAD

**Issue by legalsylvain** [OCA/OpenUpgrade#1059]
Hi all, 

I'm working on a migration from 7 to 8 with a database with 2.705.474 stock moves. As I had a huge difference of  db size before and after migration, (7.5Go -> 22Go) (```SELECT pg_size_pretty(pg_database_size('mydb'));``` I used the following SQL request to analyze db size.

```
SELECT                          
   relname as "Table",
   pg_size_pretty(pg_total_relation_size(relid)) As "Size",
   pg_size_pretty(pg_total_relation_size(relid) - pg_relation_size(relid)) as "External Size"
   FROM pg_catalog.pg_statio_user_tables ORDER BY pg_total_relation_size(relid) DESC;
```

Here are the size of the stock move table.

**Before Upgrade (on v7)**
```
                         Table                         |    Size    | External Size 
-------------------------------------------------------+------------+---------------
 mail_message                                          | 1642 MB    | 810 MB
```
Db size : 7.5Go

**After Upgrade (on v8)**

```
                         Table                         |    Size    | External Size 
-------------------------------------------------------+------------+---------------
 stock_move                                            | 12 GB      | 8448 MB
```
Db size : 22Go

**After VACUUM FULL + REINDEX DATABASE + ANALYSE**
```
                         Table                         |    Size    | External Size 
-------------------------------------------------------+------------+---------------
 stock_move                                            | 1802 MB    | 1147 MB
```
Db size : 8.8Go

* Proposal 1

Add an option on openupgrade, to realize basic clean up sql operation at the end of the upgrade. ```--db-cleanup```

* Proposal 2

Add documentation on OpenUpgrade. (https://doc.therp.nl/openupgrade/)

What do you think ? Did you faced the same problem ? What do you do after each Openupgrade process ? 

Thanks.

CC @OCA/openupgrade-maintainers

**Comment by pedrobaeza** [comment]
Some of this increase is due to the new stock records: stock.quant, stock.pack.operation, so there's no solution on that. The rest is to document that you can use database_cleanup module after for cleaning things, but you can't do anything automatic as some modules that you install after can require temporary tables (example: https://github.com/OCA/account-analytic/blob/9.0/account_analytic_parent/migrations/9.0.1.0.0/pre-migration.py).

**Comment by legalsylvain** [comment]
Well,
We are not talking about the same things. I'm just saying that after a migration, database indexes take too much spaces. New datas quants / operations take space of course, but this is not a problem for me.
 
the proposal 1 was just to launch VACUUM FULL + REINDEX DATABASE + ANALYSE (or other SQL request) after a migration.
database_cleanup doesn't realize such operations IFAIK. (and no OCA module provides such features).

**Comment by sebalix** [comment]
I noticed that too, a migrated database took about 8Go, and after a dump/restore operation, its size was about 2Go.
We migrated a 6.0 database to 8.0 lately, and we did a DB dump/restore after each step to make the development iteration easier, and as a side-effect the size was constant.

And it's not related to OpenUpgrade, I see this on another Odoo database which was built from a proprietary one almost exclusively with COPY FROM and SQL statements. A dump/restore has reduced the size, so I suppose a vacuum is run when restoring a db.

**Comment by legalsylvain** [comment]
> A dump/restore has reduced the size, so I suppose a vacuum is run when restoring a db.

I'm not a db expert, but I believe that a restore command just recreate (so correctly) all indexes. (there are no vacuum command executed)

**Comment by pedrobaeza** [comment]
OK, my assumption was that you only need to vacuum if you remove records, and this is not very frequent in OpenUpgrade itself (except for the noupdate="0" records, that's to say, views, actions..., but they are few). That why I was talking about database_cleanup. But indeed maybe some SQL extra calls can be made on end-migration script of the base module: https://github.com/OCA/OpenUpgrade/blob/10.0/odoo/addons/base/migrations/10.0.1.3/end-migration.py

**Comment by pankk** [comment]
Thanks all. I've seen the same increase in size during migrations with large numbers of stock moves. As we do the migration on a separate server and we dump and restore as well I haven't really worried about it, especially since autovacuum is on by default. However, I think right after a migration is a good opportunity for a vacuum and vacuum analyze (+reindex if you're not doing a dump/restore).

For reference: for migrations to 8.0 they would be added on: https://github.com/OCA/OpenUpgrade/blob/8.0/openerp/openupgrade/deferred_80.py
I'm not sure how to do it for older versions.

**Comment by pedrobaeza** [comment]
Are anyone going to do any PR?

**Comment by pedrobaeza** [comment]
Closing as no further answer.

**Comment by legalsylvain** [comment]
Well, the original comment was proposing two solutions : 
- by code, with an option --db-cleanup
- by documentation.

are you agree with the first option ? 
if yes, I can do a PR on the 12.0 openupgrade branch, as I'm working on it.

CC : @StefanRijnhart : any PoV about that point ?


regards.

**Comment by pedrobaeza** [comment]
But do you mean an extra argument only in OpenUpgrade? That's ugly and not really needed, as you can operate for sure on the DB or shell the same as launching an Odoo instance with that parameter. Better to document usual commands, but if proved that they serve for something.

**Comment by hbrunn** [comment]
agree with @pedrobaeza, I don't think we should do anything else than upgrading with OpenUpgrade. But a note in the documentation about that for sure doesn't hurt

**Comment by StefanRijnhart** [comment]
+1 for documentation instead of creating a command that is just a wrapper around a small set of advanced but concise database commands.

**Comment by pedrobaeza** [comment]
Closing this as old RFC with no further actions.
