### ISSUE TITLE
OpenUpgrade 11: v10 comparison

### ISSUE THREAD

**Issue by JordiBForgeFlow** [OCA/OpenUpgrade#1085]
Hi! In preparation for next week's OCA sprint we can run the OpenUpgrade Database Comparison to prepare the 'openupgrade_analysis.txt' files. However I am not clear on what would be the best branch to use, as Odoo has not yet formally created the branch 11.0. 

Seems that https://github.com/odoo/odoo/tree/master is now frozen, in preparation for the Odoo Experience, and the active development is taking place in https://github.com/odoo/odoo/tree/saas-18.

**Comment by pedrobaeza** [comment]
@StefanRijnhart and @hbrunn said in a reply to one mail mine that they are going to be in charge on the OpenUpgrade topic in the code sprint, and both are very used to make previous analysis comparisons. 

I think other times they have used master branch for doing the comparison for sure.

**Comment by hbrunn** [comment]
yes, I'd use the current master branch

**Comment by StefanRijnhart** [comment]
Planned to work on the analysis on Friday evening and Sunday afternoon/evening!

**Comment by JordiBForgeFlow** [comment]
OK, thanks for the clarification! BTW we will have 4 guys from Bloopark in LLN, very motivated to work on this topic. @mreficent will also be there.

**Comment by pedrobaeza** [comment]
Hey, latest news: Odoo doesn't use (anymore) master for 11.0. They use saas-18. Their process is:

* Fork master and create the saas-18, freezing it. 
* Stabilize saas-18 branch. 
* Create 11.0 branch from saas-18.

Source: 

https://twitter.com/Georges_Grogero/status/913414909123325952
https://twitter.com/bouvyd/status/913515621438099456

Then, you should use saas-18 for your analysis, not master.
