### ISSUE TITLE
Conversion from Product UoM %s to Default UoM %s is not possible as they both belong to different Category

### ISSUE THREAD

**Issue by mgielissen** [OCA/OpenUpgrade#1127]
I did a migration of 2 different databases from 8 to 9. Both are giving the same error:

  File "/var/tmp/openupgrade/9.0/addons/product/product.py", line 122, in _compute_qty_obj
    raise UserError(_('Conversion from Product UoM %s to Default UoM %s is not possible as they both belong to different Category!.') % (from_unit.name,to_unit.name))

**Comment by pedrobaeza** [comment]
You have to fix your DB consistency. You have products that have changed their UoM during their lifetime. Make them homogeneous for avoiding this error.
