### ISSUE TITLE
[10.0] Migration from Odoo 9 to Odoo 10 ERROR !

### ISSUE THREAD

**Issue by Boss1669** [OCA/OpenUpgrade#1129]
here is part of migration log from Odoo 9 to Odoo 10

> bad query: ALTER TABLE "mrp_workorder" ADD COLUMN "write_uid" int4
>  Failed to load registry
> Traceback (most recent call last):
>   File "/var/tmp/openupgrade/10.0/server/odoo/modules/registry.py", line 82, in new
>     odoo.modules.load_modules(registry._db, force_demo, status, update_module)

this is full log
https://pastebin.com/2kVnjZK9

**Comment by pedrobaeza** [comment]
mrp module is not yet migrated, and thus the error.

**Comment by JordiBForgeFlow** [comment]
Migration is done here: https://github.com/OCA/OpenUpgrade/pull/1076 pending to approve. You can try it
