### ISSUE TITLE
OpenERP 7 missing openerp-server.conf 

### ISSUE THREAD

**Issue by Aghilas777** [OCA/OpenUpgrade#1137]
Impacted versions:
OpenERP 7.0
Steps to reproduce:
Installation of the latest version of nightly OpenERP 7 (March 22nd)
Current behavior:
no openerp-server.conf file after installation
Expected behavior:
to have openerp-server.conf in /opt/openerp/server/

**Comment by pedrobaeza** [comment]
This has nothing to do with this project.
