### ISSUE TITLE
[8] migrate.py - Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by hivam** [OCA/OpenUpgrade#1187]
**Impacted versions:**
script migrate.py - migrations=8.0

**Steps to reproduce:**

**run script:**  python migrate.py --config=[your odoo.conf] --database=[your database] --run-migrations=[your migrations]

**Current behavior:**

running migration for 8.0
Segmentation fault (core dumped)

**last line in migration.log**:
INFO _bd__migrated openerp.models: storing computed values of fields.function 'reconcile_ref'

several times stoped in this line

**Expected behavior:**

The migration script will continue

**Video/Screenshot link (optional):**

**Comment by hivam** [comment]
## Please ignore this issue, the problem is postgresql config.

**Comment by rabchev** [comment]
I encounter the same problem. Could you please share what postgresql configurations you changed?

Thanks
