### ISSUE TITLE
Default is only mentioned for required fields

### ISSUE THREAD

**Issue by StefanRijnhart** [OCA/OpenUpgrade#1204]
It will be helpful if the analysis shows the default value for non-required fields as well.

**Comment by MiquelRForgeFlow** [comment]
Then we should debate here if this is a thing we really want. I also think approach does not improve readability, and the value of req_required is mostly just 'function' which is not very informative.

**Comment by pedrobaeza** [comment]
What is my reasoning for needing it? To know when a new field has a default value (not which one), for knowing if you have to check if the default value is correct.

It's true that you have to do similar if no default value is provided for knowing if the business logic should provide a value to field there, but it seems more straight-forward.

What do you think?

**Comment by MiquelRForgeFlow** [comment]
And how many cases are there in which the default value is not correct? 🤔

**Comment by pedrobaeza** [comment]
This was raised from one of these cases, and I remember you were involved also.

**Comment by MiquelRForgeFlow** [comment]
I don't remember 😓

**Comment by MiquelRForgeFlow** [comment]
@pedrobaeza Ok, I updated the PR with a different approach. Now it only shows 'hasdefault' string for those NEW records that have a default. I think this way it's less verbose and more readable than the previous approach. I think that with this way both point of views should be happy.
