### ISSUE TITLE
[9.0] delivery_carrier table wrong ids 

### ISSUE THREAD

**Issue by AaronHForgeFlow** [OCA/OpenUpgrade#1212]
When migrated a database from v8 to v9 the ids of the delivery_carrier table changed unexpectedly:

In the following image I am showing the ids and the name of the carrier. See in first place the values in v8, then the values in v9 after migrate and then the openupgrade_legacy table for carrier_id. The wrong rows are highlighted in red.

![image](https://user-images.githubusercontent.com/19620251/33494451-914ad64c-d6c3-11e7-8b35-0f463a55d3b1.png)

@hbrunn @pedrobaeza  Can you shed some light here? :confused:

**Comment by pedrobaeza** [comment]
That's because the delivery carrier is now populated with the lines of v8. That table is renamed to delivery_carrier. This is for propagating correctly all the fields that are in the lines, which are more suitable. If other modules use a reference to all table, you need a migration script for them.

**Comment by pedrobaeza** [comment]
Fixed in #1213
