### ISSUE TITLE
[10.0] res_country data causing duplicate key issue

### ISSUE THREAD

**Issue by AaronHForgeFlow** [OCA/OpenUpgrade#1237]
Impacted versions: 8.0, 9.0, 10.0

Steps to reproduce: upgrade base

Current behavior: 
When updating Odoo is trying to create records in table res_country state using file res.country.state.csv in base module. That causes a duplicate key issue:
`duplicate key value violates unique constraint "res_country_state_name_code_uniq"`

Expected behavior: Update base should not update res_country demo data but it's in a csv file and it's always imported.

**Comment by pedrobaeza** [comment]
Which value is duplicated? l10n_es_toponyms includes migration script.

**Comment by AaronHForgeFlow** [comment]
All states declared here: https://github.com/OCA/OpenUpgrade/blob/10.0/odoo/addons/base/res/res.country.state.csv

**Comment by pedrobaeza** [comment]
But that's not true. There are duplicates if you have already fill other states. For Spain is solved in https://github.com/OCA/l10n-spain/blob/10.0/l10n_es_toponyms/migrations/10.0.1.0.0/pre-migration.py. If you have other country (like US) that was populated with `base_location_geonames_import`, you will need to make a custom migration script for your DB for having the same XML-ID.

Not a problem of OpenUpgrade itself.

**Comment by sergiocorato** [comment]
As there are possibly many installations which used `base_location_geonames_import` , it can be solved modifying Openupgrade Odoo code in base res.country.state object creation:

```
    @api.model
    def create(self, vals):
        # check if country_state exists: if true, do not create and return
        # found state
        if vals.get('code') and vals.get('country_id'):
            existing_id = self.search([
                ('code', '=', vals.get('code')),
                ('country_id', '=', vals.get('country_id')),
            ])
            if existing_id:
                return existing_id
        return super(CountryState, self).create(vals)
```

**Comment by pedrobaeza** [comment]
OpenUpgrade doesn't change modules code, but add migration scripts, but as said, it's the duty of the integrator to fix this constraint. It's not an error and you can continue having it.
