### ISSUE TITLE
Database restore error. Odoo 8.0 to 10.0

### ISSUE THREAD

**Issue by GronThork** [OCA/OpenUpgrade#1239]
Hello,
I'm starting in Odoo's world. When I try to load a backup I get an error, I hope you can help me.

Impacted versions: 10.0

Steps to reproduce: Odoo database 8.0 -> OpenUpgrade -> 9.0 -> OpenUpgrade -> 10.0

Current behavior: When I try to restore my upgraded db i get this error:

Database restore error: "Error mientras se validaban las restricciones El elemento '<field name="display_groups_suggestions">' no puede ser localizado en la vista padre Error de contexto: Vista `res.users.form.hr` [view_id: 634, xml_id: hr.view_users_form_mail, model: res.users, parent_id: 236] None" while parsing file:///c:/program%20files%20(x86)/odoo%2010.0/server/odoo/addons/sales_team/security/sales_team_security.xml:3, near <record id="group_sale_salesman" model="res.groups"> <field name="name">User: Own Documents Only</field> <field name="category_id" ref="base.module_category_sales_management"/> <field name="implied_ids" eval="[(4, ref('base.group_user'))]"/> <field name="comment">the user will have access to his own data in the sales application.</field> </record>

I dont have custom addons.

Regards and thanks.

**Comment by pedrobaeza** [comment]
You don't have to restore database, but update it with the corresponding OpenUpgrade version.

**Comment by GronThork** [comment]
Hello Pedro,

I'm going to write in Spanish, which is more comfortable for me. I'll put a Google translation in the bottom of the page.

Gracias por contestar Pedro, puede ser que no me haya explicado muy bien. Te explico mi situación con más detalle. Tengo en un equipo Odoo8 con una base de datos sin mucho misterio, contenido de clientes, notas y poco más (pero ya son más de 900 y pasarlo a mano es muy tedioso).  Todos los addons que hay instalados son propios de Odoo por lo que no tendría que haber problemas de compatibilidad.
Para hacer la migración usé la herramienta OpenUpgrade. Ejecutando el Script primero para pasar la base de datos de la versión 8.0 a la 9.0 y la ejecuté de nuevo para pasarla de la versión 9.0 a la 10.0. 

Ahora bien, tengo la base de datos migrada en un PC con Odoo8. Mi intención y lo que estoy intentando hacer es un respaldo de la base de datos para luego importarla en un servidor con Odoo 10 recién instalado (me he fijado en que los addons instalados sean los mismos, o lo más parecidos posible) 

Pero a la hora de importarla en el servidor me da el error que he puesto en el primer comentario. 
Espero haberte aclarado la duda, y nuevamente, gracias por la ayuda.

Un saludo.


"Thanks for answering Peter, it could be that he has not explained me very well. I explain my situation in more detail. I have in an Odoo8 computer with a database without much mystery, customer content, notes and a little more (but they are already more than 900 and passing it by hand is very tedious). All the addons that are installed are Odoo's own, so there should not be compatibility problems.
To do the migration I used the OpenUpgrade tool. Executing the Script first to pass the database from version 8.0 to 9.0 and running it again to pass it from version 9.0 to 10.0.

Now, I have the database migrated on a PC with Odoo8. My intention and what I'm trying to do is backup the database and then import it into a server with newly installed Odoo 10 (I've noticed that the addons installed are the same, or as similar as possible)

But when importing it on the server it gives me the error that I put in the first comment.
I hope I have clarified the doubt, and again, thanks for the help."

**Comment by pedrobaeza** [comment]
We should speak in English in this channel anyway.

There should be something wrong on your side, as a database migrated to 10.0 with OpenUpgrade should be "dumpable" and recoverable on other PC as well. Check that you can access correctly to the OpenUpgrade v10 service before dumping.
