### ISSUE TITLE
Odoo Migration help needed

### ISSUE THREAD

**Issue by jiffingomez** [OCA/OpenUpgrade#1259]
Hi guys,

I'm trying to migrate from Odoo 8 to Odoo 11, I have downloaded Openupgrade 11 branch from github and started to run the migrate.py.

`python migrate.py --config=/etc/odoo.conf --database=Study --run-migrations=9.0`

I'm getting the below output:

```
copying database Study to Study_migrated...
Copying the database using 'with template'
running migration for 9.0
sh: 1: /var/tmp/openupgrade/9.0/server/openerp-server: not found
```
I have updated my git version to 2.15.1, still the issue persist, Can Someone help me about this, What should I do to migrate successfully?

**Comment by pedrobaeza** [comment]
That scripts is outdated and probably didn't work. You have to migrate from each version: v8 > v9 > v10 > v11, and v11 is far from being completed. For sure this is not something easy to achieve if you don't have enough technical knowledge.

**Comment by jiffingomez** [comment]
So I have to use openupgrade 9 branch to migrate from Odoo 8 to 9?

**Comment by pedrobaeza** [comment]
Yes
