### ISSUE TITLE
Problem with migration from 8 to 9/10

### ISSUE THREAD

**Issue by Edsol** [OCA/OpenUpgrade#1261]
I'm trying to migrate from version 8 to version 9/10, I have now this problem and I don't understand where is the error.
[mail_migration.log](https://github.com/OCA/OpenUpgrade/files/1639716/mail_migration.log)

**Comment by pedrobaeza** [comment]
This seems you don't have your previous v8 installation totally updated and thus there are records removed. Please do that before starting migration.
