### ISSUE TITLE
[9.0] Reconciled items are being left un-reconciled after the migration.

### ISSUE THREAD

**Issue by mvaled** [OCA/OpenUpgrade#1262]
### Summary of the issue

After migrating from Odoo 8 to 9, automatic gain/loss journal items in the debtor/creditor accounts are not reconciled, even they were in the Odoo 8 DB.

Impacted versions:  Migration from 8 to 9.

### Steps to reproduce

This is rather lengthy process and there may be some subtleties involved in the issue.  In steps where there's another (obvious) choice to do things I explain further.

1. Create a new DB (no demonstration data).

2. Install the Accounting and Finance module.  Make your company currency USD, and taxes 0% for both sales and purchases (this is not unrealistic: Cuba).  Use a general chart of accounts.

3. Activate multi-currency.

4. Modify your Bank account and diary to have currency EUR, also change your Debtor account to have secondary currency EUR.  Basically this means that you report in USD but keep your assets in EUR.

5. Create accounts for Foreign Exchange Gains and Loss and put them in the configuration.

7. Go to the Currencies configuration, chose USD and add new (for the current date) rate of 1.000.  Important: keep the old rate of 1.2834.  Notice that even the company reports in USD, we don't set its rate to 1, but keep the EUR with rate 1 and update the USD/EUR daily.

8. Create a customer invoice with a single line.  Price 100 €.  Use a date several days back so that the rate be 1.2834.  Validate the invoice.  This would make the journal entry to look like:

![screenshot from 2018-01-18 10-58-47](https://user-images.githubusercontent.com/270825/35107316-a0c2d3c2-fc3e-11e7-843c-ff5349817141.png)

9. Pay the invoice entirely (`account.voucher`).  Use the Bank diary, 100 €, date as of today (USD/EUR should be 1).  Validate the payment.   The journal entry should be like:

![screenshot from 2018-01-18 11-01-14](https://user-images.githubusercontent.com/270825/35107439-ed38a524-fc3e-11e7-91d3-c8bbe0a3850e.png)

Notice that the 28.34 USD in the Debtors account is reconciled.  

10. Post all entries.

11.  Stop there and migrate the DB to Odoo 9 with OpenUpgrade (I used branch 9.0 at 2f1674913392be418d5ddd3e632cf4ec3e7a62a5).

12.  Upgrade the migrated DB with Odoo 9 (I used branch 9.0 at odoo/odoo@40998a4dedcfa1aef85c1e94fd0648a51b8f56f2).

##### Current behavior

The migrated DB shows item crediting Debtors by 28.34 unreconciled:

![screenshot from 2018-01-18 11-07-28](https://user-images.githubusercontent.com/270825/35111557-8add2c0a-fc49-11e7-8f2d-a7f979ce31ce.png)

##### Expected behavior:

The journal item should be reconciled.

##### Notes

Even though the item is not 'reconciled' it does appear in the A1 reconciliation object:

![screenshot from 2018-01-18 11-08-16](https://user-images.githubusercontent.com/270825/35111623-a782890e-fc49-11e7-82a4-7494ba2c45ea.png)

**Comment by StefanRijnhart** [comment]
Fixed with https://github.com/OCA/OpenUpgrade/pull/1277
