### ISSUE TITLE
[9.0] Migrated channels (from groups) don't present their messages

### ISSUE THREAD

**Issue by mvaled** [OCA/OpenUpgrade#1264]
Impacted versions: Migration from 8 to 9.

Steps to reproduce:

1. Create a DB
2. Ensure to add several message to the Whole company group.
3. Migrate.

Screenshot in Odoo 8:

![screenshot from 2018-01-19 11-55-55](https://user-images.githubusercontent.com/270825/35162641-06d7ca9a-fd12-11e7-8c08-954a582713ce.png)

Current behavior:

A new mail channel is created.  But no message is shown.  Also if you add a new message, it won't get added in the view:

![screenshot from 2018-01-19 12-07-04](https://user-images.githubusercontent.com/270825/35162727-2f4e2118-fd12-11e7-8c1b-305977b1a028.png)

Notes:  

This is because the mail channel needs to be subscribed to itself.  See https://github.com/odoo/odoo/blob/9.0/addons/mail/models/mail_channel.py#L110

We're preparing a PR.

**Comment by pedrobaeza** [comment]
Closing as we can track the progress on the PR.
