### ISSUE TITLE
OpenUpgrade 8.0 to 9.0

### ISSUE THREAD

**Issue by jiffingomez** [OCA/OpenUpgrade#1267]
Hi,
Can somebody help me to migrate from Odoo 8.0 to Odoo 9.0, i.e which branch should i use for migration?, which config file should I use as parameter(Odoo 8 or Odoo 9) while running the script?

**Comment by pedrobaeza** [comment]
You must use the branch 9.0, and you need to configure your OpenUpgrade server as you would do for a regular Odoo server.

**Comment by jiffingomez** [comment]
Hi @pedrobaeza ,
Thank you for your fast reply, I'm trying migrate for an month, still haven't figured the way to do this, Please help me out, Everytime I'm facing the below issue.

`copying database Study to Study_migrated...
Copying the database using 'with template'
running migration for 9.0
sh: 1: /var/tmp/openupgrade/9.0/server/openerp-server: not found`

My git version is updated to new version, How to configure OpenUpgrade server? Is there any documentation for this?

**Comment by pedrobaeza** [comment]
OpenUpgrade server is Odoo server (with extra migration scripts), so the documentation for configuring it is the same.
