### ISSUE TITLE
Cron & ServerAction, not getting mapped during Migration [Odoo 11.0]

### ISSUE THREAD

**Issue by deepa4lok** [OCA/OpenUpgrade#1268]
Migration from Odoo 10.0 to Odoo 11.0 is fairly successful.
However, in Odoo 11.0 **IrCron's** functionalities are slightly changed, i.e it uses ServerAction to store the functional entities.

Although I can see the noupdata.xml in the respective modules' migration folder, this piece of code is not considered during the migration. How do I proceed with this?

**Comment by pedrobaeza** [comment]
You have to develop that part in migration scripts if it's not covered.
