### ISSUE TITLE
Best way to rename an xmlid

### ISSUE THREAD

**Issue by red15** [OCA/OpenUpgrade#127]
There is a problem with stock module migration, the xmlid `procurement.sequence_mrp_op_type` which now belongs to the stock module instead.

I've preliminary added a pre-migration.py which does 2 queries and it seems to work for me:

```
# These sequences used to belong to procurement module
cr.execute('''UPDATE ir_model_data SET module = 'stock' WHERE module = 'procurement' and name = 'sequence_mrp_op_type';''')
cr.execute('''UPDATE ir_model_data SET module = 'stock' WHERE module = 'procurement' and name = 'sequence_mrp_op';''')
```

Is there a better way to handle these ?

**Comment by red15** [comment]
Found the solution here :
https://github.com/OpenUpgrade/OpenUpgrade/pull/125/files#diff-72bd9ca04587930a7f05272bfd7e69a3R70

**Comment by StefanRijnhart** [comment]
For the record: https://doc.therp.nl/openupgrade/API.html#openupgrade.rename_xmlids
