### ISSUE TITLE
[9.0] account_voucher. Link from invoice to payment not created.

### ISSUE THREAD

**Issue by AaronHForgeFlow** [OCA/OpenUpgrade#1283]
The field "Originator payment" in account move lines is intended to be used as the link that relates the move lines to the payment that originated them, not the the invoice that was being paid the payment_id. https://github.com/odoo/odoo/blob/9.0/addons/account/models/account_payment.py#L511.

However,  the migration script is trying to match the account move lines generated from the invoices and the ones generated from the payment. 
https://github.com/OCA/OpenUpgrade/blob/9.0/addons/account_voucher/migrations/9.0.1.0/post-migration.py#L86

As they are not related, the table `account_invoice_payment_rel` remains empty after the migration.

**Comment by pedrobaeza** [comment]
Do you have a patch for this?

**Comment by AaronHForgeFlow** [comment]
@pedrobaeza I created https://github.com/OCA/OpenUpgrade/pull/1284 but still WIP

**Comment by pedrobaeza** [comment]
Closing as there's an opened PR
