### ISSUE TITLE
migrate.py do not find git (migration from V8 to V9)

### ISSUE THREAD

**Issue by NMuatan** [OCA/OpenUpgrade#1286]
Impacted versions: 11

Steps to reproduce: python migrate.py --config=/etc/odoo/openerp-server.conf --database=Production --run-migrations=9.0

Current behavior: 
linking server/addons to /var/tmp/openupgrade/9.0/addons
getting git://github.com/OpenUpgrade/OpenUpgrade.git
sh: 1: git: not found
sh: 1: git: not found
copying database Production to Production_migrated...
Copying the database using 'with template'
Failed, fallback on creating empty database + loading a dump
pg_restore: [archiver (db)] Error while PROCESSING TOC:
pg_restore: [archiver (db)] Error from TOC entry 10818; 0 0 COMMENT EXTENSION plpgsql 
pg_restore: [archiver (db)] could not execute query: ERROR:  must be owner of extension plpgsql
    Command was: COMMENT ON EXTENSION plpgsql IS 'PL/pgSQL procedural language';

I couldn't find why "getting git" fails.

Any help would be appreciated

**Comment by pedrobaeza** [comment]
You have to install git in your system
