### ISSUE TITLE
[9.0][delivery] post migration issue

### ISSUE THREAD

**Issue by florian-dacosta** [OCA/OpenUpgrade#1308]
Hello,
I have an issue when migrating the delivery module from v8 to 9 with Openupgrade.
I think it is a bug, but the code is 2 years old, which make me wonder why nobody would have meet the same issue... (since it is a very used module)
Here : https://github.com/OCA/OpenUpgrade/blame/9.0/addons/delivery/migrations/9.0.1.0/post-migration.py#L45 , The field `property_delivery_carrier` is renamed to `property_delivery_carrier_id` in the post-migration field. I have an error, since the field `property_delivery_carrier_id` is already created during the update of the module. 
I guess it should be in the pre-upgrade script to avoid this problem. 
This comment seems to go this way too : https://github.com/OCA/OpenUpgrade/blame/9.0/addons/delivery/migrations/9.0.1.0/post-migration.py#L11

I'd like to know the opinion of the authors of this script if possible!
What do you think? @pedrobaeza @hbrunn

**Comment by pedrobaeza** [comment]
Being a property, it's the same to do it on pre or post right now, as the values are in other table. This can only affect to default values.

**Comment by florian-dacosta** [comment]
Thanks for your answer Pedro.
Are you sure it is the same?
Old property is property_delivery_carrier.
New one is property_delivery_carrier_id.

So, on update of the module in version 9, Odoo will create a `ir.model.fieds`, with name `property_delivery_carrier_id`.
Then, on post upgrade https://github.com/OCA/OpenUpgrade/blame/9.0/addons/delivery/migrations/9.0.1.0/post-migration.py#L13 Odoo will rename old `ir.model.fields property_delivery_carrier` to `property_delivery_carrier_id`.
Doing this, Odoo fails because there is an SQL constraint so we can't have 2 ir.model.fields for same name, same model.

The problem here is not a loss of data, it is just a failure that will block openupgrade.

**Comment by StefanRijnhart** [comment]
Makes sense, @florian-dacosta. Could you do propose a fix? You can use https://github.com/OCA/openupgradelib/blob/master/openupgradelib/openupgrade.py#L1672

**Comment by pedrobaeza** [comment]
OK, it's weird, as I have migrated several DBs without hitting the problem, but OK to do it that part on pre-migration. We have now a new method in openupgradelib called `rename_fields` that you can use for this purpose.

**Comment by pedrobaeza** [comment]
Any news about this?

**Comment by pedrobaeza** [comment]
Closing as no answer

**Comment by florian-dacosta** [comment]
Oups, sorry about this.
I made a fix, I will do a pull request soon, This issue can stay closed.

**Comment by pedrobaeza** [comment]
Thanks for the follow-up
