### ISSUE TITLE
How to use OpenUpgrade 7.0

### ISSUE THREAD

**Issue by gomezgleonardob** [OCA/OpenUpgrade#1312]
Impacted versions:  6.1 ,7.0

Steps to reproduce: I dont know use this version of openupgrade

**Comment by pedrobaeza** [comment]
See documentation: https://doc.therp.nl/openupgrade/

**Comment by gomezgleonardob** [comment]
I have used openupgradelibe ,this error 

python migrate.py --config=[/etc/openerp-server.conf] --database=[tecnobal_orp6] --run-migrations=[6.1,7.0]
Traceback (most recent call last):
  File "migrate.py", line 3, in <module>
    from future.utils import iteritems
ImportError: No module named future.utils

**Comment by pedrobaeza** [comment]
Your deployment is incorrect. Check Python version.

**Comment by gomezgleonardob** [comment]
Thanks,executing migration have this error

sudo python migrate.py --config=/etc/openerp-server.conf --database=tecnobal_orp6 --run-migrations=7.0
Desde git://github.com/OpenUpgrade/OpenUpgrade
 * branch            7.0        -> FETCH_HEAD
Ya está actualizado.
copying database tecnobal_orp6 to tecnobal_orp6_migrated...
Copying the database using 'with template'
**running migration for 7.0
Running as user 'root' is a security risk, aborting**

**Comment by pedrobaeza** [comment]
Sorry, we can't help you anymore as these are basic steps that an Odoo sysadmin should know. The message is clear. This is only for reporting issues.

**Comment by gomezgleonardob** [comment]
Thanks
