### ISSUE TITLE
Problem migration odoo11 

### ISSUE THREAD

**Issue by upsens** [OCA/OpenUpgrade#1317]
Hello all,
i have run the migration from odoo 10 to 11 with the command:

`sudo  python migrate.py --config=/etc/odoo.conf --database=UpSens --run-migrations=11.0`

obtaining this file

[migration.log](https://github.com/OCA/OpenUpgrade/files/1942815/migration.log)

and i don't understand the error. I have a database UpSens in postgre (the right database) and one in sql. I have seen that the error compare during the execution of sql_db.py. 

Can you help me?

Thanks

**Comment by pedrobaeza** [comment]
That script doesn't work for >=v11. Launch the server manually (not with service) with `-u all` argument instead. Check that there's a lot of modules not yet covered.
