### ISSUE TITLE
[11.0] migration database 10 to odoo 11 issue XML view scheduled  Actions

### ISSUE THREAD

**Issue by AMhadhbi** [OCA/OpenUpgrade#1319]
Impacted versions:
run migration database odoo 11.0
Steps to reproduce:
Technical --> Automation--> scheduled actions
Current behavior:
`2018-04-27 09:53:23,238 3382 INFO odoo11 odoo.addons.base.ir.ir_ui_view: Field `**model**` does not exist

Error context:
View `n/a`
[view_id: n/a, xml_id: n/a, model: n/a, parent_id: n/a]
2018-04-27 09:53:23,238 3382 INFO odoo11 odoo.addons.base.ir.ir_ui_view: Field `**function**` does not exist

Error context:
View `n/a`
[view_id: n/a, xml_id: n/a, model: n/a, parent_id: n/a]
2018-04-27 09:53:23,239 3382 INFO odoo11 odoo.addons.base.ir.ir_ui_view: Field `**args**` does not exist

Error context:
View `n/a`
`
I check the database ir_cron 
![screen shot 2018-04-27 at 12 02 57](https://user-images.githubusercontent.com/10393083/39357494-585e41ca-4a13-11e8-9abf-1e18fe17fbcf.png)

it seems the table not migrated because field function and args not exist and model renamed by  model_id in odoo 11

**Comment by pedrobaeza** [comment]
That are view errors. You have to remove that views. It's not a question of migration.
