### ISSUE TITLE
No user found in configuration (7.0 -> 8.0)

### ISSUE THREAD

**Issue by buxx** [OCA/OpenUpgrade#132]
Hi, 
When trying to upgrade (7.0->8.0):

> python migrate.py --config="/etc/openerp/openerp-server.conf" --database="cs" --run-migrations="8.0"
> couldn't import bzrlib. You won't be able to run migrations <= 7.0!
> No user found in configuration

My [config file](http://pastebin.com/pQuCW63i). I'm doing it wrong ?

**Comment by hbrunn** [comment]
That's weird, your config looks perfectly fine. I assume you run the latest version of the code?

Could you insert the line

`print conn_parms`

at line 174 of migrate.py?

**Comment by buxx** [comment]
Fixed: My user was simply not autorized to read /etc/openerp/openerp-server.conf ...

**Comment by carras** [comment]
I have the same problem. And I use user odoo and user root all print the same:
No user found in configuration

Any ideas?

**Comment by objectsbloom** [comment]
Running fine this linux command: 

odoo@cloud9:~$ http_proxy=http://192.168.1.64:3128 https_proxy=https://192.168.1.64:3128 python migrate.py --config=/etc/odoo-server.conf --database=Mobiletalk --run-migrations=7.0,8.0
updating 7.0/web rev4203
El árbol está actualizado en la revisión 4203 de la rama http://bazaar.launchpad.net/~openerp/openerp-web/7.0
now at rev4203
updating 7.0/addons rev8174

but's taking a long while... just after installing (ubuntu 14.04):

sudo apt-get install python-bzrlib
sudo apt-get install bzr

**Comment by Yenthe666** [comment]
Thanks @buxx this solved my issue. 👍

**Comment by fred0716** [comment]
I have the same output - No user found in configuration , when excute python migrate.py.
I had tried the root and odoo user account to run the script. All have the same output.
How to fix that?

**Comment by pedrobaeza** [comment]
Read the explanation above.

**Comment by fred0716** [comment]
Do you mean I should run linux command like following ?

http_proxy=http://192.168.1.64:3128 https_proxy=https://192.168.1.64:3128 python migrate.py --config=/etc/odoo-server.conf --database=Mobiletalk --run-migrations=7.0,8.0

**Comment by pedrobaeza** [comment]
Try all the proposed solutions. Anyway, the problem is in your side, nothing to do with OpenUpgrade itself.

**Comment by fred0716** [comment]
Fixed. I typed the wrong configuration file name. 
Thanks.

**Comment by daudakhtar** [comment]
is this module able to migrate custom module from erp 7 to odoo 11?????
