### ISSUE TITLE
[9.0][product] Product weight data wrongly migrated

### ISSUE THREAD

**Issue by leio** [OCA/OpenUpgrade#1338]
In 8.0 there was product.template `weight` (Gross Weight) and `weight_net` (Net Weight).
In 9.0 there is product.product `weight` — Gross Weight; help="The weight of the contents in Kg, not including any packaging, etc.".
In 10.0 there is product.product `weight` — Weight; help="The weight of the contents in Kg, not including any packaging, etc."

9.0 had a bug in field string value stating gross weight, but it always meant to be only net weight now, as described in commit cae29df7d984d20c2cb736498b37bfb42545d67a when weight_net got removed:
```
    product
    - [REM] weight_net field. Weight net is removed from the product model.
    Indeed a product should be modeled without its possible packaging data.
    Moreover in the codebase the weight_net field is not really used.
```

The forgotten string change has been fixed by 10.0, but the tooltip (help) was already correctly describing it in 9.0 as well. This is in commit cd11497bd81a8501d5c63589f6ac6c438db5760b but doesn't seem to have reached 9.0 branch.

As-is, migrations lose important data, if data has been properly entered - nett weight into `weight_net` and not `weight` in v7 and v8.
v8 product.template weight_net values should be put into product.product weight, not a pure name by name move with net weight data incorrectly lost instead of gross weight data.

**Comment by StefanRijnhart** [comment]
Agreed! As a solution, do you agree to keep the template's weight as the product weight if weight_net was not entered? Would you like to create the PR?

**Comment by leio** [comment]
I guess that'd make sense, yes. I will not create the PR, as I have not and will not sign any CLAs, sorry.

**Comment by pedrobaeza** [comment]
Why don't you want to sign the CLA?

**Comment by StefanRijnhart** [comment]
That's a shame @leio, I see some good input from your side here on this project so it would be great if you could submit some code every now and then. I'll see what I can do about this one. In the mean time, it would be interesting to hear what your problem is with the OCA CLA in particular.

**Comment by leio** [comment]
Technically it'd be easier for me to submit my code to not worry about the changes being used by my customers under the AGPL-3 license they happen to be licensed at this point. But you refuse to take and integrate such code, so it's a wasted effort more or less. (To be clear, in this case I simply copied all weight_net into weight with SQL prior to migration, so no AGPL-3 derivative code was written). I'd be happy to contribute under AGPL-3+, GPL-2+, LGPL-2.1+ or all of those together, but I do not see a CLA as something acceptable to me, sorry.
For a random assortment of information on why this might be unacceptable to some people:
http://ebb.org/bkuhn/blog/2011/07/07/harmony-harmful.html
https://opensource.com/law/11/7/trouble-harmony-part-1
https://opensource.com/law/11/7/trouble-harmony-part-2

Overall it's a hindrance, and no, I'm not interested in discussing this in a mailing list - that's another hindrance.

**Comment by pedrobaeza** [comment]
Our CLA is not Harmony one, but it's only for ensuring that OCA can protect and lawsuit or violation of the license. If you don't understand this, then you are not really aware of how open source can work in the real world.

**Comment by leio** [comment]
Err... your ICLA even has "Harmony (HA-CLA-I-OSI) Version 1.0" in each footer...

I have worked with open source for 16 years, including for open source consultancy companies. I have never signed a CLA (yes, I have signed NDA's, but that's for customer companies trade secrets and data). It is rather outrageous to come telling people you don't know that they aren't aware how open source works in the real world.

**Comment by pedrobaeza** [comment]
> Err... your ICLA even has "Harmony (HA-CLA-I-OSI) Version 1.0" in each footer...

You're right, I didn't remember the source of our CLA, but any way, this is not NDA and I keep my position about not knowing the troubles of open source in real world without CLA. I see your position absurd, but hey, as you want, I don't need to fix the "weight net" thing. You are the first interested on that.

**Comment by leio** [comment]
Yes, I'm fine. It's OCA and its other contributors and users that are missing out due to the extra barriers. I'm fine with them, I just choose to not sign a CLA and not waste my efforts on work that you won't be able to integrate anyways due to your self inflected barriers of contribution acceptance. And I expect you to respect my choice at least.

**Comment by pedrobaeza** [comment]
As said, you can do what you want, but I don't understand that you put the code in the issue instead in a PR. You are contributing the same code, but difficulting a lot the process, forcing other to create the PR, and this will probably will be forgotten or even closed if no one is interested in doing such thing.

**Comment by leio** [comment]
1. I have not signed nor will I sign the CLA
2. I have not put any code contributions here, just explanations and references to Odoo commits
3. If I were to create the PR, you will refuse to merge it due to no CLA agreement
4. Someone will have to rewrite it for merge, which will be complicated as you've seen my code, it'll be pretty much identical, and you can't be sure anymore that it isn't a code contribution from someone without a CLA signature.

Essentially me filing a PR with code changes to fix it will mean you might not be able to ever fix the bug, as it's hard to prove it didn't come from someone who hasn't agreed to CLA. Albeit this particular instance is such a small change, I doubt it's even copyrightable, but that's only something a court can decide.

To me these comments are just an example of how you don't understand what the CLA means for the project in terms of potential contributions from people who will not sign it, or how open source licenses and "derivative works" work(sic).

**Comment by pedrobaeza** [comment]
I have very clear that you don't want to sign the CLA, of course. What I want is that you sign it for this kind of contributions. I won't insist more.

**Comment by StefanRijnhart** [comment]
Thank you for the clarification @leio. I was hesitant about adopting a CLA for the OCA, but with a history of multiple upstream licence changes it did make sense. It was important for me that the CLA was based on Outbound license option three of the Harmony CLA template which does not allow to relicense under a commercial or proprietary license. I'm currently saddened that it does prevent us from receiving your code contributions but we have to respect your individual choice. Keep your bug reports coming ;-)

**Comment by StefanRijnhart** [comment]
Thank you @sergiocorato for the fix and @leio for the analysis!
