### ISSUE TITLE
Integrity Error 8.0 -> 9.0 when cleaning up obsolete 'view' accounts

### ISSUE THREAD

**Issue by sylvainc** [OCA/OpenUpgrade#1354]
Hi all,

When running openupgrade from 8.0 to 9.0, I have the following Integrity error when running an "-u all":

```
IntegrityError: null value in column "account_id" violates not-null constraint
CONTEXT:  SQL statement "UPDATE ONLY "public"."account_invoice_line" SET "account_id" = NULL WHERE $1 OPERATOR(pg_catalog.=) "account_id""
```
I open this issue here because I didn't find any pointer on Internet about this error.

Thanks.

**Comment by pedrobaeza** [comment]
This is because you have an account of type view put in the invoice line somewhere, which is something incorrect. Change the type of the account in v8, or change the account everywhere where is incorrectly used.

**Comment by sylvainc** [comment]
The traceback:

```
Traceback (most recent call last):
  File "/data/migration/OpenUpgrade/openerp/service/server.py", line 897, in preload_registries
    registry = RegistryManager.new(dbname, update_module=update_module)
  File "/data/migration/OpenUpgrade/openerp/modules/registry.py", line 390, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/data/migration/OpenUpgrade/openerp/modules/loading.py", line 408, in load_modules
    force, status, report, loaded_modules, update_module, upg_registry)
  File "/data/migration/OpenUpgrade/openerp/modules/loading.py", line 299, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks, upg_registry=upg_registry)
  File "/data/migration/OpenUpgrade/openerp/modules/loading.py", line 189, in load_module_graph
    migrations.migrate_module(package, 'post')
  File "/data/migration/OpenUpgrade/openerp/modules/migration.py", line 169, in migrate_module
    mod.migrate(self.cr, pkg.installed_version)
  File "/data/migration/OpenUpgrade/local/lib/python2.7/site-packages/openupgradelib/openupgrade.py", line 1427, in wrapped_function
    if use_env2 else cr, version)
  File "/data/migration/OpenUpgrade/addons/account/migrations/9.0.1.1/post-migration.py", line 1219, in migrate
    move_view_accounts(env)
  File "/data/migration/OpenUpgrade/addons/account/migrations/9.0.1.1/post-migration.py", line 289, in move_view_accounts
    WHERE %s = 'view'""", (AsIs(openupgrade.get_legacy_name('type')),)
  File "/data/migration/OpenUpgrade/local/lib/python2.7/site-packages/openupgradelib/openupgrade.py", line 923, in logged_query
    cr.execute(query, args)
  File "/data/migration/OpenUpgrade/openerp/sql_db.py", line 141, in wrapper
    return f(self, *args, **kwargs)
  File "/data/migration/OpenUpgrade/openerp/sql_db.py", line 220, in execute
    res = self._obj.execute(query, params)
IntegrityError: null value in column "account_id" violates not-null constraint
```

pip show openupgradelib
Name: openupgradelib
Version: 1.3.2

**Comment by bealdav** [comment]
The solution by @florian-dacosta is
```
UPDATE account_invoice_tax SET account_id = foo.good_id 
FROM (SELECT a1.id as wrong_id, a2.id as good_id, a1.company_id 
      FROM account_account a1 FULL OUTER JOIN account_account a2 
        ON a1.company_id = a2.company_id AND a1.code = '44571' AND a2.code = '445713'
        WHERE a2.id IS NOT NULL AND a1.id IS NOT NULL) as foo 
WHERE account_invoice_tax.company_id = foo.company_id AND account_invoice_tax.account_id = foo.wrong_id;
```

**Comment by sylvainc** [comment]
Thanks you both.

**Comment by bealdav** [comment]
@pedrobaeza 
Maybe we could keep it open with a better name, like : "Helper : Integrity ..."

**Comment by pedrobaeza** [comment]
No, the error is clear and it's due to a bad DB v8 state. You must fix that state before migrating.

**Comment by bealdav** [comment]
Not sure it's completely clear for everyone not familiar with openupgrade. 
Maybe you could consider to make extra steps to encourage more users, future contibutors to openupgrade.

My 2 cents

**Comment by pedrobaeza** [comment]
Sorry, but this is not something about encouraging. This is not an issue, and I have explained why, so what more do you want? The SQL statement you have put doesn't serve. My explanation does, but obviously it requires to do the proper changes.

**Comment by StefanRijnhart** [comment]
I'm sure that a PR would be accepted that wraps the statement in a try/except + cr.savepoint clause if that makes OpenUpgrade more user friendly in your perspective.

**Comment by bealdav** [comment]
@StefanRijnhart Do you think an exception message with the query above as example could be sufficient ?

**Comment by pedrobaeza** [comment]
@bealdav as said, that SQL doesn't make any sense in this case.

**Comment by bealdav** [comment]
OK, as openupgrade beginner, I can't propose more, sorry (my PR will be not valid).

**Comment by florian-dacosta** [comment]
Well, in this particluar case, the SQL make sense and solve the problem. But I agree it can't really go to openupgrade as each case could be different. 
In this statement, we choose to replace an account by another, but it is about a specific case in a french context so, no place in openupgrade for this, it is way to specific.

This said, it is I think a very comon problem for migration of french database at least and could help some people, but I am not sure how and where it could eventually go.

**Comment by pedrobaeza** [comment]
Please check again my comment https://github.com/OCA/OpenUpgrade/issues/1354#issuecomment-392438003 about the general problem

**Comment by florian-dacosta** [comment]
Oh, yes, I read too fast, the problem is not the same as I thought, it concerns account_invoice_line and not account_invoice_tax.

**Comment by sylvainc** [comment]
I confirm it was a db state problem, there was 'view' type account on some account_invoice_line that cause trouble, sorry for the inconvenience, but maybe it can help someone with similar problem.

Thanks for your time.

**Comment by ypapouin** [comment]
Same issue, the culprit can be quickly identified using:
```
SELECT * FROM public.account_invoice_line
WHERE account_id in (
    SELECT id FROM public.account_account
    WHERE type = 'view'
);
```
I had 4 invoice lines attached to the root view.
`SELECT * FROM public.account_account WHERE id = N;`

Note that theses lines are not visible in OpenERP 6.1 but are on Odoo 8.0
Also note that theses lines have in common quantity=0, price_unit=0, etc...

**Comment by pedrobaeza** [comment]
Yes, but it's incorrect data that should be repaired at DB level, not at migration script level IMO.

**Comment by ypapouin** [comment]
Yes you're right that needs a case by case fix
