### ISSUE TITLE
[11.0] migration error in project when project_issue was not previously installed

### ISSUE THREAD

**Issue by gdgellatly** [OCA/OpenUpgrade#1363]
Impacted versions:
11
Steps to reproduce:
Migrate a v10 database without project_issue installed.

Current behavior:
Traceback regarding missing relation project_issue, pretty much identical to #1000 but I lost it.

Traced it to  https://github.com/OCA/OpenUpgrade/blob/11.0/addons/project/migrations/11.0.1.1/post-migration.py#L38 and just added a return to get past and rest worked fine but obviously not the fix for all.

Expected behavior:

Video/Screenshot link (optional):

**Comment by StefanRijnhart** [comment]
It sure looks as if that codein the migration of `project` could use a check on whether project_issue was installed https://github.com/OCA/OpenUpgrade/blob/11.0/addons/project/migrations/11.0.1.1/post-migration.py#L215

**Comment by pedrobaeza** [comment]
Fixed in #1365
