### ISSUE TITLE
Documentation improvement

### ISSUE THREAD

**Issue by js-landoo** [OCA/OpenUpgrade#1369]
Hi, we are a team of 4 people in OCA code sprint Sevilla 2018.
We'd like to improve actual official documentation with something like:
- Guide to make your first database migration
- Tricks 
- List of possible errors and suggested solutions

@StefanRijnhart and other maintainers, can you suggest which is the best way to publish this info?
Maybe in actual website https://doc.therp.nl/openupgrade?
Maybe in a big readme.rst in github.com/oca/openupgrade?
We will start with a shared Gdocs document and wait for your news to convert final work to choosed format and location.

You can see topic in https://goo.gl/JqaUvG

Thanks.

**Comment by StefanRijnhart** [comment]
Great! Please work on the RST documentation in the latest version https://github.com/OCA/OpenUpgrade/tree/11.0/odoo/openupgrade/doc/source. This is rendered on https://doc.therp.nl/openupgrade automatically on every update.

**Comment by js-landoo** [comment]
Perfect! 
Tomorrow we will try to start updating rst files.

**Comment by js-landoo** [comment]
Hi @StefanRijnhart 

It was not the aim of this issue but we have improved a bit migrate.py code in order to do it able to migrate databases until version 11. Actual version works until version 10 and fails with 11.
Please check this PR: https://github.com/OCA/OpenUpgrade/pull/1370 [FIX] to be able to detect if migrate.py was successful

**Comment by js-landoo** [comment]
Hi @StefanRijnhart 

We have pushed our first PR to update official documentation.
This one just changes a a bit actual documentation structure and some small details.

Please review it: https://github.com/OCA/OpenUpgrade/pull/1371 [IMP] improve the documentation for manual upgrade

Hope you agree with this changes.

**Comment by js-landoo** [comment]
And finally, "Sstep by step guide" has been pushed in https://github.com/OCA/OpenUpgrade/pull/1372
[IMP] add a guide how to setup pycharm to perform a migration

Hope you like it

**Comment by pedrobaeza** [comment]
Closing as there are now PRs opened.
