### ISSUE TITLE
Built-in menus and actions after upgrade

### ISSUE THREAD

**Issue by yann-papouin** [OCA/OpenUpgrade#138]
This issue is a question about post-upgrade cleaning.

After upgrading a database, some menu items are still the one created by the module at the first install.
But after a major upgrade, some action settings have changes (eg: from 6.1 the crm helpdesk action does not have the same context for the search view) but are not updated since the action already exists.

So how are you handling this ? Are you manually deleting menu items or actions and next re-updating modules ?

**Comment by pedrobaeza** [comment]
That should be handled in the corresponding migration script, to avoid such manual operations, although a workaround can be what you are saying.

**Comment by yann-papouin** [comment]
I try deleting items/actions but it leads to unexpected side effects (my database modules update is now trying to install demo data ...).

So if it should be handled in the migration script, that means that it should be reported in the "openupgrade_analysis.txt" file but it looks like to be a hard task.
