### ISSUE TITLE
Bad SQL request at migration tool - execution possible in postgres database

### ISSUE THREAD

**Issue by piapatricktresp** [OCA/OpenUpgrade#1380]
Impacted versions: v11

Steps to reproduce: use a odoo 10 database and try to migrate to v11

Current behavior: stops at a bad query:
ALTER TABLE "hr_holidays" ADD FOREIGN KEY ("manager_id") REFERENCES "hr_employee"("id") ON DELETE set null'
ERROR: column "manager_id" referenced in foreign key constraint does not exist

Expected behavior: execute query

Video/Screenshot link (optional):

I am working on a database upgrade from v10 to v11 the last couple of days. i got stuck many times, because there were some table datas missing or some constrains violated, which i could get passed.

But now i get an error with this statement:

ALTER TABLE "hr_holidays" ADD FOREIGN KEY ("manager_id") REFERENCES "hr_employee"("id") ON DELETE set null'
with this ERROR: column "manager_id" referenced in foreign key constraint does not exist

If i execute this SQL-Query direct in the database i do not get any errors. Since i have no clue where in the migration tool this query is created, i do not see any chance to move forward. Do you have any hints, what to do?

( i have the community edition so i can not use the service from odoo )

Thanks!

Patrick

**Comment by pedrobaeza** [comment]
hr_holidays module is still not migrated, so the error should come from that. Please check current coverage in #1005.

**Comment by piapatricktresp** [comment]
ok thank you very much for this hint!

**Comment by pedrobaeza** [comment]
`hr_holidays` is already migrated

**Comment by BT-fschubert** [comment]
Got the same with hr_holidays commit - any idea why this still happens?

**Comment by pedrobaeza** [comment]
Check if other third party module adds the same column
