### ISSUE TITLE
[9.0] Moves dated on the last day of a period are re-written to the first day

### ISSUE THREAD

**Issue by alexis-via** [OCA/OpenUpgrade#1407]
When migrating from v8 to v10, one of my users found that some moves that were dated on the last day of a period are re-written to the first day of a period !!!
I think the bug is located here: https://github.com/OCA/OpenUpgrade/blob/9.0/addons/account/migrations/9.0.1.1/post-migration.py#L1102

This SQL request takes into account the case where the move is dated at the first day and at the last day of the period, whereas it should only take into account the moves that are OUT of the period. So it seems to me that the SQL request should be ("<=" changed to "<" and "=>" changed to ">":

```
UPDATE account_move am
        SET date = ap.date_start
        FROM account_period ap
        WHERE am.period_id = ap.id
            AND (am.date < ap.date_start OR am.date > ap.date_stop)"""
```

I haven't tested the fix above, but the bug seems obvious. If I understand this SQL request correctly, it seems that ALL account moves dated at the last day of a period are re-written to the first day of the same period. It was introduced by @pedrobaeza in September 2017 in this commit: https://github.com/OCA/OpenUpgrade/commit/62d391560e80037f8bfe8925d756e804bdc3a89d

It is a very important bug because it modifies the date of a valid account move, which should never happen.

**Comment by alexis-via** [comment]
After I made a script to compare move dates between the old v8 database and the production v10 database and fix the modified dates, I can confirm the problem described above: all move dates dated at the last day of the period are re-written at the first day of the period.

**Comment by StefanRijnhart** [comment]
Thanks for reporting! I committed your fix as https://github.com/OCA/OpenUpgrade/pull/1408. I'm closing this as it's tracked on the PR.
