### ISSUE TITLE
[9.0] orm code has changed

### ISSUE THREAD

**Issue by rousseldenis** [OCA/OpenUpgrade#1409]
Following this https://github.com/odoo/odoo/commit/ea23a1ac8c6c68520f4f02a2f35ef7ab474b868a

Some function signature have changed. It should be updated in OpenUpgrade too.

@StefanRijnhart @pedrobaeza

**Comment by pedrobaeza** [comment]
That's not a problem on the current situation, as OpenUpgrade keeps an "outdated" version of Odoo. If we merge upstream changes, then we would need to deal with the conflicts on that merge, but it would be solved on the fly on that operation, but right now, I don't find any need for making that update (taking into account that you shouldn't use OpenUpgrade for a production server, only for migrating).

Thanks any way for notifying this.

**Comment by StefanRijnhart** [comment]
Indeed. The impact on the database scheme is covered by the recommendation to perform an update --all on the production instance (using odoo/odoo or oca/ocb) as well after applying OpenUpgrade.
