### ISSUE TITLE
v9 migration "Killed" when converting to attachment field image from model res.partner

### ISSUE THREAD

**Issue by dreispt** [OCA/OpenUpgrade#1411]
I'm trying a v8 -> v9 migration, and process is killed at this step, after a couple of minutes of intense CPU activity.

```
2018-06-29 11:54:16,446 24210 INFO v8dr-mig OpenUpgrade: Converting to attachment field image from model res.partner stored in column image
Killed
```
The `res.partner` table had 27k records, and 5k have `image` field with data.
I'm sure I'm not running with workers. I still tried increasing the `limit_time_*` options, but with no success.

**Comment by pedrobaeza** [comment]
Yes, you have to run the migration without workers for being sure no cpu time limit is applied.

**Comment by dreispt** [comment]
The problem is not running time; I repeated the process and it gets killed in less than a minute.
Digging deeper it could be a memory problem caused by a [`fetchall`](https://github.com/OCA/openupgradelib/blob/9642400f5abd5afce2cb4f90e3a987e50918587d/openupgradelib/openupgrade_90.py#L56) statement on  a large dataset.
I'm still investigating.

**Comment by pedrobaeza** [comment]
Well, that can be other option indeed. Be generous with your memory limits also.

**Comment by dreispt** [comment]
I just noticed that the `res_partner.image_medium` was processed, and the problem is with `res_partner.image`. I may have a few some unnecessarily large images in the database. Maybe spotting and removing them can fix the probem.

**Comment by pedrobaeza** [comment]
Well, I have migrated other DBs with large images (~5 MB), but I don't know your current resources.

**Comment by dreispt** [comment]
I wrote a fix to handle my case: https://github.com/OCA/openupgradelib/pull/106
