### ISSUE TITLE
[11.0] stock: Run Scheduler not created/migrated

### ISSUE THREAD

**Issue by davidtranhp** [OCA/OpenUpgrade#1420]
### Impacted versions:
11.0
### Steps to reproduce:
Finish stock migration
### Current behavior:

Server action `Run mrp scheduler` still there while the new one `Procurement: run scheduler` is absent

The same thing happend to scheduled actions

### Expected behavior:
`Run mrp scheduler` should be replaced with the new one `Procurement: run scheduler`. See: https://github.com/odoo/odoo/blob/21b2617d6fea4e2f220b13d0623996045a2b7b9d/addons/stock/data/stock_sequence_data.xml#L53

**Comment by pedrobaeza** [comment]
Fixed in b409b05
