### ISSUE TITLE
[11.0] report_ir_model_overview error

### ISSUE THREAD

**Issue by travish2** [OCA/OpenUpgrade#1424]
Impacted versions: v11

Steps to reproduce: Run upgrade with OpenUpgrade, export database and import to v11. Run -u all from command line with v11

Current behavior: Errors out with: 
```
    " you can't define a `%s` record with this ID." % (xml_id, imd_model, model)
odoo.tools.convert.ParseError: "External ID conflict, report_ir_model_overview already refers to a `ir.actions.report.xml` record, you can't define a `ir.actions.report` record with this ID." while parsing /odoo-11/odoo-11-server/addons/base/ir/ir_model_report.xml:9, near
<report id="report_ir_model_overview" string="Model Overview" model="ir.model" report_type="qweb-pdf" name="base.report_irmodeloverview" file="base.report_irmodeloverview"/>

```

Expected behavior: Upgrade modules

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
This seems something bad on the original DB, but without the full migration log, it's difficult to even say anything more.
