### ISSUE TITLE
Modules not found on upgraded 7.0 -> 8.0 database

### ISSUE THREAD

**Issue by ericnjogu** [OCA/OpenUpgrade#143]
Hi, selecting the migrated database, I am getting messages as those below when I run:
odoo.py -u all --config=/etc/openerp/odoo-server.conf
What could be the issue?

INFO ? openerp: addons paths: ['/home/openerp/.local/share/Odoo/addons/8.0', u'/usr/local/odoo/odoo/addons', '/usr/local/odoo/local/lib/python2.7/site-packages/openerp-8.0-py2.7.egg/openerp/addons']
...
ERROR springfresh_odoov8 openerp.modules.graph: module account_cancel: Unmet dependencies: account
ERROR springfresh_odoov8 openerp.modules.graph: module sale_journal: Unmet dependencies: sale_stock
...

**Comment by pedrobaeza** [comment]
You should have a chain of dependencies not solved of migration scripts not correctly ended. You should navigate through all the log to see where is the problem, and after several attempts and when you solve the other issues, these messages will dissapear.

I close this issue meanwhile.

**Comment by ericnjogu** [comment]
Thanks,  I found the log file with an error that may be related to https://github.com/odoo/odoo/issues/2954.

**Comment by pedrobaeza** [comment]
It is recommended to use Linux environment for anything related with Odoo, because Windows platform has a lot of problems with dependencies packaging.

**Comment by ericnjogu** [comment]
I am actually on Debian Linux 7 (upgraded from 6).

I think the problem could be that while I have postgresql 9.1, I have not
successfully run the cluster upgrade tool for the previous 8.4 version.

**Comment by ericnjogu** [comment]
Sorry, I am actually running postgresql-8.4 :(
