### ISSUE TITLE
8 to 9: date_maturity required on account move line

### ISSUE THREAD

**Issue by sbidoul** [OCA/OpenUpgrade#1437]
Impacted versions:

8 to 9

Steps to reproduce:

After migration, the not null constraint on date_maturity cannot be set.

Should the migration script set date_maturity = date if not set?

**Comment by StefanRijnhart** [comment]
Seems like a sensible solution!

**Comment by sbidoul** [comment]
@rousseldenis

**Comment by rousseldenis** [comment]
I think it's not dangerous at all to do so.
In v8, date_maturity is either False or computed through payment term.
See https://github.com/odoo/odoo/blob/4045e4fe66fc18f3e223a99c781a08a17ee49f60/addons/account/account_move_line.py#L743

In v9, the required is protected through create() implementation and get, as @sbidoul said, the 'date' value if not defined.
https://github.com/odoo/odoo/blob/b1a373c6649b206dd417b108a39dd214dcb106bc/addons/account/models/account_move.py#L1072

**Comment by pedrobaeza** [comment]
Yes, that's the proper solution

**Comment by pedrobaeza** [comment]
Any way, I haven't found this problem in any of the migrated DBs. I wonder why...

**Comment by sbidoul** [comment]
Done in #1454
