### ISSUE TITLE
[11.0] Error when access Scheduled Actions view

### ISSUE THREAD

**Issue by novawish** [OCA/OpenUpgrade#1438]
Impacted versions:
11.0
Steps to reproduce:
Migrated database from Odoo 10.0 to 11.0. When access Scheduled Action, it will raise an error
![image](https://user-images.githubusercontent.com/31387997/42449652-b4624f1c-83ab-11e8-8d84-e4dcc087cf2f.png)
Current behavior:
This view had some deleted fields (`model`, `function`, `args`...) and is replaced by `ir_cron_view_form` in Odoo 11.0 but somehow it still exists in the migrated DB
![image](https://user-images.githubusercontent.com/31387997/42449580-648dda60-83ab-11e8-88e0-57b2664017c1.png)

Expected behavior:
View in the screenshot above should be deleted and use the new one instead

**Comment by pedrobaeza** [comment]
Remove it manually for solving the problem. This is better described in a general way in #577, so closing in favor of that one.
