### ISSUE TITLE
[11.0] stock: merge_quants caused memory exhausted ERROR

### ISSUE THREAD

**Issue by davidtranhp** [OCA/OpenUpgrade#1445]
#### Impacted versions:
11
#### Steps to reproduce:
Do migration for a database of ~500K records of stock.quant on a laptop with the following config:

- Core i7 7th generation
- 16GB RAM DDR4
- SSD

#### Current behavior:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/openupgradelib/openupgrade.py", line 1430, in wrapped_function
    if use_env2 else cr, version)
  File "/home/tuan/git/openupgrade11/addons/stock/migrations/11.0.1.1/end-migration.py", line 31, in migrate
    merge_quants(env)
  File "/home/tuan/git/openupgrade11/addons/stock/migrations/11.0.1.1/end-migration.py", line 25, in merge_quants
    env, 'stock.quant', quants[1:].ids, quants[0].id, QUANT_MERGE_OPS,
  File "/usr/local/lib/python3.6/dist-packages/openupgradelib/openupgrade_merge_records.py", line 347, in merge_records
    _change_reference_refs_orm(*args)
  File "/usr/local/lib/python3.6/dist-packages/openupgradelib/openupgrade_merge_records.py", line 192, in _change_reference_refs_orm
    records = model.search(domain)
  File "/home/tuan/git/openupgrade11/odoo/addons/base/ir/ir_ui_menu.py", line 130, in search
    menus = super(IrUiMenu, self).search(args, offset=0, limit=None, order=order, count=False)
  File "/home/tuan/git/openupgrade11/odoo/models.py", line 1484, in search
    res = self._search(args, offset=offset, limit=limit, order=order, count=count)
  File "/home/tuan/git/openupgrade11/odoo/models.py", line 3791, in _search
    self._cr.execute(query_str, where_clause_params)
  File "/home/tuan/git/openupgrade11/odoo/sql_db.py", line 155, in wrapper
    return f(self, *args, **kwargs)
  File "/home/tuan/git/openupgrade11/odoo/sql_db.py", line 232, in execute
    res = self._obj.execute(query, params)
psycopg2.ProgrammingError: memory exhausted at or near "("
LINE 1: ...((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((...
                                                             ^
```
See more details in the attached error log [stock_mig_error.zip](https://github.com/OCA/OpenUpgrade/files/2184304/stock_mig_error.zip)

**Comment by pedrobaeza** [comment]
What is the work memory? Are you using default 4 MB value? That can be the reason.

Look this improvement for the performance of the quant removal: https://github.com/OCA/OpenUpgrade/pull/1446

**Comment by davidtranhp** [comment]
Yes, the work_mem was 4MB. I will retry with more memory to see if it could fix this. I will let you know then. Tks @pedrobaeza 
BTW, is it possible to execute the native method `_merge_quants`: https://github.com/OCA/OpenUpgrade/blob/945c1a28784104790d203c2e217859d2543cab9f/addons/stock/models/stock_quant.py#L296

**Comment by pedrobaeza** [comment]
You can execute it in the shell copying/pasting the code.

FYI, the conflicting code is:

https://github.com/OCA/openupgradelib/blob/bd93c3659de58a219f54c43e98fe537c7feedbce/openupgradelib/openupgrade_merge_records.py#L189-L192

as it creates a very long expression if you are merging together a lot of quants (for example, those on customer location). For this quant case, you can even remove the call to that function, as there are usually no interesting reference fields to fill.

**Comment by davidtranhp** [comment]
@pedrobaeza I changed the work_mem to 64MB but it did not help. Later, I changed to 512MB, the problem has gone. I think this issue could be closed now.

BTW, my team and I would like to start contribution to OpenUpgrade (i.e. fifo stock_account, mrp, etc). Would you mind telling me how to start. Do my team and I need to sign something with OCA to contribute our code to OpenUpgrade?
FYI, Odoo is not new to us, but things related to openupgradelib and OCA is new to us.

**Comment by pedrobaeza** [comment]
About using standard `_merge_quants` method, that's not enough, as all the x2x references are not updated. It has been conceived for an specific case where you just have created the quant (and can have side effects if you add more fields to quant object, so I don't like it very much).

**Comment by davidtranhp** [comment]
By increasing work_mem, the issue is solved. I am closing this.

**Comment by ajmalj** [comment]
> By increasing work_mem, the issue is solved. I am closing this.

How much memory should we allocate to solve this issue. I have 8 gb ram in total.

**Comment by pedrobaeza** [comment]
It depends on your DB size. Try with the highest available one.

**Comment by ajmalj** [comment]
> It depends on your DB size. Try with the highest available one.

Thanks for the reply. Tried with recommended value from pg tune(5MB). Still same issue.

**Comment by pedrobaeza** [comment]
That's too low. Try 512

**Comment by ivantodorovich** [comment]
Hi,

I'm facing the same issue.
I've tried with multiple pg settings, currently this one:

```
work_mem=1GB
effective_cache_size=10GB
maintenance_work_mem=2GB
shared_buffers=4GB
wal_buffers=16MB
min_wal_size=2GB
max_wal_size=8GB
max_worker_processes=8
```

Still no luck

```
odoo_1  | 2020-04-09 08:45:11,463 1 ERROR mig-11.0 OpenUpgrade: memory exhausted at or near "("
odoo_1  | LINE 1: ...((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((...
odoo_1  |                                                              ^
odoo_1  | Traceback (most recent call last):
odoo_1  |   File "/home/odoo/.local/lib/python3.5/site-packages/openupgradelib/openupgrade.py", line 1778, in wrapped_function
odoo_1  |     if use_env2 else cr, version)
odoo_1  |   File "/home/odoo/src/odoo/addons/stock/migrations/11.0.1.1/end-migration.py", line 31, in migrate
odoo_1  |     merge_quants(env)
odoo_1  |   File "/home/odoo/src/odoo/addons/stock/migrations/11.0.1.1/end-migration.py", line 25, in merge_quants
odoo_1  |     env, 'stock.quant', quants[1:].ids, quants[0].id, QUANT_MERGE_OPS,
odoo_1  |   File "/home/odoo/.local/lib/python3.5/site-packages/openupgradelib/openupgrade_merge_records.py", line 539, in merge_records
odoo_1  |     _change_reference_refs_orm(*args)
odoo_1  |   File "/home/odoo/.local/lib/python3.5/site-packages/openupgradelib/openupgrade_merge_records.py", line 212, in _change_reference_refs_orm
odoo_1  |     records = model.search(domain)
odoo_1  |   File "/home/odoo/src/odoo/odoo/addons/base/ir/ir_ui_menu.py", line 130, in search
odoo_1  |     menus = super(IrUiMenu, self).search(args, offset=0, limit=None, order=order, count=False)
odoo_1  |   File "/home/odoo/.local/lib/python3.5/site-packages/odoo/models.py", line 1494, in search
odoo_1  |     res = self._search(args, offset=offset, limit=limit, order=order, count=count)
odoo_1  |   File "/home/odoo/.local/lib/python3.5/site-packages/odoo/models.py", line 3849, in _search
odoo_1  |     self._cr.execute(query_str, where_clause_params)
odoo_1  |   File "/home/odoo/.local/lib/python3.5/site-packages/odoo/sql_db.py", line 155, in wrapper
odoo_1  |     return f(self, *args, **kwargs)
odoo_1  |   File "/home/odoo/.local/lib/python3.5/site-packages/odoo/sql_db.py", line 232, in execute
odoo_1  |     res = self._obj.execute(query, params)
odoo_1  | psycopg2.ProgrammingError: memory exhausted at or near "("
odoo_1  | LINE 1: ...((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((...
odoo_1  |                                                              ^
```

**Comment by pedrobaeza** [comment]
You can improve the openupgradelib merge method for not requiring such expression. It's very marginal as it refers to reference fields, which are weird.

**Comment by legalsylvain** [comment]
@ivantodorovich : I'm facing the same problem.

**Comment by ivantodorovich** [comment]
Yes, I'm currently testing with this change: https://github.com/druidoo-dev/openupgradelib/commit/aea7290b3b4b1dbdaef79ffcf527d78c117e6a30

Don't know if it'll fix the memory issue, will know in a few mins

**Comment by ivantodorovich** [comment]
Apparently it worked, even with default values for `work_mem`.
PR here: https://github.com/OCA/openupgradelib/pull/203

@legalsylvain
