### ISSUE TITLE
column "restrict_partner_id" does not exist : 7.0 -> 8.0 migration

### ISSUE THREAD

**Issue by ericnjogu** [OCA/OpenUpgrade#145]
Hi, I am getting the following error. Please help.

2014-12-01 13:02:15,766 32121 ERROR springFresh_migrated openerp.sql_db: Programming error: column "restrict_partner_id" referenced in foreign key constraint does not exist
, in query ALTER TABLE "stock_move" ADD FOREIGN KEY ("restrict_partner_id") REFERENCES "res_partner" ON DELETE set null

**Comment by hbrunn** [comment]
you should find a backtrace of this in your log, without it it will be very difficult to help you. You should also indicate which PRs you merged if any. If you didn't merge anything, try again with at least the stock and the procurement PR applied

**Comment by ericnjogu** [comment]
Thank you. A section of the log is available at http://pastebin.com/Atd584PY.

I have not merged any PRs. How can I do that?

**Comment by ericnjogu** [comment]
Ok, I see what you mean by PR - pull request :)

Will give it a try.

**Comment by ericnjogu** [comment]
Applied the stock and procurement PRs and got another error - http://pastebin.com/GKUbSM1C

**Comment by StefanRijnhart** [comment]
Did you start the upgrade on a fresh copy of your 7.0 database? Note that the work on stock etc. is still work in progress.

**Comment by ericnjogu** [comment]
Yes, I copied the production database and attempted the upgrade on the
copy.

**Comment by messakali** [comment]
facing same error, any hints?

Thanks

**Comment by ericnjogu** [comment]
I got over the initial reported error by cloning OpenUpgrade and applying
the stock pull request by onesteinbv.

After that I got another error that I have not resolved yet.

facing same error, any hints?

Thanks
