### ISSUE TITLE
Fetch correct balance report after migration

### ISSUE THREAD

**Issue by StefanRijnhart** [OCA/OpenUpgrade#1457]
Possibly not a technical issue, but I am struggling to get the correct balance report from Odoo 10.0 after a migration from Odoo 7.0. The closing entries are all properly removed, so we should have rolling reports.

The thing is, if I request the balance report with a start date I don't get the entries on the balance account from before the start date and if I request the balance report without a start date then the result of all previous years is present on the balance report.

It seems to me that this is what the setting 'include_initial_balance' is for on the accounts' user types: it is set correctly in my migrated database (True for balance accounts, False for profit/loss accounts). But it's use is being voided by the check on 'strict_range' in https://github.com/odoo/odoo/blob/10.0/addons/account/models/account_move.py#L1329. If I set strict_range to False here: https://github.com/odoo/odoo/blob/10.0/addons/account/wizard/account_report_common.py#L24, regardless of the setting of date_from, I get the correct results. But I'm doubting that such a bug could go unnoticed for 3 major Odoo releases (code seems unchanged in Odoo 11).

What am I missing here?

**Comment by pedrobaeza** [comment]
I think nobody is using standard reports,  and with OCA financial reports this doesn't happen. It only needs include_initial_balance correctly set.

**Comment by StefanRijnhart** [comment]
That is one possible explanation, indeed.

**Comment by StefanRijnhart** [comment]
But @pedrobaeza which module to use for Balance Sheet and Profit/Loss accounts? They have always been famously missing from account_financial_report_qweb.

**Comment by pedrobaeza** [comment]
We are using mis_builder with specific templates on our localization: https://github.com/OCA/l10n-spain/tree/11.0/l10n_es_mis_report

**Comment by StefanRijnhart** [comment]
Note that the Odoo documentation mentions "Once the accountant/bookkeeper has created the journal entry to allocate the Current Year Earnings..."[1], implying that some end of year entry is still necessary. But with strict_range set to False it is not. Maybe the documentation was written by a consultant who was confronted with the bug?

[1] https://www.odoo.com/documentation/user/9.0/accounting/others/adviser/fiscalyear.html

**Comment by StefanRijnhart** [comment]
I've created https://github.com/odoo/odoo/pull/25915 upstream.

**Comment by StefanRijnhart** [comment]
Thanks @pedrobaeza for sharing how you generate your financial reports.

**Comment by StefanRijnhart** [comment]
Interestingly, the Enterprise edition does not allow to set the report start date and relies 100% on a closing entry to allocate the current year earnings. I don't have my hopes up for my PR :-(

**Comment by JordiBForgeFlow** [comment]
@StefanRijnhart A balance sheet report by definition is described as the financial status of a company from the date it was created until a specific date. So it does not really make sense for such report to include or to use a start date. In the spanish community module `l10n_es_mis_report` there is no such thing as start date in the balance sheet report.

**Comment by StefanRijnhart** [comment]
Thanks @jbeficent for your comment. It still means that the balance report is incorrect until the current year result entry is created for the previous fiscal year but so be it then.

**Comment by hbrunn** [comment]
@StefanRijnhart @pedrobaeza @jbeficent I'm of a mind to propose Stefan's patch to OCB 10, 11, 12 anyways, as I don't see how core's balance report can be usable otherwise, and it won't affect anyone using different reporting tools.
With the patch, this basically makes the balance accounts ignore date selections anyways, and the date you select then is only passed to the profit and loss subreport.
Or am I overlooking a case where the patch might hurt?

**Comment by StefanRijnhart** [comment]
I have not pursued the patch further, as I did not want to take a different path from best practices. In the case of the migrated database, I had the customer move the profit of each year to an 'unallocated profit' account on the last day of each fiscal year, which as I understand is what closing the fiscal year closing is all about in recent Odoo versions.

Technically, I think it can still work to change the reporting itself but I would not like to see it in OCB only and not in Odoo without more support from community members that have good knowledge about accounting.

**Comment by hbrunn** [comment]
feared an answer like that, thanks. I think your patch is the way things should go, it just makes sense to me. Will keep a private patch for this then

**Comment by StefanRijnhart** [comment]
Sure. I'll be sure to revisit the patch myself on a next migration. If it works as expected, it's something to discuss at a next code sprint.
