### ISSUE TITLE
[11.0] Website page which are not used in menu directly are not linked to the new Website Page model

### ISSUE THREAD

**Issue by karan-dreambits** [OCA/OpenUpgrade#1488]
Impacted versions:

v10 to V11 Migration for Website module

Steps to reproduce: 

- Create few new pages in v10 Website but don't add them in Menu.
  Just keep their link in some other content
- Migrate to v11
- The Page without any menu link is now not available as website. Neither accessible via url or via Pages menu. But record in ir_ui_view menu is there

I suspect that the query [here](https://github.com/OCA/OpenUpgrade/blob/11.0/addons/website/migrations/11.0.1.0/post-migration.py#L15) in migration script is the cause of issue. 

I also have a fix which I tested locally and making PR using same 
But I am not much experienced in migration script so I am not sure if my issue and even the solution is valid or not

**Comment by karan-dreambits** [comment]
PR for this issue: https://github.com/OCA/OpenUpgrade/pull/1489

**Comment by pedrobaeza** [comment]
Closing as there's a PR now. No need for opening an issue if you are going to open a PR. Any way, thanks for the investigation and for the patch, which is pretty good.

**Comment by karan-dreambits** [comment]
@pedrobaeza Thank you for such quick response
