### ISSUE TITLE
[9.0 ->10.0] running migration missing migrations files at /var/tmp/openupgrade/10/addons/ directory

### ISSUE THREAD

**Issue by psugne** [OCA/OpenUpgrade#1502]
Several times I done v9 -> v10 migration successfully but the second time migration fails. I checked and noticed that the reason was missing module migration files at
/var/tmp/openupgrade/10/addons/sales_team/migrations/10.0.1.0 directory. For example sales_team migration directory contains only these files:

_noupdate_changes.xml_
_post-migration.pyc_
_pre-migration.py_

I tried to delete /var/tmp/openupgrade/ directory and run migration script again. Everything was ok but I would like to understand:

**1. What could impact this situation? Because missing files were not deleted manually.
2. What it would be recommended way to restore missing migrations files?**

**Comment by pedrobaeza** [comment]
That's because the scripts delete that things, but this is not something on OpenUpgrade itself. See script internals for performing the same operation manually (basically, cloning this repository in the proper branch).
