### ISSUE TITLE
Error migration in odoo 11 stock module due to raise ValidationError(_('A serial number should only be linked to a single product.'))

### ISSUE THREAD

**Issue by Rathnakreeswaran** [OCA/OpenUpgrade#1506]
Impacted versions:
11.0
Steps to reproduce:

Current behavior:
OpenUpgrade: stock: error in migration script stock/migrations/11.0.1.1/end-migration.py: ('A serial number should only be linked to a single product.', None)
File "/var/tmp/addons/stock/models/stock_quant.py", line 86, in check_quantity
raise ValidationError(('A serial number should only be linked to a single product.'))
odoo.exceptions.ValidationError: ('A serial number should only be linked to a single product.', None)
2018-06-19 11:51:51,671 3169 INFO odoo.service.server: Initiating shutdown
2018-06-19 11:51:51,671 3169 INFO odoo.service.server: Hit CTRL-C again or send a second signal to force the shutdown.

Expected behavior:
How to solve this problem to run migration?
Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
The problem is in your DB, where you have more than one quant for the same lot of a product defined with tracking = By serial numbers.

**Comment by Rathnakreeswaran** [comment]
Thanks for your reply @pedrobaeza

**Comment by Rathnakreeswaran** [comment]
Dear @Pedrobaeza

stock_quant table have many2one relationship with stock_production_lot. so here one lot_id can be placed in many quants based on above relation.so please suggest me how can I solve this issue?

**Comment by Rathnakreeswaran** [comment]
Dear @Pedrobaeza

stock_quant table have many2one relationship with stock_production_lot. so
here one lot_id can be placed in many quants based on above relation.so
please suggest me how can I solve this issue?

**Comment by pedrobaeza** [comment]
ORM code prevents this situation to happen. The problem can be if you change the tracking when you have already quants created. As said, you have to fix your DB or switch tracking to lot instead of serial number.

**Comment by Rathnakreeswaran** [comment]
Thanks @pedrobaeza

**Comment by trapchik** [comment]
pedrobaeza, thank you for pointing to the correct table (stock_quant)
I found double entry and removed one
