### ISSUE TITLE
from odoo.report import report_swx shows error in odoo 11

### ISSUE THREAD

**Issue by Rathnakreeswaran** [OCA/OpenUpgrade#1508]
Impacted versions:
11.0
Steps to reproduce:

Current behavior:
ImportError : No module named odoo.report
Expected behavior:
How to solve this issue??
Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Please don't open issues that has nothing to do with OpenUpgrade. Migrate your module properly. Some tips are in https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0
