### ISSUE TITLE
account bank statement migration issues

### ISSUE THREAD

**Issue by pankk** [OCA/OpenUpgrade#151]
Hi,

For the account bank statement migrations we are facing some issues. I was wondering if anyone could to share their findings on the following issues:
The bank statements when in state open, when migrated, cannot be reconciled.
Also statements which are canceled after migrating cannot be used anymore.

**Comment by pedrobaeza** [comment]
You are not indicating which version of OpenUpgrade you are using. It seems that the migration is not completed for that models (account.bank.statement and childrens).

**Comment by pankk** [comment]
Thanks for the reply. I'm using version 8.0 of OpenUpgrade.

**Comment by pedrobaeza** [comment]
All the work on statement models seems to be done (https://github.com/OpenUpgrade/OpenUpgrade/blob/8.0/addons/account/migrations/8.0.1.1/openupgrade_analysis_work.txt), and nothing related to states and so on, so I don't what's happening.. Maybe a custom module?

**Comment by pankk** [comment]
Fixed in PR #167. Simply made a legacy column for account_bank_statement.account_id. See PR for more information.
