### ISSUE TITLE
Showing error "ModuleNotFoundError: No module named 'passlib'" although I already have that python library installed

### ISSUE THREAD

**Issue by braincrewapps** [OCA/OpenUpgrade#1517]
**Impacted versions:** Migrating from Odoo 10 to 11

**Steps to reproduce:** 

1) I got the script from the below

wget https://raw.githubusercontent.com/OCA/OpenUpgrade/HEAD/scripts/migrate.py

2) After that, I run the following command to start the migration, but its showing passlib library error. 

python migrate.py --config=[my odoo 10 config file path] --database=[my odoo 10 database name] --run-migrations=11.0

**Error:**
From git://github.com/OpenUpgrade/OpenUpgrade
 * branch            11.0       -> FETCH_HEAD
Already up-to-date.
From https://github.com/OCA/openupgradelib
 * branch            master     -> FETCH_HEAD
Already up-to-date.
copying database odoo_10_inventory to odoo_10_inventory_migrated...
Copying the database using 'with template'
Failed, fallback on creating empty database + loading a dump
sh: pg_dump: command not found
sh: pg_restore: command not found
running migration for 11.0
Traceback (most recent call last):
  File "/var/tmp/openupgrade/11.0/server/odoo-bin", line 5, in <module>
    import odoo
  File "/private/var/tmp/openupgrade/11.0/server/odoo/__init__.py", line 84, in <module>
    from . import modules
  File "/private/var/tmp/openupgrade/11.0/server/odoo/modules/__init__.py", line 8, in <module>
    from . import db, graph, loading, migration, module, registry
  File "/private/var/tmp/openupgrade/11.0/server/odoo/modules/graph.py", line 10, in <module>
    import odoo.tools as tools
  File "/private/var/tmp/openupgrade/11.0/server/odoo/tools/__init__.py", line 8, in <module>
    from .config import config
  File "/private/var/tmp/openupgrade/11.0/server/odoo/tools/config.py", line 17, in <module>
    from passlib.context import CryptContext
ModuleNotFoundError: No module named 'passlib'

I'm running Odoo on MAC El Caption OS and had set up "virtualenv"  to install python and other dependent libraries.

I've already installed passlib and running Odoo 11 successfully since long, so can not understand why the migration script is showing this error. 

Please help here to resolve this issue.

**Comment by StefanRijnhart** [comment]
I'm sorry, but this is not related to OpenUpgrade. You have to make sure that the required python libraries are available in your environment.

**Comment by braincrewapps** [comment]
@StefanRijnhart,

How have you derived the conclusion that issue is not related to OpenUpgrade? I'm NOT newbie in Odoo that does not understand the meaning of such error. I already mentioned that I've already installed passlib since very long time and my Odoo setup 8, 9, 10 and 11 is working fine without showing any such python library dependency error.

I only get this error when I run OpenUpgrade migration script, so definitely its related to OpenUpgrade.

Anyway, for your satisfaction, I tried to "re-install" passlib library today again and below is the log 

>> pip install passlib
Requirement already satisfied: passlib in ./odoo2.7-env/lib/python2.7/site-packages (1.6.5)

I urge to reopen this ticket again and requesting a help to resolve this issue.

**Comment by cubells** [comment]
@braincrewapps You are trying to upgrade to version 11.0 that uses python3, aren't you?
You are installing passlib in python 2.
Can you try to run `pip3 install passlib` ?
Or better: run `pip3 install -r requirements.txt` on Openupgrade home dir.
I think Stefan is right: It's a environment setup problem.

**Comment by TurhanErgene** [comment]
I have the same issue even though I tried both `pip3 install passlib` and `pip3 install -r requirements.txt` , another thing is I can find 'passlib' in my  'site-packages'

**Comment by eksungt** [comment]
This problem is from the passlib version 
pip3 uninstall passlib
pip3 install passlib==1.7.1

**Comment by JaylonNichols** [comment]
I am getting the same error when running my FastAPI server.
I am using windows 11 with python 3.11.1
I get this when I run `pip list`
```
Package           Version
----------------- -------
passlib           1.7.4
```
And here is the error:
```ModuleNotFoundError: No module named 'passlib'```

I do not get this error if I run ```import passlib``` in another file I only get this error when running my FastAPI server with 
```uvicorn app.main:app --reload```

**Comment by JaylonNichols** [comment]
I fixed this error by installing `passlib` in my root directory. Which is very wired because `passlib` is in my site-packages in my vertal enviroment

**Comment by alexmaugm** [comment]
@JaylonNichols Can you explain in detail how you could solve it please! :)

**Comment by DhirajsGithub** [comment]
I solved the issue
I think it's in fastapi which is not allowing passlib and bcrypt
so I install passlib and bcrpt in my system and not in fast api environment
then I made another file naming hasing and for that file I changed the python interpreter to /opt/anaconda3/bin/python

**Comment by ikotun-dev** [comment]
@JaylonNichols Can you explain in detail how you could solve it please! :)

**Comment by ikotun-dev** [comment]
@JaylonNichols Can you explain in detail how you could solve it please

**Comment by mdhifta** [comment]
if you user python 3.8 just install passlib 1.7.4

pip install passlib==1.7.4

it works for me.

**Comment by siegfried0111** [comment]
@JaylonNichols @DhirajsGithub 
Hi, please check uvicorn is installed in your virtual environment. I open a new project and pip fastiapi in my virtual env, but some how uvicorn not installed in the right place. I use `where uvicorn` in win (or `where uvicorn` in linux) to check the install path, and not in my virtual env path. so I pip install uvicorn in my virtual env to solve the issue.

**Comment by faruniki** [comment]
for anyone who have the same issue like this, you can use "python -m pip install passlib" at your teminal/cmd. my problem is solved.
