### ISSUE TITLE
[v7 -> V8] try to migrate but ...

### ISSUE THREAD

**Issue by clikinfo** [OCA/OpenUpgrade#152]
Hi all,
I try to migrate my Openerp V7

I type the command line :

python /home/desktop/migrate.py --config=/etc/openerp-server.conf --database=CLIKINFO --run-migrations=8.0

and my result is :

python /home/desktop/migrate.py --config=/etc/openerp-server.conf --database=CLIKINFO --run-migrations=8.0
linking server/addons to /var/tmp/openupgrade/8.0/addons
getting git://github.com/OpenUpgrade/OpenUpgrade.git
error: unknown option `single-branch'
usage: git clone [options] [--] <repo> [<dir>]

```
-v, --verbose be more verbose
-q, --quiet be more quiet
--progress force progress reporting
-n, --no-checkout don't create a checkout
--bare create a bare repository
--mirror create a mirror repository (implies bare)
-l, --local to clone from a local repository
--no-hardlinks don't use local hardlinks, always copy
-s, --shared setup as shared repository
--recursive initialize submodules in the clone
--recurse-submodules initialize submodules in the clone
--template <template-directory>
                      directory from which templates will be used
--reference <repo> reference repository
-o, --origin <name> use <name> instead of 'origin' to track upstream
-b, --branch <branch>
                      checkout <branch> instead of the remote's HEAD
-u, --upload-pack <path>
                      path to git-upload-pack on the remote
--depth <depth> create a shallow clone of that depth
--separate-git-dir <gitdir>
                      separate git dir from working tree
-c, --config <key=value>
                      set config inside the new repository
```

copying database CLIKINFO to CLIKINFO_migrated...
Traceback (most recent call last):
  File "/home/desktop/migrate.py", line 300, in <module>
    db_name = copy_database(conn_parms)
  File "/home/desktop/migrate.py", line 26, in copy_database
    conn = psycopg2.connect(**conn_parms)
  File "/usr/lib/python2.7/dist-packages/psycopg2/**init**.py", line 179, in connect
    connection_factory=connection_factory, async=async)
psycopg2.OperationalError: FATAL: Peer authentication failed for user "openerp"

Need help :)

Thank's

**Comment by pedrobaeza** [comment]
You don't have PostgreSQL correctly configured.

**Comment by clikinfo** [comment]
I just see the topic about it. Looking on the side of the postgres user :)
work in progress...

**Comment by hbrunn** [comment]
and the error message before says you need to update git

**Comment by clikinfo** [comment]
resolved by modifying the configuration file with authentication md5

Update git ok

and now 

copying database CLIKINFO to CLIKINFO_migrated...
Copying the database using 'with template'
Failed, fallback on creating empty database + loading a dump

I create a new topic? :o) 

Thank's for your help

**Comment by hbrunn** [comment]
That's okay, though slower. This is because someone (a running openerp instance, or psql, or whatever) accesses the database, which is why the fast way to copy the database doesn't work. And yes, next time, better open a new issue

**Comment by ViktorNova** [comment]
Just wanted to say for the sake of anyone who comes across this in the future that I had the same peer authentication error and was able to get past it by following instructions I found in an Odoo installation guide here:
https://beeznest.wordpress.com/2014/08/01/howto-install-odoo-on-debian-7-64bit/

> Locate your /etc/postgresql/9.1/main/pg_hba.conf file, find the “local all all peer” line and change it to “local all all trust”, then reload postgresql

I imagine it's probably a good idea to change this back to "peer" after upgrading the database for security

**Comment by abdellatifkarroum** [comment]
i have a pb:
Failed, fallback on creating empty database + loading a dump

**Comment by spitronello** [comment]
@abdellatifkarroum did you solve the 
Failed, fallback on creating empty database + loading a dump?

**Comment by Whytehorse** [comment]
I got this error when migrating from 8->10 and resolved it by killing the running odoo process
Copying the database using 'with template'
Failed, fallback on creating empty database + loading a dump

**Comment by AMhadhbi** [comment]
@abdellatifkarroum @spitronello @WhitleyStriber did you solve the issue Failed, fallback on creating empty database + loading a dump? I have the same issue. thanks

**Comment by mrABR** [comment]
Same error, any input?

**Comment by difra** [comment]
> Same error, any input?

I solved terminating session of the original database
https://stackoverflow.com/a/5408501
