### ISSUE TITLE
[11.0] Could not upgrade to version 11.0

### ISSUE THREAD

**Issue by hosnix** [OCA/OpenUpgrade#1522]
Hi,
Please what is the issue for this problem : 
I have run the migration script : 
$ sudo python migrate.py --config=odoo-server.conf --database=MYDB --run-migrations=11.0
Depuis git://github.com/OpenUpgrade/OpenUpgrade
 * branch                    11.0       -> FETCH_HEAD
Déjà à jour.
Depuis https://github.com/OCA/openupgradelib
 * branch            master     -> FETCH_HEAD
Déjà à jour.
copying database MYDB to MYDB_migrated...
Copying the database using 'with template'
Failed, fallback on creating empty database + loading a dump
pg_restore: [archiver (db)] Error while PROCESSING TOC:
pg_restore: [archiver (db)] Error from TOC entry 8930; 0 0 COMMENT EXTENSION plpgsql 
pg_restore: [archiver (db)] could not execute query: ERROR:  must be owner of extension plpgsql
    Command was: COMMENT ON EXTENSION plpgsql IS 'PL/pgSQL procedural language';

WARNING: errors ignored on restore: 1
running migration for 11.0
Running as user 'root' is a security risk.
Could not upgrade to version 11.0

$

MYDB is originally for odoo 9, and I migrated it to 10. it works perfectly.
But from 10.0 to 11.0, the script runs without error but I have message "Could not upgrade to version 11.0".
PS: migration from 9.0 to 11.0 doesn't work!
thanks for help!

**Comment by pedrobaeza** [comment]
Sorry, the problem is in your deployment. You don't have proper rights in the DB. That script is also deprecated and might not work.
