### ISSUE TITLE
[10.0->11.0] errors during migration

### ISSUE THREAD

**Issue by mayjo79** [OCA/OpenUpgrade#1537]
Hello,
I made a migration test with a simple database.
Despite this very simple case, I still encountered errors.
I tried to fix these errors but I'm not sure of myself.
I described this migration in [this post](https://agipme.fr/2018/10/odoo-10-ce-upgrade-to-version-11.html) 
Is there a better way to migrate from 10.0 to 11.0 ?

**Comment by pedrobaeza** [comment]
Well, I think you haven't updated database later with regular Odoo distribution.

**Comment by mayjo79** [comment]
Hello @pedrobaeza ,
What do you mean exactly ?
I updated Odoo database before migration and after migration ( ./odoo-server/odoo-bin -u all -d xxx --stop-after-init )

**Comment by pedrobaeza** [comment]
Well, then everything should work correctly. Maybe you need to remove a dangling couple of views manually, but it's very easy to fix.

**Comment by mayjo79** [comment]
OK thanks
