### ISSUE TITLE
[Proposal] Provide migration service based on OpenUpgrade

### ISSUE THREAD

**Issue by blaggacao** [OCA/OpenUpgrade#1545]
It would be great, if there would be a OCA shared-service for upgrades ala Odoo SA's upgrade service.

Two arguments:

- Closer upstream integration
  - Streamlines contribution
  - Provides up-to-date state
- Convenience
  - Fuels adoption
  - Generates greater ecosystem impact.

I know there are some blind eyes for such arguments around. But if it's feasible, those arguments might deploy as a matter of fact.

I'd love to connect https://github.com/xoe-labs/click-odoo-migrator to such (future) service.

**Comment by blaggacao** [comment]
OCA could even charge for it (subscription) to cover for maintenance and server costs.

**Comment by blaggacao** [comment]
And with the [Odoo-Operator](https://xoe-labs.github.io/odoo-operator/), providing and auto-scaling such service will be rather easy.

**Comment by pedrobaeza** [comment]
It's not a question of blind eyes, but something that is not fully automatable, and thus, a manual intervention is required, and OCA must be totally neutral on providing chargeable services. And not only that, there are legal constraints like GDPR and so on. If you want to provide such service, you are free for doing it, but this not something that can start from OCA itself.

**Comment by blaggacao** [comment]
@pedrobaeza Ok, is it a question of service neutrality of the OCA constitution?

blind eyes: I just was referring to people that under valuate (or don't understand) convenience, and ecosystem dynamics arguments within the OCA. :wink: It it's not feasible, that's another point.

**Comment by pedrobaeza** [comment]
Yes, OCA are not providing that services that can be a competence of members. Maybe OCA can set ways of connecting offer and demand. This is of course current status of the association.

**Comment by blaggacao** [comment]
I mean if it results easy after getting some operational experience with the Odoo-Operator, I might step in. But I would be keen on retributing to OCA as a source of income... After all I did (almost) never contribute to OpenUpgrade...

**Comment by pedrobaeza** [comment]
You can convert it on an OCA sponsor, donating the money you want.

**Comment by blaggacao** [comment]
@pedrobaeza [Stubs](https://github.com/xoe-labs/click-odoo-migrator/blob/e5e7037f89845484a43e4702dc5f3a91b5eacf51/src/modules/parser.py#L35) already there :wink:
