### ISSUE TITLE
migrations.py / future.utils

### ISSUE THREAD

**Issue by mhoeppner-le** [OCA/OpenUpgrade#1568]
Hello,
have a local instance of Odoo8.0 running in a VM (bitnami, Ubuntu 14.04).
Have downloaded migrations.py to /opt
`root@mymachine:/opt# python migrate.py --config=/opt/bitnami/apps/odoo/conf/openerp-server.conf --database=DB-live_01 --run-migrations=9.0,10.0
Traceback (most recent call last):
  File "migrate.py", line 3, in <module>
    from future.utils import iteritems
ImportError: No module named future.utils`

Could somebody tell me what to do / which preparations I have missed?

`root@mymachine:/opt# python --version
Python 2.7.10`

BR

**Comment by mhoeppner-le** [comment]
who can read ....
2 issues solved but next one see below [EDIT]: had to install git

`root@mymachine:/opt# pip install future
/opt/bitnami/python/lib/python2.7/site-packages/setuptools-18.4-py2.7.egg/pkg_resources/__init__.py:1256: UserWarning: /opt/bitnami/.tmp is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
You are using pip version 6.0.8, however version 18.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting future
  Downloading https://files.pythonhosted.org/packages/00/2b/8d082ddfed935f3608cc61140df6dcbf0edea1bc3ab52fb6c29ae3e81e85/future-0.16.0.tar.gz (824kB)
    100% |################################| 827kB 83kB/s 
Installing collected packages: future
  Running setup.py install for future
    Installing pasteurize script to /opt/bitnami/python/bin
    Installing futurize script to /opt/bitnami/python/bin
Successfully installed future-0.16.0`
==> done

`root@mymachine:/opt# python migrate.py --config=/opt/bitnami/apps/odoo/conf/openerp-server.conf --database=rad3-live_01 --run-migrations=9.0,10.0
Traceback (most recent call last):
  File "migrate.py", line 11, in <module>
    from configparser import SafeConfigParser
ImportError: No module named configparser
root@hermes-VM:/opt# pip install configparser
/opt/bitnami/python/lib/python2.7/site-packages/setuptools-18.4-py2.7.egg/pkg_resources/__init__.py:1256: UserWarning: /opt/bitnami/.tmp is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
You are using pip version 6.0.8, however version 18.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting configparser
  Downloading https://files.pythonhosted.org/packages/7c/69/c2ce7e91c89dc073eb1aa74c0621c3eefbffe8216b3f9af9d3885265c01c/configparser-3.5.0.tar.gz
Installing collected packages: configparser
  Running setup.py install for configparser
    Skipping installation of /opt/bitnami/python/lib/python2.7/site-packages/backports/__init__.py (namespace package)
    Installing /opt/bitnami/python/lib/python2.7/site-packages/configparser-3.5.0-py2.7-nspkg.pth
Successfully installed configparser-3.5.0`
==> done

`root@mymachine:/opt# python migrate.py --config=/opt/bitnami/apps/odoo/conf/openerp-server.conf --database=rad3-live_01 --run-migrations=9.0,10.0
linking server/addons to /var/tmp/openupgrade/9.0/addons
getting git://github.com/OpenUpgrade/OpenUpgrade.git
sh: 1: git: not found
Could not clone version`

`root@mymachine:/opt# apt-get install git
Reading package lists... Done
Building dependency tree       
Reading state information... Done
...
...`

**Comment by pedrobaeza** [comment]
Sorry, but this is the normal stuff, as the prerequisites are there, and can be found when you search for the error, so you have to comply with them, and it's something outside OpenUpgrade itself.

**Comment by mhoeppner-le** [comment]
Sorry, yesterday I was reading for 3-4 hours but did not find the right hint.
Just now is seems to run after installing future, configparser and git.
I would like to ask again if further problems are coming up.
BR

**Comment by mhoeppner-le** [comment]
bitnami@hermes-VM:/opt$ python migrate.py --config=/opt/bitnami/apps/odoo/conf/openerp-server.conf --database=rad3-live_01 --run-migrations=9.0,10.0
linking server/addons to /var/tmp/openupgrade/9.0/addons
getting git://github.com/OpenUpgrade/OpenUpgrade.git
Cloning into '/var/tmp/openupgrade/9.0/server'...
remote: Enumerating objects: 28836, done.
remote: Counting objects: 100% (28836/28836), done.
remote: Compressing objects: 100% (22818/22818), done.
remote: Total 28836 (delta 9881), reused 12653 (delta 5018), pack-reused 0
Receiving objects: 100% (28836/28836), 125.85 MiB | 563.00 KiB/s, done.
Resolving deltas: 100% (9881/9881), done.
Checking connectivity... done.
Checking out files: 100% (26528/26528), done.
linking server/addons to /var/tmp/openupgrade/10.0/addons
getting git://github.com/OpenUpgrade/OpenUpgrade.git
Cloning into '/var/tmp/openupgrade/10.0/server'...
remote: Enumerating objects: 25046, done.
remote: Counting objects: 100% (25046/25046), done.
remote: Compressing objects: 100% (20534/20534), done.
remote: Total 25046 (delta 7991), reused 9692 (delta 3590), pack-reused 0
Receiving objects: 100% (25046/25046), 116.33 MiB | 607.00 KiB/s, done.
Resolving deltas: 100% (7991/7991), done.
Checking connectivity... done.
Checking out files: 100% (22456/22456), done.
Cloning into '/var/tmp/openupgrade/openupgradelib'...
git-remote-https: /opt/bitnami/common/lib/libldap_r-2.4.so.2: no version information available (required by /usr/lib/x86_64-linux-gnu/libcurl-gnutls.so.4)
git-remote-https: /opt/bitnami/common/lib/liblber-2.4.so.2: no version information available (required by /usr/lib/x86_64-linux-gnu/libcurl-gnutls.so.4)
remote: Enumerating objects: 38, done.
remote: Counting objects: 100% (38/38), done.
remote: Compressing objects: 100% (33/33), done.
remote: Total 38 (delta 0), reused 20 (delta 0), pack-reused 0
Unpacking objects: 100% (38/38), done.
Checking connectivity... done.
copying database rad3-live_01 to rad3-live_01_migrated...
Copying the database using 'with template'
running migration for 9.0
/opt/bitnami/python/lib/python2.7/site-packages/setuptools-18.4-py2.7.egg/pkg_resources/__init__.py:1256: UserWarning: /opt/bitnami/.tmp is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
Could not upgrade to version 9.0
