### ISSUE TITLE
Outfactoring db analyzing

### ISSUE THREAD

**Issue by blaggacao** [OCA/OpenUpgrade#1587]
@StefanRijnhart Don't [bark at me](https://github.com/OCA/OpenUpgrade/issues/502#issuecomment-225495301). :) It's a suggestion to make the UX of OpenUpgrade simpler.
I already started [`click-odoo-migrator`](https://github.com/xoe-labs/click-odoo-migrator) to drive the migration process in a scriptable way.

I'm evaluating the possibility to outfactor the relevant parts of the analysis plugin into a subcommand like `click-odoo-migrator analyze` (eg. via a `openupgrade-analyzer` lib)

Obviously that does not make any sense at all if there is no shared single repository for the apriori and blacklist information. And it would only make limited sense if it would not be a true and coordinated attempt to become the preferred way of driving database analysis (eventually through CI automation) in the community.

Please let me know your thoughts and feelings about this idea.

Best, David

/cc @rvalyi

**Comment by blaggacao** [comment]
Ps: My vision of a workflow would look like this:

- `click-odoo-migrator analyze 11.0..12.0` on any given git repository that has both branches/tags `11.0` and `12.0`
- Would report a complete module tree with migration folders only (for all modules recognized in this repository), and the analysis therein.
- This tree could then be passed to `click-odoo-migrator --mig-directory` for applying the migration(s)
- And for the shared apriori, a multioption flag needs to be provided that takes one or several file(s) or URL(s) to pre-load know mutations (preferably from `json` format).

Furthermore: Maintaining a priori data within such library should be avoided in order to disconnect release cycles.

**Comment by blaggacao** [comment]
This thought leads me to another question: All methods in the [compare module](https://github.com/OCA/OpenUpgrade/blob/11.0/odoo/addons/openupgrade_records/lib/compare.py) are supposedly public. I guess that does not express the correct usage intention. Is my assumption correct that there are only 2 really public methods in this module?

**Comment by blaggacao** [comment]
Once that's achieved, what about code-generators (e.g. jinja tamplates) for some of the more commonly identifiable ("patternable") cases, like: 

- https://doc.therp.nl/openupgrade/xmlids.html
- https://doc.therp.nl/openupgrade/format.html

in a `openupgrade-generators` lib package?

**Comment by blaggacao** [comment]
Here we go, with complete history: https://github.com/xoe-labs/openupgradelib-contrib

**Comment by lina2358** [comment]
Any opinion on this one? It would be nice to further this thought.

**Comment by lina2358** [comment]
Cross reference of _potentially_ relevant items: #213 #468 #590 #1204

**Comment by pedrobaeza** [comment]
@acl2358 why do you enumerate other unrelated issues?

**Comment by StefanRijnhart** [comment]
I'm not interested. @blaggacao our interests are never aligned, and I have a real problem with your communication.

**Comment by lina2358** [comment]
@pedrobaeza Thanks for your question. It is a "note to ourselves" because I think those issues have to be taken into consideration if/when work starts.

@StefanRijnhart Sorry to hear that: I perceived modularizing as a common _enough_ goal worth aiming at.

**Comment by blaggacao** [comment]
@StefanRijnhart I'm sorry, would a disclosure of my honest and best intentions towards you and this library reduce that problem?

**Comment by blaggacao** [comment]
Funnily enough, I lost my first Job because of a question starting with "What if we could ... " in the second week and I haven't learned a bit. :wink:

**Comment by blaggacao** [comment]
For anyone indeed interested, I started work here: https://github.com/xoe-labs/dodoo-migrator/tree/master/src/analyzer/schema_analyzer .I think the core is to define a well designed [set of known transitions](https://github.com/xoe-labs/dodoo-migrator/blob/master/src/analyzer/schema_analyzer/_transitions.py) in order to be able to achieve further automations...

**Comment by pedrobaeza** [comment]
Closing this as the advertising has been done.

**Comment by blaggacao** [comment]
More than advertising, I intend an *open* exchange of ideas. Is it that so hard to achieve? 

Note: I can be always conveniently blamed for not achieving it, but I don't think it's the whole truth. :wink:

Happy Christmas!
