### ISSUE TITLE
[11.0] base: images and templates missed after upgrade 10 -> 11

### ISSUE THREAD

**Issue by trapchik** [OCA/OpenUpgrade#1600]
Impacted versions: 11.0

Steps to reproduce: python migrate.py --config=/etc/odoo/odoo.conf --database=DB --run-migrations=11.0

images from products and partners as well as templates (headers/footers for PDF) removed after upgrade 10 -> 11

Thanks

**Comment by trapchik** [comment]
p.s. we could change external_layout_header / external_layout_footer in Odoo 10 (Settings-> General Settings)

**Comment by pedrobaeza** [comment]
This has nothing to do with the migration, but with the filestore and proxy/configuration for reports.

**Comment by trapchik** [comment]
where can I get more details about filestore please? always thought all images in postgresql db
am I wrong?

**Comment by StefanRijnhart** [comment]
This should be common knowledge, but I can't say it's very well documented by Odoo (although googling gives a lot of results). Attachments and some binary fields are stored in the filestore, which by default is the filesystem. The default location is .local/share/Odoo/filestore in your Odoo user's home directory. The ir.attachment model contains a file name and a function field that presents you with the file contents.
