### ISSUE TITLE
Can I use this to upgrade from 9EE to 10 CE ?

### ISSUE THREAD

**Issue by AEK-BKF** [OCA/OpenUpgrade#1606]
Hi,

This is just a question, I've **9EE** installed, and I wanna upgrade it to **10CE**.
Is it possible ? if yes, what are the others steps to do that ?

Thanks

**Comment by pedrobaeza** [comment]
This is for upgrading a database with CE modules, but you should uninstall possible EE modules and lose the information they add.

**Comment by AEK-BKF** [comment]
So the best way is to migrate the database by Odoo, and  install fresh Odoo 10 CE, then do restore database with custom modules ?

**Comment by pedrobaeza** [comment]
No, you will have the same problem of losing information of the enterprise modules when uninstalling them. You have to analyze what you lose or not.
