### ISSUE TITLE
Duplicated countries/states

### ISSUE THREAD

**Issue by dcorio** [OCA/OpenUpgrade#1613]
Hello, not sure this can considered a bug but... using the latest migration script, while trying to migrate from 8.0 to 9.0,10.0,11.0, the migration fails because there's a constraint that prohibits to create duplicated countries or states.
Countries and states may exist because customers create them by hand.
Is there a common approach to this?

**Comment by StefanRijnhart** [comment]
Thanks for noting! A patch to catch these duplicates would be welcome, I
think! Countries can easily be identified by their ISO code, so based on
that you could add an xml id in the pre-script.

**Comment by pedrobaeza** [comment]
You can use openupgradelib merge records feature for merging countries with same code.

**Comment by pedrobaeza** [comment]
Please identify in which version the constraint is added for adding the code in the proper branch.

**Comment by dcorio** [comment]
Hi @pedrobaeza i wasn't aware of this "merge records feature". 
For instance I'm facing this problem migrating an 8.0 to 11.0 and the constraint is present in 10.0 and 11.0. Not on 9.0 AFAIK.
I can try to help here if you can point some examples

Many thanks in advance.

**Comment by pedrobaeza** [comment]
Ok, then it seems you have to add the merge operation on OpenUpgrade 10.0. I would put in on the migration scripts of base module, but doing on pre-migration phase would lead that you can't use it with ORM mode, so this gets more difficult and not completed by SQL, so we can have the initial warning for not appearing anymore after the post-migration.

This is the method to call:

https://github.com/OCA/openupgradelib/blob/0ac601497c9849c3f257ca505bc00d28af368155/openupgradelib/openupgrade_merge_records.py#L407

and here you have an example with stock module in v11 for merging quants with same "significant key" (as v11 does):

https://github.com/OCA/OpenUpgrade/blob/168b1ab166b29955ead25b36428b464622df7710/addons/stock/migrations/11.0.1.1/end-migration.py#L14

**Comment by MiquelRForgeFlow** [comment]
Solved in https://github.com/OCA/OpenUpgrade/pull/1619.
