### ISSUE TITLE
API map_values: same source and target column

### ISSUE THREAD

**Issue by christophlsa** [OCA/OpenUpgrade#162]
I found this error in log:

```
2014-12-12 09:23:43,487 23335 ERROR testdb OpenUpgrade: map_values is called with the same value for source and old columns : notify_email
None
```

In the post-migration of the mail addon the API method `openupgrade.map_values` is called with the same source and target column name. I think this is right. This error is thrown in log but however the UPDATE statement of this mapping is called.

We should change something. Some ways to solve:
- change the logging level to warning or lower
- delete this check completely
- change the call to do this mapping with other methods
- add a parameter to suppress this error because the author intend the mapping of the same columns

What do you thinking?

**Comment by pedrobaeza** [comment]
The method is correct. Explanation here: https://github.com/OpenUpgrade/OpenUpgrade/pull/116/files#r21844972
