### ISSUE TITLE
7 -> 8 violates foreign key constraint "ir_module_module_dependency_module_id_fkey"

### ISSUE THREAD

**Issue by zzwxrchi** [OCA/OpenUpgrade#1634]
Impacted versions:  7 upgrade to 8.0

Steps to reproduce: 
ubuntu 14.40 server, openerp 7, progressql 9.3

# run migrate.py:
--- show terminal -------
From git://github.com/OpenUpgrade/OpenUpgrade
 * branch            8.0        -> FETCH_HEAD
Already up-to-date.
From https://github.com/OCA/openupgradelib
 * branch            master     -> FETCH_HEAD
Already up-to-date.
copying database UP8_OS to UP8_OS_migrated...
Copying the database using 'with template'
running migration for 8.0
--- end terminal ------------

--- error log  /var/tmp/openupgrade/migration.log -----

2018-11-22 18:10:48,319 10543 ERROR UP8_OS_migrated openerp.sql_db: Programming error: there is no unique constraint matching given keys for referenced table "res_lang"
, in query ALTER TABLE "ir_translation" ADD CONSTRAINT "ir_translation_lang_fkey_res_lang" FOREIGN KEY(lang) REFERENCES res_lang(code)
2018-11-22 18:10:52,364 10543 ERROR UP8_OS_migrated openerp.sql_db: bad query: ALTER TABLE "ir_module_module_dependency" ADD FOREIGN KEY ("module_id") REFERENCES "ir_module_module" ON D$
Traceback (most recent call last):
  File "/var/tmp/openupgrade/8.0/server/openerp/sql_db.py", line 247, in execute
    res = self._obj.execute(query, params)
IntegrityError: insert or update on table "ir_module_module_dependency" violates foreign key constraint "ir_module_module_dependency_module_id_fkey"
DETALLE:  Key (module_id)=(287) is not present in table "ir_module_module".

--- end log ----
Current behavior:
En postgresql comando
delete from ir_module_module_dependency where module_id NOT IN (select id from ir_module_module);
DELETE 0

Expected behavior:
delete from ir_module_module_dependency where module_id NOT IN (select id from ir_module_module);
DELETE (1 or more)

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
This is a missing dependency in your OpenUpgrade v8 deployment. You should resolve it or remove manually the line as you have done.

Closing as no issue in OpenUpgrade itself.

**Comment by zzwxrchi** [comment]
Thank you @pedrobaeza 

But why give message:
IntegrityError: insert or update on table "ir_module_module_dependency" violates foreign key constraint "ir_module_module_dependency_module_id_fkey"
DETALLE: Key (module_id)=(287) is not present in table "ir_module_module".   ?

In actualy, table "ir_module_module" have id=287 value.

**Comment by pedrobaeza** [comment]
When updating module list, this kind of things happen. As said, check missing modules in v8.

**Comment by zzwxrchi** [comment]
Thank you very much !!

How is the best  for run migrated scripts ?

The old openerp-server and the new odoo-server both activived or stopped ?
