### ISSUE TITLE
[10.0]Advanced payment are not correctly set 

### ISSUE THREAD

**Issue by flotho** [OCA/OpenUpgrade#1638]
Impacted versions:

Steps to reproduce:
start in v8, create a SO, make a down payment, migrate into 10.0, invoice the residual 

Current behavior:
New invoice is not getting the down payments.
Down payments have no sale.order line available associated to the invoice.line

Expected behavior:

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Well, this is a not covered case. Are you able to contribute with the code for this?

**Comment by pedrobaeza** [comment]
You should analyze if this should be done on v9 or v10.

**Comment by flotho** [comment]
Hi @pedrobaeza ,

Unfortunatley we're fulltime for the moment and our customer analyzed that only less than 30 SO were impacted so the job will be done manually.
Yet we clearly identify the way to solve this. If possible we'll try to also contribute on this too.

regards

**Comment by pedrobaeza** [comment]
OK, thanks.

**Comment by pedrobaeza** [comment]
Closing as no news.
