### ISSUE TITLE
7.0 to 8.0 error: old_id = cr.fetchone()[0] get exception "'NoneType' object has no attribute '__getitem__'"

### ISSUE THREAD

**Issue by zzwxrchi** [OCA/OpenUpgrade#1643]
Hi guys.

I'm trying to make the migration to 8.0

Old version:
OpenErp 7.0:  launchpad bzr version 5292
l10n_es:        launchpad bzr version 459

When run migrate.py, in code post-migration.py of l10n_es addons.
...... error log .....
"/var/tmp/openupgrade/8.0/addons/l10n_es/migrations/8.0.4.0/post-migration.py", line 52, in map_account_types
old_id = cr.fetchone()[0]
TypeError: 'NoneType' object has no attribute '__getitem__'
2018-12-02 15:14:21,275 22047 ERROR UP8_OS_migrated openerp.modules.loading: Error executing post migration script for module l10n_es
: 'NoneType' object has no attribute '__getitem__'
......

For code in addons/l10n_es/migrations/8.0.4.0/post-migration.py:
account_types_mapping = [
     ('l10n_es.capital', 'l10n_es.account_type_capital'),
     ('l10n_es.financieras', 'l10n_es.account_type_financieras'),
     ('l10n_es.gastos', 'account.data_account_type_expense'),
     ('l10n_es.gastos_neto', 'l10n_es.account_type_gastos_neto'),
     ('l10n_es.ingresos', 'account.data_account_type_income'),
     ('l10n_es.ingresos_neto', 'l10n_es.account_type_ingresos_neto'),
     ('l10n_es.inmo', 'l10n_es.account_type_inmo'),
     ('l10n_es.stock', 'l10n_es.account_type_stock'),
     ('l10n_es.tax', 'account.conf_account_type_tax'),
     ('l10n_es.terceros', 'l10n_es.account_type_terceros'),
     ('l10n_es.terceros_-_pay', 'account.data_account_type_payable'),
     ('l10n_es.terceros_-_rec', 'account.data_account_type_receivable'),
     ('l10n_es.view', 'account.data_account_type_view'),
]

In db I not find any old account_typess of the name of column left,  E.J.: 'l10n_es.financieras'
Then, the code "old_id = cr.fetchone()[0]" get exception "'NoneType' object has no attribute '__getitem__'"

I find code improved of post-migration.py in page
https://github.com/OCA/l10n-spain/commit/4f8fd9540d45685e44c1c4dad2ddb8399968b1bc

Why this improved has not included in post-migration.py of OpenUpgrade 8.0, in l10n_es addons:
https://github.com/OCA/OpenUpgrade/blob/8.0/addons/l10n_es/migrations/8.0.4.0/post-migration.py

Thanks.

**Comment by pedrobaeza** [comment]
You must use `l10n_es` from OCA/l10n-spain instead of standard one in Odoo v7, and the same for v8

**Comment by zzwxrchi** [comment]
Hi Pedro.

I download my l10n_es and installed in openerp 7.0 for:
bzr branch lp:~openerp-spain-team/openerp-spain/7.0 -r 459 openerp-spain 
Is same of  OCA/l10n-spain or standard one in Odoo v7 ?

And my question is:
Why this improved has not included in post-migration.py of OpenUpgrade 8.0, in l10n_es addons

**Comment by pedrobaeza** [comment]
You are using outdated references. Later ones are in https://github.com/OCA/l10n-spain/tree/7.0, and it's this way because there was no control over Odoo core content.

**Comment by zzwxrchi** [comment]
Tanks Pedro.

Is it mandatory to update to the latest version of openerp 7.0 and the third addons as a Spanish location before migrating to 8.0 ?
How I do to upgrade that if yes ? 
I tryed do upgrade from Settings: Modules -> Installed Molules -> l10n_es (Latest Version | 7.0.3.1)
and upgrade that, but nothing happens.

Or have other method to do it ?

**Comment by pedrobaeza** [comment]
Yes, it is, and you should do it from source, not using app store.

**Comment by zzwxrchi** [comment]
Hi @pedrobaeza , you mean command: bzr pull ? 
Or git pull ? 
But only have bzr version control in my server and addons folders.
The bzr pull is still valid today ?

**Comment by pedrobaeza** [comment]
Sorry, but this is out of the scope of this issue tracker.

**Comment by zzwxrchi** [comment]
Ok @pedrobaeza I'm going to open another thread.

I think it is essential to tell people how to prepare their installation before migration.
It will avoid many error and save everyone's time.

I am asking why you spend so much time developing the complicated codes and offering yourself free to everyone, but it does not make a clearer document to demonstrate and guide the people that use your work well.

Thank you very much !!
