### ISSUE TITLE
ImportError: No module named

### ISSUE THREAD

**Issue by nagybal** [OCA/OpenUpgrade#1647]
I am not maintaing any addons or modules. I would like to migrate my database 10.0 to 12.0

```
root@odin10:/home/bigb# python migrate.py --config=/etc/odoo/odoo.conf --database=nam --run-migrations=11.0,12.0
Traceback (most recent call last):
  File "migrate.py", line 3, in <module>
    from future.utils import iteritems
ImportError: No module named future.utils
```

I am reading the forums, wiki and docs for couple of days now. What I am missing?

**Comment by pedrobaeza** [comment]
Several points:

- Module coverage for v12 is yet very low, so for sure you are not going to be able to migrate to this version.
- That script (migrate.py) is deprecated and doesn't work for new versions.
- You have to use Python 3.

**Comment by nagybal** [comment]
Dear Pedro! **Python 3** does almost the same:
```
root@odin10:/home/bigb# python3 migrate.py --config=/etc/odoo/odoo.conf --database=nam --run-migrations=11.0,12.0 
Traceback (most recent call last):
  File "migrate.py", line 3, in <module>
    from future.utils import iteritems
ImportError: No module named 'future'
```
