### ISSUE TITLE
Migration of addon "warning"

### ISSUE THREAD

**Issue by christophlsa** [OCA/OpenUpgrade#165]
Hi,

I wanted to start to write migration of the addon "warning" because there was no status on doc page. I tested the migration without new migration files and the data was migrated from "product.product" to "product.template". So I think there is no work needed. I don't know which code does this copying but it works.

Did I overlooked something or am I right? Can we update the status?

**Comment by hbrunn** [comment]
I think you'll need a post-migrate script that copies over the old values from product_product to the respective columns in product_template. Something like

```
update product_template pt set sale_line_warn=pp.sale_line_warn, [..] from product_product where pp.product_tmpl_id=pt.id
```

(from the top of my head, untested)

Then in your PR, also set the status to done in `openerp/openupgrade/doc/source/modules70-80.rst`

**Comment by christophlsa** [comment]
Oh my fault. I looked in the wrong table. I will create a pull request.
