### ISSUE TITLE
ImportError: No module named

### ISSUE THREAD

**Issue by nagybal** [OCA/OpenUpgrade#1651]
Dear Pedro! Python 3 does almost the same:

```
root@odin10:/home/bigb# python3 migrate.py --config=/etc/odoo/odoo.conf --database=nam --run-migrations=11.0
Traceback (most recent call last):
  File "migrate.py", line 3, in <module>
    from future.utils import iteritems
ImportError: No module named 'future'
```

**Comment by zzwxrchi** [comment]
In Python 2.x need install future module and others: 
sudo su
apt-get install git
su - odooUserName -s /bin/bash
pip install openerp-client-lib --user
pip install decorator --user
pip install requests --user
pip install pyPdf --user
pip install passlib --user
pip install future --user
pip install configparser --user
exit

**Comment by pedrobaeza** [comment]
As said, migration.py script is not adapted for Python 3. You must use the manual method explained also on docs.
