### ISSUE TITLE
Old modules in Module-list after upgrade

### ISSUE THREAD

**Issue by peter2018abc** [OCA/OpenUpgrade#1670]
Hi

I managed to upgrade from 8 to 11 community. Everthing is working, log is clean. Unfortunately old modules are still in the module list (with version 11.0.1.0) eventhough the module is not in my addon folder.

I tried to run database_cleanup => delete obsolete modules, but the modules are still listet...

Any idea how to get rid of them?

**Comment by pedrobaeza** [comment]
Simply remove the records in the module list.
