### ISSUE TITLE
Odoo 8 to Odoo 9 migration Issue: Reset Templates error and DB size ~50% less

### ISSUE THREAD

**Issue by mosaabdulali** [OCA/OpenUpgrade#1671]
Hello,

I'm trying to migrate our company db from Odoo v8 --> v11 but getting 500 internal server error and reset template in the web page. Also, the size of migrated DB dump is much less than the original by ~50%!

**Migration log attached**
[migration9.log](https://github.com/OCA/OpenUpgrade/files/2720728/migration9.log)

As per my understanding I don't see major issues compared to 
[https://travis-ci.org/OCA/OpenUpgrade/builds/147954920#L4416]

**Impacted versions:**
Odoo 9

**Steps to reproduce:**
Migrate Odoo 8 to Odoo 9

**Current behavior:**
Got 500 Internal Server Error
Reset templates
The selected templates will be reset to their factory settings.
Type 'yes' in the box below if you want to confirm.

Database dump size of v8 is ~80Mb while migrated one is ~40MB
Even after Update all modules

**Expected behavior:**
To have working DB for Odoo 9 to able to proceed with migration 10 and 11.

**Comment by pedrobaeza** [comment]
This is caused by QWeb website views that have noupdate="1" due to manual manipulations, so you have to reset them to noupdate="0" on v8 before migrating, or fix them with the proper values in v9 via SQL. Typical cases are references to fields that no longer exist in new version. Odoo log can serve as a hint for knowing which is the conflicting view and which field is failing.

**Comment by mosaabdulali** [comment]
Thanks Pedro, fixed as advised.
Now, I'm getting this error JS console in v11 when try to open any app e.g. sale, purchase .... noting get loaded except the sidebar with the logo:

`Uncaught Error: QWeb2: Can't clone undefined template FieldMany2ManyTag`
`    at Object.exception (web.assets_common.js:3689)`
`    at Engine.add_template (web.assets_common.js:3706)`
`    at Object.<anonymous> (web.assets_common.js:3980)`
`    at Object.<anonymous> (web.assets_common.js:802)`
`    at fire (web.assets_common.js:796)`
`    at Object.fireWith [as resolveWith] (web.assets_common.js:801)`
`    at done (web.assets_common.js:1192)`
`    at XMLHttpRequest.callback (web.assets_common.js:1212)`

Any clue where to check?

**Comment by pedrobaeza** [comment]
You should check missing modules and uninstall them.

**Comment by mosaabdulali** [comment]
I've already uninstalled all the missing modules but getting this error.

**Comment by pedrobaeza** [comment]
Check server log to see possible errors, and dangling views that modifies assets. See also JS console in browser.

**Comment by mosaabdulali** [comment]
Hi Pedro,

What do you mean by dangling views? Those views with *Error Context* in the migration log?

JS Console has nothing other than above error.

Odoo log looks fine.

The migration log contains these types of warnings/errors (I managed to fix others),
I can understand what they mean but appreciate if you could explain what I need to do for each type:

`
Error context:
View "res.partner.view.form.inherit.mail"
[view_id: 1767, xml_id: n/a, model: res.partner, parent_id: 126]
`

`
2019-01-09 20:12:48,400 14872 ERROR db_migrated OpenUpgrade: Error deleting XML-ID project.portal_issue_rule: ValueError('External ID not found in the system: project.portal_issue_rule',)
`

`
2019-01-09 20:15:08,082 14872 WARNING db_migrated odoo.addons.base.ir.ir_ui_view: Error-prone use of @class in view product.product.pack (): use the hasclass(*classes) function to filter elements by their classes
`

`
2019-01-09 20:15:33,138 14872 WARNING db_migrated odoo.modules.loading: Model purchase.config.settings is declared but cannot be loaded! (Perhaps a module was partially removed or renamed)
`

`
2019-01-09 20:15:47,270 14872 WARNING db_migrated odoo.addons.base.ir.ir_model: Could not delete obsolete record with id: 596 of model ir.ui.view
`

**Comment by pedrobaeza** [comment]
No, views that doesn't apply now in this version.

**Comment by mosaabdulali** [comment]
Are they documented somewhere?

**Comment by pedrobaeza** [comment]
No, that's why they are "dangling". See XML-IDs and so on. You need a deep knowledge of the system to debug these things.

**Comment by mosaabdulali** [comment]
Thanks

**Comment by thaiger14** [comment]
> This is caused by QWeb website views that have noupdate="1" due to manual manipulations, so you have to reset them to noupdate="0" on v8 before migrating, or fix them with the proper values in v9 via SQL. Typical cases are references to fields that no longer exist in new version. Odoo log can serve as a hint for knowing which is the conflicting view and which field is failing.

Hi, Pedro
I have the same situation happening on ODOO v11 running on Ubuntu 16.4 with reset template question show up, can you help to explain how to fix the value in postgreSQL? Where should I look for to update the value noupdate="0" ?

**Comment by pedrobaeza** [comment]
XML-IDs are stored on ir_model_data table.

**Comment by thaiger14** [comment]
Hi,Pedro sorry I have been working on other case and haven't tried your solution, I look up the xml in 
ir_model_view.xml

and this is the code inside

```
 <record id="view_model_data_search" model="ir.ui.view">
            <field name="model">ir.model.data</field>
            <field name="arch" type="xml">
                <search string="External Identifiers">
                    <field name="name" filter_domain="[('name','ilike',self)]" string="External Identifier"/>
                    <filter string="Updatable" domain="[('noupdate', '=', False)]"/>
```

does this mean, the noupdate is already set to 0? or I need to change False to "0"?
