### ISSUE TITLE
[9.0] Stock_available module error

### ISSUE THREAD

**Issue by kmorganr** [OCA/OpenUpgrade#1687]
Impacted versions: 9

Steps to reproduce: Inventory -> Settings -> Stock available to promise -> Check either of the boxes 

Current behavior: Takes to Odoo store website.

Expected behavior: Enables features

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
And how is this related to OpenUpgrade?

**Comment by kmorganr** [comment]
My mistake, which category does it belong in?

**Comment by pedrobaeza** [comment]
In the repository of the module. Any way, I'm just scared if you are using OpenUpgrade for a regular system in production...
