### ISSUE TITLE
Error while migration from odoo 10.0 to 11.0

### ISSUE THREAD

**Issue by deebo2121** [OCA/OpenUpgrade#1696]
Migration from version 10.0 to 11.0 using command 
`python migrate.py --config=odoo-server.conf --database=CMS --run-migrations=10.0,11.0`
while validating i have an issue and its interrupt the process
it shows in the terminal  

>ahmed@ahmed-Inspiron-3558:/var/tmp/openupgrade$ python migrate.py --config=odoo-server.conf --database=CMS --run-migrations=10.0,11.0
>error: cannot open .git/FETCH_HEAD: Permission denied

>error: cannot open .git/FETCH_HEAD: Permission denied

>error: cannot open .git/FETCH_HEAD: Permission denied

>copying database CMS to CMS_migrated...
>Copying the database using 'with template'
>running migration for 10.0
>ERROR: couldn't create the logfile directory. Logging to the standard output.
>2019-01-20 19:40:42,535 5915 INFO ? odoo: Odoo version 10.0
>2019-01-20 19:40:42,535 5915 INFO ? odoo: Using configuration file at /var/tmp/openupgrade/10.0/server.cfg
>2019-01-20 19:40:42,535 5915 INFO ? odoo: addons paths: [u'/var/tmp/openupgrade/10.0/server/odoo/addons', u'/var/tmp/openupgrade/10.0/addons']
>2019-01-20 19:40:42,535 5915 INFO ? odoo: database: odoo@localhost:5432
>2019-01-20 19:40:42,562 5915 INFO ? odoo.sql_db: bad query: CREATE SEQUENCE base_registry_signaling INCREMENT BY 1 START WITH 1
>2019-01-20 19:40:42,562 5915 ERROR ? odoo.modules.registry: Failed to load registry
>Traceback (most recent call last):
  File "/var/tmp/openupgrade/10.0/server/odoo/modules/registry.py", line 80, in new
    registry.setup_signaling()
  File "/var/tmp/openupgrade/10.0/server/odoo/modules/registry.py", line 384, in setup_signaling
    cr.execute("CREATE SEQUENCE base_registry_signaling INCREMENT BY 1 START WITH 1")
  File "/var/tmp/openupgrade/10.0/server/odoo/sql_db.py", line 154, in wrapper
    return f(self, *args, **kwargs)
  File "/var/tmp/openupgrade/10.0/server/odoo/sql_db.py", line 231, in execute
    res = self._obj.execute(query, params)
ProgrammingError: relation "base_registry_signaling" already exists

>2019-01-20 19:40:42,563 5915 CRITICAL ? odoo.service.server: Failed to initialize database `CMS_migrated`.
Traceback (most recent call last):
  File "/var/tmp/openupgrade/10.0/server/odoo/service/server.py", line 914, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/var/tmp/openupgrade/10.0/server/odoo/modules/registry.py", line 80, in new
    registry.setup_signaling()
  File "/var/tmp/openupgrade/10.0/server/odoo/modules/registry.py", line 384, in setup_signaling
    cr.execute("CREATE SEQUENCE base_registry_signaling INCREMENT BY 1 START WITH 1")
  File "/var/tmp/openupgrade/10.0/server/odoo/sql_db.py", line 154, in wrapper
    return f(self, *args, **kwargs)
  File "/var/tmp/openupgrade/10.0/server/odoo/sql_db.py", line 231, in execute
    res = self._obj.execute(query, params)
>ProgrammingError: relation "base_registry_signaling" already exists

>2019-01-20 19:40:42,563 5915 INFO ? odoo.service.server: Initiating shutdown
>2019-01-20 19:40:42,563 5915 INFO ? odoo.service.server: Hit CTRL-C again or send a second signal to force the shutdown.
Could not upgrade to version 10.0

and in the migration.log is the same 
what i miss or what to do

**Comment by pedrobaeza** [comment]
Script `migrate.py` is not suitable for that version migration, as stated in the documentation (https://doc.therp.nl/openupgrade/migrate.py.html).

**Comment by deebo2121** [comment]
is there any way to fix it or i cant use this script ?!

**Comment by pedrobaeza** [comment]
Use manual migration procedure.
