### ISSUE TITLE
Could not migrate, no error

### ISSUE THREAD

**Issue by mrABR** [OCA/OpenUpgrade#1699]
Impacted versions:
8.0

Steps to reproduce:
python migrate.py --config=/etc/openerp-server.conf --database=database_to_migrate --run-migrations=8.0

Current behavior:

From git://github.com/OpenUpgrade/OpenUpgrade
 * branch            8.0        -> FETCH_HEAD
Already up-to-date.
From https://github.com/OCA/openupgradelib
 * branch            master     -> FETCH_HEAD
Already up-to-date.
copying database database_to_migrate to database_to_migrate_migrated...
Copying the database using 'with template'
Failed, fallback on creating empty database + loading a dump
running migration for 8.0
Could not upgrade to version 8.0

Expected behavior:
A migration from 7.0 to 8.0

(I've gone to the length of trying to set version 7.0,8.0, output is the same)

python migrate.py --config=/etc/openerp-server.conf --database=database_to_migrate --run-migrations=7.0,8.0

From git://github.com/OpenUpgrade/OpenUpgrade
 * branch            7.0        -> FETCH_HEAD
Already up-to-date.
From git://github.com/OpenUpgrade/OpenUpgrade
 * branch            8.0        -> FETCH_HEAD
Already up-to-date.
From https://github.com/OCA/openupgradelib
 * branch            master     -> FETCH_HEAD
Already up-to-date.
copying database database_to_migrate to database_to_migrate_migrated...
Copying the database using 'with template'
Failed, fallback on creating empty database + loading a dump
running migration for 7.0
running migration for 8.0
Could not upgrade to version 8.

How am I supposed to figure out what's wrong without an error?

**Comment by pedrobaeza** [comment]
The error is that the database is not being copied. Any way, I always recommend manual method for full control.

**Comment by mrABR** [comment]
I've done this previously (about a few months ago) on another machine with another database and it worked flawlessly, I'm trying to decypher what the result variable should be within the migrate file but without success

 result = os.system(
        os.path.join(
            options.branch_dir,
            version,
            'server',
            migrations[version]['server']['cmd'] % {
                'db': db_name,
                'config': os.path.join(options.branch_dir, version,
                                       'server.cfg')
            }))
    if result != 0:
        print("Could not upgrade to version %s" % version)
        sys.exit(7)

**Comment by pedrobaeza** [comment]
Yeah, but this is not something in OpenUpgrade itself, so closing.

**Comment by mrABR** [comment]
For future reference:

This was due to apparently some modules (after uninstalling a few, it managed to work)

(You can close this, just wanted to add a note for whoever finds this)
