### ISSUE TITLE
Migration v12

### ISSUE THREAD

**Issue by mosaabdulali** [OCA/OpenUpgrade#1701]
Hi,

Is migration script to v12 ready?

**Comment by pedrobaeza** [comment]
See #1448 for the coverage.

**Comment by mosaabdulali** [comment]
Thanks.
I can check the status of checked module by referring to the issue against it.
What about those that are not checked, does it mean no change required or work not started even the  analysis?
What about those unchecked and marked as OCA Project like Sale, Purchase?

**Comment by pedrobaeza** [comment]
All the information is in the issue. Obviously, if no mark and no PR in progress, it means there's still no work done.

**Comment by mosaabdulali** [comment]
Thanks Pedro for your usual support 👍
