### ISSUE TITLE
Too slow to update 7 to 8

### ISSUE THREAD

**Issue by bizslink-calon** [OCA/OpenUpgrade#1705]
Impacted versions:8

Steps to reproduce:

Current behavior: 
2, 500, 000 records in stock.move, should be update one by one, and it will take about a week to do this.
You browse all records at once in your code?
```
with api.Environment.manage():
        env = api.Environment(cr, SUPERUSER_ID, {})
        moves = env['stock.move'].search(
            [('state', 'in', ['assign', 'done'])], order="date")
        for move in moves:
            if move.state == 'assign':
                _move_assign(env, move)
            else:
                _move_done(env, move)
```
And, about 100records/30s is too slow.
I tried rewrite your code with threading and failed, always have some bugs here and there.
Any good idea to speed up? or pre-upgrade in production server?
Expected behavior:
we should speed up, no so much times to upgrade cause of company business.
Video/Screenshot link (optional):

**Comment by bizslink-calon** [comment]
And, the server with 8 core and 32G Memory.

**Comment by StefanRijnhart** [comment]
Indeed, browsing more than a coule of hundreds of records is terribly slow, as Odoo caching starts working against you. Can you try chunking the move lines, implementing this method: https://github.com/EssentNovaTeam/bank-payment/blob/8.0-nova/account_banking_pain_base/models/banking_export_pain.py#L30?

**Comment by pedrobaeza** [comment]
Any news on this?

**Comment by bizslink-calon** [comment]
Still have problem on executing procurement/8.0.1.0/post-migration.py - migrate_stock_qty


This takes about 5 days, it's too long.


Any idea to excute it within 1 day except rewriting all the built-in method?


Calon

________________________________

**Comment by davidtranhp** [comment]
Did you try the chunking suggested?

**Comment by pedrobaeza** [comment]
Yes, there's no other way. Any way, I'm about closing this if no work is going to be done, as being slow is not an issue per se, but a nice to have thing.

**Comment by bizslink-calon** [comment]
Thanks too much for your job.


Calon

________________________________

**Comment by bizslink-calon** [comment]
In fact, this has little influence.


Thanks


Calon

________________________________
