### ISSUE TITLE
[11.0] WH/IN missed since migrated from Odoo 10

### ISSUE THREAD

**Issue by trapchik** [OCA/OpenUpgrade#1707]
Since migrating to odoo 11 we are missing all WH/IN records while all WH/OUT records are working perfectly any idea how we can fix this issue it it known to happen? Note if we create a purchase order in odoo 11.0 and book products on WH/IN they work fine, its just all pre-existing WH/IN records from Odoo 10.0 don't appear to have been migrated correctly.

Thanks,

<img width="270" alt="screenshot 2019-01-29 at 13 51 31" src="https://user-images.githubusercontent.com/22664992/51912869-31a9f300-23cd-11e9-92c8-1e81caed2063.png">
<img width="247" alt="screenshot 2019-01-29 at 13 51 40" src="https://user-images.githubusercontent.com/22664992/51912870-31a9f300-23cd-11e9-94f5-d07ab9197b5e.png">

**Comment by pedrobaeza** [comment]
@trapchik this has been refined across time, so maybe you migrated when not all patches were applied (or maybe there's something remaining), but without more data, we can't say.

**Comment by trapchik** [comment]
@pedrobaeza database we used has been backed up from Odoo 10.0-20190124 (Community Edition)
And we used OpenUpgrade 11 downloaded from GitHub at the end of last weekend
We even checked stock_move table postgres records in Odoo 10 DB and converted Odoo 11 DB and can see exactly the same WH/IN entries, but not showing in Odoo 11?

**Comment by pedrobaeza** [comment]
I think that traceability report is got from stock.move.line, but as said, this is not enough for investigating anything, but unfortunately, we can't investigate for you the problem. I recommend you to try again the migration with latest code and see, and if everything is correct, then check what are the changes in OpenUpgrade code between last time and now.

Closing this meanwhile there's no specific information for targeting the possible problem.

**Comment by trapchik** [comment]
@pedrobaeza we did another back up from Odoo 10.0-20190130 (Community Edition) an converted by using the latest OpenUpgrade 11 downloaded from GitHub this morning but have the same issue, in fact we can see the records in our system but somehow the link has been broken between UP/DOWN traceability (only showing WH/OUT) the only possible way for us to track the WH/IN is by going to the purchase order directly however this still doesn't appear to have any link to the serial number / lot that was assigned to the product. 

We have also checked the database it appears all products that were created before migration are missing the WH/IN step somehow? please see examples below from 2 different products

```
select * from stock_quant where lot_id=32029 or lot_id=31220;
  id   |        create_date         | quantity | propagated_from_id | package_id | cost | lot_id | location_id | create_uid | reservation_id | company_id | owner_id |         write_date         | write_uid | product_id | packaging_type_id | negative_move_id |       in_date       | reserved_quantity | removal_date
-------+----------------------------+----------+--------------------+------------+------+--------+-------------+------------+----------------+------------+----------+----------------------------+-----------+------------+-------------------+------------------+---------------------+-------------------+--------------
 35126 | 2018-12-20 10:10:14.863362 |        1 |                    |            |    0 |  31220 |           9 |          1 |                |            |          | 2019-01-30 00:10:01.371756 |         1 |         92 |                   |                  | 2018-12-20 10:10:15 |                 0 |
 36803 | 2019-01-28 13:25:39.324859 |       -1 |                    |            |      |  32029 |           8 |          1 |                |            |          | 2019-01-30 00:10:01.371756 |         1 |         92 |                   |                  | 2019-01-28 13:25:39 |                 0 |
 36829 | 2019-01-29 09:27:42.180811 |        1 |                    |            |      |  32029 |           9 |          1 |                |            |          | 2019-01-30 00:10:01.371756 |         1 |         92 |                   |                  | 2019-01-28 13:25:39 |                 0 |
(3 rows)
```

```
 select * from stock_quant where lot_id=32034 or lot_id=21193;
  id   |        create_date         | quantity | propagated_from_id | package_id | cost  | lot_id | location_id | create_uid | reservation_id | company_id | owner_id |         write_date         | write_uid | product_id | packaging_type_id | negative_move_id |       in_date       | reserved_quantity | removal_date
-------+----------------------------+----------+--------------------+------------+-------+--------+-------------+------------+----------------+------------+----------+----------------------------+-----------+------------+-------------------+------------------+---------------------+-------------------+--------------
 23682 | 2018-05-09 08:21:30.908658 |        1 |                    |            | 199.1 |  21193 |           9 |          1 |                |            |          | 2019-01-30 00:10:01.371756 |         1 |       1071 |                   |                  | 2018-05-09 08:21:33 |                 0 |
 36813 | 2019-01-28 13:25:39.324859 |       -1 |                    |            |       |  32034 |           8 |          1 |                |            |          | 2019-01-30 00:10:01.371756 |         1 |       1071 |                   |                  | 2019-01-28 13:25:40 |                 0 |
 36830 | 2019-01-29 09:27:42.180811 |        1 |                    |            |       |  32034 |           9 |          1 |                |            |          | 2019-01-30 00:10:01.371756 |         1 |       1071 |                   |                  | 2019-01-28 13:25:40 |                 0 |
(3 rows)
```

See how products with ID 36830 and ID 36829 both have 2 x records (these were created after migration 

While 23682 and 35126 only have 1 record and this is the WH/OUT record.

**Comment by pedrobaeza** [comment]
You are looking to the wrong place, as traceability is not done through quants, but as said, through `stock.move.line`. Quants are merged together on the migration, so the changes can be explained by that.

There's still a missing PR in #1702 for filling the lot in some rare cases (see the description on the PR), that can be your case. Try again the migration with that branch and tell me back.

**Comment by trapchik** [comment]
@pedrobaeza, tried again the migration using /addons/stock/migrations/11.0.1.1/post-migration.py from #1702 but same problem

We even created completely new database in Odoo 10.0-20190129 CE, created some products and some allocations in and out, but when did migration with OpenUpgrade still can't see any WH/IN records?

Please find backup attached (user dan AT serverfactory.co.uk / pass 123testing)

[odootest_2019-01-30_17-10-56.zip](https://github.com/OCA/OpenUpgrade/files/2813722/odootest_2019-01-30_17-10-56.zip)

**Comment by trapchik** [comment]
Hi @pedrobaeza Please could you confirm for me if anyone has had a chance to look at this? we really want to migrate to Odoo 11.0 however due to this problem we are very hesitant.

**Comment by pedrobaeza** [comment]
Please check #1768 to see if it solves your problem.
