### ISSUE TITLE
Annual financial statements accounting entries after upgrade to odoo 11

### ISSUE THREAD

**Issue by peter2018abc** [OCA/OpenUpgrade#1713]
Hi!
I migrated from odoo8 to odoo11 a few weeks ago. Unfortunately I only realized now that I forget to close the fiscal year 2017, so I am missing the annual financial statements accounting entries. Now my financial reports are all mixed up because the start entries are missing...

Since in odoo11 the whole concept about fiscal years has been changed I don't know how to correct this. Unfortunately I cannot run the migration again as I have been working in my odoo11 database since a month now...

So I guess I will have to enter the entries manually somehow. I could probably close the fiscal year in my odoo8 instance and then manually enter all the entries in odoo 11. Do you think this would be the way to go?

Thank you very much for your support.

**Comment by pedrobaeza** [comment]
In Odoo 11, there's no closing nor opening entries. Your problem will be probably the reverse one: you have entries that you have to remove. The initial balance is computed on the fly for all the past moves, and if there are opening entries, they are unbalancing the amount.

The other option is that you have an incorrect balance in previous years that you "patched" through opening entries, and now that "sins of the past"  are shown as no reset is done on each fiscal year.

Closing this any way as no directly related to OpenUpgrade.

**Comment by peter2018abc** [comment]
Thank you pedrobaeza!
I realized everything is working perfectly... My problem was I entered a start date when I ran the balance sheet wizzard... This is only requried for the win + loss calculation, not for the balance sheet!
