### ISSUE TITLE
openupgrade_records not available in v7?

### ISSUE THREAD

**Issue by christophlsa** [OCA/OpenUpgrade#172]
Hi,

I tried to install openerp v7 with the openupgrade_records addon to start the [analysis](https://doc.therp.nl/openupgrade/analyse.html) but I could not found this addon in the backend (all other addons are available). I used the 7.0 branch. Also I tried to use the bzr branch, started openupgrade with addons-path and increased the file permissions. Did I overseen something or is this broken?

**Comment by StefanRijnhart** [comment]
Well, we recently migrated this branch to github but it seems to be there: https://github.com/OpenUpgrade/OpenUpgrade/tree/7.0/openerp/addons/openupgrade_records

**Comment by StefanRijnhart** [comment]
Note that this branch was overwritten with a second attempt, maybe you have the first version and it's missing there.
