### ISSUE TITLE
[10.0->11.0] Error key already exists

### ISSUE THREAD

**Issue by lukepower** [OCA/OpenUpgrade#1724]
Impacted versions: Migration from 10.0 to 11.0

Steps to reproduce: Start the automated script as per documentation. The script runs the migration, but fails after a few minutes with the following error  in the log:

`odoo.tools.convert.ParseError: "duplicate key value violates unique constraint "ir_config_parameter_key_uniq"
DETAIL:  Key (key)=(mail.catchall.alias) already exists.
" while parsing /var/tmp/openupgrade/11.0/addons/mail/data/mail_data.xml:36, near
<record id="icp_mail_catchall_alias" model="ir.config_parameter">
            <field name="key">mail.catchall.alias</field>
            <field name="value">catchall</field>
        </record>
`

**Comment by pedrobaeza** [comment]
This is because you delete that system parameter in the past and recreate it manually. You have to delete it again, and run upgrade, or update your current DB deleting it.
