### ISSUE TITLE
[12.0] web: could not get content for web_planner_common.less defined in bundle 'web.assets_common'

### ISSUE THREAD

**Issue by davidtranhp** [OCA/OpenUpgrade#1735]
### Impacted versions:
12.0

### Steps to reproduce:
1. Prepare a v11.0 database with web_planner installed
2. Migrate to v12.0

### Current behavior:
The browser pops out a window with message:
```
The style compilation failed, see the error below. Your recent actions may be the cause, please try reverting the changes you made.

Could not get content for /web_planner/static/src/less/web_planner_common.less defined in bundle 'web.assets_common'.
```
### Expected behavior:
web_planner's Assets should be removed/replaced?

### Video/Screenshot link (optional):
![selection_202](https://user-images.githubusercontent.com/7938973/52532930-b9ddb000-2d5e-11e9-84ea-9df21d147e5d.png)

**Comment by davidtranhp** [comment]
In my migration test, I also found the table `web_planner` is still there after migration. Should it be removed during migration?

**Comment by mgielissen** [comment]
web_planner is part of Enterprise?

**Comment by davidtranhp** [comment]
It was in Odoo 11 CE and removed in Odoo 12. It is neither in Odoo 12 CE nor in EE

**Comment by ACouasnonPerso** [comment]
So is there a solution to this problem?

**Comment by pedrobaeza** [comment]
I haven't faced this using latest code. Can you repeat the migration?

**Comment by cubells** [comment]
@pedrobaeza 

I have faced this in a migration. To solve the problem I removed a view by running a sql command like this:

> delete from ir_ui_view where arch_db like '%web_planner%' and arch_db like '%less%';

**Comment by rvalyi** [comment]
not sure if that was the correct way either, but I had similar problems and in my tests with OpenUpgrade 1 month ago, I moved forward with ```delete from web_planner;``` and also deleting the module views with
```
delete from ir_ui_view where id in (select ir_model_data.res_id from ir_model_data join ir_module_module on ir_module_module.name = ir_model_data.module where model='ir.ui.view' and state='uninstalled' and active=False);
```

**Comment by cubells** [comment]
@rvalyi 

Perfect, but web_planner only had in my migration 1 view.

I delete all the views of uninstalled modules with 

> DELETE FROM ir_model_data WHERE model='ir.ui.view' AND res_id NOT IN(SELECT id FROM ir_ui_view);

I'll test your query in the future.

**Comment by pedrobaeza** [comment]
Without more information, I can't determine why that view is still there after the migration. When doing more migrations, if I face it, then I will be able to tell. Any way, the workaround of removing the view proposed by @cubells is good enough.

**Comment by davidtranhp** [comment]
I haven't faced this issue any more using latest code for the two recent databases. I am closing this for now.
Please feel free to reopen if you want.
