### ISSUE TITLE
Migration from [8.0] to [9.0] help is needed

### ISSUE THREAD

**Issue by GabbasovDinar** [OCA/OpenUpgrade#1749]
Hello OCA community. 

I migrated data from 7.0 to 8.0 and I had no problems. Then I started the database migration from 8.0 to 9.0 and I have some problems:

Some modules have been removed in Odoo 9.0 and some modules have been transferred to OCA. How can I migrate the database using the transferred ones to OCA with saving database? 
For example: in 8.0 I have account_analytic_analysis. After migration to 9.0 using the script: 
`python migrate.py --config=.openerp_serverrc-8 --database=odoo8db --run-migrations=9.0`
I have some errors 

> GET http://localhost:8069/account_analytic_analysis/static/src/css/analytic.css net::ERR_ABORTED 404 (NOT FOUND)
> GET http://localhost:8069/web/content/7469-f04e079/web.assets_common.js net::ERR_CONNECTION_REFUSED
> web:15 Uncaught ReferenceError: odoo is not defined
>     at web:15
> (anonymous) @ web:15
> web:35 GET http://localhost:8069/account_analytic_analysis/static/src/css/analytic.css net::ERR_ABORTED 404 (NOT FOUND)
> web:83 Uncaught ReferenceError: $ is not defined
>     at web:83

also the interface is not loaded. Should I put OCA modules in addons_path in the config file to migrate data of **account_analytic_analysis** to **contract** module? How can I remove account_analytic_analysis module? I tried via psql but is wrong

**Comment by pedrobaeza** [comment]
For this specific case, put `contract` on the addons path while migrating. OpenUpgrade already contains the renaming of the module (https://github.com/OCA/OpenUpgrade/blob/904045963f76169bcf4c2d54cb91715b976318dd/openerp/addons/openupgrade_records/lib/apriori.py#L44), and the migration scripts included in `contract` module do the rest (https://github.com/OCA/contract/blob/9.0/contract/migrations/9.0.1.0.0/pre-migration.py).

**Comment by GabbasovDinar** [comment]
@pedrobaeza I put the `contract` module to OpenUpgrade server 9.0 > server > addons and made new migration but the problem is not solved
![2019-02-14 20-43-39](https://user-images.githubusercontent.com/15119940/52798249-5b376f80-3099-11e9-93a7-6d53c63d8e1a.png)

**Comment by pedrobaeza** [comment]
Have you updated your DB later with a regular Odoo 9.0 distribution? Any way, it seems as simple as removing manually the offending view. Take into account this kind of "strange things" should be handled sometimes manually, but it's not so complicated.

**Comment by GabbasovDinar** [comment]
> Have you updated your DB later with a regular Odoo 9.0 distribution?

Yes. After migration, I updated modules using `-u all`.

**Comment by pedrobaeza** [comment]
Then remove by SQL the offending view
