### ISSUE TITLE
[9.0-account] with multicompany, the initial balance is deleted with all companies except the first one

### ISSUE THREAD

**Issue by cvinh** [OCA/OpenUpgrade#1753]
Impacted versions: 9.0

Steps to reproduce:
Migrate account from 8.0 to 9.0 with multicompany
The initial balances are in opening periods for all companies
Current behavior:
The initial balance is moved to standard journal only for the first company the query takes (ramdomly or postgresqlly I don't know)
The inital balances are deleted for other companies
Expected behavior:
The initial balances should be moved for every company.
Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
What do you mean by "starting balance"?

**Comment by cvinh** [comment]
'Initial balance'

**Comment by cvinh** [comment]
It happens here https://github.com/OCA/OpenUpgrade/blob/011d92c38665b4a65a1e99bc66520df422a57059/addons/account/migrations/9.0.1.1/pre-migration.py#L160

**Comment by pedrobaeza** [comment]
And what makes you think that only happens for first company? The code is generic, not centered in a specific company. This seems more a misconfiguration of data in the rest of the companies.

**Comment by cvinh** [comment]
The first the query takes... ;-)
The code does not look like it manages multicompany.
You can verify that with a 2 sec glance :-)

**Comment by pedrobaeza** [comment]
Which first? Unless you will be more specific, I will close the issue as no valid (which is for me now, as I have migrated without problems multi-company DBs).

**Comment by cvinh** [comment]
We did it too with a multicompany and the initial balances were deleted, can you point out the code that takes into account the multicompany ?
Maybe you managed to migrate a multicompany because the initial balance were not in 'special' periods (like we have here, the initial balances were in 'opening periods')
We managed it by moving the initial balance in a standard period so it's not a problem for us anymore but I believe that the code has to manage that case...
You also might consider that nobody migrates v8 to v9 nowadays...
I close the issue because we won't push a PR. We won't have the case anymore... but I wanted to contribute...

**Comment by pedrobaeza** [comment]
Then I think that's the problem: the special period must be used only for opening and closing entries, not for initial balances.

**Comment by cvinh** [comment]
Btw you would agree that the code should not search for the first special period to identify the initial balance and move it to a standard period... if the initial period is not supposed to be in a special period... it makes nonsense

**Comment by pedrobaeza** [comment]
IMO, that's a personal way of interpreting what special periods mean. I haven't never put an initial balance in a special period, but on the first normal period, and I haven't got any problem.
