### ISSUE TITLE
account_id not null constraint while inserting into account_voucher table during 8 to 9 migration

### ISSUE THREAD

**Issue by Rathnakreeswaran** [OCA/OpenUpgrade#1757]
Impacted versions:
account_id not null constraint while inserting into account_voucher table during 8 to 9 migration

Current behavior:
In post_migration.py file it shows error inside the move_view_accounts function 

How to solve it?
whether i have to delete the rows in account_account table where "type" column contains "views" .
please kindly anyone give me a solution???

**Comment by pedrobaeza** [comment]
This is because you have used in v8 view accounts for uses where regular accounts should be used, so change the type for that accounts, or switch the account to another regular one.
