### ISSUE TITLE
[12.0] password_crypt field migration

### ISSUE THREAD

**Issue by paulius-sladkevicius** [OCA/OpenUpgrade#1771]
After migration to v12, the `password` field for `res.users` was different from old field `password_crypt`, so I suppose there is need migration script. What you think?

**Comment by pedrobaeza** [comment]
Yes, it seems so. We should copy `password_crypt` in `password`

**Comment by MiquelRForgeFlow** [comment]
It's not than easy as a copy. We should encrypt the v11 passwords (in case they don't have password_crypt)

**Comment by pedrobaeza** [comment]
Not really. `auth_crypt` is auto-installed. We needed that in previous version, and it was done.
