### ISSUE TITLE
ProgrammingError: column "parent_id" of relation "project_task" already exists

### ISSUE THREAD

**Issue by ntodorova** [OCA/OpenUpgrade#1781]
Impacted versions: 10.0

Steps to reproduce: 
Migrate db to v 10.0 with installed project and hr_timesheet modules

Current behavior:
Logs critical error: ProgrammingError: column "parent_id" of relation "project_task" already exists.

The problem is caused by hr_timesheet/10.0.1.0/pre-migration.py line 32
When the line is removed everything works fine.

Expected behavior:
No error log

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
@ntodorova you have that column due to another module adding it, but it's not in standard Odoo. Thus, you have to rename the column before starting the migration.
