### ISSUE TITLE
while migrating the odoo database from 10 to 11 error raises in pyyaml because of the unknown tag !python present in stock_data.yml in openupgrade folder 

### ISSUE THREAD

**Issue by Rathnakreeswaran** [OCA/OpenUpgrade#1784]
Impacted versions:
unknown constructor tag !python in stock_data.yml
Steps to reproduce:

Current behavior:

Expected behavior:
how to resolve this?
Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Are you using migrate.py script? That one is not valid for version 11.

**Comment by Rathnakreeswaran** [comment]
yes i am using migrate.py script for database migration

**Comment by Rathnakreeswaran** [comment]
if not migrate.py what to be used?

**Comment by Rathnakreeswaran** [comment]
openupgrade package 11 --> scripts --> migrate.py

python migrate.py --config="path of config file" --database="name of the database" --run-migrations="11.0"

By above mentioned command i run the migration but it shows the error in pyyaml package  how to solve it?

Currently i am using python version 3.5.2

**Comment by pedrobaeza** [comment]
Use manual migration:

https://doc.therp.nl/openupgrade/migration_details.html
