### ISSUE TITLE
[12.0] Admin cannot log in with the old password.

### ISSUE THREAD

**Issue by LoisRForgeFlow** [OCA/OpenUpgrade#1797]
Impacted versions: 12.0

Steps to reproduce: migrate a database from v11.

Current behavior:
Admin cannot log in with the old password. You need to reset admin password through sql query to be able to access the database as admin.

Expected behavior:
Admin can log in with the v11 password.

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/23449160/56207524-46eb0100-604f-11e9-8074-a49ecf333e24.png)

@pedrobaeza @StefanRijnhart @mreficent any clue?

**Comment by pedrobaeza** [comment]
Well, in theory #1773 serves for this, but no more insights right now.

**Comment by captainjapeng** [comment]
I've experienced the same issue when I upgraded from 10.0 -> 11.0 -> 12.0
It seems that the password from 11 was set to id=1 where in my instance it should have been id=4 since id=1 is named **`__system__`**

**Comment by pedrobaeza** [comment]
Are the rest of users able to log-in  as usual?

**Comment by captainjapeng** [comment]
I've just tested with clean 10.0 with demo data but **demo** user successfully logged in on the 12.0 haven't tried on 11.0

**Comment by StefanRijnhart** [comment]
@captainjapeng if res_users with id = 1 still contains the old admin password and the new admin user does not have a password, this code has not run: https://github.com/OCA/OpenUpgrade/blob/12.0/odoo/addons/base/migrations/12.0.1.3/end-migration.py#L91. It therefore looks likely that your migration did not finish successfully.

**Comment by pedrobaeza** [comment]
Fix in #1801

**Comment by StefanRijnhart** [comment]
Kudos to @pedrobaeza who deduced that copying the password column is no good if every user's password is overwritten by password_crypt two lines down in the same migration script! Closing as there is a PR.

**Comment by captainjapeng** [comment]
Thanks

**Comment by mamcode** [comment]
I have the same issue today. :(

**Comment by pedrobaeza** [comment]
This is solved, so you probably migrated with outdated code.

**Comment by mamcode** [comment]
![Captura de pantalla de 2019-08-31 15-24-10](https://user-images.githubusercontent.com/334317/64068242-83388b80-cc03-11e9-9981-d261179a6d68.png)

@pedrobaeza screenshot of result of git log in my copy of OpenUpgrade v12

**Comment by pedrobaeza** [comment]
You should provide more information then as the original issue is solved.

**Comment by mamcode** [comment]
Is the same issue, but is not only the admin, I tried with two more users and I can't log in either.

**Comment by mamcode** [comment]
@pedrobaeza the database has the module auth_crypt, will it have something to do with the issue?

**Comment by pedrobaeza** [comment]
Well, that's the normal thing, and no, it doesn't matter that factor.

**Comment by mstuttgart** [comment]
Same bug here. I update two database of 11.0 to 12.0 and the older users not can login.

The last update in log is:

2020-01-28 07:44 OCA-git-bot                                          M─┐ Merge PR #2179 into 12.0
2020-01-28 07:41 Jairo Llopis                                         │ o [FIX] website_blog: use sets for attr_rm
2020-01-28 00:08 Pedro M. Baeza                                       M─┤ Merge pull request #2177 from Tecnativa/12.0-FIX-website_blog-change-templates
2020-01-27 21:41 Sergio Teruel                                        │ o [FIX] website_blog: Migration script. Add more replacements
2020-01-27 07:03 OCA-git-bot                                          M─┤ Merge PR #2176 into 12.0

**Comment by Uryon987** [comment]
Got same bug as @mstuttgart, old users can't login to updated database v12

**Comment by webgourou** [comment]
when restoring password from 11.0 version, it seems everything working fine now. 
Note: my previous passwords where already encrypt in SHA512
