### ISSUE TITLE
Migration from 8.0 to 9.0 fail with the filestore

### ISSUE THREAD

**Issue by sebastienhasa** [OCA/OpenUpgrade#1810]
Impacted versions:
12.0

I've got a dedicated instance of OpenUpgrade where I load the database
I want to migrate. I use the migration.py script, latest version.

If I only restore the database and not the filestore, the migration
work. Very well. But, if I load the filestore on my instance, with the
database, before doing the migration, the migration fail. I checked
the path and the access right of the filestore, and it is OK. I read
the migration log, but I'm not sure to understand it.

I joint the migration log to this repport.

PS: It would be great if we can have an IRC channel or a mailling list
for this kind of question.

[migration.log](https://github.com/OCA/OpenUpgrade/files/3121407/migration.log)

**Comment by sebastienhasa** [comment]
So, I got a typo on the config file for the `data_dir`. Now, this part is fixed.

**But** I still got missing attachments after my migration. It's strange. Before the migration, I've restored my entire archive (dump and filestore). But if I load the migrated archive, I got all my attachment missing. And the documentation didn't say anything about the attachments or the filestore.

**Comment by pedrobaeza** [comment]
The migration creates some attachments, so that can be the reason. Any way, not linked with OpenUpgrade itself, but with the deployment. And it's very advisable to not use `migrate.py` method, but manual one, as you don't control what automations do that script (maybe it's that one that discard the filestore).

**Comment by sebastienhasa** [comment]
> And it's very advisable to not use migrate.py method, but manual one, as you don't control what automations do that script (maybe it's that one that discard the filestore).

I'm sorry, I didn't understand this part.

**Comment by pedrobaeza** [comment]
Don't use the script for doing the migration, but migrate manually: https://doc.therp.nl/openupgrade/migration_details.html

**Comment by sebastienhasa** [comment]
> not linked with OpenUpgrade

If it is not linked with OpenUpgrade: Why after doing a migration _and_ still got a filestore in the migrated archive, Odoo 9.0 say that it missing all the attachments?

**Comment by pedrobaeza** [comment]
I mean this is not an issue of OpenUpgrade code, but how you are using it.

**Comment by sebastienhasa** [comment]
> I mean this is not an issue of OpenUpgrade code, but how you are using it.

I've just followed the documentation: https://doc.therp.nl/openupgrade/migrate.py.html
If it don't work by following the documentation, it maybe need a fix.

**Comment by pedrobaeza** [comment]
migrate.py is not supported since a long. It remains there, but with no support.

**Comment by sebastienhasa** [comment]
If I do the manual migration, is it going to work?

**Comment by pedrobaeza** [comment]
It should. I have migrated about 30 databases already and that problem didn't appear.

**Comment by sebastienhasa** [comment]
After checking the migrate.py script source code, it didn't modify
anything in the file store. So, the problem come from data about
attachment files that OpenUpgrade modify on the database. Or forget
to modify.

On my side, I wrote a shell script to automate a maximum the process.
This is what my script do:
- Unzip the Odoo database archive
- Extract the database name on the `manifest.json`
- Create locally a database with the name obtained from the manifest,
  the database is owned by odoo user.
- Restore the database file `dump.sql` in the database
- Restore the filestore on the right path and give it user odoo as owner
- Lunch `migrate.py` with the correct arguments (database, targeted version, etc)
- Copy the file store a directory with the `manifest.json`
- Modify the Odoo version in the `manifest.json`
- Dump the migrated database on a file named `dump.sql` and put it at side of
  the new version of `manifest.json` and the new filestore
- Build a zip archive with the `manifest.json`, the `dump.sql` and the filestore


At the end I obtain an archive I can restore on a version 9 of Odoo.
No error message during restoration. But, even with a filestore
restored, Odoo say it cannot find some attachments, like contact
photos, etc.

As I cannot find any info about the filestore and OpenUpgrade, or even
only on the filestore, I don't know if what I do is correct.

**Comment by pedrobaeza** [comment]
Sorry, but again this is not something that I have found in any of the migrations I have done, so I can't say what is the problem.
