### ISSUE TITLE
[Migration v8 to v9] migration tax problem

### ISSUE THREAD

**Issue by pedroortega-punt** [OCA/OpenUpgrade#1817]
We have made the upgrade from v8 to v9, then made the update all in v9, but when you try to eliminate the records of "account_fiscal_position_template" that are in other works and by restrictions of sql does not allow.

We have tried, doing in v8 before migrating, to pass the account_chart_update, without passing the "account_chart_update" and the process is cut when trying to delete the records of these tables.

Are we doing something wrong? or is there some process missing?

**Comment by pedrobaeza** [comment]
In v8, you have fiscal position templates with account mapping that are views, not regular accounts. Change this in v8 and then migrate.

**Comment by pedroortega-punt** [comment]
@pedrobaeza 
![imagen](https://user-images.githubusercontent.com/18347857/57451390-5ed62f00-7261-11e9-95d3-42850ab4b71f.png)
do you mean here, or do we have to change all the view type accounts of v8 to regular?
do you mean here, or do we have to change all the view type accounts of v8 to regular?
