### ISSUE TITLE
[Migration v8 to v9] migration tax problem

### ISSUE THREAD

**Issue by pedroortega-punt** [OCA/OpenUpgrade#1818]
@pedrobaeza
imagen
do you mean here?
In the Position templates you can only select from the view type, I do not understand?

**Comment by pedroortega-punt** [comment]
![imagen](https://user-images.githubusercontent.com/18347857/57453148-e9b92880-7265-11e9-8b06-10c0adcef3f0.png)
Here?

**Comment by pedrobaeza** [comment]
Yes, that should be normal accounts, not regular.
