### ISSUE TITLE
duplicate key value violates unique constraint "ir_sequence_type_code_unique

### ISSUE THREAD

**Issue by Yenthe666** [OCA/OpenUpgrade#183]
Hi guys

First of all, thanks for this open-sourced idea.
After trying the script for a migration from V7 to V8 I get the following error:
<code>ParseError: "duplicate key value violates unique constraint "ir_sequence_type_code_unique"
DETAIL:  Key (code)=(stock.orderpoint) already exists.
" while parsing /odoo/odoo-server/addons/stock/stock_data.xml:153, near
<record id="sequence_mrp_op_type" model="ir.sequence.type">
            <field name="name">Stock orderpoint</field>
            <field name="code">stock.orderpoint</field>
        </record></code>

In the logfile I get this:
<code>2014-12-29 07:27:44,003 4051 ERROR myDB_migrated openerp.sql_db: bad query: INSERT INTO "ir_sequence_type" ("id", "code", "name", "create_uid", "write_uid", "create_date", "write_date") VALUES(nextval('ir_sequence_type_id_seq'), 'stock.orderpoint', 'Stock orderpoint', 1, 1, (now() at time zone 'UTC'), (now() at time zone 'UTC')) RETURNING id
Traceback (most recent call last):
  File "/var/tmp/openupgrade/8.0/server/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
IntegrityError: duplicate key value violates unique constraint "ir_sequence_type_code_unique"
DETAIL:  Key (code)=(stock.orderpoint) already exists.</code>

Could anybody tell me why this happened, if it is a common bug and how I could fix it?

**Comment by pedrobaeza** [comment]
This can be due to a bad initial DB, with the sequence type not linked to an XML-ID sequence. Delete manually `stock.orderpoint` record on ir_sequence_type table and you can continue with the migration.

**Comment by StefanRijnhart** [comment]
You need to merge the pull requests of the modules that you need to migrate. Your error is solved in the stock migration, in this line: https://github.com/OpenUpgrade/OpenUpgrade/pull/125/files#diff-72bd9ca04587930a7f05272bfd7e69a3R73
Note that all unmerged migration scripts are pretty much work in progress.

**Comment by lucaorioli** [comment]
How can I merge the pull requests of the modules that you need to migrate?

Thanks
Luca Orioli

**Comment by StefanRijnhart** [comment]
@lucaorioli Your question is out of scope for this project. Lots of tutorials over the web I would think.

**Comment by lucaorioli** [comment]
Can you link me someone? I'm not able to find any how-to... I've tried to launch migration script without luck..

Thanks in advance!

**Comment by StefanRijnhart** [comment]
http://stackoverflow.com/questions/867831/merge-changes-from-remote-github-repository-to-your-local-repository

**Comment by lucaorioli** [comment]
thanks! And some how to about how to use openupgrade? I have to launch migration script as it is? Or I have to download something else?

Thanks!

**Comment by legalsylvain** [comment]
To begin, you can read the wiki of this project, https://github.com/OpenUpgrade/OpenUpgrade/wiki/Migration-from-7.0-to-8.0
and specially this link : https://doc.therp.nl/openupgrade/index.html

Kind regards.

**Comment by ovnicraft** [comment]
Merge dont fix the issue, i am migrating and got the same error.

**Comment by OpiumSmoke** [comment]
I'm trying to migrate a reference database and I'm getting a similar error:
```
odoo.tools.convert.ParseError: "duplicate key value violates unique constraint "res_users_login_key"
DETAIL:  Key (login)=(admin) already exists.
```

Migrating to 12. Used the reference DB from here: https://github.com/OCA/OpenUpgrade/releases/tag/databases
