### ISSUE TITLE
[6.1 -> 7.0] edi.document removed but table and datas still present

### ISSUE THREAD

**Issue by legalsylvain** [OCA/OpenUpgrade#184]
Hi all,
I just realized an quick analyse on my current database 7.0 and I saw that the bigger table was edi_document with datas older than the migration 6.1 -> 7.0.
In fact, 
in 6.1 there is a osv model edi.document : https://github.com/OpenUpgrade/OpenUpgrade/blob/6.1/addons/edi/models/edi.py#L77
in 7.0 there isn't : https://github.com/OpenUpgrade/OpenUpgrade/blob/7.0/addons/edi/models/edi.py#L77

but in my database, the model is still present in ir.model.model and datas are in the table, although I guess there are now useless.

Do you think there is a bug in OpenUpgrade. (models that are not present must be deleted ?) In that case I can provide a patch to fix it in https://github.com/OpenUpgrade/OpenUpgrade/blob/7.0/addons/edi/migrations/7.0.1.0 ?

Or Do I have to clean manually the database after a migration ? Is there some tools to do that ? Did you faced to the same problem ?

Kind regards.

**Comment by pedrobaeza** [comment]
I think by default OpenUpgrade doesn't remove any table because it can be used in a later migration script or only for reference (as done with columns with legacy names), but you can install database_cleanup module to remove these tables.

**Comment by StefanRijnhart** [comment]
Exactly, that is what https://github.com/OCA/server-tools/tree/8.0/database_cleanup is for. I would say that this module should be used (still with care!) after the upgraded database has been running stable for a while. Version 7 here: http://bazaar.launchpad.net/~therp-nl/openupgrade-tools/7.0-add-database_cleanup/files/head:/database_cleanup/

**Comment by pedrobaeza** [comment]
FYI, I have just created a PR to bring the module to server tools GitHub repo: https://github.com/OCA/server-tools/pull/106

@StefanRijnhart, maybe a reference to this module in the OpenUpgrade documentation would be good, doesn't it?

**Comment by StefanRijnhart** [comment]
Yes!

**Comment by legalsylvain** [comment]
Thanks for your clear explanations.
I'll take a look on that module and review the PR.

Kind regards.

**Comment by pedrobaeza** [comment]
I have improved the documentation here: https://github.com/OpenUpgrade/OpenUpgrade/pull/186.

Please review
