### ISSUE TITLE
[12.0] Account payment term multicompany ir.rule disabled

### ISSUE THREAD

**Issue by JordiBForgeFlow** [OCA/OpenUpgrade#1859]
I don't see why the rule 'account.account_payment_term_comp_rule' is explicitly disabled after the migration the post-migration:

https://github.com/OCA/OpenUpgrade/blame/12.0/addons/account/migrations/12.0.1.1/post-migration.py#L8

@mreficent

**Comment by pedrobaeza** [comment]
Check https://github.com/OCA/OpenUpgrade/issues/1448#issuecomment-405007947. It was for preserving the same behavior that you have in previous versions, but maybe it's better to revert to my previous idea of emptying `company_id`.

**Comment by MiquelRForgeFlow** [comment]
I explained explicitly in https://github.com/OCA/OpenUpgrade/pull/1861.
