### ISSUE TITLE
Some product.template are gone after migration from v7 to v8

### ISSUE THREAD

**Issue by sebastienhasa** [OCA/OpenUpgrade#1869]
Impacted versions:

Latest version for migration from OpenERP v7 to v8

Steps to reproduce:

Load our database, migrate and inspect the result

Current behavior:

Some product.template are gone after the migration. It searched but
cannot find why the product.template and not any other. When I read
the migration.log, I don't find any error for product.template. And
when I see a SQL request in the migration.log on product_template,
they are restricted to only apply on centain product_template.id. The
contraint list some id and this list only contain id who where
preserved after the migration.

It's like some product.template are simply ignored. But I cannot find why.

Expected behavior:

All product.template are preserved

**Comment by pedrobaeza** [comment]
AFAIK, there are no product_template rip-off in the migration. Are you sure the database is the same or is it an old one? Is there any DROP CASCADE operation you have made?

**Comment by sebastienhasa** [comment]
After check, the migration was done from the wrong database.
