### ISSUE TITLE
[12.0-product] Attribute line values are gone with product variants

### ISSUE THREAD

**Issue by cvinh** [OCA/OpenUpgrade#1875]
Impacted versions: 12.0

Steps to reproduce:
Migrate to v12.0 a database with product variants
Current behavior:
attribute line values do not appear
Expected behavior:
attribute line values should be migrated

Video/Screenshot link (optional):

**Comment by MiquelRForgeFlow** [comment]
See https://github.com/OCA/OpenUpgrade/pull/1882.
