### ISSUE TITLE
constraints

### ISSUE THREAD

**Issue by hbrunn** [OCA/OpenUpgrade#188]
do we want to have a helper function that lifts all constraints on a column?

**Comment by StefanRijnhart** [comment]
:+1:

**Comment by pedrobaeza** [comment]
It can be useful :+1:

**Comment by StefanRijnhart** [comment]
WIP still, or did I miss something?

**Comment by pedrobaeza** [comment]
Any news on this?

**Comment by hbrunn** [comment]
didn't happen up to now. I think this is on hold until somebody runs into a case again where this is necessary

**Comment by hbrunn** [comment]
finally: https://github.com/OCA/openupgradelib/pull/49
