### ISSUE TITLE
Missing migration that deals with the removal of project_long_term in Odoo.

### ISSUE THREAD

**Issue by mvaled** [OCA/OpenUpgrade#189]
After a migration from 7.0.  Several errors are found as reported in this [email](https://lists.launchpad.net/openupgrade-drivers/msg00460.html).

This issue deals with having the "Project Phase" actions and menus still in the DB after the migration.  The addon `project_long_term` was removed in Odoo.  This needs to be dealt with.  This issue servers to track this removal and its migrations.

**Comment by StefanRijnhart** [comment]
This module is deprecated ('deprecation' Odoo style is of course: removed completely). You should either port it to 8.0, or uninstall it from your migrated database.

**Comment by StefanRijnhart** [comment]
You could comment on this module on https://github.com/OpenUpgrade/OpenUpgrade/wiki/Migration-from-7.0-to-8.0 (which I think should be in the Sphinx doc really)

**Comment by StefanRijnhart** [comment]
Actually, maybe OpenUpgrade should warn about obsolete modules and any known adoption attempt by the OCA.

**Comment by mvaled** [comment]
Hi @StefanRijnhart,

There are three possible scenarios here:  (1) You need to keep the data, (2) You have decided you will move to Odoo and forget about the data, (3) You're exploring the changes between OpenERP 7.0 to make your mind.

The first and third cases would be satisfy by simply giving a BIG BIG WARNING when you have a module installed and it is removed in your target version. 

The second case would simply drop everything.

I think OpenUpgrade should work by default as in (3), ie. be conservative.   This means no change whatsoever in the code.  But as you suggest the docs should address the issue and perhaps several functions in `openupgrade` could assist those who need to simply drop everything.

Currently, I have simply reintroduced this module with empty models and XMLs so the upgrading process takes care of removing everything.  I know my employer doesn't really use it.

**Comment by mvaled** [comment]
BTW, where is the code of the Sphinx doc?

**Comment by StefanRijnhart** [comment]
Doc are in https://github.com/OpenUpgrade/OpenUpgrade/tree/8.0/openerp/openupgrade/doc

To clean up your database, use our module https://github.com/OCA/server-tools/tree/8.0/database_cleanup

**Comment by StefanRijnhart** [comment]
Closing this as this is out of scope for the default migration. If a version of the module is maintained for older versions, it can take care of its own migration, otherwise it can be removed with database_cleanup.
