### ISSUE TITLE
[12.0][account] action_view_account_move_line_reconcile ('account.move.line.reconcile')

### ISSUE THREAD

**Issue by OthmaneGhandi** [OCA/OpenUpgrade#1890]
Impacted versions: 12.0

Current behavior: When you try to open Account items you got error related to 'account.move.line.reconcile' 

The problem is that the action action_view_account_move_line_reconcile in V11 is related  to 'account.move.line.reconcile' that doesn't exist anymore in V12

you can see #1507 for more insights

**Comment by pedroslopez** [comment]
This happened to me as well, and I was able to solve it by simply deleting the ir.actions.act_window for account.move.line.reconcile

**Comment by OthmaneGhandi** [comment]
> This happened to me as well, and I was able to solve it by simply deleting the ir.actions.act_window for account.move.line.reconcile

I was able to solve it the same way, but I think it will be better if it is be included in migration script to avoid it in upstream

**Comment by pedrobaeza** [comment]
Yes, better to be solved on OpenUpgrade itself if possible. I'll check next week.

**Comment by pedroslopez** [comment]
My guess is that since there is now an ir.actions.client with the same xml id (account.action_view_account_move_line_reconcile), it didn't delete the old ir.actions.act_window that was removed?

**Comment by OthmaneGhandi** [comment]
I made a PR to handle this issue #1896 it needs to be reviewed
