### ISSUE TITLE
[12.0] Admin user cannot see/edit groups after running the migration

### ISSUE THREAD

**Issue by MaxyMoos** [OCA/OpenUpgrade#1891]
### Steps to reproduce
- Create a new database in Odoo v11
(Optional ?) I installed the `account` module for good measure
- Migrate this database to v12
- Check the admin user form view

### Current behavior
* When we are not in debug mode, nothing is seen in the `Access rights` panel
* In debug mode, we can only see the `User type` selection field, with only 'Portal' or 'Public' values enabled

### Expected behavior
* We get the same set of groups settings as we had in v11 or as we have in a newly created database in v12

### Video/Screenshot link (optional)

The admin user form view in v11 (technical features activated)
![adminv11_withdebug](https://user-images.githubusercontent.com/5863446/59913364-4fc5cd80-9418-11e9-9ec7-44511b3a691e.png)

The admin user form view in the v12 migrated database (technical features activated)
![admin_debug](https://user-images.githubusercontent.com/5863446/59913429-69671500-9418-11e9-9129-008e36673f88.png)

The admin user form view in a v12 non-migrated database (technical features activated)
![admin_vanillav12](https://user-images.githubusercontent.com/5863446/59913727-fd38e100-9418-11e9-96b5-cfb7885b183a.png)

**Comment by pedrobaeza** [comment]
Thanks for reporting. Fixed in 8870b55

**Comment by MaxyMoos** [comment]
Thanks so much @pedrobaeza 👍
