### ISSUE TITLE
[12.0] website_hr_recruitment: cannot located in the parent view <xpath expr="//div[@id='o_new_content_menu_choices']//ul">

### ISSUE THREAD

**Issue by davidtranhp** [OCA/OpenUpgrade#1894]
Impacted versions:
12.0

Steps to reproduce:
Migrate a v11 production database

Current behavior:
```
cannot located in the parent view
<xpath expr="//div[@id='o_new_content_menu_choices']//ul">
```

Expected behavior:
The ul does not exist in v12. It should be div

**Comment by pedrobaeza** [comment]
This has nothing to do with the migration, but with noupdate views you have on your previous production database. Please filter a bit your issues before publishing here.

**Comment by octagonosrl** [comment]
yes it has. I just finished the upgrade,  and I have the same problem. In Odoo 11 all is working ok.

odoo12@ip-172-31-6-166:~/OpenUpgrade$ tail -f  /var/log/odoo12/odoo12-server.log 
ValueError: El elemento '<xpath expr="//div[@id='wrapwrap']/header/div">' no puede ser localizado en la vista padre
Contexto del error:
Vista `preHeader`
[view_id: 2572, xml_id: n/a, model: n/a, parent_id: 1087]

load could not load template
Template: website.layout

**Comment by pedrobaeza** [comment]
It's the same. You have to manually remove offending views.
