### ISSUE TITLE
Adding progressbar2 support to OpenUpgrade and openupgradelib

### ISSUE THREAD

**Issue by yann-papouin** [OCA/OpenUpgrade#1897]
I made some changes in my OpenUpgrade and openupgradelib local branches to use the progressbar module [1] in order to display current progress for very long methods.

Would you accept PR with this dependency ?

```
    with progressbar.ProgressBar(max_value=cr.rowcount) as bar:
        for template_id, std_price in cr.fetchall():
            template_obj.write(cr, SUPERUSER_ID, [template_id],
                            {'standard_price': std_price})
            bar.update(bar.value+1)
```
Will output:
```
2019-06-23 12:13:15,571 5481 INFO db OpenUpgrade.product: Creating product_template.standard_price properties for 364176 products. 
80% (294001 of 364176) |#################            | Elapsed Time: 2:12:08 ETA:   0:42:41
```
[1] https://pypi.org/project/progressbar2/

**Comment by pedrobaeza** [comment]
The problem with that library is that is Python 2, isn't it? We need one to be compatible with both P2 and P3, and ideally this should be implemented as a decorator or similar in `openupgradelib`.

**Comment by ypapouin** [comment]
progressbar2 is Python 2/3 compatible, and I found that some work has already be done to cover this problem with a decorator.

https://github.com/OCA/OpenUpgrade/issues/326
https://github.com/OCA/openupgradelib/pull/68

**Comment by pedrobaeza** [comment]
OK, perfect. Then can you propose the decorator in openupgradelib?

**Comment by ypapouin** [comment]
I made a MP that is now green

**Comment by pedrobaeza** [comment]
OK, closing this issue and we continue in the PR.
