### ISSUE TITLE
[11.0] odoo.tools.convert.ParseError: "External ID not found in the system: web._assets_primary_variables" while parsing None:3, near

### ISSUE THREAD

**Issue by sarahosay** [OCA/OpenUpgrade#1905]
Impacted versions: 11.0

Steps to reproduce: run migrate.py file

sudo python migrate.py --config=/opt/odoo10/.odoorc --database=sample_db --run-migrations=11.0

Current behavior: Could not upgrade to version 11.0

Expected behavior: Should successfully migrated the database.

Video/Screenshot link (optional):
![Selection_016](https://user-images.githubusercontent.com/7303737/60430502-0b180e80-9c30-11e9-8ec0-9be69786b0c7.png)

**Comment by pedrobaeza** [comment]
migrate.py is not supported on version 11.0.

Use manual migration method.

**Comment by pedrobaeza** [comment]
Removed script in 65c2e458223fc5c83870801b75d0de3bccdb5618 for avoiding more mistakes.
