### ISSUE TITLE
[7 -> 8] Bad handling of attachments on products

### ISSUE THREAD

**Issue by alexis-via** [OCA/OpenUpgrade#1912]
Impacted versions: migration from 7 to 8

When you have a look at the code introduced by this PR of @M2tec :
https://github.com/OCA/OpenUpgrade/pull/706

It executes : UPDATE ir_attachment SET res_model = 'product.template'  WHERE res_model = 'product.product';

But "res_id" is not updated !!! Either both res_model AND res_id are updated, or both are left unchanged ; but the current code is not good.

**Comment by pedrobaeza** [comment]
Totally right! I have never needed it though... Are you doing a PR?

**Comment by alexis-via** [comment]
I don't plan to do a PR myself, because, for my use-case, I disabled the SQL query that updates res_model from product.product to product.template (I need to keep the attachments on product.product).

**Comment by pedrobaeza** [comment]
Reverted in f4ff1d62de1ad8da16eaa948bfc083fa7bbbe24c
