### ISSUE TITLE
[12.0] stock: migration of stock.rule

### ISSUE THREAD

**Issue by LoisRForgeFlow** [OCA/OpenUpgrade#1919]
https://github.com/OCA/OpenUpgrade/blob/7a0eba613ac70809847f1797e1e5458134e0e73f/addons/stock/migrations/12.0.1.1/post-migration.py#L13

@pedrobaeza @mreficent Are you sure about this?, in most of the cases the rules will be just pull, and by adding them the push component you might be introducing unwanted behaviors. You can start to anticipate that with this example:

1. Take standard stock -> customers rule (which in a new v12 db is just pull) and change it to pull n push, which would be the result in a v11 db migrated with this script (not tested but that's what I undertand here):
![image](https://user-images.githubusercontent.com/23449160/61044292-9d5ea600-a3d8-11e9-8b7b-d76cd4e442ac.png)

2. Then just receive products into stock:
![image](https://user-images.githubusercontent.com/23449160/61044322-b10a0c80-a3d8-11e9-8686-02db09b1ca82.png)

3. And here you have a automatic  (and unwanted) delivery to customers
![image](https://user-images.githubusercontent.com/23449160/61044437-f0385d80-a3d8-11e9-9255-da517018c003.png)

Please, correct me if I did any incorrect assumption. 

Thanks!

**Comment by MiquelRForgeFlow** [comment]
Fixed in https://github.com/OCA/OpenUpgrade/pull/1924.

**Comment by LoisRForgeFlow** [comment]
Thanks!
