### ISSUE TITLE
[11.0] error expected singleton mail.followers()

### ISSUE THREAD

**Issue by mohamedhagag** [OCA/OpenUpgrade#1928]
https://github.com/OCA/OpenUpgrade/blob/08fde8991ae9352f0ec69c0eb1b09572081f57fe/addons/project/migrations/11.0.1.1/post-migration.py#L98

mail.followers() have zero records in my case.

should we add new_follower to the condition to avoid the mentioned error ?

I tried it this way and it's bypassing this error.

**Comment by pedrobaeza** [comment]
Which are the conditions for having that error? I haven't faced it after migrating a lot of databases.

**Comment by mohamedhagag** [comment]
this line defining new_follower
https://github.com/OCA/OpenUpgrade/blob/08fde8991ae9352f0ec69c0eb1b09572081f57fe/addons/project/migrations/11.0.1.1/post-migration.py#L93 
may return false which is the case that happened with me, so it raised the mentioned error with zero records.

I'm not sure how this happened (new_follower = zero record) as the system age is about 2 yrs and have long history of work.

**Comment by pedrobaeza** [comment]
It seems something incorrect in your DB, but in this case checking that is very cheap, so I introduce it in f93b7ca94425233c83ff92297fd0b3fe7f2d5e3e.
