### ISSUE TITLE
[12.0] exclude custom fields from base upgrade

### ISSUE THREAD

**Issue by mohamedhagag** [OCA/OpenUpgrade#1929]
Impacted versions: 12.0

Steps to reproduce: add a custom field to users or any model using the web UI

Current behavior: base upgrade fails on ir.model.fields(FIELD_ID) and keyError model.name

Expected behavior: base upgrade should not fail

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Exclude from what? Unless you put more information of the error, it's impossible to deduce anything.

**Comment by mohamedhagag** [comment]
from base module upgrade, when trying to upgrade custom fields in the base module upgrade it raises errors as these custom fields are not related to a module .

BTW This error didn't happen with OpenUpgrade 11.0 -- upgrading from 10.0 > 11.0 passed without this error and with custom fields in place, but fails with 12.0 .

to pass the error I deleted the custom fields from the DB .

I didn't dig deep in the code to know exactly what should be changed, sorry for that .

**Comment by pedrobaeza** [comment]
Sorry, but this is still not enough information. You must put the exact log error and the context in which it happens.

**Comment by pedrobaeza** [comment]
Closing as no further answer.
