### ISSUE TITLE
[12.0][MRP] company_id not null constraint while creation a new mrp production 

### ISSUE THREAD

**Issue by OthmaneGhandi** [OCA/OpenUpgrade#1930]
Hi @mreficent 

I was using #1683 and I got a weird error related to company_id constraint while trying to work with mrp production (That was migrated from V10 -> V11 then V11 -> V12)

I can't create a new mrp production because the stock.move couldn't be created

https://user-images.githubusercontent.com/6293989/61187869-0b23ff80-a66f-11e9-8393-2c39f72b63a6.png

I checked that in _generate_finished_moves (method related to create the stock move) all values (company_id within them) are well set --> but in the creation of the stock move, some of these values are not taken into consideration, which is very weird. Is there an explanation to this ?

@pedrobaeza  do you have any suggestion for this issue ?
Is there any one who got this same issue ?

Thanks

**Comment by pedrobaeza** [comment]
Why are you opening an issue for a non merged PR? Sorry, but no suggestion nor action to take here until PR gets reviewed and merged.
