### ISSUE TITLE
[Info] how to patch existing Odoo branch to be able to launch openupgrade analysis

### ISSUE THREAD

**Issue by njeudy** [OCA/OpenUpgrade#1931]
Hello, 

I want to try to migrate from 12.0 to saas-12.3 odoo community database.
I know I need to launch openupgrade analysis, but what are the steps to patch saas-12.3 branch to  have openupgrade version ? Is there a readable doc to do this (and migrate for correct version because I think some times we had to change it ?)

This question is valid to prepare work between 12.0 and master for example, or to launch analysis between 10.0 to 12.0 directly for example.

Is it possible, where can I read and check to find steps to achieve ?

Thanks,

**Comment by pedrobaeza** [comment]
For analysis, you can read https://doc.therp.nl/openupgrade/analyse.html, but the only way to get the patches we have done in Odoo itself is to compare regular Odoo code with OpenUpgrade one, as it has been split through several commits and progressive patches.

I don't recommend you to do this upgrade though, as it will require a lot of efforts by your part and you will be then stuck in that intermediate version, needing also to provide other migration scripts/patches for migrating to 13.0/14.0/... Why don't you wait for official 13.0? It's not so far, and you can contribute to the official OpenUpgrade 13.0, having "for free" already analysis and patched Odoo.

**Comment by pedrobaeza** [comment]
Closing as no further answer.
