### ISSUE TITLE
[12.0] mail_bot migration is renaming former admin user to "OdooBot"

### ISSUE THREAD

**Issue by LoisRForgeFlow** [OCA/OpenUpgrade#1953]
It should rename v12 new System (`__system__`) user.

Current:
ID: 1, name: Sytem, login:`__system__`
ID: XXX, name: OdooBot, login: admin

Expected:
![image](https://user-images.githubusercontent.com/23449160/62118661-61737e00-b2be-11e9-8151-c35c6b890db6.png)

cc @mreficent @pedrobaeza

**Comment by pedrobaeza** [comment]
This is done for preserving all assignations, comments and so on to not become `OdooBot` suddenly. You decide if deactivating user `admin` from here (being now a normal user). I think this is the best approach.

**Comment by LoisRForgeFlow** [comment]
But now if I log with my old admin login I am suddenly renamed to "OdooBot" and if I write in any chatter it will say "OdooBot". Don't you think this is also not good?

**Comment by pedrobaeza** [comment]
I'm not getting you now... Please rephrase again the main comment of the issue for trying to understand you.

**Comment by LoisRForgeFlow** [comment]
Recent test migration from v11 to v12:

1. send new messages:
![image](https://user-images.githubusercontent.com/23449160/62119835-bc0dd980-b2c0-11e9-8c4b-8c91d863ce79.png)

2. Old messages:
![image](https://user-images.githubusercontent.com/23449160/62119940-efe8ff00-b2c0-11e9-8594-13f74ae698b6.png)



before it would say that the message was sent by Administrator. Is this preserving assignations to not  become OdooBot?

**Comment by pedrobaeza** [comment]
But then OdooBot is uid=1 or is it another one?

**Comment by LoisRForgeFlow** [comment]
@pedrobaeza it is a different one. But if you test with a new v12 database after installing mail_bot, uid 1 is renamed from "System" to "OdooBot".

If this renaming is done also this way in Openupgrade, old comments and new ones from Administrator will be respected, however now Openupgrade lets you with uid 1 "System" (login `__system__`) and a new uid (for example 999) with name "OdooBot" (login admin)

**Comment by MiquelRForgeFlow** [comment]
Fixed in https://github.com/OCA/OpenUpgrade/pull/1954.

**Comment by pedrobaeza** [comment]
Fixed in #1956
