### ISSUE TITLE
ODoo 10 - Odoo 11

### ISSUE THREAD

**Issue by jayo2005** [OCA/OpenUpgrade#1957]
Can someone please tell me steps to upgrade Odoo 10 to 11. I can only find 

```
Basically these are the steps :

a) First You need to download two openupgrade libraby,

 1) https://github.com/OCA/OpenUpgrade/tree/8.0

 2) https://github.com/OCA/OpenUpgrade/tree/9.0


b) Install openupgradelib.
1) Download openupgradelib from https://pypi.python.org/pypi/openupgradelib
2) Install with command : sudo python setup.py install

c) Run Automated Migration script
1) Go to specific path of openupgrade where you find 'migrate.py' file

2) python migrate.py --config=[your openerp.conf] --database=[your database] --run-migrations=[your migrations]

 --config = v9 config file(in which version you want to migrate)

 --database = database which we would like to migrate(installed database)

 --run-migrations = version in which you would like to migration



d) 'migration.log' file is created for error tracking.

e) If any error occured while migration script is running, need to solve explicitly the problem(by psql) and run migration script again.

f) New database is created in v9 'databasename_migrated' with '_migrated'.
```

I cannot find migrate.py in the Odoo 11 folder when I download from https://github.com/OCA/OpenUpgrade/tree/11.0

**Comment by pedrobaeza** [comment]
Check manual migration steps: https://doc.therp.nl/openupgrade/migration_details.html

**Comment by jayo2005** [comment]
https://github.com/OCA/OpenUpgrade/blob/11.0/scripts/migrate.py is  missing how can I run it

**Comment by pedrobaeza** [comment]
That script is not working in that version and that's why it has been removed.

**Comment by jayo2005** [comment]
The Manual says to use migrate.py. What script should I use? When upgrading to Odoo 11 from 10 do I download Branch 10 or Branch 11

**Comment by pedrobaeza** [comment]
That's not true. See the link I have provided.

**Comment by jayo2005** [comment]
Ok so I use branch 11. What script do I run to start the migration?

**Comment by pedrobaeza** [comment]
Sorry, no more to say. Read documentation.

**Comment by Flash619** [comment]
@pedrobaeza Following up on this with a similar issue. Documentation only references migrate.py, you just stated earlier that migrate.py was removed due to bugs. What do you suggest we use as an alternative?

**Comment by Flash619** [comment]
All documentation says is,

> Run the upgrade and check for errors.

How?

**Comment by rvalyi** [comment]
@Flash619 mostly you should look at the errors that you get in the logs where you started Odoo. Typically you get some blocking errors that you fix with extra scripts or preparing the data with SQL or something like https://github.com/camptocamp/anthem then you try again untill it finish. You can still have non blocking errors in your logs, typically failures to create unique constraintes because of your data, then you better do extra work with your data to have Odoo standard --update=all option generate no error at all. And of course you should still do functional tests...
