### ISSUE TITLE
7.0 - 8.0, 8.0 - 9.0 'sale_report' table (view) is not copied into migrated database

### ISSUE THREAD

**Issue by raviprasadmr** [OCA/OpenUpgrade#1961]
Impacted versions:
8.0, 9.0
Steps to reproduce:
run the migrate script successfully
Current behavior:
sale_report view is not copied in migrated database.
Expected behavior:
sale_report view should have been copied.
Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
This is not a real table, but an SQL view, so no copy possible. If you have changed it, you must change it the same in new version.
