### ISSUE TITLE
[11.0] migration from v10 to v11 : stock quant not the same

### ISSUE THREAD

**Issue by OthmaneGhandi** [OCA/OpenUpgrade#1962]
When I run this query  **select count(*) from stock_quant;**   in both my databases V10 & V11 I don't get the same result.
* V10 = 3026
* V11 = 1467

Hint maybe the issue has relation with this #1952  but I'm not sure

Thanks
@mreficent  @pedrobaeza

**Comment by MiquelRForgeFlow** [comment]
This is because of https://github.com/OCA/OpenUpgrade/blob/11.0/addons/stock/migrations/11.0.1.1/end-migration.py#L14.

**Comment by pedrobaeza** [comment]
Yes, it's because quants are merged for following the approach of v11 of no quant fragmentation.
