### ISSUE TITLE
[12.0] When migrating Assets are not being migrated

### ISSUE THREAD

**Issue by PlainGreed** [OCA/OpenUpgrade#1964]
Impacted versions:
12.0

Steps to reproduce:
Upgrade DB from 11.0 to 12.0 with assets module installed with some assets and account.moves already created.

Current behavior:
Assets are not being upgraded

Expected behavior:
Assets should be upgraded and included in the 12.0 DB

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Assets are now enterprise, so you have to find an alternative.
