### ISSUE TITLE
[11.0] Converting issue to task could have some issues regarding the priority

### ISSUE THREAD

**Issue by flotho** [OCA/OpenUpgrade#1977]
Hi @OCA/openupgrade-maintainers 

I have some old project_issue with priority = 2.
When trying to upgrade the migration script failed here https://github.com/OCA/OpenUpgrade/blob/11.0/addons/project/models/project.py#L237 after coming form the migrate script

What is your recommendation, add a SQL in the migrate process to update the priority to 1 if > 1, or maybe force the module https://github.com/OCA/project/tree/12.0/project_task_add_very_high to be installed ?

Thanks for your feedback

**Comment by legalsylvain** [comment]
As the module you mention is not a standard one, I'm not in favor of forcing the installation of an extra OCA modules.

What I suggest is to Propose a PR on OpenUpgrade which includes in a pre-migration script:
 
- Backup old column via regular algorithm (like [here](https://github.com/OCA/OpenUpgrade/blob/12.0/addons/account/migrations/12.0.1.1/pre-migration.py#L6))
- Make a SELECT request to know if there are inconsistent values, regarding new selection values
- if yes, add a warning message in log, to say that values will be changed, and propose to user to install ``project_task_add_very_high`` 
- Add a UPDATE request to fix priority

my two cents.

**Comment by pedrobaeza** [comment]
I would include in OpenUpgrade a conversion from 2 to 1 in the issue to task creation, and add a post_init_hook in `project_task_add_very_high` that following link to original issue, restore the value 2.

**Comment by flotho** [comment]
so my interpretation was incorrect. 
Actually the point is I have already some task (and not issues) that already have priority > 1 and this is when copying those task that the problem appears.
What is the correct way to patch this ?

Regards

**Comment by pedrobaeza** [comment]
Put a `CASE` on the SQL sentence that make the INSERT in `project_task` table from `project_issue` to put `1` instead of `2` in `priority` column.

**Comment by pedrobaeza** [comment]
Any news on this?

**Comment by flotho** [comment]
Hi @pedrobaeza , sadly no.
I'll let you know if I can rework on it

**Comment by pedrobaeza** [comment]
Closing as no news.
