### ISSUE TITLE
[12.0] noupdate new records in v12 are not loaded correctly after the migration

### ISSUE THREAD

**Issue by HviorForgeFlow** [OCA/OpenUpgrade#1978]
**Impacted versions:**

12.0 at least

**Steps to reproduce:**

Upgrade db + update all

**Current behavior:**

New groups that enter in the system between tag noupdate="1" are not being created during the migration.

https://github.com/OCA/OCB/blob/c21dd92e46a0391c7960367d0d08a30fa2b8da3e/addons/account/security/account_security.xml#L204 is not on v12 after the migration

**Expected behavior:**

They should. Is there any way to do it without editing manually the xml files? Am I doing anything wrong?

**Comment by pedrobaeza** [comment]
noupdate records that have changed must be loaded manually in https://github.com/OCA/OpenUpgrade/blob/12.0/addons/account/migrations/12.0.1.1/noupdate_changes.xml. That file is obtained automatically with an script in https://github.com/OCA/OpenUpgrade/blob/12.0/scripts/compare_noupdate_xml_records.py, but it's not populated.

@mreficent do you know why?

**Comment by MiquelRForgeFlow** [comment]
@pedrobaeza That script only compare records that exist in the two versions with noupdate=1. The record that pointed @hveficent is new in v12, so obviously won't appear in the noupdate_changes.xml file. If this record has to appear in the xml file, then the script must be updated. So, the question is, that record has to appear in the xml or not?

**Comment by pedrobaeza** [comment]
This is an edge case, but I would say that it should appear when XML-ID module is different from the current one as a way to mitigate these problems.

**Comment by MiquelRForgeFlow** [comment]
Ok, then I should update the script.

**Comment by MiquelRForgeFlow** [comment]
Fixed in https://github.com/OCA/OpenUpgrade/pull/1980.
