### ISSUE TITLE
[11.0] Converting issue to task Redun

### ISSUE THREAD

**Issue by OthmaneGhandi** [OCA/OpenUpgrade#1985]
Impacted versions: v 11.0 - project.issue & project.task
Current behavior:
When you have issues and tasks => after migration you got projects with **"project name" that include only tasks** + an additional projects are added with **"project name" + (Issues) that include issues `but also the tasks that were listed in the first project (Redundancy)`**

**Comment by pedrobaeza** [comment]
Fixed in bed80f332032f1dce865ddf18397454715c501ca
