### ISSUE TITLE
[11.0][12.0] undesirable xml data update 

### ISSUE THREAD

**Issue by OthmaneGhandi** [OCA/OpenUpgrade#2006]
Steps to reproduce:
It happens that you change the content of the name (or other field) of a record that is coming from data folder that doesn't contains noupdate tag.

When running the script it erases your content and put back the old data

How to overcome this ? is there a way to avoid these changes ?

Thanks

**Comment by pedrobaeza** [comment]
If it's data noupdate="0", then it's changed each time you update the module. It's not something specific of OpenUpgrade, but the intended behavior is to keep the data that way, not to be changed, so you should reconsider why are you changing that data.
