### ISSUE TITLE
module coverage 4.2 -> 5.0

### ISSUE THREAD

**Issue by hbrunn** [OCA/OpenUpgrade#201]
Should this be added to the documentation?

**Comment by pedrobaeza** [comment]
Well, as a branch that exists, I think so.

**Comment by StefanRijnhart** [comment]
Wait a little bit. As our 4.2 migration lead is still pending, I have not ported the full architecture yet. What has been ported is the analysis section, and some minor patches. I will propose subsequent PRs over the next couple of days. What has not been ported is the migration bit: rearranging transactions per module, the OpenUpgrade lib etc. Until we have that, there is no use for module coverage IMHO.

**Comment by hbrunn** [comment]
clear, thanks
