### ISSUE TITLE
migration.py is removed for branch 10.0

### ISSUE THREAD

**Issue by bizslink-calon** [OCA/OpenUpgrade#2023]
We are preparing upgrade 9 to 10, but 'migration.py' is removed in branch 10.0.
How to run the script?

**Comment by pedrobaeza** [comment]
Yes, there's no support for that script. Use manual migration steps: https://doc.therp.nl/openupgrade/migration_details.html

**Comment by bizslink-calon** [comment]
Bad, this is temporary or will be for the next branches?

**Comment by bizslink-calon** [comment]
> Yes, there's no support for that script. Use manual migration steps: https://doc.therp.nl/openupgrade/migration_details.html

Bad, this is temporary or will be for the next branches?

**Comment by pedrobaeza** [comment]
The script is not going to be restored. You must know how to do a manual upgrade without a script that depends on a lot of variables (installed libraries and binaries, distribution, etc).

**Comment by bizslink-calon** [comment]
> The script is not going to be restored. You must know how to do a manual upgrade without a script that depends on a lot of variables (installed libraries and binaries, distribution, etc).

Is it possible to upgrade with the old migration.py since we did many customized migration based on it.

**Comment by pedrobaeza** [comment]
Adapt it by yourself if you want it, but no official support is going to be provided.
