### ISSUE TITLE
[12][WEBSITE] Homepage not migrated + not able to edit it

### ISSUE THREAD

**Issue by OthmaneGhandi** [OCA/OpenUpgrade#2041]
while migration my database to V12 the homepage comes blank and also I'm not able to add some elements on it (it remains blank)

<img width="1106" alt="Blank Homepage" src="https://user-images.githubusercontent.com/6293989/65761861-ff00f780-e11f-11e9-9b6c-44f2f11de22a.png">

**Comment by pedrobaeza** [comment]
If you don't give more details... All my migrated websites have been editable, migrated, and so on for now.

**Comment by OthmaneGhandi** [comment]
> If you don't give more details... All my migrated websites have been editable, migrated, and so on for now.

I just submitted the issue accidentally before giving details :)

**Comment by pedrobaeza** [comment]
OK, but still not enough data. As said, there has been something that triggers this condition, as on regular websites don't happen.

**Comment by OthmaneGhandi** [comment]
My database was migrated from V10 -> v11 then v11 -> V12. My homepage was migrated to V11 but not to V12.

Our database uses the standard snippets of Odoo. I don't know what is the thing that can trigger this condition🙂

**Comment by pedrobaeza** [comment]
I migrated last week one from v9 and without problems...

We are in the same problem: without steps to reproduce the problem, we can't do too much.

**Comment by OthmaneGhandi** [comment]
Okey let me try to see if I can do this

**Comment by pedrobaeza** [comment]
Closing as no more answers.
