### ISSUE TITLE
[12.0]weight_uom_id doesn't exists

### ISSUE THREAD

**Issue by flotho** [OCA/OpenUpgrade#2045]
Hi,

i have a migration script failing at this line
https://github.com/OCA/OpenUpgrade/blob/b6d503c424496649d4ed0d98d701a10d90665703/addons/delivery/migrations/12.0.1.0/pre-migration.py#L21
with the message indicating that the field doesn't exists.
It's really strange because it's coming from a freshly v11.0 migrated and the field is present in the v11.0 database
What could be the origin of this ?

**Comment by pedrobaeza** [comment]
Well, the field is clearly defined in 11.0:

https://github.com/odoo/odoo/blob/9de188df0c4cb081d8aaeef7a1d9167fce25b358/addons/delivery/models/stock_picking.py#L93

so probably you didn't fully upgrade your DB.

Closing meanwhile we don't have more traces of what's going on.
