### ISSUE TITLE
[8.0 -> 9.0] ir_ui_view structure

### ISSUE THREAD

**Issue by zeroincombenze** [OCA/OpenUpgrade#2049]
I am uncomfortable man trying to upgrade a DB from 8.0 to 9.0. 
After hours of investigation, it seems ir_ui_view is not converted. The field "arch" should become "arch_db" (see openupgrade/openerp/addons/base/migrations/9.0.1.3/pre-migration.py).
For some reason OU creates new column "arch_db" but does not copy the content of "arch" into "arch_db"
In final DB I see both "arch" (with data) and "arch_db" (empty) fields.

Does someone have an idea and address me in right direction?
Thanks

Impacted versions:
Migration from 8.0 to 9.0

Steps to reproduce:
Replicable only my DB

Current behavior:
Field ir_ui_view.arch_db empty

Expected behavior:
Field ir_ui_view.arch_db copyed from ir_ui_view.arch

**Comment by cubells** [comment]
What are you doing exactly?
You must follow this instructions: https://doc.therp.nl/openupgrade/migration_details.html

**Comment by pedrobaeza** [comment]
In this line the copy to `arch_db` is performed:

https://github.com/OCA/OpenUpgrade/blob/b368026c30b7a23bafe197f5c2c6e382a80c4aaf/openerp/addons/base/migrations/9.0.1.3/pre-migration.py#L15

so for some reason, this is not being executed, but it's not a problem of OpenUpgrade itself, so closing.
