### ISSUE TITLE
Special Characters Migrating Odoo8.0 to Odoo9.0 using OpenUpgrade

### ISSUE THREAD

**Issue by swidmaier** [OCA/OpenUpgrade#2054]
Impacted versions: OpenUpgrade branch 9.0

Steps to reproduce: Submit special characters to project_task -> description i.e. German Umlaute, ü, ö, ä, or "degrees" °

Current behavior: OpenUpgrade: project: error in migration script project/migrations/9.0.1.1/post-migration.py: UnicodeDecodeError('ascii', "UPDATE project_task SET description = '<p>SomeDescriptionContainingSpecialCharacters</p>' WHERE id = XYZ", 99, 100, 'ordinal not in range(128)')

Suggested fix in openupgrade.py line 1123:
Change   full_query = cr._obj.query.decode() to full_query = cr._obj.query.decode('utf8', 'replace')

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
I have migrated several databases with this kind of characters and having no problem. Can you put the exact text you have problem? And also the full traceback?

**Comment by pedrobaeza** [comment]
No answer, so closing.
