### ISSUE TITLE
[11.0][12.0] account_accountant remains installed

### ISSUE THREAD

**Issue by sergiocorato** [OCA/OpenUpgrade#2061]
Impacted versions: 11.0 12.0

Steps to reproduce: do a migration from 10.0

Current behavior: account_accountant remains installed

Expected behavior: account_accountant is uninstalled

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Module shouldn't be auto-uninstalled for several reasons:

- There's no replacement module for that one, so no renaming nor merge can't be done.
- There's an enterprise module with the same name.
- People may use OpenUpgrade for upgrading their enterprise databases, and in that case, we shouldn't assume the path they are going to take.

If you don't want it, just uninstall it after completing the upgrade.

**Comment by sergiocorato** [comment]
thanks
