### ISSUE TITLE
[12.0] hr_expense attachments not visible in chatter

### ISSUE THREAD

**Issue by Vartkat** [OCA/OpenUpgrade#2071]
Impacted versions:
V12

Steps to reproduce:
Do a migration with a database containing attachments

Current behavior:
In hr_expense, the attachment is there in database (as the document button shows it) but not visible in the message board.
On a new expense, done on V12, the attachment is there both up and down.

Expected behavior:

Attachments coming from V11 should be visible in the message board.

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/1696899/67618647-51523880-f7f2-11e9-9758-5942b6a730be.png)

**Comment by trapchik** [comment]
Just migrated 11 to 12 where had a lot of attachments as notes in vendor bills

<img width="271" alt="Screen Shot 2020-01-18 at 09 32 06" src="https://user-images.githubusercontent.com/22664992/72661716-95aa3a80-39d5-11ea-8a0d-131ec7d495d7.png">

Links like http://localhost:8069/web/content/10675?download=true

But downloaded PDF - Zero bytes?

**Comment by pedrobaeza** [comment]
Closing as stalled.
