### ISSUE TITLE
accounting.report v11 to v12

### ISSUE THREAD

**Issue by AndresLincango** [OCA/OpenUpgrade#2072]
Impacted versions: v12

Steps to reproduce: Migrate

Current behavior: TypeError: Model 'accounting.report' does not exist in registry.

Expected behavior: to find the model. 

I don't know if I have to change the config for the migrate.conf pointing to the folder with the enterprise for v12 since accounting.report isn't in the odoo/lib anymore. 

Do I need to use the v12 enterprise package while running openupgrade?

Video/Screenshot link (optional):

![Screen Shot 2019-10-26 at 23 05 04](https://user-images.githubusercontent.com/41710656/67629532-188f7f00-f845-11e9-85b5-f3f846bfbd0a.png)

**Comment by pedrobaeza** [comment]
Do you have enterprise modules installed in your DB? If so, you need to provide migration scripts for them.

**Comment by AndresLincango** [comment]
Yes, there are enterprise modules installed. Is there any documentation about how to create the scripts?

**Comment by AndresLincango** [comment]
Looks simple. Tyvm for your help. I'll try it on that module
