### ISSUE TITLE
[12.0] Migration of sale module does not work if website_quote is not installed

### ISSUE THREAD

**Issue by cvinh** [OCA/OpenUpgrade#2073]
Impacted versions: 12.0

Steps to reproduce:
Migrate a v11 database with sale module installed but website_quote not installed
Current behavior:
Error require_payment does not exist in sale_order
Expected behavior:
The require_payment column that is introduced by website_quote in sale_order should not be renamed if website_quote is not installed
Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
What is the log error?

**Comment by cvinh** [comment]
Sql error : require_payment column does not exist in sale_order table
Sorry I did not note it exactly
Workaround has been to install website_quote on v11 database (unless it was not wanted)

**Comment by pedrobaeza** [comment]
I don't have that module installed in databases, and I don't receive the error, so unless you put the exact error log for seeing where and what exactly, seems something on your end. Closing meanwhile.

**Comment by cvinh** [comment]
Ok, we were in a special case : website_quote has been uninstalled in v10 and then db was migrated in v11... so the sale_quote_line column did exist but require_payment column did not

**Comment by pedrobaeza** [comment]
But uninstalling the module in regular operation mode must remove the SQL table as well...
