### ISSUE TITLE
[8.0 -> 9.0] fail to migrate sale / purchase module (invoice line UoS undefined)

### ISSUE THREAD

**Issue by legalsylvain** [OCA/OpenUpgrade#2076]
Hi all, 

Similar bug as #2075. 

The 8.0 setting is the following : 

- ``purchase.order.line`` ``product_id`` : False
- ``purchase.order.line`` ``uom_id`` : **Unit**
- ``account.invoice.line`` ``product_id`` : False
- ``account.invoice.line`` ``uom_id`` : **False**

This case is valid in 8.0, because invoice UoS is optional.

Running the migration, the following error is raised.

    Conversion from Product UoM **False** to Default UoM **Unit** is not possible as they both belong to different Category!.
 
### Current Fix for purchase migration
if invoice line uos_id is NULL, set the purchase order line uom

    UPDATE account_invoice_line ail
    SET uos_id = pol.product_uom
    FROM purchase_order_line_invoice_rel rel,
        purchase_order_line pol
    WHERE pol.id = rel.order_line_id
    AND ail.id = rel.invoice_id
    AND ail.uos_id is null; 

### Current fix for sale migration
(theoritical, I don't have the case)
if invoice line uos_id is NULL, set the sale order line uom

    UPDATE account_invoice_line ail
    SET uos_id = sol.product_uom
    FROM purchase_order_line_invoice_rel rel,
        sale_order_line sol
    WHERE sol.id = rel.order_line_id
    AND ail.id = rel.invoice_id
    AND ail.uos_id is null;

### Proposal

Add this two requests in pre-migration script of sale and purchase (well with uom_id and not uos_id because at this step, uos_id has been renamed)

Regarding https://github.com/OCA/OpenUpgrade/issues/2075#issuecomment-548084628, we could imagine also creating an new UoM with no name (only a space, because name is required), and disabled, and affect this UoM to the invoice line UoS, but I is a little dirty, and not sure that it is required in this case.

**Comment by pedrobaeza** [comment]
Please see #1599

**Comment by legalsylvain** [comment]
thanks for taking a look on that issue. If I understand correctly, #1599 is about missing ``product_id`` on ``purchase.order.line``.
The current issue is about missing ``uos_id`` on ``account.invoice.line``.

But I'll take a look ! because in my multicompany context, the current code that create product is not ok. (as you said on #1599)

**Comment by pedrobaeza** [comment]
I think that they are related, as having the product with proper UoM in sale/purchase, then you can propagate that UoM to `account.invoice.line` when missing, don't you think?

**Comment by pedrobaeza** [comment]
Closing as stalled.
