### ISSUE TITLE
[11.0 -> 12.0] Migration failed in website_sale view

### ISSUE THREAD

**Issue by Danoolo** [OCA/OpenUpgrade#2088]
Hi guys!....when i migrate a backup i found this error in views

2019-11-20 12:54:22,577 8353 INFO AP12.0b odoo.addons.base.models.ir_ui_view: El elemento `<xpath expr="//div[hasclass('o_brand_promotion')]">`  no puede ser localizado en la vista padre

Contexto del error:
Vista `website_sale.brand_promotion`
[view_id: 3215, xml_id: website_sale.brand_promotion, model: n/a, parent_id: 2956] 

but this module website_sale is from odoo modules and i supposed that were already migrated...any ideas?...thanks in advance

**Comment by geozoone** [comment]
what is the solucion?? im install other module and see this error
