### ISSUE TITLE
Wrong login/password prompt

### ISSUE THREAD

**Issue by WDMdanila** [OCA/OpenUpgrade#2117]
Impacted versions: 12

Steps to reproduce: upgrade database from v11 to v12

Current behavior: when user tries to login he/she receives prompt about wrong login/password

Expected behavior: user is able to log in normally

P.S. Noticed that sometimes database migrates and this problem is not present and sometimes it is. Database was firstly migrated from 10 to 11 via OpenUpgrade

**Comment by pedrobaeza** [comment]
This has nothing to do with the migration itself (or not at least with latest code), so you have to dig in the problem, and if you find something related, then come back to this issue tracker.

**Comment by steync027** [comment]
Probably this is the reason: https://github.com/OCA/OpenUpgrade/issues/2183
