### ISSUE TITLE
Analysis does not detect renamed many2many tables

### ISSUE THREAD

**Issue by StefanRijnhart** [OCA/OpenUpgrade#213]
Example: property_ids on mrp.bom changed its table from mrp_bom_property_rel to mrp_bom_mrp_property_rel in 8.0

**Comment by pedrobaeza** [comment]
Is this solved?

**Comment by StefanRijnhart** [comment]
no

**Comment by pedrobaeza** [comment]
@mreficent did you handle this already with your improvements?

**Comment by MiquelRForgeFlow** [comment]
I would say no. Should I try to do it?

**Comment by pedrobaeza** [comment]
And do you see it feasible?

**Comment by MiquelRForgeFlow** [comment]
Feasible and done :)
