### ISSUE TITLE
is custom addons will updated also?

### ISSUE THREAD

**Issue by agharaafat** [OCA/OpenUpgrade#2141]
I need to upgrade from v11 to v12 ce 
but i'm using a lot of addons 
so what i need to do?
remove all addons files and upload the files compatible with v12 and if yes, do this after or before the upgrade?

**Comment by pedrobaeza** [comment]
You need to include in the addons path that custom modules and if they have migration scripts, they will be executed as well. If no migration is needed, there's no need of put that custom addons in intermediate versions that you are migrating.
