### ISSUE TITLE
[12.0] Assets not migrated

### ISSUE THREAD

**Issue by linuxnow** [OCA/OpenUpgrade#2153]
Impacted versions: v12

Steps to reproduce: run migration script

Current behavior: 
account_asset_asset, account_asset_category, account_asset_depreciation_line are migrated
account_asset, account_asset_group, account_asset_profile
Then all the assets are not available.

Expected behavior:
Migrated assets

This error keeps on appearing in the atached logs:
odoo.addons.base.models.ir_ui_view: El camp `asset_category_id` no existeix
which means that column does not exist in catalan.
I've added the financial-tools repo and soe of the required modules.

[output.txt](https://github.com/OCA/OpenUpgrade/files/4021828/output.txt)

Thank you for your help
Pau

**Comment by cubells** [comment]
Before migration to 12.0 you must set as uninstalled module `account_asset` and must set as installed module `account_asset_management` because now, in community edition, the module to manage assets is the last one.

**Comment by cubells** [comment]
https://github.com/OCA/account-financial-tools

**Comment by pedrobaeza** [comment]
That's not really the procedure. Just put in addons path the new account_asset_management before migrating and let OpenUpgrade to do the rest.

**Comment by linuxnow** [comment]
As you can see in the log file I've attached, I have added
account_asset_management
but the table account_asset is not populated.,but the original tables are
still there.

Is there anything else I could try, I'll be glad to test it, otherwise I'll
just recreate the assets and be done.

Best
Pau

**Comment by pedrobaeza** [comment]
`account_asset_management` mustn't be installed previously. You'll get this information if you read a bit:

https://github.com/OCA/account-financial-tools/blob/98f195c7f6f7127f103017745c2f80d985d257a2/account_asset_management/migrations/12.0.1.0.0/pre-migration.py#L82
