### ISSUE TITLE
'module' not callable

### ISSUE THREAD

**Issue by steync027** [OCA/OpenUpgrade#2154]
I am not sure why, but sometimes I get an error on this line:

https://github.com/OCA/OpenUpgrade/blob/12.0/odoo/modules/graph.py#L76

'module' not callable

I then have to replace

`tools.safe_eval()`

with

`tools.safe_eval.safe_eval()`

So to successfully run the migration I had to change the code to:

    try:
        forced_deps = tools.safe_eval(forced_deps)
    except:
        forced_deps = tools.safe_eval.safe_eval(forced_deps)

**Comment by steync027** [comment]
Btw, this was the only change I needed to make as everything else worked perfectly. I successfully upgraded a database from 9.0 to 12.0 and this change was only needed on 11.0 and 12.0 branches.

**Comment by pedrobaeza** [comment]
That's because you have in a weird way your addons path, but nothing to do with OpenUpgrade. In fact, you'll have the same problem in standard Odoo with that deployment configuration.

**Comment by letzdoo-js** [comment]
Hi,
I face the same issue using DOOBA to upgrade. Any precision of what an "have in weird way your addons path" means ?

DOOBA just links all addons in /opt/odoo/auto/addons is it not a fair way to work ?

Jerome

**Comment by pedrobaeza** [comment]
We are using Doodba (as creators of it), and we don't face that problem, so I can't say more except that it works...

**Comment by letzdoo-js** [comment]
First... good work.... I'm using it to upgrade my project and I start to get very good results.

This bug is the only encountered so far and I cannot figure out why despite some research. 

I will investigate more and let you know.

**Comment by pedrobaeza** [comment]
Do you have by a chance an old version module in your addons path (even with installable=False) that has an old import format of this safe_eval? It's the only thing I can think about.

**Comment by letzdoo-js** [comment]
Hello,

Thanks for the tip, as starting from scratch gets me to the same issue.

I did some research using grep -nre 'safe_eval' * | grep from on my odoo/auto/addons directorty.

I found that one looking weird

project/migrations/11.0.1.1/post-migration.py:7:from odoo.tools import safe_eval

Could it be my problem ?

Jerome

**Comment by letzdoo-js** [comment]
Nope, ok found it in my modules !! 

Thanks for the tip.
