### ISSUE TITLE
[11.0 -> 12.0] Fail with delivery and mass_mailing assets

### ISSUE THREAD

**Issue by Danoolo** [OCA/OpenUpgrade#2162]
After migrate my 11.0 db, the chrome debugger display this

![Captura de pantalla de 2020-01-16 17-12-48](https://user-images.githubusercontent.com/30710193/72559534-c37f6a00-3883-11ea-9650-d5a596b428a6.png)

Any help with this? Thanks so much

**Comment by pedrobaeza** [comment]
There should be any view that has not been removed. You make sure you update all again on regular Odoo. Any way, you can remove the view manually, and this is something out of scope of OpenUpgrade.

**Comment by Danoolo** [comment]
Indeed Pedro, the error in red is about the module sale_layout_category_hide_detail in sale_reporting, because there is a reference to an js asset in odoo delivery module which is not anymore in there. It needs to be rewritten this reference.

![Captura de pantalla de 2020-01-17 15-13-32](https://user-images.githubusercontent.com/30710193/72635620-fb49e880-393b-11ea-8027-7716ad835c52.png)

The last reference is the problem here for me...but i should do an issue in that oca module maybe...

**Comment by pedrobaeza** [comment]
Remove manually the view that is adding that. I can't help you more as I don't face that problem.
