### ISSUE TITLE
[11.0 -> 12.0] product.product and intrastat_id

### ISSUE THREAD

**Issue by trapchik** [OCA/OpenUpgrade#2164]
Migrated v11 DB to v12 DB 

Have all orders, invoices, purchases, products and all other data

The only problem is that we can't see product details as something wrong with intrastat data?

When we try to open any product page
e.g. http://localhost:8069/web?debug=assets#id=2684&model=product.product

We got "TypeError: undefined is not an object (evaluating 'field.type')" popup 
[ODOO_full_error_popup.txt](https://github.com/OCA/OpenUpgrade/files/4080715/ODOO_full_error_popup.txt)

And the following in ODOO logs

`2020-01-18 13:07:50,942 25544 INFO dbname odoo.addons.base.models.ir_ui_view: Field `intrastat_id` does not exist

Error context:
View `n/a`
[view_id: n/a, xml_id: n/a, model: n/a, parent_id: n/a] `

Any recommendation how to fix the issue, would be much appreciated.

Thank you!

**Comment by pedrobaeza** [comment]
Remove or migrate the module that adds `instrastat_id` field.

Closing as this is not something of OpenUpgrade itself.
