### ISSUE TITLE
[11.0 -> 12.0] ZERO size attachments after migration

### ISSUE THREAD

**Issue by trapchik** [OCA/OpenUpgrade#2169]
Just migrated 11 to 12 where had a lot of attachments as notes in vendor bills

<img width="271" alt="Screen Shot 2020-01-18 at 09 32 06" src="https://user-images.githubusercontent.com/22664992/72907876-9243e580-3d2c-11ea-8343-9f68f6adff98.png">

But downloaded PDF - Zero bytes?

Original backup made in odoo 11 was over 500MB, while current is 30MB ?

**Comment by pedrobaeza** [comment]
You haven't copied filestore, but this is not something of OpenUpgrade
