### ISSUE TITLE
[12.0] problem migrating point_of_sale

### ISSUE THREAD

**Issue by GSLabIt** [OCA/OpenUpgrade#2171]
Impacted versions: 12.0

Steps to reproduce:
1. on version 11.0 install point_of_sale
2. delete products tips and consumable added by default by point of sale installation
3. run migration to 12

Current behavior:
error is raised because of:
https://github.com/OCA/OpenUpgrade/blob/7dbc5d8d2cd7bcd523e4684bf8b88812b890cb11/addons/point_of_sale/migrations/12.0.1.0.1/noupdate_changes.xml#L3-L11

any hint on how to prevent/fix it? Would be possible to safely remove the 2 lines in xml?

Expected behavior:
No error should be raised

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Update again the module in v11 for re-adding the products. If you don't want them, deactivate them, but not delete them.

You must always update the DB before migrating with latest code in previous version.

**Comment by GSLabIt** [comment]
Ok, i'll double-check it but i tried and same error has been raised. Probably need to remove xml id from data, will check and let u know. Thx for the hint

**Comment by GSLabIt** [comment]
@pedrobaeza product xmlid has not been deleted, so this prevented product re-adding on upgrade. Now all works, thx again for the hint.

**Comment by pedrobaeza** [comment]
Do they have `forcecreate=False`?

**Comment by GSLabIt** [comment]
Nope, i can't find `forcecreate`, i think user deleted product from UI interface, but xmlid has not been deleted.

**Comment by pedrobaeza** [comment]
Yeah, I'm seeing that it's only noupdate="1":

https://github.com/OCA/OpenUpgrade/blob/55dad8b188e2dd1354918940686775b42fc48876/addons/point_of_sale/data/point_of_sale_data.xml#L47

so that's expected. As said, you must update always the DB in previous version with latest code. If not, other bad things will happen.

**Comment by GSLabIt** [comment]
I've updated using Auto update module, but now i'm getting:

```
ValidationError(_("A user cannot have both Tax B2B and Tax B2C.\n"
odoo.tools.convert.ParseError: "A user cannot have both Tax B2B and Tax B2C.
You should go in General Settings, and choose to display Product Prices
either in 'Tax-Included' or in 'Tax-Excluded' mode
(or switch twice the mode if you are already in the desired one).
None" while parsing /Users/giovanni/dev/odoo-dev/openupgrade/OpenUpgrade/addons/account/security/account_security.xml:5, near
<record id="group_account_invoice" model="res.groups">
        <field name="name">Billing</field>
        <field name="category_id" ref="base.module_category_accounting_and_finance"/>
        <field name="implied_ids" eval="[(4, ref('base.group_user'))]"/>
    </record>
```
any hint?

**Comment by pedrobaeza** [comment]
You have a user with such situation of belonging to both groups.

**Comment by pedrobaeza** [comment]
About module_auto_update, it doesn't serve, as the module may not change its code (it's you that you have removed the product!). You need to force -u all in this case.
