### ISSUE TITLE
Migration 7-8 almost ok

### ISSUE THREAD

**Issue by mayjo79** [OCA/OpenUpgrade#220]
I test migration OE7->Odoo 8 with a simple case .
All is correct but i have only one error during migrate.py :
2015-01-22 14:21:09,363 3842 ERROR sale-demo-1_migrated OpenUpgrade: Invalid value 'tree_account_reconciliation' in the table 'ir_ui_view' for the field 'type'. (1 rows).

What means this error ?

**Comment by StefanRijnhart** [comment]
Well, in a hackish way Odoo allows you to define your own view types. This is what happens in addons/account/account_view.xml for tree_account_reconciliation as this is the top level view tag which is interpreted as the view type in 7.0 (note that 8.0 has the deprecated 'type' tag in the view definition, explicitely setting the type to 'tree' regardless of the top level view tag).

Of course, the type field on the ir.ui.view model is a selection field with a discrete set of values. It checks whether all the occurring values exist in the field's selection list which is clearly not the case here.

So it should be nothing to be worried about. But does this error stop the migration process?

**Comment by mayjo79** [comment]
No this error didn't stop the migration process.
Except this error, everything is ok.
