### ISSUE TITLE
ImportError on OpenUpgrade 7.0

### ISSUE THREAD

**Issue by sebastienhasa** [OCA/OpenUpgrade#2202]
When I try to run OpenUpgrade 7.0, I got an import error:
```
[…]
File "/OpenUpgrade-7.0/openerp/sql_db.py", line 43, in <module>
    from psycopg2.psycopg1 import cursor as psycopg1cursor
ImportError: No module named psycopg1
```

After installing openupgradelib, I simply do a `pip install .` on a
clone of the OpenUpgrade repo to install it.

Impacted versions:
Branch 7.0, commit `dad564a`

Steps to reproduce:
- Create a Dockerfile
- Put this in the Dockerfile:
```
from python:2.7

workdir /

run pip install git+git://github.com/OCA/openupgradelib.git

run wget https://github.com/OCA/OpenUpgrade/archive/7.0.zip

run unzip 7.0.zip

workdir /OpenUpgrade-7.0

run pip install .
```
- Build your image: `docker build . --tag openupgrade:7.0`
- Run it: `docker run -it --rm openupgrade:7.0 bash`
- On the called bash, just try to start openerp-server: `python openerp-server`

Current behavior:

Error message:
```
[…]
File "/OpenUpgrade-7.0/openerp/sql_db.py", line 43, in <module>
    from psycopg2.psycopg1 import cursor as psycopg1cursor
ImportError: No module named psycopg1
```

Expected behavior:
OpenUpgrade correctly start

Post-scriptum: I know, my docker file is incomplete on the entrypoint
and command. I try to first run OpenUpgrade manually before automate
it.

**Comment by pedrobaeza** [comment]
Seems a problem of the installed version of psycopg

**Comment by pedrobaeza** [comment]
Closing as no answer and it should be what was suggested.
