### ISSUE TITLE
[9 -> 10] Custom addons not found after upgrade

### ISSUE THREAD

**Issue by ikdekker** [OCA/OpenUpgrade#2204]
I am upgrading a database from V9 to V10. However, after the upgrade, I am unable to locate addons through the Apps interface. Is there a way to debug this, since I am not really getting any errors.

I am using the 'update apps list' feature from the debugger mode and manually importing addons through the import interface does work. The addons I refer to are listed in a `/mnt/extra-addons/` dir (docker) and are found on a clean install of Odoo when installed the same way.

Additionally, is there need to remove the references to stale (custom) modules, which have been removed, but are still in my database?  After the update I have 76 modules left installed, yet there are over 300 modules listed in the app screen (most of them seem to be native).  
An example:

`WARNING odoo_db odoo.modules.module: module sale_forecast: module not found`

Note: I am upgrading from V9 -> V12 (which mostly seems to work, aside from some web-view files js and less files not being found, causing errors) and I hope to retain as much of my data as possible. A few things have not been clear in the migration process, but I am still learning. I wonder if some warnings, like db constraints that can not be added are a problem for the migration. Is there a FAQ or a plan for a FAQ / Wiki? (maybe an extension of [https://doc.therp.nl/openupgrade/](https://doc.therp.nl/openupgrade/))

**Comment by pedrobaeza** [comment]
Sorry, but this is not an OpenUpgrade issue, as OpenUpgrade is an Odoo server with additional features, so any problem you have finding addons is a deployment problem like you will have with regular Odoo. For modules that you don't want, just uninstall them.
