### ISSUE TITLE
OpenUpgrade 6.1 -> 7.0, SQL error: relation "ir_model_constraint" does not exist

### ISSUE THREAD

**Issue by sebastienhasa** [OCA/OpenUpgrade#2209]
Impacted versions:
OpenUpgrade, branch 7.0

Steps to reproduce:
- Have a system where all the dependencies for OpenERP 7.0 are
  installed as well as git and python pip
- Install `openupgradelib`
- Make a clone of the OpenUpgrade repo, branch 7.0
- Restore the OpenERP 6.1 database dump and name it `migration_db`
- Run the command:
  `openupgrade/openerp-server --update=all --config=/etc/openerp/openerp-server.conf --database=migration_db --stop-after-init --no-xmlrpc --no-netrpc`

Current behavior:
When I try to upgrade a database from an OpenERP 6.1 for an OpenERP
7.0, with OpenUpgrade 7.0, I got an error while OpenUpgrade performing
a SQL request.

This error is:
```
relation "ir_model_constraint" does not exist at character 28
```

The query is:
``` sql
SELECT 1 FROM ir_model_constraint, ir_module_module 
WHERE ir_model_constraint.module=ir_module_module.id
AND ir_model_constraint.name='ir_model_obj_name_uniq' 
AND ir_module_module.name='base';
```

The complete traceback is:
```python
Traceback (most recent call last):
  File "/openupgrade/openerp/cli/server.py", line 97, in preload_registry
    db, registry = openerp.pooler.get_db_and_pool(dbname,update_module=update_module)
  File "/openupgrade/openerp/pooler.py", line 33, in get_db_and_pool
    registry = RegistryManager.get(db_name, force_demo, status, update_module)
  File "/openupgrade/openerp/modules/registry.py", line 203, in get
    update_module)
  File "/openupgrade/openerp/modules/registry.py", line 233, in new
    openerp.modules.load_modules(registry.db, force_demo, status, update_module)
  File "/openupgrade/openerp/modules/loading.py", line 329, in load_modules
    loaded_modules, processed_modules = load_module_graph(cr, graph, status, perform_checks=update_module, report=report, registry=registry)
  File "/openupgrade/openerp/modules/loading.py", line 183, in load_module_graph
    init_module_models(cr, package.name, models)
  File "/openupgrade/openerp/modules/module.py", line 374, in init_module_models
    result = obj._auto_init(cr, {'module': module_name})
  File "/openupgrade/openerp/osv/orm.py", line 3339, in _auto_init
    self._add_sql_constraints(cr)
  File "/openupgrade/openerp/osv/orm.py", line 3482, in _add_sql_constraints
    self._save_constraint(cr, conname, 'u')
  File "/openupgrade/openerp/osv/orm.py", line 2973, in _save_constraint
    """, (constraint_name, self._module))
  File "/openupgrade/openerp/sql_db.py", line 161, in wrapper
    return f(self, *args, **kwargs)
  File "/openupgrade/openerp/sql_db.py", line 226, in execute
    res = self._obj.execute(query, params)
ProgrammingError: relation "ir_model_constraint" does not exist
LINE 2:             SELECT 1 FROM ir_model_constraint, ir_module_mod...
```

Expected behavior:

OpenUpgrade upgrade the data without error

**Comment by pedrobaeza** [comment]
The DB doesn't seems to be correctly restored or something, but this is out of the scope of this issue tracker and there's no support anymore for that migration script.

**Comment by sebastienhasa** [comment]
> The DB doesn't seems to be correctly restored or something

The table `ir_model_constraint` didn't exist in the original 6.1 database.

**Comment by sebastienhasa** [comment]
After some checks, I see that `ir_model_constraint` didn't exist in OpenERP 6.1 but it does in 7.0.

If OpenUpgrade 7.0 is for 6.1 to 7.0 upgrade, why does it need `ir_model_constraint` on the 6.1 database?

**Comment by pedrobaeza** [comment]
That's not true. OpenUpgrade 7.0 is 7.0. `ir_model_constraint` is set immediately after base module update. I have migrated recently a 6.1 DB without problems, so there should be something bad in your end, or the steps to reproduce the error are not clear.

**Comment by sebastienhasa** [comment]
This is the first log lines of OpenUpgrade 7.0:
```
INFO ? openerp: OpenERP version 7.0
INFO ? openerp: addons paths: /mnt/extra-addons,/usr/lib/python2.7/dist-packages/openerp/addons
INFO ? openerp: database hostname: db
INFO ? openerp: database port: 5432
INFO ? openerp: database user: openerp
INFO migration_db openerp.modules.loading: loading 1 modules...
INFO migration_db openerp.modules.module: module base: creating or updating database tables
ERROR migration_db openerp.sql_db: Programming error: relation "ir_model_constraint" does not exist
LINE 2:             SELECT 1 FROM ir_model_constraint, ir_module_mod... 

, in query 
            SELECT 1 FROM ir_model_constraint, ir_module_module 
            WHERE ir_model_constraint.module=ir_module_module.id
                AND ir_model_constraint.name=%s
                AND ir_module_module.name=%s

Traceback (most recent call last):
…
```

And this is the log lines of Postgres a this moment:

```
ERROR:  relation "ir_model_constraint" does not exist at character 28
STATEMENT:
                    SELECT 1 FROM ir_model_constraint, ir_module_module
                    WHERE ir_model_constraint.module=ir_module_module.id
                        AND ir_model_constraint.name='ir_model_obj_name_uniq'
                        AND ir_module_module.name='base'
```

**Comment by pedrobaeza** [comment]
No pre-migration is being executed, so it's normal that this happens. Check why.

**Comment by sebastienhasa** [comment]
I do not understand.

On your previous message you say that `ir_model_constraint` is set after base module is updated.
And now you saying the opposite.

My initial problem is:
- OpenUpgrade 7.0 do not upgrade a database from an OpenERP 6.1 to a database for an OpenERP 7.0
- After starting OpenUpgrade, I got an error: OpenUpgrade execute an SQL request on the table `ir_model_constraint` but this table doesn't exist
- As this table does not exist on OpenERP 6.1 but exist on OpenERP 7.0, why OpenUpgrade 7.0 don't create the missing table?

I mean, as the goal of OpenUpgade is to upgrade a database from one version of OpenERP/Odoo to another, why doesn't he create tables for models which appeared between 2 versions of OpenERP?
Is there something I need to do before launch the upgrade that is not documented?
The database come from an OpenERP 6.1 where I removed all modules not supported by OpenUpgrade 7.0 migration and I followed the documentation. I do the same thing I already do with other migrations that worked.

**Comment by pedrobaeza** [comment]
Well, I mean that it's handled by regular process. I haven't dug enough to say if that relation is set regularly or in pre, but whay I can say is that in your log I didn't see any stuff of the pre-migration being executed, so that should be the problem.

**Comment by sebastienhasa** [comment]
I tried to mnully create the table `ir_model_constraint` before doing the migration, and I resulted with another table missing: `ir_model_constraint`

Effectively, pre-migration part are note done. 

The last time you migratied from 6.1 to 7.0, which commit where your copy on OpenUpgrade?

**Comment by pedrobaeza** [comment]
With latest one, as we migrate one DB from 6.1 to 12 2 weeks ago without problems. Definitively you should check the way you perform the migrations and check addons path.
