### ISSUE TITLE
[12.0] Migration when quality_control is installed fails

### ISSUE THREAD

**Issue by diggy128** [OCA/OpenUpgrade#2211]
Impacted versions: 12

Steps to reproduce:

- Install in v11 quality_control from OCA/Manufacture
- Run migration 11>12

Current behavior:
Migration stops because in base there is quality_control reserved for module quality_control for Odoo Enterprise (to facilitate install from within MRP settings)

Expected behavior:
There should be separation between quality_control in OCA and Odoo Enterprise

Comments:
I guess this should be handled in OCA/Manufacture since I don't think there is a chance to mess with base, I just report it here because since we had quality_control installed before v12, the failure came from the OpenUpgrade side.
I think we should rename quality_control in OCA manufacture in something else to avoid the name collision and include that in the migration script for OCA/quality_control

**Comment by pedrobaeza** [comment]
I have migrated to v12 with that module without problem. Simply don't have both in your addons path. And yes, this has nothing to do with OpenUpgrade itself.

**Comment by diggy128** [comment]
>...Simply don't have both in your addons path. ...

OK, but since the entry for the enterprise module is in base (just an entry in ir_modules table), updating a database that already has quality_control from OCA should conflict.

Will handle it internally, just thought to point out the issue here in case anyone else comes across it. 
Thanks for the response.

**Comment by PieterPaulussen** [comment]
> I have migrated to v12 with that module without problem. Simply don't have both in your addons path. And yes, this has nothing to do with OpenUpgrade itself.

@pedrobaeza that is a bit crude don't you think? The module should be renamed so this repository can be used completely side by side with the enterprise repo.

**Comment by pedrobaeza** [comment]
Crude no. Direct and pragmatic. A renaming can't be done in a stable, or you will break all existing installations, and what more do you expect me to do?
