### ISSUE TITLE
Migration of custom module

### ISSUE THREAD

**Issue by suhaib96-sudo** [OCA/OpenUpgrade#2212]
Impacted versions: version 10 to version 11

Steps to reproduce: 

Current behavior: Stock Valuation report

Expected behavior: Stock Valuation Report

Video/Screenshot link (optional):

[opening_balance_stock_report.zip](https://github.com/OCA/OpenUpgrade/files/4303217/opening_balance_stock_report.zip)

**Comment by pedrobaeza** [comment]
?
