### ISSUE TITLE
Migrate module from v10 to v11

### ISSUE THREAD

**Issue by suhaib96-sudo** [OCA/OpenUpgrade#2213]
I want to migrate this simple report module,  from odoov10 to version 11, As I am a fresher so I am not that much familiar with the module migration, this module is a custom report of stock valuation which is in version 10, I want to use this in version 11, 

I have attached the module in this zip file, kindly help me solve this
[opening_balance_stock_report.zip](https://github.com/OCA/OpenUpgrade/files/4303234/opening_balance_stock_report.zip)

**Comment by pedrobaeza** [comment]
Sorry, but this is not the scope of this project.
