### ISSUE TITLE
migration for openerp v5 to openerp v6

### ISSUE THREAD

**Issue by PaulGiancarlo** [OCA/OpenUpgrade#224]
hi folks, i see the great job you doing here, well i try to migrate openerp5 to openerp6 so i make my own research and i found OpenUpgrade.

So the thing is: i have the openerpv5 can be run by root, and i download with bzr openerp6 to upgrade
and when i execute the openerp v6 fail, normal advice for be root
so i create a new one acount named openerp6
so use in: su - openerp6
i follow the path and run the openerp v6 and fail,  tells me that i dont have some imports, like lxml,netsvc,misc so that's it, and i can't fixed, please help

i already configure  python2.6 and python26 vertions

so here i show you the issue:
**( [root@adm2-1 bin]# su - openerp6
[openerp6@adm2-1 ~]$ cd 6.0/bin/
[openerp6@adm2-1 bin]$ python2.6 openerp-server.py 
Traceback (most recent call last):
  File "openerp-server.py", line 58, in <module>
    import netsvc
  File "/home/openerp6/6.0/bin/netsvc.py", line 292, in <module>
    import tools
  File "/home/openerp6/6.0/bin/tools/**init**.py", line 25, in <module>
    from misc import *
  File "/home/openerp6/6.0/bin/tools/misc.py", line 47, in <module>
    from lxml import etree
ImportError: No module named lxml )**

when i try with just python

**( [openerp6@adm2-1 bin]$ python openerp-server.py 
Traceback (most recent call last):
  File "openerp-server.py", line 58, in ?
    import netsvc
  File "/home/openerp6/6.0/bin/netsvc.py", line 487
    self.log('params', replace_request_password(params), depth=(None if logger.isEnabledFor(logging.DEBUG_RPC_ANSWER) else 1))
                                                                      ^
SyntaxError: invalid syntax )**

and when i just run like script:

**( [openerp6@adm2-1 bin]$ ./openerp-server.py 
Traceback (most recent call last):
  File "./openerp-server.py", line 58, in ?
    import netsvc
  File "/home/openerp6/6.0/bin/netsvc.py", line 487
    self.log('params', replace_request_password(params), depth=(None if logger.isEnabledFor(logging.DEBUG_RPC_ANSWER) else 1))
                                                                      ^
SyntaxError: invalid syntax )**

so here it's the list to show you the permissions:
[openerp6@adm2-1 6.0]$ ls -la
total 148
drwxr-xr-x 14 openerp6 openerp6  4096 Feb  2 13:02 .
drwx------  3 openerp6 openerp6  4096 Feb  2 13:02 ..
drwxr-xr-x 13 openerp6 openerp6  4096 Feb  3 12:08 bin
drwxr-xr-x  5 openerp6 openerp6  4096 Feb  2 13:02 build
drwxr-xr-x  6 openerp6 openerp6  4096 Feb  2 13:02 .bzr
-rw-r--r--  1 openerp6 openerp6   250 Feb  2 13:02 .bzrignore
drwxr-xr-x  6 openerp6 openerp6  4096 Feb  2 13:02 debian
drwxr-xr-x  4 openerp6 openerp6  4096 Feb  2 13:02 doc
-rw-r--r--  1 openerp6 openerp6 34927 Feb  2 13:02 LICENSE
drwxr-xr-x  2 openerp6 openerp6  4096 Feb  2 13:02 man
-rw-r--r--  1 openerp6 openerp6   478 Feb  2 13:02 MANIFEST.in
-rw-r--r--  1 openerp6 openerp6   107 Feb  2 13:02 openerp-server
drwxr-xr-x  2 openerp6 openerp6  4096 Feb  2 13:02 openerp_server.egg-info
drwxr-xr-x  2 openerp6 openerp6  4096 Feb  2 13:02 pixmaps
drwxr-xr-x  2 openerp6 openerp6  4096 Feb  2 13:02 python25-compat
-rw-r--r--  1 openerp6 openerp6   664 Feb  2 13:02 README
-rw-r--r--  1 openerp6 openerp6   673 Feb  2 13:02 rpminstall_sh.txt
-rw-r--r--  1 openerp6 openerp6   354 Feb  2 13:02 setup.cfg
-rw-r--r--  1 openerp6 openerp6 15316 Feb  2 13:02 setup.nsi
-rwxr-xr-x  1 openerp6 openerp6 10268 Feb  2 13:02 setup.py
drwxr-xr-x  2 openerp6 openerp6  4096 Feb  2 13:02 sql
-rw-r--r--  1 openerp6 openerp6  2138 Feb  2 13:02 ssl-cert.cfg
drwxr-xr-x  2 openerp6 openerp6  4096 Feb  2 13:02 tools
drwxr-xr-x  2 openerp6 openerp6  4096 Feb  2 13:02 win32

so please help i'm lost

**Comment by pedrobaeza** [comment]
Your problem is about environment. You don't have lxml python library, and probably you will find more of this. You should set an environment to run both v5 and v6 version, as OpenUpgrade is an v6 modified one.

**Comment by PaulGiancarlo** [comment]
Thanks for the answer, so i trying now with OpenUpgrade: Please a litle help here, i don't know what's wrong.

[root@adm2-1 MIGRATE]# python2.5 migrate.py --config=/root/.openerp_serverrc --database=aen --run-migrations=6.0
Traceback (most recent call last):
  File "migrate.py", line 6, in <module>
    import psycopg2
ImportError: No module named psycopg2
[root@adm2-1 MIGRATE]# ./migrate.py --config=/root/.openerp_serverrc --database=aen --run-migrations=6.0
  File "./migrate.py", line 237
    if isinstance(addon_config, dict)\
     ^
SyntaxError: invalid syntax
[root@adm2-1 MIGRATE]# python migrate.py --config=/root/.openerp_serverrc --database=aen --run-migrations=6.0
  File "migrate.py", line 237
    if isinstance(addon_config, dict)\
     ^
SyntaxError: invalid syntax

**Comment by pedrobaeza** [comment]
The problem is still with libraries. This time, psycopg2. Please check all of this stuff before querying again.
