### ISSUE TITLE
[11.0 -> 12.0] Migration failed with stock warehouse updating

### ISSUE THREAD

**Issue by Danoolo** [OCA/OpenUpgrade#2248]
Hi guys, i'm trying a migration on a 11.0 db and i was hit for this error

2020-03-21 13:52:56,420 8474 INFO AP12.0b odoo.models: Storing computed values of stock.rule.route_sequence 
2020-03-21 13:52:56,507 8474 ERROR AP12.0b odoo.sql_db: bad query: ALTER TABLE "stock_warehouse" ADD FOREIGN KEY ("mto_pull_id") REFERENCES "stock_rule"("id") ON DELETE set null
ERROR: insert or update on table "stock_warehouse" violates foreign key constraint "stock_warehouse_mto_pull_id_fkey"
DETAIL:  Key (mto_pull_id)=(2) is not present in table "stock_rule".

It's strange because stock module was already migrated. Why could it be producing? Thanks a lot my friends!

**Comment by pedrobaeza** [comment]
You have your database a bit unstable. Check that the MTO rule is correctly put and always update to latest code in previous version and updating all modules.

Closing as this is not an OpenUpgrade issue per se.

**Comment by Danoolo** [comment]
Pedro, In stock module from openupgrade, the pre_migration.py should execute before check constraints..but debugging code this migration file dont do it...and the record copy of procurement.rule to stock.rule is not made. And therefore, i have migrated the same db backup in other moments in the past and everything was fine but now with the same db (but updated) dont. Any help?

**Comment by Danoolo** [comment]
Comment again to leave some self-reply for those with this problem...indeed i had bad written .conf file and the migration script was never running because in conf file i reference to another odoo addons (not openupgrade addons).
