### ISSUE TITLE
[11.0] Duplicated key name in res.currency.rate

### ISSUE THREAD

**Issue by sergiocorato** [OCA/OpenUpgrade#2249]
Impacted versions: 11.0

Steps to reproduce: migrate from 10.0

Current behavior: error in res.currency.rate name field duplicated

Expected behavior: no error

ERROR: ERRORE:  un valore chiave duplicato viola il vincolo univoco "ir_model_data_module_name_uniq_index"
DETAIL:  La chiave (module, name)=(base, field_res_currency_rate_name) esiste già.

**Comment by pedrobaeza** [comment]
Please don't open issue if you are going to open a PR. Put the issue description directly on the PR. Closing as we have the PR.

**Comment by sergiocorato** [comment]
I didn't know if I was able to find a solution ;D
