### ISSUE TITLE
openupgrade_records: Misses on transitioning from v7 api to v8 api

### ISSUE THREAD

**Issue by hbrunn** [OCA/OpenUpgrade#227]
This issue is meant to gather all problems we encounter with the analysis module on transitioning from the v7 api to v8. Please only put things here you're sure about to have a concise list on things to work on.

**Comment by pedrobaeza** [comment]
#225 mentions one of this

**Comment by hbrunn** [comment]
@pedrobaeza that issue was my reason to start this one ;-)

**Comment by hbrunn** [comment]
A many2many that had an explicit pivot table name before and resorts to the default name in the new version is not mentioned in the analysis if those names differ.

**Comment by StefanRijnhart** [comment]
An autogenerated cross table is not necessarily a 8.0 API feature. I think it was introduced here: https://github.com/odoo/odoo/commit/ad4a216e7d301fe0737be43fab511375c5677114, so we should take its logic into account from 6.1 on.

**Comment by pedrobaeza** [comment]
Are these features already included in the comparison?

**Comment by hbrunn** [comment]
not to my knowledge

**Comment by pedrobaeza** [comment]
Is this still relevant on v10 or should we close it?

**Comment by pedrobaeza** [comment]
Can you please tell me if this is still relevant for v10?

**Comment by hbrunn** [comment]
well, we survived until now, so I don't expect any news here
