### ISSUE TITLE
[12.0 -> 13.0] migrating of mass_mailing problem with obsolete model mail.mass_mailing.campaign

### ISSUE THREAD

**Issue by Yasaie** [OCA/OpenUpgrade#2271]
Hello,
I just tried to migrate mass_mailing but i saw mail.mass_mailing.campaign merged into utm.campaign. I looked into openupgradelib and i find move_field_m2o function but in this case mail.mass_mailing.campaign will be removed before migration so I copied mail_mass_mailing_campaign in pre-migration.py:
```python
```

**Comment by pedrobaeza** [comment]
`mass_mailing` module is still not completed, so this can't be discussed until when it is done. Some work has been done in advance in existing `utm` module due to the model changes, but as said, other things remain. Closing thus.
