### ISSUE TITLE
Migration Feedback 11.0 -> 13.0

### ISSUE THREAD

**Issue by gdgellatly** [OCA/OpenUpgrade#2322]
This is just for feedback. I don't expect a response. Issues found raised in seperate PR's.

OK so 11.0 -> 12.0 went smooth. I only include the fact here just in case relevant.

I had a small database that had enough commonality in place with the open PR's to give it a whirl. It was pretty good, only half a dozen issues to fix.

These are the PR's, now bear in mind many of these module have very little data installed.
```yaml
    - odoo refs/pull/2275/head  # account
    - odoo refs/pull/2277/head  # crm
    - odoo refs/pull/2280/head  # project
    - odoo refs/pull/2285/head  # hr
    - odoo refs/pull/2290/head  # hr
    - odoo refs/pull/2291/head  # hr
    - odoo refs/pull/2297/head  # sale
    - odoo refs/pull/2299/head  # website
    - odoo refs/pull/2295/head  #
    - odoo refs/pull/2305/head  # survey
    - odoo refs/pull/2278/head  # payment
    - odoo refs/pull/2319/head  # snailmail
```

At the end of the migration I reran with -u all and encountered that

```
        <record id="module_category_operations_inventory" model="ir.module.category">
            <field name="name">Inventory</field>
            <field name="sequence">4</field>
            <field name="parent_id" ref="module_category_operations"/>
        </record>
```
Was not present in base module, plus base hadn't actually migrated as expected, but I think that was my fault.

On start I received
`AttributeError: 'website' object has no attribute 'social_googleplus'`
Which I traced back to the default footer. Later I found it was endemic with nearly everything website and website_blog related, so I just deleted all views with those keys in ir_ui_view and reinstalled the modules.

For Account Taxes look weird on existing invoices as a seperate line instead of in taxes. It doesn't really matter for the historic ones anyway.

**Comment by pedrobaeza** [comment]
Thanks for your feedback. Indeed, website migration from any version to another implies a manual cleanup of invalid noupdate=1 views. There's no automatic way of disabling it as it depends on the render context and we can't emulate this in the migration process. Only real navigation through website structure can rise them.

About v13, it's very soon for giving feedback, although it's welcome on corresponding PRs, but as you should know the process on our OCA funded joint-venture, first ForgeFlow performs the initial PR and then Tecnativa reviews in deep and retouch it, so you should wait for this second pass for being sure of the validness of the PR. I'm currently reviewing/touching account migration.

For the rest, I'm closing this issue as the notification has been delivered to all the subscribed and can be referenced if needed in any other part.

**Comment by pleirb** [comment]
Dear, maybe it is ignorance on my part or something that I do wrong but when trying to migrate from 12 to 13 the same error occurs as the partner @gdgellatly 

500: Internal Server Error

**QWeb**

Error to render compiling AST
AttributeError: 'website' object has no attribute 'social_googleplus'
Template: web.frontend_layout
Path: /t/html/body/div/footer/div[1]/div/div[2]/h2/a[6]
Node: <a t-att-href="website.social_googleplus" t-if="website.social_googleplus" rel="publisher">
              <i class="fa fa-google-plus-square"/>
            </a>
            

Error ocurrido durante el dibujado de la plantilla web.frontend_layout y evaluando la siguiente expresión: <a t-att-href="website.social_googleplus" t-if="website.social_googleplus" rel="publisher"> <i class="fa fa-google-plus-square"/> </a> 

**Traza**

Traceback (most recent call last):
  File "/odoo/OpenUpgrade/odoo/addons/base/models/qweb.py", line 333, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_web_frontend_layout_100
AttributeError: 'website' object has no attribute 'social_googleplus'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/odoo/OpenUpgrade/odoo/addons/base/models/ir_http.py", line 234, in _dispatch
    result = request.dispatch()
  File "/odoo/OpenUpgrade/odoo/http.py", line 809, in dispatch
    r = self._call_function(**self.params)
  File "/odoo/OpenUpgrade/odoo/http.py", line 350, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/OpenUpgrade/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/OpenUpgrade/odoo/http.py", line 342, in checked_call
    result.flatten()
  File "/odoo/OpenUpgrade/odoo/http.py", line 1241, in flatten
    self.response.append(self.render())
  File "/odoo/OpenUpgrade/odoo/http.py", line 1234, in render
    return env["ir.ui.view"].render_template(self.template, self.qcontext)
  File "/odoo/OpenUpgrade/odoo/addons/base/models/ir_ui_view.py", line 1194, in render_template
    return self.browse(self.get_view_id(template)).render(values, engine)
  File "/odoo/OpenUpgrade/addons/website/models/ir_ui_view.py", line 344, in render
    return super(View, self).render(values, engine=engine, minimal_qcontext=minimal_qcontext)
  File "/odoo/OpenUpgrade/addons/web_editor/models/ir_ui_view.py", line 27, in render
    return super(IrUiView, self).render(values=values, engine=engine, minimal_qcontext=minimal_qcontext)
  File "/odoo/OpenUpgrade/odoo/addons/base/models/ir_ui_view.py", line 1202, in render
    return self.env[engine].render(self.id, qcontext)
  File "/odoo/OpenUpgrade/odoo/addons/base/models/ir_qweb.py", line 58, in render
    result = super(IrQWeb, self).render(id_or_xml_id, values=values, **context)
  File "/odoo/OpenUpgrade/odoo/addons/base/models/qweb.py", line 260, in render
    self.compile(template, options)(self, body.append, values or {})
  File "/odoo/OpenUpgrade/odoo/addons/base/models/qweb.py", line 335, in _compiled_fn
    raise e
  File "/odoo/OpenUpgrade/odoo/addons/base/models/qweb.py", line 333, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_web_login_38
  File "/odoo/OpenUpgrade/odoo/addons/base/models/qweb.py", line 335, in _compiled_fn
    raise e
  File "/odoo/OpenUpgrade/odoo/addons/base/models/qweb.py", line 333, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_web_login_layout_44
  File "/odoo/OpenUpgrade/odoo/addons/base/models/qweb.py", line 340, in _compiled_fn
    raise QWebException("Error to render compiling AST", e, path, node and etree.tostring(node[0], encoding='unicode'), name)
odoo.addons.base.models.qweb.QWebException: 'website' object has no attribute 'social_googleplus'
Traceback (most recent call last):
  File "/odoo/OpenUpgrade/odoo/addons/base/models/qweb.py", line 333, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_web_frontend_layout_100
AttributeError: 'website' object has no attribute 'social_googleplus'

Error to render compiling AST
AttributeError: 'website' object has no attribute 'social_googleplus'
Template: web.frontend_layout
Path: /t/html/body/div/footer/div[1]/div/div[2]/h2/a[6]
Node: <a t-att-href="website.social_googleplus" t-if="website.social_googleplus" rel="publisher">
              <i class="fa fa-google-plus-square"/>
            </a>

**Comment by pedrobaeza** [comment]
You have to remove such element inside the view before migrating, or now through any way in your migrated DB.

**Comment by pleirb** [comment]
> Debe eliminar dicho elemento dentro de la vista antes de migrar, o ahora a través de cualquier forma en su base de datos migrada.

Excellent, it is solved when deleting all the <a> tags that contain in the structure of the view this: website.social_googleplus

Thank you !
