### ISSUE TITLE
[RFC][V12] point_of_sale : Improving migration

### ISSUE THREAD

**Issue by legalsylvain** [OCA/OpenUpgrade#2328]
Hi all, two question, regarding point_of_sale migration from 11.0 to 12.0

1) regarding ``pos.order.line`` the current migration script is calling ``_compute_amount_line_all()`` via ``_onchange_amount_line_all()`` [here](https://github.com/OCA/OpenUpgrade/blob/12.0/addons/point_of_sale/migrations/12.0.1.0.1/post-migration.py#L13)

The purpose is to recompute ``price_subtotal_incl`` and ``price_subtotal`` fields for each lines.
That is great, but very slow, and it is not required in the case the database has the OCA module pos_pricelist installed. [see](https://github.com/OCA/pos/blob/8.0/pos_pricelist/models/point_of_sale.py#L73).

**Proposal** : Call _onchange_amount_line_all() only for items with ``price_subtotal_incl`` != 0. So if we come from a database with non null values, recompute will be skipped.

2) regarding ``pos.order``, the current migration script is calling ``_compute_batch_amount_all()`` [here](https://github.com/OCA/OpenUpgrade/blob/12.0/addons/point_of_sale/migrations/12.0.1.0.1/post-migration.py#L6). to compute ``amount_paid``, ``amount_return``, ``amount_tax``, ``amount_total``.

**problem A)** taxes and taxed depends on pos_order_line values ``price_subtotal_incl`` and ``price_subtotal`` that are not computed at this step.
**problem B)** the computation is also very slow, and can be done by a SQL request, in the post-migration script, very quickly.

**Proposal**
Add there two request, in the post-migration.py file
```
UPDATE pos_order po
    SET amount_paid = tmp.amount_paid,
    amount_return = tmp.amount_return
FROM (
    SELECT
        po.id,
        sum(absl.amount) as amount_paid,
        sum(LEAST(absl.amount, 0)) as amount_return
    FROM pos_order po
    INNER JOIN account_bank_statement_line absl ON absl.pos_statement_id = po.id
    GROUP BY po.id
) as tmp
where po.id = tmp.id;
```
and 
```
UPDATE pos_order po
    SET amount_total = tmp.amount_total,
    amount_tax = tmp.amount_total - tmp.amount_untaxed
FROM (
    SELECT
        po.id,
        sum(pol.price_subtotal_incl) as amount_total,
        sum(pol.price_subtotal) as amount_untaxed
    FROM pos_order po
    INNER JOIN pos_order_line pol ON pol.order_id = po.id
    GROUP BY po.id
) as tmp
where po.id = tmp.id;
```

CC : original authors : @pedrobaeza, @MiquelRForgeFlow

**Comment by pedrobaeza** [comment]
Seems OK at first sight.

**Comment by MiquelRForgeFlow** [comment]
Well explained. LGTM
