### ISSUE TITLE
[10.0] product_uos module not uninstalled

### ISSUE THREAD

**Issue by legalsylvain** [OCA/OpenUpgrade#2330]
Context : 
- ``product_uos`` is an Odoo module, present only in odoo 9.0 version. (new in [9.0](https://github.com/OCA/OpenUpgrade/blob/9.0/openerp/openupgrade/doc/source/modules80-90.rst), removed in [10.0](https://github.com/OCA/OpenUpgrade/blob/10.0/odoo/openupgrade/doc/source/modules90-100.rst))
- it contains ``product.template`` fields that was present before in ``product`` 8.0 module (``uos_id``, ``uos_coeff``) (and also computed fields on ``sale.order.line``)
- in version 10.0 template fields seems to have disappeared.

Step to reproduct : 
- migrate a database from 8.0 to 10.0 (or >)
- the openupgrade 9.0 will install the module [here](https://github.com/OCA/OpenUpgrade/blob/9.0/addons/product/migrations/9.0.1.2/pre-migration.py#L104)
- in the end, the product_uos module is still in the installed state, but not available.

I guess it should be uninstalled in the openupgrade 10.0.
- Am I right ? 
- If yes, I don't know in which step (where) it should be done.

thanks.

CC : original authors : @JordiBForgeFlow

**Comment by pedrobaeza** [comment]
I think the module should be merged instead with the corresponding one (`account` or `sale`).

**Comment by pedrobaeza** [comment]
Closing as stalled.
