### ISSUE TITLE
[11.0] Sale line linked to project is of another partner sale order

### ISSUE THREAD

**Issue by sergiocorato** [OCA/OpenUpgrade#2336]
I'm investigating why this happen (in 2 out of 3 migration)

https://github.com/OCA/OpenUpgrade/blob/98e6d57611c4ccc1a6b4b9a075b1ab8080149390/addons/sale_timesheet/migrations/11.0.1.0/post-migration.py#L122

**Comment by sergiocorato** [comment]
I add PR for solution

**Comment by pedrobaeza** [comment]
Well, it's good habit to link both, but I'm closing this having the PR.
