### ISSUE TITLE
[12.0] MemoryError in point_of_sale/migrations/12.0.1.0.1/post-migration.py

### ISSUE THREAD

**Issue by ivantodorovich** [OCA/OpenUpgrade#2344]
Impacted versions: 12.0

Steps to reproduce:
Migrate a big database with lots of pos.orders and lines

Current behavior:
```
odoo_1  | 2020-06-02 04:55:37,235 517 ERROR migrate OpenUpgrade: point_of_sale: error in migration script point_of_sale/migrations/12.0.1.0.1/post-migration.py:  
odoo_1  | 2020-06-02 04:55:37,235 517 ERROR migrate OpenUpgrade:  
odoo_1  | Traceback (most recent call last):
odoo_1  |   File "/home/odoo/.local/lib/python3.5/site-packages/odoo/api.py", line 1049, in get
odoo_1  |     value = self._data[key][field][record._ids[0]]
odoo_1  | KeyError: 416960
odoo_1  | 
odoo_1  | During handling of the above exception, another exception occurred:
odoo_1  | 
odoo_1  | Traceback (most recent call last):
odoo_1  |   File "/home/odoo/.local/lib/python3.5/site-packages/odoo/fields.py", line 1032, in __get__
odoo_1  |     value = record.env.cache.get(record, self)
odoo_1  |   File "/home/odoo/.local/lib/python3.5/site-packages/odoo/api.py", line 1051, in get
odoo_1  |     raise CacheMiss(record, field)
odoo_1  | odoo.exceptions.CacheMiss: ('pos.order(416960,).pricelist_id', None)
odoo_1  | 
odoo_1  | During handling of the above exception, another exception occurred:
odoo_1  | 
odoo_1  | Traceback (most recent call last):
odoo_1  |   File "/home/odoo/.local/lib/python3.5/site-packages/openupgradelib/openupgrade.py", line 1778, in wrapped_function
odoo_1  |     if use_env2 else cr, version)
odoo_1  |   File "/home/odoo/src/odoo/addons/point_of_sale/migrations/12.0.1.0.1/post-migration.py", line 19, in migrate
odoo_1  |     fill_pos_order_amounts(env)
odoo_1  |   File "/home/odoo/src/odoo/addons/point_of_sale/migrations/12.0.1.0.1/post-migration.py", line 8, in fill_pos_order_amounts
odoo_1  |     env["pos.order"].search([])._compute_batch_amount_all()
odoo_1  |   File "/home/odoo/src/odoo/addons/point_of_sale/models/pos_order.py", line 624, in _compute_batch_amount_all
odoo_1  |     currency = order.pricelist_id.currency_id
odoo_1  |   File "/home/odoo/.local/lib/python3.5/site-packages/odoo/fields.py", line 1036, in __get__
odoo_1  |     self.determine_value(record)
odoo_1  |   File "/home/odoo/.local/lib/python3.5/site-packages/odoo/fields.py", line 1139, in determine_value
odoo_1  |     record._prefetch_field(self)
odoo_1  |   File "/home/odoo/.local/lib/python3.5/site-packages/odoo/models.py", line 2835, in _prefetch_field
odoo_1  |     records = self._in_cache_without(field)
odoo_1  |   File "/home/odoo/.local/lib/python3.5/site-packages/odoo/models.py", line 5178, in _in_cache_without
odoo_1  |     for record_id in self.env.cache.get_missing_ids(recs - self, field):
odoo_1  |   File "/home/odoo/.local/lib/python3.5/site-packages/odoo/models.py", line 5057, in __sub__
odoo_1  |     return self.browse([id for id in self._ids if id not in other_ids])
odoo_1  |   File "/home/odoo/.local/lib/python3.5/site-packages/odoo/models.py", line 4719, in browse
odoo_1  |     return self._browse(ids, self.env, prefetch)
odoo_1  |   File "/home/odoo/.local/lib/python3.5/site-packages/odoo/models.py", line 4706, in _browse
odoo_1  |     prefetch[cls._name].update(ids)
odoo_1  | MemoryError
```

---

I'm running openupgrade on a server with 120GB RAM
Migrating a database with 1.078.170 pos.order.lines

**Comment by ivantodorovich** [comment]
I'm not 100% sure but it looks like it's python who's running out of memory, not postgres.
I'm wondering if we shouldn't compute these in batches:

https://github.com/OCA/OpenUpgrade/blob/12.0/addons/point_of_sale/migrations/12.0.1.0.1/post-migration.py#L8

https://github.com/OCA/OpenUpgrade/blob/12.0/addons/point_of_sale/migrations/12.0.1.0.1/post-migration.py#L13

?

`_compute_batch_amount_all` may be replaced by a more efficient raw sql, I think.


In any case, I'm not sure what would be the approach to compute these methods in batches. Should I split the recordset in chunks, and  `invalidate_cache()` after each chunk is processed? :thinking:

**Comment by legalsylvain** [comment]
Did you tried : https://github.com/OCA/OpenUpgrade/pull/2329/files ?

**Comment by ivantodorovich** [comment]
> Did you tried : https://github.com/OCA/OpenUpgrade/pull/2329/files ?

Nice one! I'll give it a try!

**Comment by ivantodorovich** [comment]
It worked for `_compute_batch_amount_all`, but it gave me the same error in `fill_pos_order_line_prices`

```
odoo_1  | 2020-06-02 17:07:06,349 517 INFO migrate OpenUpgrade: point_of_sale: post-migration script called with version 11.0.1.0.1 
odoo_1  | 2020-06-02 17:07:13,889 517 ERROR migrate OpenUpgrade: point_of_sale: error in migration script point_of_sale/migrations/12.0.1.0.1/post-migration.py:  
odoo_1  | 2020-06-02 17:07:13,890 517 ERROR migrate OpenUpgrade:  
odoo_1  | Traceback (most recent call last):
odoo_1  |   File "/home/odoo/.local/lib/python3.5/site-packages/openupgradelib/openupgrade.py", line 1778, in wrapped_function
odoo_1  |     if use_env2 else cr, version)
odoo_1  |   File "/home/odoo/src/odoo/addons/point_of_sale/migrations/12.0.1.0.1/post-migration.py", line 74, in migrate
odoo_1  |     fill_pos_order_line_prices(env)
odoo_1  |   File "/home/odoo/src/odoo/addons/point_of_sale/migrations/12.0.1.0.1/post-migration.py", line 25, in fill_pos_order_line_prices
odoo_1  |     env["pos.order.line"].search([])._onchange_amount_line_all()
odoo_1  |   File "/home/odoo/.local/lib/python3.5/site-packages/odoo/models.py", line 1586, in search
odoo_1  |     res = self._search(args, offset=offset, limit=limit, order=order, count=count)
odoo_1  |   File "/home/odoo/.local/lib/python3.5/site-packages/odoo/models.py", line 4153, in _search
odoo_1  |     res = self._cr.fetchall()
odoo_1  | MemoryError
```

I guess I should try installing `pos_pricelist` in `9.0`, before running the migration ,right? :thinking:

**Comment by legalsylvain** [comment]
> It worked for _compute_batch_amount_all, 

Nice ! 

> but it gave me the same error in fill_pos_order_line_prices

For my part, I came from 8.0, with 8.115.838 pos order lines and with pos_pricelist installed.
2 approaches for you : 
- install pos_pricelist in V9. (maybe it will take a lot of time, also, but you have all the time to compute correctly the data).
- improve the openupgrade script, adding a SQL script, instead of the heavy ORM call.

I think the first approach is more simple, but the second is more community. Anyway, thanks for your review of #2329.

Question : did you tuned correctly odoo ?

**Comment by ivantodorovich** [comment]
Yeah, I'll try option 1.

Re: option 2.. It seems really complex, there are taxes and fiscal positions involved. I don't think it's worth trying to compute all of that in raw sql.

Maybe what could really help is finding a way to process the lines in batches, to avoid the MemoryError.

In any case, thanks you for that PR and for pointing me in that direction :smile: :+1:

**Comment by legalsylvain** [comment]
> Maybe what could really help is finding a way to process the lines in batches, to avoid the MemoryError.

@sebastienbeau : we was talking about such feature some time ago... Batching before / after migration...

**Comment by pedrobaeza** [comment]
https://github.com/OCA/openupgradelib/blob/6c18ce0c160b9cf47c4fa898d9b6c4265d98c216/openupgradelib/openupgrade.py#L2416

**Comment by ivantodorovich** [comment]
> https://github.com/OCA/openupgradelib/blob/6c18ce0c160b9cf47c4fa898d9b6c4265d98c216/openupgradelib/openupgrade.py#L2416

great! I'll try it

**Comment by ivantodorovich** [comment]
Thank you both!
it's working now :smiley:
