### ISSUE TITLE
[8.0 -> 9.0] Error in migration script account/migrations/9.0.1.1/post-migration.py

### ISSUE THREAD

**Issue by sebastienhasa** [OCA/OpenUpgrade#2347]
While running a migration from Odoo 8.0 to 9.0, with OpenUpgrade 9.0, I got an error:
```
ERROR migration_db OpenUpgrade: account: error in migration script account/migrations/9.0.1.1/post-migration.py: NotNullViolation('null value in column "account_id" violates not-null constraint\nDETAIL:  Failing row contains (60046, 7, 2017-11-19 10:22:18.669788, 2020-06-09 10:23:01.738099, 1, null, null, null, 23505, 0.00, 0.00, 1, null, 0.00, null, 7305, null, null, 61, break, percent,  , 0, null, null, 0, null, 0.0).\nCONTEXT:  SQL statement "UPDATE ONLY "public"."account_invoice_line" SET "account_id" = NULL WHERE $1 OPERATOR(pg_catalog.=) "account_id""\n',)

2020-06-05 14:18:12,482 60 ERROR migration_db OpenUpgrade: null value in column "account_id" violates not-null constraint
DETAIL:  Failing row contains (60046, 7, 2017-11-19 10:22:18.669788, 2020-06-09 10:23:01.738099, 1, null, null, null, 23505, 0.00, 0.00, 1, null, 0.00, null, 7305, null, null, 61, break, percent,  , 0, null, null, 0, null, 0.0).
CONTEXT:  SQL statement "UPDATE ONLY "public"."account_invoice_line" SET "account_id" = NULL WHERE $1 OPERATOR(pg_catalog.=) "account_id""
```

Openupgrade try to set `null` value to the field `account_id`. But this field had the modifier set to `not null`.

**Comment by pedrobaeza** [comment]
You have a view account set in any place like journal entries, fiscal positions, taxes, etc.

**Comment by sebastienhasa** [comment]
> You have a view account set in any place like journal entries, fiscal positions, taxes, etc.

A what?

**Comment by pedrobaeza** [comment]
An account of type view. Please use now the newly created mailing list for these things:

https://odoo-community.org/groups/openupgrade-87?mode=thread

**Comment by sebastienhasa** [comment]
> Please use now the newly created mailing list for these things:
> 
> https://odoo-community.org/groups/openupgrade-87?mode=thread

How can I join? I created an account but cannot see any option to subscribe to the list.

**Comment by pedrobaeza** [comment]
Subscribe it in https://odoo-community.org/groups
