### ISSUE TITLE
unit price and paid status blank in odoo13

### ISSUE THREAD

**Issue by mevivek4u** [OCA/OpenUpgrade#2349]
Impacted versions: V13

Steps to reproduce: migration from V7 to V13

Current behavior: unit price blank in account_move_line

Expected behavior: unit price should copy from account_invoice _line

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
v13 migration is not ready yet, so this issue is with WIP scripts. You can comment in the involved PR, but not here, and probably you have a deeper problem doing such jump. You can try to write also on the mailing list, but not here.
