### ISSUE TITLE
[13.0][product] Wrong product_template_attribute_value_ids value on Product form

### ISSUE THREAD

**Issue by kos94ok-3D** [OCA/OpenUpgrade#2354]
Current behavior:
![image](https://user-images.githubusercontent.com/33932458/85409264-46f96180-b56e-11ea-96b6-0302b1eb7db0.png)

Expected behavior:
![image](https://user-images.githubusercontent.com/33932458/85409345-5d9fb880-b56e-11ea-9b23-6ff143ad7748.png)

**Comment by pedrobaeza** [comment]
Closing as there's the PR #2355
