### ISSUE TITLE
[13.0] need to refresh Odoo 

### ISSUE THREAD

**Issue by sbidoul** [OCA/OpenUpgrade#2356]
We need [this commit](https://github.com/odoo/odoo/commit/0e3c5d3ee1726db2641cd683a84fe59e867d4319) in OpenUpgrade 13.0, because `product_variant_configurator` adds a `product_id` field on `product_product`.

How is it usually done in this project?

**Comment by pedrobaeza** [comment]
We propose an upstream update like OCB, but manual, like #2220
