### ISSUE TITLE
[7.0 -> 12.0] English translation terms shouldn't be present

### ISSUE THREAD

**Issue by ivantodorovich** [OCA/OpenUpgrade#2366]
**Impacted versions:**
Don't know exactly, coming from 7.0

**Steps to reproduce:**
Migrate db from 7.0 to 12.0

**Current behavior:**
Final database contains "en_US" translation terms, which is causing buggy behaviours on translatable fields.

(Impossible to edit the english term from the UI, because if user language is english, odoo will change the source term and not the translation value)

**Expected behavior:**
No translation terms for "en_US", as this is the default behaviour

Have anyone encountered something like this?
I've simply removed all the 'en_US' translation terms to fix it, but I have a feeling this should be handled in openupgrade somewhere.

`
DELETE FROM ir_translation WHERE lang = 'en_US';
`

**Comment by pedrobaeza** [comment]
OpenUpgrade is not adding en_US terms in any of the versions AFAIK, so your patch is OK.

Closing until further evidence is given of a problem in OU.
