### ISSUE TITLE
In this migration script all records of model mail.tracking.value get deleted. 

### ISSUE THREAD

**Issue by vikichavada** [OCA/OpenUpgrade#2368]
Here is found that in the migration script it just removing all the records of mail.tracking.values as i  migrated from 12 to 13.
And found possible code from where it is removing the records. (see link below)
[Odoo Ir.model.felds](https://github.com/odoo/odoo/blob/0e5c3cf8fc85105249e1f75e8e8f1053ee37b889/addons/mail/models/ir_model_fields.py#L34)

I think we need the tracking logs for the records in newly migrated database. 
Please help.

**Comment by pedrobaeza** [comment]
Why are you linking Odoo code and not OpenUpgrade? Anyway, please indicate all the steps for the problem, as the pointed code is correct.

**Comment by pedrobaeza** [comment]
Closing as no answer. We can reopen if more information that proves a problem in OU is given.
