### ISSUE TITLE
AttributeError: module 'odoo.api' has not attribute 'model_create_multi'

### ISSUE THREAD

**Issue by natthanank** [OCA/OpenUpgrade#2371]
I have to create new Odoo server with Odoo 13 (my old Odoo is Odoo 10).
I install Odoo 13 in my server and need to migrate old db to new db.
So I dump the old db (db of Odoo 10) to new server (Odoo 13) and want to use the OpenUpgrade.
I plan to migrate db from Odoo 10 -> Odoo 11, Odoo 11 -> Odoo 12 and then Odoo 12 -> Odoo 13.
But in the step Odoo 10 -> Odoo 11, I got the error message "AttributeError: module 'odoo.api' has not attribute 'model_create_multi'". 
How do I managed this error?

** Note: modules on the new server are version 13 already. **

**Comment by pedrobaeza** [comment]
You have done something incorrect, as that decorator is used in version 12, but can't say more. Anyway, this is something of deployment, not of OpenUpgrade itself, so closing.

**Comment by natthanank** [comment]
I cant use OpenUpgrade right?

**Comment by pedrobaeza** [comment]
You can, but you are doing things in an incorrect way and that's why you get that error. I can't say more, because there's no more information by your part (but it's something out of the scope of this issue tracker - try mailing list or forums).

**Comment by jayachanran** [comment]
AttributeError: module 'odoo.api' has no attribute 'ondelete'
