### ISSUE TITLE
v12 --> v13 [Invoices are not migrated] with openupgrade

### ISSUE THREAD

**Issue by mr-module** [OCA/OpenUpgrade#2396]
While upgrading from v12 to v13, 

Invoices are not migrated using openupgrade. 
They still remain in account.invoice, whereas it is suppose to be transferred to account.move .

Anyone has an idea on this?

**Comment by pedrobaeza** [comment]
Write on the opened PR. Anyway, I have already told you that next week I will push a new version. Wait until then.

**Comment by mr-module** [comment]
Where to write open issues?

**Comment by pedrobaeza** [comment]
Sorry, on the open PR, but don't insist, a new version will arrive soon in the PR.

**Comment by mr-module** [comment]
Okay, I'll wait for next version. Hopefully this gets fixed.

**Comment by pedrobaeza** [comment]
If not, write on the PR, and put all the details needed for reproducing the problem. Issues are only when the code has been already merged.

**Comment by mr-module** [comment]
If not, will do
