### ISSUE TITLE
[10 -> 11] psycopg2.errors.SerializationFailure: could not serialize access due to concurrent update

### ISSUE THREAD

**Issue by sebastienhasa** [OCA/OpenUpgrade#2397]
Impacted versions:

OpenUpgrade, branch 11.0, commit b73127be5bf

Steps to reproduce:

* Load the database of our cilent
* Launch the migration
* See OpenUpgrade stop with the an error message

Current behavior:

After some times, OpenUpgrade fail with the error:
```
ERROR migration_db odoo.modules.registry: Failed to load registry
Traceback (most recent call last):
  File "/OpenUpgrade/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/OpenUpgrade/odoo/modules/loading.py", line 451, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check, upg_registry)
  File "/OpenUpgrade/odoo/modules/loading.py", line 337, in load_marked_modules
    upg_registry=upg_registry,
  File "/OpenUpgrade/odoo/modules/loading.py", line 206, in load_module_graph
    module.write(module.get_values_from_terp(package.data))
  File "/OpenUpgrade/odoo/models.py", line 3142, in write
    self._write(old_vals)
  File "/OpenUpgrade/odoo/models.py", line 3245, in _write
    cr.execute(query, params + (sub_ids,))
  File "/OpenUpgrade/odoo/sql_db.py", line 155, in wrapper
    return f(self, *args, **kwargs)
  File "/OpenUpgrade/odoo/sql_db.py", line 232, in execute
    res = self._obj.execute(query, params)
psycopg2.errors.SerializationFailure: could not serialize access due to concurrent update
```

Expected behavior:

OpenUpgrade didnt bug and finish the migration

Notes:

* I cannot share the database of our client, so it could be difficult to reproduce this bug
* The database come from a version 6.1 that I migrated to 7.0, 9.0 and then 10.0 with OpenUpgrade

**Comment by pedrobaeza** [comment]
This can't happen in a properly configured migration. This is sign of Odoo running normally over the same DB, executing for example crons.

Closing as no OpenUpgrade issue, but migration procedure.

**Comment by sebastienhasa** [comment]
> This is sign of Odoo running normally over the same DB

Odoo is stopped when I run OpenUpgrade

**Comment by pedrobaeza** [comment]
Then workers or similar, but there's something concurrent.
