### ISSUE TITLE
Hash Sum mismatch nightly.odoo.com/13.0/nightly/deb

### ISSUE THREAD

**Issue by avping** [OCA/OpenUpgrade#2401]
Hey, Im using the debian nightly repository and I get the following error after "apt update":

Reading package lists... Done
E: Failed to fetch http://nightly.odoo.com/13.0/nightly/deb/./Packages  Hash Sum mismatch
   Hashes of expected file:
    - Filesize:1873 [weak]
    - SHA512:e556b03536dab3a264098edcb57b488b18beed58b3ddc0b4cb16c1afedc020ebf8c023f3a33a0439b9b2514b6a3bf5e6673f4be7ec391a56aae0b909bcda4971
    - SHA256:ed30f320788bdfb0b9f366ba5b15d8e5bfd67d1e168a59cf5acae194bc3c07cc
    - SHA1:057e4a5a0e8217e42206fa13765375608659f63b [weak]
    - MD5Sum:7b3855b1502b750cd0dc039599fd90f3 [weak]
   Hashes of received file:
    - SHA512:e38920835da5177e89bc4106f01d181b170e5896474f9d21e03b9f5ff13a2e07b7e57ff764b1f80c048d1dbf93e9c81e91405158f047571368f9ade524ec8f43
    - SHA256:d8bb3530458f7f15cfc62153ff043ec466a9348d0f2c1e35d846e11e6a176b70
    - SHA1:f40d6d12304b82ec75f0ae35492a5d32137d13bc [weak]
    - MD5Sum:440e7555cf9117abe8cfb130466446a4 [weak]
    - Filesize:1873 [weak]
   Last modification reported: Tue, 01 Sep 2020 04:21:01 +0000
   Release file created at: Mon, 31 Aug 2020 03:42:40 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead.

I have debian 10 buster

apt-key list
/etc/apt/trusted.gpg
--------------------
pub   rsa4096 2014-11-27 [SC]
      5D13 4C92 4CB0 6330 DCEF  E2A1 DEF2 A219 8183 CBB5
uid           [ unknown] Odoo SA, Linux Package Signing Key <info@odoo.com>
sub   rsa4096 2014-11-27 [E]

**config:**
/etc/apt/sources.list.d/odoo.list
deb http://nightly.odoo.com/13.0/nightly/deb/ ./

/etc/apt/apt.conf.d/98proxy.conf
Acquire::http::Pipeline-Depth 0;
Acquire::http::No-Cache true;
Acquire::BrokenProxy    true;

the following attempts have not been successful:

apt clean
rm -rf /var/lib/apt/lists/*

any suggestions?

**Comment by pedrobaeza** [comment]
This has nothing to do with OpenUpgrade. Anyway, I think it has been fixed by Odoo. Wait till tomorrow.
