### ISSUE TITLE
[13.0] don't generate openupgrade.records (xmlid / fields)

### ISSUE THREAD

**Issue by legalsylvain** [OCA/OpenUpgrade#2431]
Impacted versions: 13.0 (maybe other)

**Steps to reproduce:**

- checkout the last version of openupgrade 13.0
- install ``openupgrade_records`` module
- log in and click on "Settings > Openupgrade Developppement > generate records" and confirm
- go to "Records"

**Current behavior:**
- only 131 records has been generated. (only type== 'model')

**Expected behavior:**
- all records should be generated. ('fields', 'xmlid')

Did I missed something ? I saw that @MiquelRForgeFlow recently updated in #2411 and #2409 the analysis. So it worked for him. what I am doing wrong ?

(sorry, I didn't found openpugrade project on OCA runbot, so I cant reproduce the problem online.)

Thanks for your help !

Context : working on Openupgrade 14.0 (but in this issue, i just use openupgrade 13.0, executing one part of the [doc](https://doc.therp.nl/openupgrade/analyse.html).)

(version : python 3.6.9 ; postgresql : 10.14)

CC : @StefanRijnhart, @pedrobaeza

**Comment by MiquelRForgeFlow** [comment]
I am doing analysis using script instead of using user interface of openupgrade_records.

**Comment by legalsylvain** [comment]
Thanks for your quick answer ! 

> I am doing analysis using script instead of using user interface of openupgrade_records.

1) Do you mean, you use : https://github.com/OCA/OpenUpgrade/wiki/Crude-script-to-create-the-full-analysis-between-two-versions-of-Odoo

it seems that it is using the same code ``client.env['openupgrade.generate.records.wizard'].generate([])``

if you are using other code, could you share it ?

2) why don't you use interface ? because it doesn't work ? or other reason ?

thanks !

**Comment by MiquelRForgeFlow** [comment]
1. Yes, that one, but I still use erppeek + xmlrpc.client instead of odoorpc because with odoorpc I had an issue (I don't remember why).

2. Because using interface it's pain: You have to create two bbdd, one using previous version and other using new version (and using different ports), and doing that manually consumes time excessively from my POV.

**Comment by legalsylvain** [comment]
OK. thanks for the information.

Problem solved. I made a mistake in my addons_path, and the code used was odoo, and not openugprade. 
- records type = model are created by openupgrade_records : OK
- record type != model are created with patches in core : KO.

sorry for the noice !

Note : regarding, [script](https://github.com/OCA/OpenUpgrade/wiki/Crude-script-to-create-the-full-analysis-between-two-versions-of-Odoo), it works like a charm. (python3.6.9 / odoorpc==0.7.0) replacing ``print ""`` by ``print("")``
