### ISSUE TITLE
[13.0] migrations are not triggered except for module base

### ISSUE THREAD

**Issue by JordiBForgeFlow** [OCA/OpenUpgrade#2446]
Impacted versions: 13.0

Steps to reproduce:
clone openugrade in branch 13.0
clone openupgradelib in master branch
install the other required pip dependencies

Create a database in v12 with a validated supplier invoice, on a separate odoo 12.

Run the 'odoo-bin.py' with update=all in openupgrade.

Current behavior:
The migration log only shows a migration log for the 'base' module.
`odoo.modules.migration: module base: Running migration [>13.0.1.3] pre-migration `

All other modules are just updated.

Expected behavior:
For all modules the upgrade process is run. I expect a log entry 'Running migration' for each module.

Full log until module 'mail' is upgraded: https://pastebin.com/yV9bQ4CK

**Comment by JordiBForgeFlow** [comment]
cc @MiquelRForgeFlow this is very strange. Does it happen to you? Am I missing something here?

**Comment by legalsylvain** [comment]
@JordiBForgeFlow do you have regular odoo/odoo branch in your addons path ?

**Comment by JordiBForgeFlow** [comment]
Oh dear, you are right......

**Comment by legalsylvain** [comment]
I lost some time with the same problem some weeks ago :-).
Note : this should not happen on 14, with https://github.com/OCA/OpenUpgrade/issues/2440
