### ISSUE TITLE
[13.0] Account tags for taxes issues

### ISSUE THREAD

**Issue by elperrofarelo** [OCA/OpenUpgrade#2462]
Impacted versions:
1- Data table account.account.tag won't be complete migrated. Only the tags used in the invoices will be migrated
2- Tag in tax grid not complete migrated
Steps to reproduce:

Current behavior:

Expected behavior:

Video/Screenshot link (optional):
1- Before [12.0]
<img width="689" alt="image" src="https://user-images.githubusercontent.com/9564408/100841038-61b9f580-347f-11eb-9302-7d9e62618d1a.png">
After [13.0]
<img width="646" alt="image" src="https://user-images.githubusercontent.com/9564408/100841111-7f875a80-347f-11eb-8686-c7145097f288.png">

2-Before [12.0]
<img width="1027" alt="image" src="https://user-images.githubusercontent.com/9564408/100841671-47cce280-3480-11eb-9d90-9379da6a6f99.png">
After [13.0]
<img width="1437" alt="image" src="https://user-images.githubusercontent.com/9564408/100841735-5e733980-3480-11eb-9614-2bc048d22491.png">

**Comment by pedrobaeza** [comment]
You have to execute account_chart_update for that.

**Comment by elperrofarelo** [comment]
Thanks
