### ISSUE TITLE
[SOVED] - ValueError: Invalid field 'layout_type' in leaf

### ISSUE THREAD

**Issue by chdrsto** [OCA/OpenUpgrade#247]
Hi all

I've upgraded OpenERP from V6.1 to 7.0 using openupgrade. The migration went pretty well through with some small issues i could solve by my own.
The upgraded system is up and running, but I face one issue on "Order Lines to Invoice" function which I'm not able to get it fixed.

When I call the function .. i get following message. (see below).
I've checked the database and the field layout_type does exist in the table sale_order_line. But actually I'm not sure if this field is necessary at all, since Ive created a reference installation (DB) with all the modules I have and this column doesn't exist in the fresh V7 DB.

How can I solve this issue?
Any hints are appreciated.

Server Traceback (most recent call last):
  File "/opt/openerp70/addons/web/session.py", line 89, in send
    return openerp.netsvc.dispatch_rpc(service_name, method, args)
  File "/opt/openerp70/openerp/netsvc.py", line 296, in dispatch_rpc
    result = ExportService.getService(service_name).dispatch(method, params)
  File "/opt/openerp70/openerp/service/web_services.py", line 632, in dispatch
    res = fn(db, uid, _params)
  File "/opt/openerp70/openerp/osv/osv.py", line 190, in execute_kw
    return self.execute(db, uid, obj, method, *args, *_kw or {})
  File "/opt/openerp70/openerp/osv/osv.py", line 132, in wrapper
    return f(self, dbname, _args, *_kwargs)
  File "/opt/openerp70/openerp/osv/osv.py", line 199, in execute
    res = self.execute_cr(cr, uid, obj, method, _args, *_kw)
  File "/opt/openerp70/openerp/osv/osv.py", line 187, in execute_cr
    return getattr(object, method)(cr, uid, _args, *_kw)
  File "/opt/openerp70/openerp/osv/orm.py", line 2398, in search
    return self._search(cr, user, args, offset=offset, limit=limit, order=order, context=context, count=count)
  File "/opt/openerp70/openerp/osv/orm.py", line 4991, in _search
    query = self._where_calc(cr, user, args, context=context)
  File "/opt/openerp70/openerp/osv/orm.py", line 4817, in _where_calc
    e = expression.expression(cr, user, domain, self, context)
  File "/opt/openerp70/openerp/osv/expression.py", line 646, in __init__
    self.parse(cr, uid, context=context)
  File "/opt/openerp70/openerp/osv/expression.py", line 810, in parse
    raise ValueError("Invalid field %r in leaf %r" % (left, str(leaf)))
ValueError: Invalid field 'layout_type' in leaf "<osv.ExtendedLeaf: ('layout_type', '=', 'article') on sale_order_line (ctx: )>"

**Comment by legalsylvain** [comment]
I'm not sure that your problem come from openUpgrade Process. Could you mention the list of the modules you're using. 
Regards.

**Comment by chdrsto** [comment]
Following modulse I use:
crm
mail
account_voucher
account_accountant
sale
stock
purchase
account
account_cancel
account_payment
account_report_company
analytic
auth_crypt
auth_signup
base
base_action_rule
base_calendar
base_iban
base_report_designer
base_setup
base_status
base_vat
board
date_in_so_line (-->I've adjusted this module to to run under V7.0 / but I get the same issue without this module)
decimal_precision
delivery
document
edi
email_template
fetchmail
knowledge
l10n_ch
l10n_multilang
process
procurement
product
resource
sale_crm
sale_journal
sale_order_dates
sale_quotation_number
sale_stock
share
stock_invoice_directly
warning
web
web_calendar
web_diagram
web_gantt
web_graph
web_kanban
web_tests
web_view_editor

**Comment by chdrsto** [comment]
![bildschirmfoto 2015-03-05 um 11 14 09](https://cloud.githubusercontent.com/assets/11310649/6502978/d567b8ba-c328-11e4-80fa-a638cd5ef3ec.png)
I just want to add the last row of the error message (which I miss somehow):

ValueError: Invalid field 'layout_type' in leaf '<osv.ExtendedLeaf: ('layout_type', '=', 'article') on sale_order_line (ctx: )>'

This column exists in the database with the values article

UPDATE : Ive attached the Screenshot of the Message. The Table entries of the fresh reference V7 Installation and my migrated. The only difference is that my table contains the column layout_type and the order of the columns are different between them. But even when I delete the column layout_type, ... the error is the same.

**Comment by chdrsto** [comment]
## Soved

The issue could be soved on the migrated system by deleting the domain value on table 
**<addr> ir_act_window**

**Comment by StefanRijnhart** [comment]
Thanks for the feedback. I see that the module 'sale_layout' causes this. This module is no longer supplied for 7.0 and up. The usual strategy of OpenUpgrade is not to deal with this during the migration. Users can uninstall deprecated manuals after the migration, optionally using the database_cleanup module to help them with that.

In this case, it breaks the migration so you should uninstall sale_layout ahead of the migration.

**Comment by manohar1231** [comment]
Iam getting ValueError: Invalid field 'parent_id.user_id' in leaf "<osv.ExtendedLeaf: ('parent_id.user_id', '=', 11) on project_project (ctx: )>". please help me out of this Issue as Iam new to ERP and Python code.

thanks in advance
Manohar

**Comment by pedrobaeza** [comment]
Remove the context that contains that expression on your action window

**Comment by manohar1231** [comment]
Thanks for responding Mr pedrobaeza, but there is no expression in my context field it is blank. can u eloborate the solution?

**Comment by pedrobaeza** [comment]
Well, the error is that, so you should dig a bit more then.

**Comment by manohar1231** [comment]
I have an Error saying Error 405 Not Allowed - nginx/1.10.1 when Iam trying to submit post form data in ubuntu 16.10, please someone help me out
