### ISSUE TITLE
OpenUpgrade 11.0 -> 12.0  -> 13.0

### ISSUE THREAD

**Issue by rajwrdhn** [OCA/OpenUpgrade#2494]
Impacted versions: 11.0, 12.0, 13.0

Current behavior: I had some self introduced columns in Odoo11 database for table "account_invoice" and I migrated it to Odoo13 via Odoo12. My self introduced fieldnames got migrated to "account_move" but the data did not migrate. 

What should i do? What is the reason for this? 

Expected behavior: All the database along with the fields and values should be migrated. 

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
You must create specific migration scripts in your custom code for that columns, using populated columns that binds old invoices and lines with moves and move lines.
