### ISSUE TITLE
pre_init_hook and post_init_hook not called: bug or feature?

### ISSUE THREAD

**Issue by rvalyi** [OCA/OpenUpgrade#2503]
**Impacted versions:** 12.0 but probably all other

**Steps to reproduce:**
migrate a module which as an pre_init_hook or post_init_hook declared in its `__manifest__.py`
In my case the module was https://github.com/OCA/l10n-brazil/tree/12.0/l10n_br_fiscal
and in v8 the module that was installed was l10n_br_account_product that was renamed to l10n_br_fiscal via a local patch in the apriori.py. So I'm not sure if the observed behavior is affected by the module rename or not.

**Current behavior:**
pre_init_hook and post_init_hook  are not called.

**Expected behavior:**
may be pre_init_hook and post_init_hook  should called. May be a warning should be dsiplayed (it may be missed though)

**So as a workaround:**
 in my local `l10n_br_fiscal/migrations/12.0.1.0/post-migration.py` I called the hook:
```
from openupgradelib import openupgrade
from odoo.addons.l10n_br_fiscal.hooks import post_init_hook


@openupgrade.migrate()
def migrate(env, version):
    post_init_hook(env.cr, None)
```

and I did a similar thing in the pre-migration script of l10n_br_account to call the l10n_br_account pre_init_hook this time.
It seems to work...

But I wonder is this a bug or a feature? May be we should document it?

cc @legalsylvain @renatonlima

**Comment by rvalyi** [comment]
cc @marcelsavegnago

**Comment by pedrobaeza** [comment]
They are other mechanism: installing a module is not the same as upgrading a module (in the migration context). Maybe you need to make the same thing on both operations, but if that's the case, then make the import and call from the migration script to the proper hook.

**Comment by rvalyi** [comment]
all right @pedrobaeza , that's what I did then.
However it took me some time to discover it was not called, so may be we could have a doc section about that.

**Comment by legalsylvain** [comment]
Hi @rvalyi.

>  However it took me some time to discover it was not called, so may be we could have a doc section about that.

``pre_init_hook`` and ``post_init_hook`` are fired only on install. (Ref : https://www.odoo.com/documentation/14.0/reference/module.html?highlight=pre_init_hook)
If you come from a previous version with the module installed, it is normal that the functions are not executed.
Not sure it should be documented, as it is the standard behaviour. don't you think ? 

(however if an openupgrade forces a module to be installed (by a new dependency), then the functions should be executed).

If a function has to be executed from an upgrade AND for an installation, I guess your workaround is correct.

kind regards.

**Comment by pedrobaeza** [comment]
Well, if you think as needed. Odoo documentation clearly states where the hooks are triggered, and that's don't include on upgrading the module (which is the process that is done on the migration). And as said, a lot of times, it's not the same thing what you have to do on upgrade than on install.

**Comment by pedrobaeza** [comment]
If a module is auto-installed by new dependencies, the hooks are executed.

**Comment by rvalyi** [comment]
> Hi @rvalyi.
> 
> > However it took me some time to discover it was not called, so may be we could have a doc section about that.
> 
> `pre_init_hook` and `post_init_hook` are fired only on install. (Ref : https://www.odoo.com/documentation/14.0/reference/module.html?highlight=pre_init_hook)
> If you come from a previous version with the module installed, it is normal that the functions are not executed.
> Not sure it should be documented, as it is the standard behaviour. don't you think ?
> 
> (however if an openupgrade forces a module to be installed (by a new dependency), then the functions should be executed).
> 
> If a function has to be executed from an upgrade AND for an installation, I guess your workaround is correct.
> 
> kind regards.

Hey @legalsylvain , I open the issue because you just told me on Twitter to do so...
As I said I wasn't shocked by the current behavior, but I assumed you might want to debate it... If not then that's fine.

**Comment by legalsylvain** [comment]
Hi @rvalyi. I asked you to open an issue because : 
- i didn't have the context. so It could be a bug or a feature, depending if the module was installed before. (bug or feature, the eternal question for Odoo ;-)) and Twitter is not the best place to talk about bug.
- if you wondered if ``pre_init_hook`` was executed during an Openupgrade, for sure others users will have the same question. so better to open an issue.
- 
regards.

**Comment by rvalyi** [comment]
@legalsylvain In fact in our case it's like if this module was totally rewritten, so in a sense yes despite being listed in the apriori renamed_modules key, it rather means where you had this old module before install this new module instead, and this is why I was surprised hooks were skipped.

But I agree today, from the renamed_modules OpenUpgrade cannot know that it's rather a module substitution instead of a pure upgrade. Should be have a new key in apriori.py for that kind of situation? All in all I guess it's not common enough to justify something special in apriori.py, may be just taking care in the pre/post-migration scripts as I did.

**Comment by pedrobaeza** [comment]
For me nothing should be modified. If you have such case of a total revamp from scratch, and need to call the same hook as installing it, then add the proper code in the migration script for version x.0.1.0.0, as that script will only be executed if you are doing such major version migration and with the renaming done. If not present before, then the install hook will run.

Complicating the keys structure and OpenUpgrade code for such case, and more having an easy solution (that is not a workaround, it's the proper solution), doesn't make sense.
