### ISSUE TITLE
crm / failed to upgrade due to model crm.partner.binding removed from v14

### ISSUE THREAD

**Issue by jcdrubay** [OCA/OpenUpgrade#2509]
# Impacted versions:

14.0

# Steps to reproduce:

Upgrade a database with crm module installed

# Current behavior:

Application error:

 ```
 2021-02-01 03:43:12,615 31579 ERROR ou_2 odoo.modules.registry: Failed to load registry
2021-02-01 03:43:12,615 31579 CRITICAL ou_2 odoo.service.server: Failed to initialize database `ou_2`.
Traceback (most recent call last):
  File "{project_dir}/odoo/odoo/service/server.py", line 1198, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "{project_dir}/odoo/odoo/modules/registry.py", line 89, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "{project_dir}/odoo/odoo/modules/loading.py", line 497, in load_modules
    env['ir.model.data']._process_end(processed_modules)
  File "{project_dir}/addons/OpenUpgrade/openupgrade_framework/odoo_patch/odoo/addons/base/models/ir_model.py", line 52, in _process_end
    return IrModelData._process_end._original_method(self, modules)
  File "{project_dir}/odoo/odoo/addons/base/models/ir_model.py", line 2237, in _process_end
    record.unlink()
  File "{project_dir}/odoo/odoo/addons/base/models/ir_model.py", line 1357, in unlink
    self._process_ondelete()
  File "{project_dir}/odoo/odoo/addons/base/models/ir_model.py", line 1372, in _process_ondelete
    Model = self.env[selection.field_id.model]
  File "{project_dir}/odoo/odoo/api.py", line 473, in __getitem__
    return self.registry[model_name]._browse(self, (), ())
  File "{project_dir}/odoo/odoo/modules/registry.py", line 177, in __getitem__
    return self.models[model_name]
KeyError: 'crm.partner.binding'
```

Expected behavior:

No Exception

# Workaround

I deleted manually from database and it seems to work

```
delete from ir_model where model='crm.partner.binding';
delete from ir_model where model='base.automation.lead.test';
```

**Comment by gdgellatly** [comment]
@jcdrubay You do know the v14 migration scripts aren't written yet? If you are trying to migrate a module, best write the script for it first and make a PR rather than raising issues that a module without a script doesn't work.

**Comment by jcdrubay** [comment]
@gdgellatly hi, I am aware that the v14 migration isn't ready yet for CRM.

With each issue I reported, I provided a workaround in the hope to help anyone who could be working on the v14 migration script. Maybe I could add a prefix `[analysis]` to the issue title if this could clarify.

I am quite new to OpenUpgrade and even if I could make it work successfully, it will take me a little while to be able to contribute PR. I will try to follow a recommendation to review some existing PR so I can learn more on how to solve different situations.

If you think this is creating more noise than help, please feel free to close the issue.

**Comment by gdgellatly** [comment]
@jcdrubay Honestly IMO it is more noise than help. We already do automated analysis and those files get worked through. Nothing you are reporting isn't in those files and it is hugely unlikely anyone will be looking through these issues lists. Also the workarounds are in no way how it would be done. The underlying openupgradelib has methods for all sorts of migration cases including model removal.

The hard parts in migration are when there are significant changes and they require complicated scripts. The parts you are discussing are almost candidates for automatic script generation, just standard easy things. 

As for the advice on reviewing PR's, it is good advice, but generally I find it easier to learn by doing. Once you know the openupgradelib methods, and look at a few previous examples of merged scripts *most* module migrations where the module has undergone minimal change are very easy.

**Comment by pedrobaeza** [comment]
Yes, closing by the reason exposed by Graeme. Thanks anyway for the effort.
