### ISSUE TITLE
[14.0] crm / Invalid primary phone field on model crm.lead

### ISSUE THREAD

**Issue by jcdrubay** [OCA/OpenUpgrade#2510]
# Impacted versions:

14.0

# Steps to reproduce:

Upgrade a database with the CRM module installed

# Current behavior:

I get an application error:

```
   File "{project_dir}/odoo/odoo/modules/loading.py", line 451, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check)
  File "{project_dir}/odoo/odoo/modules/loading.py", line 348, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "{project_dir}/odoo/odoo/modules/loading.py", line 198, in load_module_graph
    registry.init_models(cr, model_names, {'module': package.name}, new_install)
  File "{project_dir}/odoo/odoo/modules/registry.py", line 416, in init_models
    env['base'].flush()
  File "{project_dir}/odoo/odoo/models.py", line 5434, in flush
    self.recompute()
  File "{project_dir}/odoo/odoo/models.py", line 5893, in recompute
    process(field)
  File "{project_dir}/odoo/odoo/models.py", line 5877, in process
    field.recompute(recs)
  File "{project_dir}/odoo/odoo/fields.py", line 1120, in recompute
    self.compute_value(recs)
  File "{project_dir}/odoo/odoo/fields.py", line 1142, in compute_value
    records._compute_field_value(self)
  File "{project_dir}/odoo/addons/mail/models/mail_thread.py", line 412, in _compute_field_value
    return super()._compute_field_value(field)
  File "{project_dir}/odoo/odoo/models.py", line 4059, in _compute_field_value
    getattr(self, field.compute)()
  File "{project_dir}/odoo/addons/phone_validation/models/mail_thread_phone.py", line 48, in _compute_phone_sanitized
    self._assert_phone_field()
  File "{project_dir}/odoo/addons/phone_validation/models/mail_thread_phone.py", line 114, in _assert_phone_field
    raise UserError(_('Invalid primary phone field on model %s', self._name))
odoo.exceptions.UserError: Invalid primary phone field on model crm.lead
```

# Expected behavior:

No application error

# Workaround

It seems that I can pass this step

## ...When commenting these few lines of code from the native odoo code (addons/phone_validation/models/mail_thread_phone.py)

```
    def _assert_phone_field(self):
        # if not hasattr(self, "_phone_get_number_fields"):
        #     raise UserError(_('Invalid primary phone field on model %s', self._name))
        # if not any(fname in self and self._fields[fname].type == 'char' for fname in self._phone_get_number_fields()):
        #     raise UserError(_('Invalid primary phone field on model %s', self._name))
        pass
```

## ... and adding the `sanitized=""` in:

```
    @api.depends(lambda self: self._phone_get_number_fields())
    def _compute_phone_sanitized(self):
        self._assert_phone_field()
        number_fields = self._phone_get_number_fields()
        for record in self:
            sanitized = ""
            for fname in number_fields:
                sanitized = record.phone_get_sanitized_number(number_fname=fname)
                if sanitized:
                    break
            record.phone_sanitized = sanitized
```

# Analysis

When debugging, it seems that `_phone_get_number_fields` returns an empty list which should not thanks to the modules `sms` and `crm_sms` (both modules being installed in my db):

from sms:

```
    def _phone_get_number_fields(self):
        """ Add fields coming from sms implementation. """
        sms_fields = self._sms_get_number_fields()
        res = super(PhoneMixin, self)._phone_get_number_fields()
        for fname in (f for f in res if f not in sms_fields):
            sms_fields.append(fname)
        return sms_fields
```

from crm_sms:

```
    def _sms_get_number_fields(self):
        """ This method returns the fields to use to find the number to use to
        send an SMS on a record. """
        return ['mobile', 'phone']
```

# Note

- After the step is passed thanks to the workaround, it is possible to revert the changes in the code of Odoo without facing the issue anymore.
- Could this be a possible explanation "The module `sms` being `auto_install =True`, the order of loading of the python files might be wrong" ?
- Maybe this could have been solved using the configuration option `force_deps` mentioned in `migration_details.rst` which is not deprecated anymore but obsolete for v14 (https://github.com/OCA/OpenUpgrade/pull/2495/files#r567574819).

**Comment by StefanRijnhart** [comment]
Thanks for all the analysis. Note that the modules for which you are filing issues are not covered by OpenUpgrade 14 yet, so as such I hope these issues will be solved once migration scripts are provided for those modules.

**Comment by jcdrubay** [comment]
Hi @StefanRijnhart , I understand.
From the documentation, I tried to imagine what kind of migration scripts would be needed but I could not guess.
I hope that someone with more than my current knowledge  (hopefully me later) will be able to provide the clean migration script in a PR.
I will keep learning about OpenUpgrade in coming weeks.
I am now launching the second upgrade of a project from v12 to v14 that includes accounting.
I am expecting to face a lot of difficulties but learn a lot more on the way ...

**Comment by JulianaPoudou** [comment]
Hello,

We face the same issue migrating our instance from v12.
Seems that this issue is not really closed, but not sure how to address it ?

Thanks for the workaround we will look into it.

@pedrobaeza how did you overcome that issue ?

Best Regards,
