### ISSUE TITLE
[14.0] Cleanup web assets

### ISSUE THREAD

**Issue by jcdrubay** [OCA/OpenUpgrade#2511]
# Impacted versions:

14.0

# Steps to reproduce:

migrate a database where web_diagram was installed (that module was removed from v14)

# Current behavior:

WUI does not load due to missing references to web_diagram js files ...

# Expected behavior:

See the full beauty of Odoo

# Workaround

Delete the web assets from db:

```
DELETE FROM ir_attachment WHERE store_fname SIMILAR TO '%.(js|css)';
DELETE FROM ir_attachment WHERE url LIKE '/web/content/%';
DELETE FROM ir_attachment WHERE url LIKE '/web_diagram/static/%';
delete from ir_ui_view where arch_db ilike('%web_diagram%')
```

then upgrade all again

**Comment by olivierb2** [comment]
+1

**Comment by pedrobaeza** [comment]
There's still no work done on that module, so when the scripts are developed, please re check your case. Meanwhile, closing.

**Comment by nmkpedroporras** [comment]
Hello, is there another way to do this?

**Comment by HebaKM** [comment]
Hi, I'm facing the same issue, is there any update on this?

**Comment by pedrobaeza** [comment]
Right now, there shouldn't be any problem with such module, as now it's merge in `web` module, so your problem should seem similar, but cause by other root cause. Probably a missing module in your deployment, or something not correctly cleanup.

**Comment by HebaKM** [comment]
@pedrobaeza Thank you for your response. It seams the end-migration script was not executed, the upgrade process had no errors and the pre and post scripts were executed successfully. Is there any step I might be missing here?

**Comment by pedrobaeza** [comment]
You can't resume the migration. It should be performed at once.

**Comment by HebaKM** [comment]
@pedrobaeza thank you, I have tried the migration in a new restored DB, it is fine now.
