### ISSUE TITLE
[14.0] DB Migration already possible?

### ISSUE THREAD

**Issue by treylade** [OCA/OpenUpgrade#2527]
Impacted versions:

13.0 > 14.0

Steps to reproduce:

I want to do a DB migration for modules 'base' and 'hr'.

Current behavior:

- 14.0 Branch for OpenUpgrade repo is existing
- Can't find readme or hints how to do a DB migration from 13 to 14 using this repo

Expected behavior:

Video/Screenshot link (optional):

**Comment by legalsylvain** [comment]
Hi.
regarding the documentation, there is a single setting to do. it is explained here : 
https://github.com/OCA/OpenUpgrade/tree/14.0/openupgrade_framework#id2

``base`` module is covered.
``hr`` module is not.

Can you review this PR ? it is updating the website documentation.
https://github.com/OCA/OpenUpgrade/pull/2495

thanks.
