### ISSUE TITLE
Problem with migration of module "warning" 

### ISSUE THREAD

**Issue by thomaspaulb** [OCA/OpenUpgrade#253]
One of the migrations, possibly Odoo 8 itself, adds a product called "Service" to the product_product table during OpenUpgrade procedure.

The product_product table also contains the _purchase_line_warn_ column, I believe this is a helper column used in migration that is removed later? It is filled for the products that existed before but for the new "Service" product this column is NULL.

In **warning/migrations/8.0.1.0/post-migration.py**, the line

```
openupgrade.move_field_m2o(
    cr, pool,
    'product.product', 'purchase_line_warn', 'product_tmpl_id',
    'product.template', 'purchase_line_warn')
```

calls query

```
UPDATE product_template as new_table SET purchase_line_warn=(    SELECT old_table.purchase_line_warn    FROM product_product as old_table    WHERE old_table.product_tmpl_id=new_table.id    LIMIT 1)  WHERE id in ( .....list of ids....)
```

which then breaks on the "Service" product:

```
IntegrityError: null value in column "purchase_line_warn" violates not-null constraint
DETAIL:  Failing row contains (1719, 1, 2015-03-11 15:55:47.484275, 2015-03-11 15:55:47.484275, 1, 0, null, 75.00, null, 0.00, 0.00, fixed, 5, null, 1, Service, 1.00, 0, f, null, null, 4, null, null, 5, f, service, null, null, null, null, null, null, null, 0, null, null, t, null, null, null, null, null, null, null, null, null, no-message).
```

I think that somehow the `move_field_m2o` command should skip any lines that were not in the table when the (full) upgrade procedure started. One way could be copying the table before the upgrade; another way could be skipping lines that have purchase_line_warn is null. But this is me saying, with little OpenUpgrade experience - how could I best go about solving this?

**Comment by pedrobaeza** [comment]
Hi, Tom, thanks for reporting.

I think this is an inconsistency in your DB, because "purchase_line_warn" field is required in both v7 and v8, although maybe something in the migration breaks this logic.

You can use `set_defaults` OpenUpgrade API method to set a default value on all product.product columns before calling `move_field_m2o` as a workaround solution.

**Comment by thomaspaulb** [comment]
Hi, thanks for the workaround, I will try it. 

I wonder why, when the Service product is added during migration, it does not fill the purchase_line_warn column. But for that I'd need to know which module adds it and how.

**Comment by pedrobaeza** [comment]
It is added by product module: https://github.com/odoo/odoo/blob/8.0/addons/product/product_data.xml#L248
