### ISSUE TITLE
[12.0 -> 13.0]

### ISSUE THREAD

**Issue by gloobal-net** [OCA/OpenUpgrade#2530]
Hi guys!...i'm getting this issue when i try to migrate, any idea?. Thanks so much!

psycopg2.IntegrityError: duplicate key value violates unique constraint "ir_translation_model_unique"
DETAIL:  Key (type, lang, name, res_id)=(model, es_AR, ir.module.category,name, 123) already exists.

**Comment by legalsylvain** [comment]
No idea. could you provide the xml_id of the ``ir.module.category`` #123 ?

**Comment by gloobal-net** [comment]
Hi @legalsylvain, thanks for replying, i simply solved the problem deleting duplicated ir.translation record, it correspond to Timesheets module category..maybe some spurious data. Deleting it, the migration process went on good! Thanks so much!
