### ISSUE TITLE
[6.1 -> 7.0] mailgate fkey leftover

### ISSUE THREAD

**Issue by bwrsandman** [OCA/OpenUpgrade#254]
I'm inspecting a database that was migrated from 6.1 to 7.0.

The problem manifests as a error while adding a file in the chattr which has an attachment and output this very unhelpful message:

> Integrity Error
> 
> The operation cannot be completed, probably due to the following:
> - deletion: you may be trying to delete a record while other records still reference it
> - creation/update: a mandatory field is not correctly set
> 
> [object with reference: mailgate_message - mailgate.message] 

Inspecting the logs we have something much more useful:

```
openerp.sql_db: bad query: insert into message_attachment_rel (message_id,attachment_id) values (92443,2655)
Traceback (most recent call last):
  File "openerp/sql_db.py", line 226, in execute
    res = self._obj.execute(query, params)
IntegrityError: insert or update on table "message_attachment_rel" violates foreign key constraint "message_attachment_rel_message_id_fkey" 
DETAIL:  Key (message_id)=(92443) is not present in table "mailgate_message".
```

Inspecting the database of a fresh 7.0 install, the `mailgate_message` table doesn't exist.
The foreign key `message_attachment_rel_message_id_fkey` points to the `mail_message` table.

Therefore, I suspect that the mail migration script fails to remove the `mailgate_message` table and replace all references to it with `mail_message`.

This might already be resolved, but I am positing it here in case it's not and others are having this issue.

**Comment by hbrunn** [comment]
To my knowledge, mailgate_\* is 6.0, right? https://github.com/OpenUpgrade/OpenUpgrade/blob/6.1/addons/mail/migrations/6.1.1.0/pre-migration.py#L40 renames this table, so it shouldn't exist any more.

Did you run https://github.com/OCA/server-tools/tree/8.0/database_cleanup on the database afterwards?

**Comment by bwrsandman** [comment]
If this is from 6.0, then this is a problem specific to another migration and is unique to our case. 
Thank you for clearing this up.

We did not run database_cleanup.
