### ISSUE TITLE
[13.0] calendar / calendar.alarm wrong data migration 

### ISSUE THREAD

**Issue by bishalgit** [OCA/OpenUpgrade#2548]
Impacted versions: 13.0

Steps to reproduce:
- Create database in version 12
- Install calendar module
- Check Technical > Calendar > Calendar Alarm
- Take backup of your database and migrate database to version 13.0
- Now check Technical > Calendar > Calendar Alarm

Current behavior: calendar.alarm is not migrated properly. Type for all alarm set been set to Email.

Expected behavior: After migration 'emal' and 'notification' type should be properly mapped.

Video/Screenshot link (optional):
Data in 12
![image](https://user-images.githubusercontent.com/7806952/107559643-77c4fe80-6c04-11eb-902e-7200169ca9f8.png)

Data in 13
![image](https://user-images.githubusercontent.com/7806952/107559706-890e0b00-6c04-11eb-88a2-7006ee557616.png)

**Comment by bishalgit** [comment]
@MiquelRForgeFlow #2265 Is this migration correct? Because I am writing migration scripts for calendar_sms and it depends on calendar but I got weird migration for calendar.alarm. Can you verify it?

**Comment by pedrobaeza** [comment]
@MiquelRForgeFlow did you check this?

**Comment by MiquelRForgeFlow** [comment]
Sorry, not yet, I forgot.

**Comment by MiquelRForgeFlow** [comment]
I will check now.

**Comment by MiquelRForgeFlow** [comment]
Fixed in https://github.com/OCA/OpenUpgrade/pull/3250.
