### ISSUE TITLE
Odoo CE 13 to CE 14

### ISSUE THREAD

**Issue by vmelnych** [OCA/OpenUpgrade#2590]
Impacted versions: CE 13.0

I am a newbie, trying this framework first time ever. I want to upgrade just two modules: `Employees` and `Time Off`. Went through all possible links, and I am getting desperate - have absolutely no clarity which steps and in which order I should take to upgrade smoothly. There are lots of statements for the experts, but no procedure for newbies (`https://doc.therp.nl/openupgrade/intro.html`). 

Questions:
1. I have installed a nightly R13.0 on my Ubuntu and restored a database from production - all works. What should I do to activate this upgrade process? I tried to copy to the `addons` folder and install two modules (`Openupgrade Framework` and `OpenUpgrade Records`) from the OpenUpgrade branch 14.0, but I get error messages: `AttributeError: type object 'View' has no attribute 'handle_view_error'`
2. Should I pull and launch the `odoo-bin` from the OpenUpgrade branch 13.0 or from the original Odoo nightly build?
3. Where do I put those `–update all` flags?

Please, help! I am willing to contribute by bringing changes to the manual, if someone explains to me the upgrade process.
Thanks!

**Comment by pedrobaeza** [comment]
OpenUpgrade v14 is far from being complete, and the process and documentation for it is on progress. #2495 added a bit, but as said, you can't migrate yet.
