### ISSUE TITLE
[13.0] POS / Inventory issue with picking after upgrade

### ISSUE THREAD

**Issue by E-HO** [OCA/OpenUpgrade#2597]
Impacted versions: 13.0

Steps to reproduce: Migrate a db from v12 with POS / Stock (Inventory)

Current behavior: POS is not working anymore (sales are not saved), and modules upgrade fail

Hi,

After an upgrade from V12, encounter issues mainly with the existing POS :

- On POS GUI, error message : "_You must be connected to the internet to save your changes. Orders that where not synced before will be synced next time you close an order while connected to the internet or when you close the session._" and "_Something went wrong ! Reference must be unique per company!_" and no other action car be done like another sale, nor closing it.

- When trying to upgrade modules : "_Model: Point of Sale Configuration (pos.config), Constraint: pos_config_picking_type_id_fkey_"

- In logs : 
> odoo.sql_db: bad query: INSERT INTO "stock_picking" (..."name"...) VALUES (..."/"...)
> ERROR: duplicate key value violates unique constraint "stock_picking_name_uniq"
> DETAIL:  Key (name, company_id)=(/, 1) already exists.

Note that the error is that the name is no more a POS order name like "POS/2021/xyz" but just a unique "/".

Thanks,

**Comment by legalsylvain** [comment]
Hi. point_of_sale is not covered by Openupgrade project for the time being.
https://github.com/OCA/OpenUpgrade/blob/13.0/odoo/openupgrade/doc/source/modules120-130.rst
Feel free to propose a PR.

kind regards.
