### ISSUE TITLE
What to do with modules that are missing in 8?

### ISSUE THREAD

**Issue by thomaspaulb** [OCA/OpenUpgrade#260]
After migration, Odoo 8 cannot find certain modules that were installed before, simply because they don't seem to be part of Odoo anymore - either they are merged into other modules, or they have been dropped into the community.

Notably I am talking about,
base_status (seems to be merged with base)
account_report_company
process
stock_location
project_long_term (dropped into the community)

Now I find myself wondering what to do with the warnings that Odoo 8 gives about not being able to find them anymore. For project_long_term, I just deinstalled it before the migration, but I am not sure if I can also safely deinstall the others before migration without losing migration data.

Does anybody know what happened to each of the modules, and share how they handled them during migration?

**Comment by hbrunn** [comment]
run https://github.com/OCA/server-tools/tree/8.0/database_cleanup after a succesful migration
