### ISSUE TITLE
[RFC] Documentation: suggestions for doc of openupgradelib API methods (classify per category, highlight popular methods, define "cow")

### ISSUE THREAD

**Issue by jcdrubay** [OCA/OpenUpgrade#2603]
Following a past review of https://github.com/OCA/OpenUpgrade/pull/2495 and after gaining some experience in OpenUpgrade through testing, doing code review, here are some suggestions.

Hopefully this will help more than pollute, I have not been too successful so for in this repo :p

My feeling after few weeks is that it is really hard to get into OpenUpgrade.
It seems that several people would like to start contributing, but many just loose hope not knowing where to start.
For sure, all the work done so far is great and amazing.
But some efforts could probably be done on the onboarding as well.

In this page https://doc.therp.nl/openupgrade/API.html
We could have one title per category of methods
I believe that this would help people to find what they are looking for.
See a suggestion of categories per method below.

Also, we could highlight the most popular / most used methods which might help the onboarding of newcomers.
In the list of methods below, I marked some with the the hashtag `#popular`.
Maybe, these could be candidate for a "Quickstart"

It might be helpful if someone could add in the docstring of the methods `cow_templates_mark_if_equal_to_upstream` and `cow_templates_replicate_upstream` what `cow` means. I could not figure it out.

Suggestion of classification of the methods of the API:

Decorators

- logging  #popular
- migrate

Fields

- check_values_selection_field
- rename_fields  #popular
- warn_possible_dataloss
- set_defaults
- get_legacy_name
- m2o_to_x2m
- m2o_to_m2m
- float_to_integer
- map_values  #popular
- move_field_m2o
- convert_field_to_html
- date_to_datetime_tz
- rename_property
- add_fields
- update_module_moved_fields
- convert_to_company_dependent

Files (data and xml)

- load_data
- _get_existing_records

ir

- add_ir_model_fields
- disable_invalid_filters

Module

- update_module_names
- is_module_installed

Postgres

- allow_pgcodes
- rename_tables
- rename_columns
- remove_tables_fks
- drop_columns
- logged_query  #popular
- lift_constraints
- savepoint
- copy_columns

Translations

- copy_fields_multilang
- delete_record_translations
- update_field_multilang

Tools (Chunk, Message Logger

- message
- chunked

Website

- cow_templates_mark_if_equal_to_upstream
- cow_templates_replicate_upstream

Workflows

- update_workflow_workitems
- delete_model_workflow
- deactivate_workflow_transitions
- reactivate_workflow_transitions
- Xml_ids and records
- rename_xmlids  #popular
- add_xmlid  #popular
- delete_records_safely_by_xml_id
- set_xml_ids_noupdate_value  #popular

**Comment by pedrobaeza** [comment]
Each method has a good enough IMO docstring, but it's true this is not dumped to the other documentation. The reason is that it's very costly to maintain both sources synchronized, and more being in 2 different projects. An automatic generation via sphynx will be the way to go.

About the "popular" tag, I don't think it's a good idea, as when you need something depending on the analysis file, it's the same that it's popular or not. It's what you need to migrate the data. Instead, my idea that I haven't been able to do yet is to put each of the possible things that you find in the analysis file, and explain what to do:
```
module      / model     / field (selection)    : now required

Do this and call openupgradleib method X
```
```

**Comment by legalsylvain** [comment]
>  explain what to do:

```
module      / model     / field (selection)    : now required

Do this and call openupgradleib method X

```
It could be a great addition, indeed !

**Comment by pedrobaeza** [comment]
Closing as stalled.
