### ISSUE TITLE
[RFC] Allow a step by step migration during Manual migration development process

### ISSUE THREAD

**Issue by jcdrubay** [OCA/OpenUpgrade#2605]
# Current behavior:

The manual migration described in https://doc.therp.nl/openupgrade/migration_details.html says:

> Expect to repeat the process several times as you encounter errors, clean up your data, and try again.

But running the execution of the `--update all` is quite long making the trial and error process really time consuming.

# Expected behavior:

Be able to run the upgrade restarting from an "intermediate" step just before the previous failure.

From the documentation

> There are three migration stages at which you can have migration scripts executed: before the module is loaded (`pre` stage), after the module is loaded into the database (`post` stage) and when all the modules are loaded (`end` stage). 

Ideally we should be able to run with the following options:

- `--update all`: run the full upgrade
- `--update account:post`: run the upgrade starting from the post stage of the module account, then run the `end` stage for all modules
- `--update account:end`: run the `end` stage for account module and all of the following modules

To be able to achieve this, we would also need to:

- [A] be able to know in which order OpenUpgrade would upgrade all the modules.
- [B] at the end of the successful execution of the upgrade of each module, commit the change in the database
- [C] each migration script must be executable multiple times without getting a different result then if it is executed only one time

This feature [B] should be activated if we are using the option `--dev openupgrade`.

**Comment by rvalyi** [comment]
Hello @jcdrubay there is probably room for improvement in this trial and error workflow as you say.
That being said I have been successful by trying `--update=all` first and then when it fails on a given module some_module, I try to fix the scripts and do a `--update=<some_module>`. I don't know if there is a better way but usually this enables me to fix the some_module scripts. After it is fixed however I go back to my dump and run with `--update=all` because just doing `--update=<some_module>` and letting dependent modules is likely to lead to parial and incomplete migration.

Another hint tro speed things up: I use a Porstgres conf with filesync=off for OpenUpgrade which gives a significant boost (at the cost of zero security with the durability of your data, that is never do that in production).

**Comment by legalsylvain** [comment]
Hi @jcdrubay. 

Regarding ``update account:post`` I don't see the interest. update are done automatically in the correct order. If it breaks during account, you can re-run your migration, and the still updated modules (like ``base``) will not be upgraded again. (just updated)
The only thing i'm not sure is regarding the ``end`` option. 
You can maybe check that PR is related. https://github.com/OCA/OpenUpgrade/pull/2499

kind regards.

**Comment by jcdrubay** [comment]
Thanks @rvalyi and @legalsylvain for your great and fast answers

I have tried to write a piece of documentation after reading your answers.
I think it could land in the page: https://doc.therp.nl/openupgrade/migration_details.html
I can create a PR if you think it's a good idea, then we can refine the content of the documentation in the PR.

# The Trial and error process for the development of your scripts

- [A] get the copy of your database in old version as `db-upgrade`, it easy to do through the database manager of your old odoo `http://localhost:8012/web/database/manager`
- [B] run `odoo -d db-upgrade -u all --stop-after-init`
In case of an error (when developing or debugging), with this fix you can
- [C] In case of error, fix the error (adding or editing migration scripts), then rerun **without** the `--upgrade all`: `odoo -d db-upgrade --stop-after-init`. This will continue the upgrade process from where it left off, starting with the module that caused the error. That way, the migration will not run the end-migration scripts of the modules that were already upgraded before the error, so in case of a live migration you always need to restore the database. But running this will help you save a lot of time in the upgrade process.

Note that for the time being [C] is not available in all versions (see explanations here: https://github.com/OCA/OpenUpgrade/pull/2499). It is available for 12 and 13: https://github.com/OCA/OpenUpgrade/pulls?q=is%3Apr+%5BFIX%5D+reset+exception

Whenever facing unexpected errors, you might want to restart from [A] as the step [C] might leave your database in an inconsistent state.

# Restart upgrade of the failed module instead of upgrading all systematically

_This is an alternative to the step [C] mentioned above_ 

Try `--update=all` first and then when it fails on a given module some_module, try to fix the scripts and do a `--update=<some_module>`

This enables fixing and testing the some_module scripts

After it is fixed go back to `--update=all` because just doing `--update=<some_module>` and letting dependent modules is likely to lead to partial and incomplete migration.

# `fsync = off` in your postgresql.conf

Use the Postgres configuration fsync=off for OpenUpgrade which gives a significant boost (at the cost of zero security with the durability of your data, that is never do that in production).

The config file can be found in `/etc/postgresql/13/main/postgresql.conf` in Linux and `~/Library/Application\ Support/Postgres/var-*/postgresql.conf`for iOS.

Read more about fsync config: https://www.postgresql.org/docs/current/runtime-config-wal.html

**Comment by legalsylvain** [comment]
Hi @jcdrubay,

What you wrote makes sense. I think it deserves a PR. For the time being the doc has been written by main OpenUpgrade maintainers / developpers. but : 
- it take times to write and maintain the doc
- the documentation is very synthetic and may not be adequate for people who have less deep technical knowledge of Odoo / OpenUpgrade. 

So I think that it's a great addition if others people write / complete current documentation.

Thanks also @rvalyi for the ``fsync`` tips.

**Comment by jcdrubay** [comment]
Here is the PR: https://github.com/OCA/OpenUpgrade/pull/2606

**Comment by StefanRijnhart** [comment]
We have had [B] for a long time, and in recent versions, Odoo supports it natively.

**Comment by pedrobaeza** [comment]
Let's close this as handled.
