### ISSUE TITLE
[DOC] move the "contents of the migration directory" from analysis to development 

### ISSUE THREAD

**Issue by jcdrubay** [OCA/OpenUpgrade#2623]
Should we move this section to development?

Contents
--------

The contents of the migration directory per module are:

* A file `openupgrade_analysis.txt` that contains data model changes and
  changes in the set of XML records
* A file `openupgrade_analysis_work.txt` which is a copy of the previous file,
  annotated by the developers of the migration scripts
* A file `noupdate_changes.xml` containing changes that may need to be loaded
  during module migration (after reviewing the contents of this automatically
  generated file).
* A file `pre-migration.py` (or any Python file(s) starting with `pre-`) that
  is executed by the Odoo migration manager just before the module is loaded.
* A file `post-migration.py` (or any Python file(s) starting with `post-`) that
  is executed by the Odoo migration manager right after the module was loaded.
* A file `end-migration.py` (or any Python file(s) starting with `end-`) that
  is executed by the Odoo migration manager when all modules have been
  processed.

The migration directory of the base module contains an additional file
`openupgrade_general_log.txt`. This file contains some statistics as well
as the analysis records of modules that could not be found in the target
release of Odoo anymore.

**Comment by pedrobaeza** [comment]
Closing as stalled.
