### ISSUE TITLE
Add a link to the OpenUpgrade documentation in the README

### ISSUE THREAD

**Issue by jcdrubay** [OCA/OpenUpgrade#2630]
Impacted versions: 14.0

Steps to reproduce:
Open the README
https://github.com/OCA/OpenUpgrade/tree/14.0

Expected behavior:

I think it will depend on where the documentation will be be depending on the result of the discussions in https://github.com/OCA/OpenUpgrade/issues/2479
But maybe, a temporary link should still be added to https://doc.therp.nl/openupgrade/ .

**Comment by legalsylvain** [comment]
:+1: Feel free to make a PR !

i think that a small text summarizing what is openupgrade, and adding main links could be great.
- https://doc.therp.nl/openupgrade/ .
- coverage [page](https://github.com/OCA/OpenUpgrade/blob/14.0/doc/source/modules130-140.rst)
- ...

**Comment by pedrobaeza** [comment]
You can check 13.0 README as reference and recover the logo.

**Comment by jcdrubay** [comment]
Ok, I ll do that :)

**Comment by jcdrubay** [comment]
Done : https://github.com/OCA/OpenUpgrade/pull/2636
