### ISSUE TITLE
standard_price moved from product.product to product.template in v8

### ISSUE THREAD

**Issue by cod3monk** [OCA/OpenUpgrade#264]
could this be handled by openupgrade directly or do I need to handle this on my own? currently all standard_price fields in product.template are set to zero and deleted in product.product after upgrade from 7.0 to 8.0

**Comment by pedrobaeza** [comment]
Yes, this must be handled by OpenUpgrade itself, but this is in theory already covered in the product migration:

https://github.com/OpenUpgrade/OpenUpgrade/blob/8.0/addons/product/migrations/8.0.1.1/post-migration.py#L62

And there is already an improvement as a PR from @legalsylvain : https://github.com/OpenUpgrade/OpenUpgrade/pull/249

Are you sure you don't have any custom modules that modifies the behaviour of the field?

**Comment by legalsylvain** [comment]
Hi, 
I don't have this problem. standard price properties are created correctly. Did you try with a clean database ?

**Comment by cod3monk** [comment]
ok, after further investigation it looks actually a little different: in the new db the standard_price column completly disappeared from the database and is now set in ir_property. In the old data the standard_price column was located in product_template (unlike I said in my first post). None of the standard_price values were moved to the new db.

I cant find any module modifying the standard_price field. Is there a sure way to find out?

**Comment by StefanRijnhart** [comment]
For the record, this is handled here: https://github.com/OCA/OpenUpgrade/blob/8.0/addons/product/migrations/8.0.1.1/post-migration.py#L58. The fact that this was not succesfully carried out on your database could be a symptom of another problem, or it was not merged completely at the time. Sorry missing your issue at the time. Closing this for now.
