### ISSUE TITLE
Fixed asset depreciation run VS posting period in Odoo Version14

### ISSUE THREAD

**Issue by Donzhangqd** [OCA/OpenUpgrade#2642]
Impacted versions: Version 14

Steps to reproduce: run fixed asset depreciation at month end

Current behavior: 
I have heard that ,due to function module upgrade ,system will create 'depreciation document draft ' for all the periods of the asset lift cycle in Odoo Version 14, we have to create all the finance posting periods in advance (eg: Fixed asset A with 20 years depreciation life cycle, we need to create 240 = 20 X 12 posting periods ), otherwise ,we can't do fixed asset transaction in the system.

I would like to confirm it , is it the real case?  What's the actual scenario?  Can anybody help on this case? Any input is appreciated, thanks.

 
Expected behavior: clarify the new function of fixed asset module (Odoo version 14)

Video/Screenshot link (optional):

Thanks again.

**Comment by pedrobaeza** [comment]
Incorrect repository and issue trackers are not for this.
