### ISSUE TITLE
[Question] Migration from odoo v9 to odoo v10 country table changed

### ISSUE THREAD

**Issue by carlosecv** [OCA/OpenUpgrade#2647]
Im trying to do my first migration from odoo v9 to odoo v10, so i have custom module on version 9 has custom gpc_country_id field that is related to country table on sale_order so how do i tell my module that country table has being changed to other table on ver 10?

This gives me the try of upgrade from version 9 to 10

IntegrityError: update or delete on table "res_country" violates foreign key constraint "sale_order_gpc_country_id_fkey" on table "sale_order"
DETAIL: Key (id)=(265) is still referenced from table "sale_order".

I apologize if this is not the correct project or way to ask this but on OpenUpgrade there is no Discussion forum where to do this kind of basic questions.

**Comment by pedrobaeza** [comment]
Such table is not something of OpenUpgrade itself, but a custom module, so it doesn't belong here.
