### ISSUE TITLE
[13.0] Module portal - cannot be located in parent view

### ISSUE THREAD

**Issue by estraka** [OCA/OpenUpgrade#2677]
Impacted versions: 12.0 --> 13.0

I have a crash when I try to upgrade from odoo v12.0 to v13.0.
According to the log, the error is in the portal module, which according to the openupgrade status is DONE. I have tried to investigate, and I do not discover why it fails, since the views of V13, if they have the parent elements ...

As a consequence of the error, the website does not show the upper menu bar to access the backend functions and menu of public web.

I don't know if the problem is because the website (OCA project) module is not migrated. Are the scripts being worked on?
If so, the PORTAL module should have a dependency tag, right?

My LOG: 

`2021-04-26 10:56:29,499 1 INFO Desa odoo.addons.base.models.ir_ui_view: Element '<t name="Main Frontend Layout" t-name="portal.frontend_layout">' cannot be located in parent view

Contexto del error:
Vista `Main Frontend Layout`
[view_id: 2621, xml_id: n/a, model: n/a, parent_id: 3136] 
2021-04-26 10:56:29,503 1 INFO Desa odoo.addons.base.models.ir_ui_view: Element '<xpath expr="//ul[@id='top_menu']">' cannot be located in parent view

Contexto del error:
Vista `Show Sign In`
[view_id: 2622, xml_id: n/a, model: n/a, parent_id: 2621] 
2021-04-26 10:56:29,701 1 INFO Desa odoo.addons.base.models.ir_ui_view: Element '<t name="Main Frontend Layout" t-name="portal.frontend_layout">' cannot be located in parent view

Contexto del error:
Vista `Main Frontend Layout`
[view_id: 2621, xml_id: n/a, model: n/a, parent_id: 3136] 
2021-04-26 10:56:29,705 1 INFO Desa odoo.addons.base.models.ir_ui_view: Element '<xpath expr="//a[@id='o_logout']">' cannot be located in parent view

Contexto del error:
Vista `Link to frontend portal`
[view_id: 2623, xml_id: n/a, model: n/a, parent_id: 2621] 
`

If you guide me I will be happy to collaborate in the work.

Regards, and thank you very much.

**Comment by pedrobaeza** [comment]
That errors are normal and they are not aborting the migration process, so you must ignore them.

**Comment by estraka** [comment]
OK. The problem is that the migration is "incomplete" because the web cannot be used, as it has neither the public web menu nor the backend menu and I interpreted that it would be some error in the scripts.

**Comment by estraka** [comment]
> That errors are normal and they are not aborting the migration process, so you must ignore them.

OK. The problem is that the migration is "incomplete" because the web cannot be used, as it has neither the public web menu nor the backend menu and I interpreted that it would be some error in the scripts.

**Comment by pedrobaeza** [comment]
You have to assure all modules have their counter-part in the new version, or uninstall them.

**Comment by estraka** [comment]
Thank you. As you never doubted that the scripts were correct, I continued my investigation on the other hand, and I have detected that my ir.ui.view table is inconsistent, it has many duplicate records ...perhaps due to previous migrations and my inexperience. I am going to find a way to fix it. I am considering deleting it entirely with type = qweb filter, even if I lose some websites created, do you think it could have any greater implication? I see that when doing update, all the entries are recreated ... less clearly the ones that are customized through the web host.

Thanks again.

I take this opportunity to congratulate @pedrobaeza  for their great work in odoo.

**Comment by pedrobaeza** [comment]
Thanks for the compliments. I think it's better to just remove the offending views once migrated, for avoiding other side effects.
