### ISSUE TITLE
Error message - Migrate v7 to v8 

### ISSUE THREAD

**Issue by fred0716** [OCA/OpenUpgrade#268]
python migrate.py --config=/etc/openerp/openerp-server.conf --database=MYDB --run-migrations=8.0
....

copying database MYDB to MYDB_migrated...
Copying the database using 'with template'
Failed, fallback on creating empty database + loading a dump
running migration for 8.0
/usr/lib/python2.7/dist-packages/babel/**init**.py:33: UserWarning: Module openerp was already imported from /var/tmp/openupgrade/8.0/server/openerp/**init**.pyc, but /usr/lib/python2.7/dist-packages is being added to sys.path
  from pkg_resources import get_distribution, ResolutionError
Running as user 'root' is a security risk, aborting.

How to fix the problem?

**Comment by pedrobaeza** [comment]
The message is clear. Don't run as root. Use another user with enough privileges. Typically, openerp, erp or odoo (that you need to create in your install process).
