### ISSUE TITLE
Superfluous updates during mail migration

### ISSUE THREAD

**Issue by dhmetros** [OCA/OpenUpgrade#270]
In `OpenUpgrade/addons/mail/migrations/8.0.1.0/post-migration.py`, the following leads to a rediculous amount of updates:

```
 31     """
 32     The following fields have been moved from mail.mail to mail.message
 33       * mail_server_id
 34       * reply_to
 35     Get the mail.message from the mail.mail object and transfer the data that
 36     way.
 37     """
 38     legacy_server_id = openupgrade.get_legacy_name('mail_server_id')
 39     legacy_reply_to = openupgrade.get_legacy_name('reply_to')
 40     openupgrade.logged_query(cr, """
 41 UPDATE mail_message
 42 SET %s = %s, %s = %s
 43 FROM mail_message AS a JOIN mail_mail AS b ON a.id = b.mail_message_id
 44 """ % ('mail_server_id', legacy_server_id, 'reply_to', legacy_reply_to, ))
```

Many of the `mail_message` rows could be without a `mail_mail` row.  Instead, this updates _all_ `mail_message` rows regardless of how many `mail_mail` rows you have.  In our testing, it's extremely slow.  I could swear it tries to update each `mail_message` for each `mail_mail` row.  (`m*n` update operations when it should be only doing `n` operations)  It's that slow.

Perhaps this is more what the author had in mind? (Note line `41` & `43`)

```
 31     """
 32     The following fields have been moved from mail.mail to mail.message
 33       * mail_server_id
 34       * reply_to
 35     Get the mail.message from the mail.mail object and transfer the data that
 36     way.
 37     """
 38     legacy_server_id = openupgrade.get_legacy_name('mail_server_id')
 39     legacy_reply_to = openupgrade.get_legacy_name('reply_to')
 40     openupgrade.logged_query(cr, """
 41 UPDATE mail_message AS c
 42 SET %s = %s, %s = %s
 43 FROM mail_message AS a JOIN mail_mail AS b ON a.id = b.mail_message_id where a.id = c.id
 44 """ % ('mail_server_id', legacy_server_id, 'reply_to', legacy_reply_to, ))
```

**Comment by legalsylvain** [comment]
Agree. This process is very slow. Could you provide a PR ?

**Comment by pedrobaeza** [comment]
I think the correct syntax for this is:

```
UPDATE a
SET %s = %s, %s = %s
FROM mail_message a
INNER JOIN mail_mail b
ON a.id = b.mail_message_id
```

Simpler, easily readable, and crossing only two tables (not 3, one of them the same).

**Comment by dhmetros** [comment]
@pedrobaeza I tried that in our environment and got: `ERROR:  relation "a" does not exist`.  We're running on postgresql 9.3.6 if that makes any difference.

**Comment by pedrobaeza** [comment]
Try then:

```
UPDATE mail_message a
SET %s = %s, %s = %s
FROM mail_message
INNER JOIN mail_mail b
ON a.id = b.mail_message_id
```

**Comment by pedrobaeza** [comment]
@dhmetros Did you try to provide us feedback?

**Comment by dhmetros** [comment]
@pedrobaeza 

Sorry.  In-house, we moved on from this since the first query I mentioned worked fine.

That last query you mentioned returns:

```
ERROR:  invalid reference to FROM-clause entry for table "a"
LINE 1: ... a.id from mail_message inner join mail_mail b on a.id = b.m...
                                                         ^
HINT:  There is an entry for table "a", but it cannot be referenced from this part of the query.
```

I actually came across the right syntax a while back while working on something else, but I haven't tested to see whether it is any faster.  It may make the statement's intentions a little clearer, though.

Example:

```
update mail_message a
set id = a.id
from mail_mail b
where a.id = b.mail_message_id;
```

(The `set` section can reference anything from a or b.)
