### ISSUE TITLE
Pricelists company_id not set

### ISSUE THREAD

**Issue by BartvandenHout** [OCA/OpenUpgrade#2709]
Impacted versions: 12 > 13

Steps to reproduce:

Current behavior: company_id = False

Expected behavior: company_id = default res.company

Video/Screenshot link (optional): When adding a pricelist to a product an error occures

![Schermafbeelding 2021-05-07 om 10 41 18](https://user-images.githubusercontent.com/69815812/117423259-d1497a80-af20-11eb-866c-b5c9b88e8b9a.png)

**Comment by pedrobaeza** [comment]
Fixed with 3ea78dbbc5923a324f2da5a80f9aa19c7ad7054d
