### ISSUE TITLE
Obsolete tables/columns to be always ammended with "_legacy" ?

### ISSUE THREAD

**Issue by LoisRForgeFlow** [OCA/OpenUpgrade#2718]
When someone external to Odoo work with an odoo database, say a BI engine like PowerBI, it is useful that obsolete tables do not keep silently working, I think that renaming then always will raise error to those external developers and help to find error earlier.

My obvious use case is the `account_invoice` table, which is kept after migrating to v13 with the same name. Why don't wee keep it as `account_invoice_legacy`?

Opinoins?

cc @pedrobaeza @MiquelRForgeFlow

**Comment by pedrobaeza** [comment]
For me it's a totally no. It means a lot of manual work + no real gain on Odoo itself. Using a external access is against the integration philosophy of Odoo, and if you use it, then you should be aware of these changes and act accordingly.

**Comment by legalsylvain** [comment]
Hi @LoisRForgeFlow. Agree with @pedrobaeza regarding that topic. If you have obsolete table, the good way is to use ``database_cleanup`` to remove them.

**Comment by LoisRForgeFlow** [comment]
If you don't see any easy way to automate it and it would involve a lot of manual work, I can understand your position. The value added is low. I won't give this much more battle.

Thanks for your quick answers!

**Comment by pedrobaeza** [comment]
Yeah, but an immediate round of `database_cleanup` after migrating as suggested by Sylvain will give you the same result: obsolete things will be reported as error in the external tool, so I think it's a good solution.

**Comment by LoisRForgeFlow** [comment]
I understand, but for big databases most of the times `database_cleanup` does not work, or at least that has been my experience. I will take the time to review the queries of the BI guys and point errors, I would have to do it anyway for the ones that would raise an error with "_legacy renaming", so it is just a bit more of work.

**Comment by pedrobaeza** [comment]
Then you have to check why it doesn't work, and report the problem for that module. I think you are trying to get bad workarounds instead of focusing on working on the best solution.
