### ISSUE TITLE
Problem with stock upgrade

### ISSUE THREAD

**Issue by aliencrash** [OCA/OpenUpgrade#272]
After making a upgrade, update=all cannot update stock module and purchase. The first problem is related with the stock journal, that already exists. After removing the stock journal, the next problem is with stock orderpoint sequence, this is solved by removing it. Then when you run again the update, it cannot find stock_picking_in xml id. This issue is due to the fact that in table ir_model_data the stock_picking_in, stock_picking_out  have 0 in res_id.  Also the stock_picking_type is completely empty.

All this issue is because the purchase module, need to install stock_account. running upgrade to stock module also doesn't help.

**Comment by pedrobaeza** [comment]
stock_account migration is not yet covered by OpenUpgrade, so you should make the corresponding scripts, and maybe contribute back with a PR.
