### ISSUE TITLE
11.0 to 12.0 password issue

### ISSUE THREAD

**Issue by webgourou** [OCA/OpenUpgrade#2746]
Hi,

many people have already post on this but I would like to submit that I have replace v12 password by v11 password and now the user is able to login.

Aurel

**Comment by pedrobaeza** [comment]
I don't get what is the thing you want to report.

**Comment by webgourou** [comment]
based on this thread #1797. Users cannot log when migrate to 11.0 to 12.00
it seems that password was changed during migration process and passlib is not able to identify new password as SHA512 hash.

If come back to old password everything works fine. I don't know if it is a correct way to proceed, anyhow that do the trick.

**Comment by pedrobaeza** [comment]
Then just answer on that thread with that.
