### ISSUE TITLE
Programming error: relation "stock_move" does not exist

### ISSUE THREAD

**Issue by houssine78** [OCA/OpenUpgrade#276]
in the the defered80.py the following update will always run

https://github.com/OpenUpgrade/OpenUpgrade/blob/8.0/openerp/openupgrade/deferred_80.py#L192

because the if condition check if there is at least one record returned
https://github.com/OpenUpgrade/OpenUpgrade/blob/8.0/openerp/openupgrade/deferred_80.py#L190

and hence there will always be one because the query on which the result is tested make a count so it will at least return one record with 0 even if stock is not installed

cr.execute(
        "SELECT count(*) FROM ir_module_module WHERE name='stock' "
        "AND state='installed'")

a possible fix should be to remove the count or to change the if condition

**Comment by houssine78** [comment]
for database having stock installed it's not a problem... but for others it just break the migration process

**Comment by pedrobaeza** [comment]
I don't see any problem. It will return 1 only if all conditions are met, so `state='installed'` is also checked.

**Comment by houssine78** [comment]
yes and no because the if statement will always evaluate the result of the query as true because is 0 or 1 never None

if not cr.fetchone():  # No stock
        return

**Comment by pedrobaeza** [comment]
OK, got it. You put the wrong reference on the issue explanation. 

Then it must be:

```
if not cr.fetchone()[0]:
    return
```

**Comment by pedrobaeza** [comment]
Please check #277 for the fix

**Comment by houssine78** [comment]
or change the query to 

SELECT \* FROM ir_module_module WHERE name='stock' "
"AND state='installed'"

it makes the code easier to understand at the reading

**Comment by pedrobaeza** [comment]
Well, both queries serve, so I let the other.

**Comment by houssine78** [comment]
I get this raising at line 102

TypeError: 'NoneType' object has no attribute '**getitem**'
