### ISSUE TITLE
l10_be module set to False 

### ISSUE THREAD

**Issue by houssine78** [OCA/OpenUpgrade#278]
Hi, 

I can see that the l10_be module installable parameter has been set to False by @hbrunn 

This lead to stop the migration process for databases under belgian accounting. Setting the parameter to True on my local openupgrade instance seems to work properly. Maybe I missed something in the reason of the deactivation of this module marked as nothing to do in the module coverage from 7 to 8 

https://doc.therp.nl/openupgrade/modules70-80.html

Thanks in advance for the help/answer you may give
Houssine

**Comment by hbrunn** [comment]
you seem to have misused git blame: https://github.com/OpenUpgrade/OpenUpgrade/commit/125bc4459860cce0cf4f6dd64968d34af900692d

So better ask @StefanRijnhart for an explanation

**Comment by houssine78** [comment]
Yes you're right sorry!

**Comment by houssine78** [comment]
the commit comment is quiet clear. Thanks!
