### ISSUE TITLE
[RFC] Nothing to Do tag

### ISSUE THREAD

**Issue by gdgellatly** [OCA/OpenUpgrade#2851]
Should we add one for OpenUpgrade? Just to clear down the PR's faster. Maybe if it was tagged as such we could automerge after x days? Or at least put it in the title of the PR.

**Comment by pedrobaeza** [comment]
It's a delicate one, as you can consider nothing to do, but someone can check that it's not true.

**Comment by gdgellatly** [comment]
Yes this true, but worst case, they are wrong and nothing happens. Its really no different to any other scripts first release. We often find performance issues, missed cases after the fact, sometimes years after. Oh well at least in PR title then.

**Comment by pedrobaeza** [comment]
If they are nothing to do, being merged with such label doesn't add any value. I prefer to keep them as is.

**Comment by gdgellatly** [comment]
Well Nothing to Do PR's have a lower reviewer skill threshold, so arguably it can free up better reviewer time.

**Comment by pedrobaeza** [comment]
As said, they can qualify the same, and merging then incorrectly will give the sensation that they are covered, while it can let things without be done (like loading noupdate_changes.xml file, perform a change, do a performance improvement, etc). If they are not reviewed, it's because the modules are not so popular, not because they are nothing to do.

**Comment by legalsylvain** [comment]
Hi. 

intermediate PoV for me : 

- :+1: to Add a convention to add a flag / tag / label or a text in the title, to identify the "Nothing to do" PRs : In fact, there are easier to review. basically : Check noupdate xml file + check analysis.txt file. So, once the label is set, it allows maintainers to filter to display all the opened PR and validate a lot of PR in a few time. I mean when I see a PR named "_[14.0] lunch - Nothing to do_", I know that I'll have review this PR more easily than the "_[13.0] account_" one.

- :-1: to "automerge" : Agree with pedro, we should consider that it is possible that it is wrong, and that there is "something to do".

my two cents.

**Comment by MiquelRForgeFlow** [comment]
Ok guys. I created the new tag and added it to the corresponding PRs  🎉
