### ISSUE TITLE
Page source link broken in docs

### ISSUE THREAD

**Issue by yajo** [OCA/OpenUpgrade#2871]
Just go to the bottom of https://oca.github.io/OpenUpgrade/index.html to the "Page source" link:

![image](https://user-images.githubusercontent.com/973709/127278317-f15b5b18-a878-4108-b5f1-40e6feb92e2c.png)

It's broken.

**Comment by StefanRijnhart** [comment]
Thanks! See https://github.com/OCA/OpenUpgrade/pull/2904
