### ISSUE TITLE
Enable to login after Migration from V13 to V14

### ISSUE THREAD

**Issue by hsnconsult** [OCA/OpenUpgrade#2893]
After migration, Im not enable to login
I tried to set the password using SQL but i still enable to login

**Comment by pedrobaeza** [comment]
Unless you give more information, nothing can be done.

**Comment by hsnconsult** [comment]
> Unless you give more information, nothing can be done.

I followed the procedure for the migration
1.Copy openupgrade_framework and openupgrade_scripts in V14 addons
2.install the library
python –m pip install git + https: //github.com/OCA/openupgradelib.git@master#egg=openupgradelib.
I specify that I am on Windows
3.then
python odoo-bin -d SHOP_KOUBRI13 --upgrade-path = ”C: \ Program Files (x86) \ Odoo 14 \ server \ odoo \ addons \ openupgrade_scripts / scripts” --load = web, openupgrade_framework -u all
4.I check the logs and everything looks correct
2021-08-24 16: 15: 53,475 38732 INFO SHOP_KOUBRI13 odoo.addons.base.models.ir_attachment: filestore gc 69 checked, 20 removed
2021-08-24 16: 15: 53,514 38732 INFO SHOP_KOUBRI13 odoo.addons.base.models.res_users: GC'd 0 user log entries
2021-08-24 16: 15: 53,545 38732 INFO SHOP_KOUBRI13 odoo.modules.registry: Registry changed, signaling through the database
2021-08-24 16: 15: 53,545 38732 INFO SHOP_KOUBRI13 odoo.addons.base.models.ir_cron: Job `Base: Auto-vacuum internal data` done.

But When I try to login i get ![image](https://user-images.githubusercontent.com/42925803/130664617-75d1d3dc-3104-4caf-926a-a6ef34cd6d58.png)

**Comment by pedrobaeza** [comment]
Are all modules in your list already covered by the migration scripts? Anyways, this process doesn't change login process, so something else should be there. Check logs when you are logging.

**Comment by gdgellatly** [comment]
I sometimes get this when doing staging installs, dealing with loads of databases. I don't think it is an openupgrade specific problem. Generally connecting via shell and doing the password change there fixes it for me.

That said, a space in the module list looks weird, is that allowed?
