### ISSUE TITLE
OCA Days 2021 Talk Requests on Openupgrade

### ISSUE THREAD

**Issue by gdgellatly** [OCA/OpenUpgrade#2905]
- New framework, using / writing.
- Openupgrade writing migrations best practice/process

If you feel like doing these for OCA Days please let me know.

**Comment by legalsylvain** [comment]
Could you precise date, expected duration of the talks, etc ?

**Comment by gdgellatly** [comment]
Hi @legalsylvain 

Thankyou for your interest. 
https://odoo-community.org/event/oca-days-2021-online-2021-10-28-2021-10-29-128/track_proposal
The details are there but in summary
28/29th October.
30/60/ (90 - training) minute slots.

In further discussions, OpenUpgrade may have a number of shorter talks on different areas. It is the most requested topic.
