### ISSUE TITLE
Initialize OpenUpgrade 15

### ISSUE THREAD

**Issue by legalsylvain** [OCA/OpenUpgrade#2915]
Hi all,

Fall is coming, and with it, the new annual release of Odoo. (15.0)

here a list in my mind, regarding how to initialize Openupgrade. Feel free to comment if you think I forgave some things.

**First**
- [x] Create a new v15.0 empty branch of OCA/server-tools. Done by OCA.
- [x] Create a new v15.0 empty branch of OCA/OpenUpgrade. Done by @pedrobaeza  here https://github.com/OCA/OpenUpgrade/commit/c80d7525643323c69c2b40743cb450441ed985e1

**openupgrade_framework**
- [x] create demo 14.0 database, following the wiki instructions [here](https://github.com/OCA/OpenUpgrade/wiki/How-to-create-a-reference-database).
- [x] port ``openupgrade_framework`` module from 14.0 to 15.0 and adapt it. (+base modules). Pending work available [here](https://github.com/OCA/OpenUpgrade/pull/2967).

**openpupgrade_scripts**
- [x] port ``openpupgrade_scripts`` from 14.0 to 15.0 and remove ``scripts`` folder. Done by @pedrobaeza here https://github.com/OCA/OpenUpgrade/commit/c80d7525643323c69c2b40743cb450441ed985e1

**upgrade_analysis**
- [x]  Port ``upgrade_analysis`` module from 14.0 to 15.0. done by @legalsylvain here https://github.com/OCA/server-tools/pull/2196
- [x] generate analysis files using 14.0 and 15.0 instance and commit result in ``openpupgrade_scripts``. Done by @legalsylvain here https://github.com/OCA/OpenUpgrade/pull/2961

**doc**
- [x] cherry-pick V14 docs part into 15.0. Done by @pedrobaeza  here https://github.com/OCA/OpenUpgrade/commit/c80d7525643323c69c2b40743cb450441ed985e1
- [x] set the website pointing on the new release. (maybe it's automatic ?)

comment welcome.

kind regards.

**Comment by yajo** [comment]
Since this repo is now only a collection of scripts, and migration scripts are in a specific folder prefixed with the version, do we really need to keep branching this every year? Can't we just use a `main` branch and add migration scripts there for 14+ versions?

**Comment by pedrobaeza** [comment]
`openupgrade_framework` is specific for each version, and anyways, I prefer to split things for not accumulating everything in the same place.

**Comment by legalsylvain** [comment]
> Since this repo is now only a collection of scripts, and migration scripts are in a specific folder prefixed with the version, do we really need to keep branching this every year? Can't we just use a main branch and add migration scripts there for 14+ versions?

Agree with Pedro. 
- Don't see the real interest. what do you think would be better?
- accumulate everything in the same branch make tools less understandable. (I stil see a lot of question regarding old / new design, if we set all the code in the same branch, it will be worse IMO)
- can generate extra troubles. Each openupgrade release should be executed for a spectific Odoo version that allows specific Python version. (mix all revision will make it difficult to implement / maintain CI and other quality tools  
- in fact it's not a collection of script, but a collection of modules. So there are available in [pipy](https://pypi.org/project/odoo14-addon-openupgrade-framework/), in odoo [appstore](https://apps.odoo.com/apps/modules/14.0/openupgrade_framework/) that is great in my opinion to make the project visible.

regarding V15 branch, waiting for https://github.com/OCA/maintainer-tools/issues/509#issuecomment-943430218

**Comment by yajo** [comment]
> Don't see the real interest. what do you think would be better?

Just one version of docs, just one version of code, no need to split work across branches, no need to open a new branch every year, ability to fix and test multiversion migrations in one shot. Basically everything would be better.

> can generate extra troubles. Each openupgrade release should be executed for a spectific Odoo version that allows specific Python version. (mix all revision will make it difficult to implement / maintain CI and other quality tools

Every new solution introduces new problems, but as long as they are smaller, it's a good solution.

These things you say would be easy to fix in the CI matrix.

`openupgradelib` already supports multiple versions of odoo in the same branch, and it works perfectly fine. So these things should be fixable.

> in fact it's not a collection of script, but a collection of modules. So there are available in [pipy](https://pypi.org/project/odoo14-addon-openupgrade-framework/), in odoo [appstore](https://apps.odoo.com/apps/modules/14.0/openupgrade_framework/) that is great in my opinion to make the project visible.

I was talking about `OpenUpgrade` (the migration scripts), not `openupgrade_framework` (the module).

**Comment by legalsylvain** [comment]
> I was talking about OpenUpgrade (the migration scripts), not openupgrade_framework (the module).

migration scripts are also in a odoo module, that allows to be also visible on pipy, in odoo appstore. See : https://pypi.org/project/odoo14-addon-openupgrade-scripts/

@pedrobaeza : @sbidoul (Or other @OCA/community-maintainers ...) One question : I see that all the 15.0 branches have been created some days ago. Do you know why Openupgrade 15.0 was not created ? let me know if I can help. 

Thanks.

**Comment by pedrobaeza** [comment]
It's because this branch doesn't follow the standard copier template. @StefanRijnhart are you going to work in this initialization?

**Comment by StefanRijnhart** [comment]
Oh, I was waiting for the branch to appear because I already did some work on OpenUpgrade 15 before the Odoo release.

**Comment by sbidoul** [comment]
> Do you know why Openupgrade 15.0 was not created ?

This repo is [excluded](https://github.com/OCA/maintainer-tools/blob/bde63eeb13a64561ef53bb9d609f6b9b87efd301/tools/config.py#L60) from the scripts that mass-process addons repos, because it used to not be an addons repo...

**Comment by StefanRijnhart** [comment]
@sbidoul thanks! In that case, https://github.com/OCA/maintainer-tools/pull/514

**Comment by legalsylvain** [comment]
I updated the todo list. Currently working on porting ``upgrade_analysis`` module and generating analysis file.

kind regards.

**Comment by pedrobaeza** [comment]
Wasn't that done already by @StefanRijnhart ?

**Comment by legalsylvain** [comment]
> Wasn't that done already by @StefanRijnhart ?

- porting ``upgrade_analysis`` ? https://github.com/OCA/server-tools/pulls?q=upgrade_analysis
- generating analysis file ? https://github.com/OCA/OpenUpgrade/milestones/15.0

If yes, please point the pending work to avoid duplicated efforts. Thanks.

**Comment by pedrobaeza** [comment]
https://twitter.com/stefan_opener/status/1437558579767164928?s=20

**Comment by legalsylvain** [comment]
> https://twitter.com/stefan_opener/status/1437558579767164928?s=20

damn'it ! I missed this "Pull request" ;-)

Thanks Pedro.

@StefanRijnhart : could you give me a few minutes to know the status of your work and if I can help contribute or review ?

**Comment by StefanRijnhart** [comment]
@legalsylvain no worries. I did not look at it since that tweet.
I see you put out https://github.com/OCA/OpenUpgrade/pull/2961 now, so I can perform my own analysis and compare with your PR by means of review.

**Comment by legalsylvain** [comment]
FYI, I'll try to work on the port of ``openupgrade_framework``. If you have pending work / ideas / points of attention, please let me know.

here : https://github.com/OCA/OpenUpgrade/pull/2967

**Comment by legalsylvain** [comment]
Hi @StefanRijnhart, @pedrobaeza. 
As pedro said, current V14 database is missing, making the test failing. Do you know the process to generate it for the V14 and to add it here https://github.com/OCA/OpenUpgrade/releases/tag/databases ?

thanks !

**Comment by StefanRijnhart** [comment]
@legalsylvain it's https://github.com/OCA/OpenUpgrade/wiki/How-to-create-a-reference-database
To add, you need to have the right privileges on the releases page. Do you have the pencil icon?

![image](https://user-images.githubusercontent.com/1033124/141790955-8d6a0419-ebae-4d33-9099-9cebeaf1f0ff.png)

**Comment by legalsylvain** [comment]
thanks @StefanRijnhart. 

Yes it seems I have the correct access right. (as a maintainer of the repo I guess).

It's done. https://github.com/OCA/OpenUpgrade/releases/tag/databases

this seems "OK" on the current draft PR https://github.com/OCA/OpenUpgrade/pull/2967

The [log](https://github.com/OCA/OpenUpgrade/runs/4217881102?check_suite_focus=true) points that the "DB Restore" step is ok.

![image](https://user-images.githubusercontent.com/3407482/141952474-444fcb7a-0578-448c-8394-eac41f353299.png)

**Comment by StefanRijnhart** [comment]
@legalsylvain fantastic!

**Comment by tmotyl** [comment]
Hi
Thanks for the work! Can somebody summarize what is still open to be done and how I can help?

**Comment by legalsylvain** [comment]
Finish this pending PR 
https://github.com/OCA/OpenUpgrade/pull/2967
I have no time in the next weeks but if you want to work on it, i'll review it.
Thanks for your interest.

**Comment by StefanRijnhart** [comment]
OK, I'll have a look!

**Comment by StefanRijnhart** [comment]
Oh, I misunderstood. @tmotyl feel free if you like!

**Comment by sutidor** [comment]
Looks like it is almost done, right?

**Comment by legalsylvain** [comment]
Hi all.

The last task to do is to make the website https://oca.github.io/OpenUpgrade/ pointing on new 15.0 branch (with new modules140-150.rst file) 


Do you know how to do it ? @pedrobaeza / @StefanRijnhart. 

I think an admin access right is required for this action.

**Comment by StefanRijnhart** [comment]
@legalsylvain thanks for the reminder! Indeed, I had to change the Github Pages config at https://github.com/OCA/OpenUpgrade/settings/pages to the 15.0 branch. Done now.

**Comment by legalsylvain** [comment]
Closed ! 

_(and ready to be duplicated for V16 in 3 months ...)_
