### ISSUE TITLE
Missing bom lines from V7 to V8

### ISSUE THREAD

**Issue by gunaidin** [OCA/OpenUpgrade#292]
Hello to all.
I used migration.py to migrate a v7 database to V8.
In the new v8 db I am missing all the bom relations (products have empty boms). I have seen that in v8 there is a new mrp_bom_line table (empty). Is that expected or it depends on v7 configuration?
regards
stefano

**Comment by pedrobaeza** [comment]
The mrp module migration is still not integrated on the main branch. You can see it here: https://github.com/OpenUpgrade/OpenUpgrade/pull/117, and it takes care of the problem you mention. Please check it, and if all goes well, comment on the PR for being approved.
