### ISSUE TITLE
[13.0][l10n_generic_coa][account] Failed migration

### ISSUE THREAD

**Issue by kos94ok-3D** [OCA/OpenUpgrade#2934]
The problem comes from https://github.com/odoo/odoo/pull/37606 and filling `default_pos_receivable_account_id` here:https://github.com/OCA/OpenUpgrade/commit/f1b1002d78b243e1eb5049308066226c8a34fe0c
```
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "account_account_code_company_uniq"
DETAIL:  Key (code, company_id)=(101300, 1) already exists.
```
In v12 we have `account.account.template`:
    `Tax Paid` with code `1013`
    do not have `Account Receivable (PoS)`

In v13 we have  `account.account.template`:
    `Tax Paid` with code `1310`
    have `Account Receivable (PoS)` with code `1013`

Steps to reproduce:
1. Create DB
2. Install `l10n_generic_coa` and `account`
3. Try to migrate

**Comment by kos94ok-3D** [comment]
Hi, @pedrobaeza. Could you share your experience with this kind of problem?

**Comment by pedrobaeza** [comment]
Check #2524
