### ISSUE TITLE
[RFC] futur of wiki of openupgrade

### ISSUE THREAD

**Issue by legalsylvain** [OCA/OpenUpgrade#2972]
Hi all, 

here is the current pages present in wiki of odoo : 

![image](https://user-images.githubusercontent.com/3407482/141958883-3e7ffcc6-b26f-4b65-b958-650de447d5ed.png)

1) **I propose to delete obsolete pages**
 
- Migration from 7.0 to 8.0
- Migration from Launchpad to Github of 7.0 branch
- Planned migrations

2) **I propose to add pages**
- @pedrobaeza, if you have time, could you write a short page, to explain how to initialize a new branch. (the command to do for the 16.0) branch

3) **update**
- I updated "Crude script to create the full analysis between two versions of Odoo" [page](https://github.com/OCA/OpenUpgrade/wiki/Crude-script-to-create-the-full-analysis-between-two-versions-of-Odoo) because the script is obsolete.
- I updated "How to create a reference database" [page](https://github.com/OCA/OpenUpgrade/wiki/How-to-create-a-reference-database) adding minor information. (I added the ``--format=c`` option for the dump, because this is not the default export option in pg_dump command)

review welcome. (please, if you see error, changes directly, I don't know how to do Pull request on wiki. (i don't think it's possible)).

4) **next step**

when https://github.com/OCA/OpenUpgrade/issues/2915 will be closed, write a page to mention all the things to do when a new branch has to be created. (I can do it).

**Comment by pedrobaeza** [comment]
Well, the initialization I made was simply to locally create a new branch from scratch and put files in it copying from previous version and changing 14 by 15.

**Comment by pedrobaeza** [comment]
Closing as stalled.
