### ISSUE TITLE
[13.0][sale_timesheet]bad deletion of model and relation

### ISSUE THREAD

**Issue by flotho** [OCA/OpenUpgrade#2985]
openupgrade v13 ran perfectly.

Now running a -u all on OCB v13.

Here is the log : 
```
odoo.addons.base.models.ir_model: Deleting 825@ir.model (sale_timesheet.model_project_task_assign_sale) 
2021-11-28 20:52:51,410 550897 ERROR defacto_13 odoo.sql_db: bad query: DELETE FROM ir_model WHERE id IN (825)
ERROR: ERREUR:  UPDATE ou DELETE sur la table « ir_model » viole la contrainte de clé étrangère « ir_model_relation_model_fkey » de la table « ir_model_relation »
DÉTAIL : La clé (id)=(825) est toujours référencée à partir de la table « ir_model_relation ».

```
The deletion of the model is totally "legal" https://github.com/OCA/OpenUpgrade/blob/13.0/addons/sale_timesheet/migrations/13.0.1.0/openupgrade_analysis.txt#L2 but seems to be incomplete
I don't find where to force the cascade deletion on this model. 

Any advice on this would be appreciated

Regards

**Comment by flotho** [comment]
I faced another similar case : https://github.com/OCA/OpenUpgrade/blob/13.0/addons/mass_mailing/migrations/13.0.2.0/openupgrade_analysis.txt#L4

**Comment by pedrobaeza** [comment]
This is happening since #2966, and while the fix is correct, we should provide in OpenUpgrade a change for deleting cascade the `ir.model.relation` references, preferable on engine that case by case. cc @MiquelRForgeFlow
