### ISSUE TITLE
[13.0]Cancel and draft account move bad name

### ISSUE THREAD

**Issue by flotho** [OCA/OpenUpgrade#3004]
## Module
Account module

## Describe the bug
As you can see, the cancel and draft move (ex invoice) have bad names : 
![image](https://user-images.githubusercontent.com/1043935/145657913-a7f4ead3-0a1c-4709-b9b1-ea143b0c6eaf.png)

## To Reproduce
migrate from v12 with no validated invoices

**Expected behavior**
Use '/' as default names for those invoices

**Comment by pedrobaeza** [comment]
If you are going to open a PR, please include the issue description there and don't open 2 things. Closing this one.
