### ISSUE TITLE
[WIP]MassMailing keep invalid domains in its table, opt_out invalied

### ISSUE THREAD

**Issue by flotho** [OCA/OpenUpgrade#3014]
## Module
mass_mailing

## Describe the bug
on v14
![image](https://user-images.githubusercontent.com/1043935/146034289-e250d141-3dc0-47ba-a7ff-fb56f5932bf6.png)

## To Reproduce

migrate from 10 ->14

**Affected versions**:
v14 once migrated

**Expected behavior**
change the domain or recompute legal doamin

**Comment by pedrobaeza** [comment]
That's barely impossible, as there are tons of possible fields that disappear or are renamed. One possible thing is that you tackle specific cases that are common like the `opt_out` one, that was introduced in every domain of mass mailing, but I remember that I introduced already some code for that.

Another possible option is to handle renaming of fields in the `rename_fields` method, querying if `mass_mailing` is installed (through the existence of the corresponding table), and then looking on the field, but the table name is different across versions, so this gets complicated.

**Comment by pedrobaeza** [comment]
Closing as stalled.
