### ISSUE TITLE
[11.0 -> 12.0] sales.order.form TypeError: %u format: a number is required, not str

### ISSUE THREAD

**Issue by Andrea399** [OCA/OpenUpgrade#3037]
Hi,
my problem is while migration ver. 11 -> 12, in sale.order.form

error log:

[log11-12.log](https://github.com/OCA/OpenUpgrade/files/7787763/log11-12.log)

how can I solve it ?
Thanks

**Comment by pedrobaeza** [comment]
It seems you have an offending view coming the is crashing the process. Locate a view with `<group name="invoicing">` for the `sale.order` model, and remove it manually before migrating.

**Comment by Andrea399** [comment]
Thank you for your early reply.
I have removed the views with the ```<group name="invoicing">``` that I think it wasn't blocking.
The new log:
[test12_2.log](https://github.com/OCA/OpenUpgrade/files/7799939/test12_2.log)

**Comment by pedrobaeza** [comment]
You still have a similar problem. There's an offending view in `sale.order`.

**Comment by Andrea399** [comment]
I have solved this issue: I have removed the button  'payment_transation_count' from  'date_payment.sale_order_view_form'
