### ISSUE TITLE
[12.0 -> 13.0 -> 14.0] account migration issues

### ISSUE THREAD

**Issue by remi-filament** [OCA/OpenUpgrade#3050]
## Module
account

## Describe the bug
When migrating our internal DB from Odoo v12.0 to Odoo v14.0 using OpenUpgrade we faced a number of issues related to account that I will try to share here so that others may find some solutions should they face the same ones !
Also a few things should be fixed in script for migration from 13.0 to 14.0.

A bit of context : we started our database on v9.0, then migrate to v10.0, then to v12.0 and now to v14.0 (of course with intermediate version migration required by OpenUpgrade to v11.0 and v13.0 but we never used these versions).

### Invoice payment widget shows no amount for payment, only date
After migration, when opening a paid invoice, the payment widget at the bottom shows only date of payment but not the amount.
After a bit of investigation, it is because new fields **debit_amount_currency** and **credit_amount_currency** added in v14.0 on account.partial.reconcile model are empty (these are usually filled during reconciliation with the following functions from account_move : reconcile() > _prepare_reconciliation_partials() but the old lines are not updated).

The workaround we found was to set these 2 fields to the same figure as amount but I fear that more elaborated commands should be added in account migration scripts for dealing with multi currency environments (we only have EUR so this was not an issue). The following SQL command was used : 
```sql
update account_partial_reconcile
set 
    debit_amount_currency = amount,
    credit_amount_currency = amount
where debit_amount_currency is null;
```

### Links between account_bank_statement_line and account_move
An account move is now mandatory for every account_bank_statement_line. The migration script tries to find which existing account_move should be linked to account_bank_statement_line (in pre-migration part) and the create the missing ones (in post-migration part) but we had a few issues that led to have multiple account_bank_statement_line linked to the same account_move.
These issues seemed to be caused by the following :
- we had different account_move with same name
- we had various account_bank_statement_line with same account_number and various account_move with same ref

Not sure why, or where it came from (probably v9 or v10 according to the dates) but it caused quite a mess after migration :
- various account_bank_statement_lines got linked to the same account_move
- when one of these account_move was modified, all related account_bank_statement_lines where modified as well because of _synchronize_business_models() function from account_move called on write() that caused all these bank statement lines to get wrong amounts and partners...

As far as I could tell, we should update [pre-migration script](https://github.com/OCA/OpenUpgrade/blob/14.0/openupgrade_scripts/scripts/account/14.0.1.1/pre-migration.py) to replace the SQL command from function add_move_id_field_account_bank_statement_line() on lines 214 - 225 in 2 SQL commands to first link the account_bank_statement_line to account_move.statement_line_id, then do the rest of the command for account_bank_statement_line which do not have move_id.
I should propose a PR on this next week but here is the code for the time being : 
```python
    # Force move ids when statement_line_ids already set on account_move
        openupgrade.logged_query(
            env.cr,
            """
            UPDATE account_bank_statement_line absl
            SET move_id = am.id
            FROM account_move am
            WHERE am.statement_line_id = absl.id
            """,
    # Find move_id by using either move_name or payment_ref from account_bank_statement_line
        openupgrade.logged_query(
            env.cr,
            """
            UPDATE account_bank_statement_line absl
            SET move_id = am.id
            FROM account_move am, account_bank_statement bs
            WHERE absl.statement_id = bs.id 
            AND absl.move_id IS NULL
            AND (am.name NOT IN ('', '/')
            AND COALESCE(NULLIF(absl.move_name, ''), absl.payment_ref) = am.name
            AND am.company_id = bs.company_id
            """,
```

Also, every account_move created for account_bank_statement_line without move_id were incorrect and had 2 lines of suspense account (instead of only 1). I had no time to investigate why, but might be related to the [post-migration script ](https://github.com/OCA/OpenUpgrade/blob/14.0/openupgrade_scripts/scripts/account/14.0.1.1/post-migration.py) fill_account_journal_payment_credit_debit_account_id() function ?

### Grouped account_move_lines for invoice journal
Finally, we had issue during migration because we used to have move lines grouped by account in invoice journals using group_invoice_lines on invoice journals.
This configuration was removed with v13 and grouped lines were set in [v13 post-migration script](https://github.com/OCA/OpenUpgrade/blob/13.0/addons/account/migrations/13.0.1.1/post-migration.py) to exclude_from_invoice_tab.
Excluding these lines from invoice tab, makes total sense, but it has a bad side effect that anytime amounts are recomputed for an invoice, the untaxed amount and total amount are wrong since exclude_from_invoice_tab lines are excluded from calculation in account_move _compute_amount() function...

For this we could not find any good solution, so far the only way to work around this issue was to : 
1. Cancel invoice using account.move button_cancel
2. Bring back invoice to draft status account.move button_draft
3. Update related account_move_line : delete group line and update other lines with correct amount on each line
4. Validate invoice
5. Reconcile payments

Hopefully most of the invoices should not need recalculation of amounts, but if you come up with a better way to solve this once and for all, let me know !

**Comment by pedrobaeza** [comment]
Please put one problem per issue, and dig if the problem is in the v12 > v13 step or v13 > v14 step.

**Comment by pedrobaeza** [comment]
Can this be closed?

**Comment by remi-filament** [comment]
I was writing the last one, now it can be closed :)
