### ISSUE TITLE
[12.0 --> 13.0] account - grouped lines in v12 lead to inconsistencies in v13+

### ISSUE THREAD

**Issue by remi-filament** [OCA/OpenUpgrade#3054]
## Module
account

## Describe the bug
On out v12 database, move lines were grouped (to have only one move line per account) for all invoices (configured in account_journal with  group_invoice_lines boolean).

This group_invoice_lines was removed in v13 together with rework of account module and merge of invoices and account moves.

This leads us to issues when amounts are recalculated on invoice (for instance when a payment is registered), with incorrect untaxed and total amounts.

The cause is that these grouped lines are set in v13 [post-migration script](https://github.com/OCA/OpenUpgrade/blob/a82a1c75d171fed2f2fccfcafb01843cb894f762/addons/account/migrations/13.0.1.1/post-migration.py#L298) to exclude_from_invoice_tab.
Excluding these lines from invoice tab, makes total sense, but it has a bad side effect that anytime amounts are recomputed for an invoice, the untaxed amount and total amount are wrong since exclude_from_invoice_tab lines are excluded from calculation in [account_move _compute_amount() function](https://github.com/odoo/odoo/blob/7a2ff9e8fe56668201da17e199849598180d25f7/addons/account/models/account_move.py#L1127)...

For this we could not find any good solution, so far the only way to work around this issue was to :
1. Cancel invoice using account.move button_cancel
2. Bring back invoice to draft status account.move button_draft
3. Update related account_move_line : delete group line and update other lines with correct amount on each line
4. Validate invoice
5. Reconcile payments

Hopefully most of the invoices should not need recalculation of amounts, but if you come up with a better way to solve this once and for all, let me know !

## To Reproduce
**Affected versions**: migrating from v12.0 to v13.0

1. Activate group_invoice_lines on customer invoice journal
2. generate an invoice with 2 or more lines pointing to the same account.account
3. Validate invoice
4. Migrate DB
5. Register payment on invoice, amounts become incorrect

**Expected behavior**
The amount should remain correct.

**Comment by remi-filament** [comment]
Splitting #3050 as requested by @pedrobaeza

**Comment by pedrobaeza** [comment]
Yes, grouped invoice lines is a very bad decision you can take. I forbid it in all my installations as it was sure sooner or later such mangling will have side effects. Anyways, if done, no possible revert, and no possible solution in the OpenUpgrade part. The only solution is to remove manually the journal items, so take note of that as instructions for these mangled DBs.

**Comment by MiquelRForgeFlow** [comment]
@etobella you also have grouped lines. What's your opinion on this issue and how you handle it?

**Comment by etobella** [comment]
My opinion is that grouped lines was one of the wrongest decisions I made with odoo. I found similar issues but there is no easy solutions

**Comment by legalsylvain** [comment]
Hi @pedrobaeza and @remi-filament. 

I'm currently working on 12.0 version and planned to migrate on 16.0 version next year. my database comes from V5, and I used grouped option since years... So I'll face the same problem in a while. happy to see I'm not alone !

I was wondering if we could not treat the problem upstream. I mean develop a V12 module named : ``account_no_group_invoice_lines``. Quick description : 

- during the installation uncheck the box for all the journals.
- forbid new "bad" configuration.
- have a cron that fixes the problem by transforming (by SQL queries / by ORM / or both with option) "grouped" accounting move into "non-grouped" accounting moves.

Do you think it could work ?

Thanks.

**Comment by remi-filament** [comment]
Yes it should work, the only thing I do not know is the mess it would put in your accounting since you would have much more account.move.lines than you had before !

**Comment by legalsylvain** [comment]
well, 
I will have as much account.move.line as I would have had if I had always been in v13.
If this quantity is a problem, the V13 is a problem ;-)

**Comment by remi-filament** [comment]
Yes I meant that past account_move_lines would increase a lot (on closed fiscal years and depending on when you do that on current year as well), which I am sure our accountants will not like :) !

**Comment by pedrobaeza** [comment]
I also don't see changing closed fiscal years is the way to go.

**Comment by gdgellatly** [comment]
@legalsylvain I had a similar experience. Slightly different as it was 1 invoice line becoming 2 move lines (anglosaxon price differences).

However in general I visually solved this issue by setting price_unit to be different to debit / credit. But honestly while it worked OK, it still causes some issues, especially with more recent data. if you can do pre migration

So if I think about your v12 module there is possibly a simpler approach. Obviously you need to take care of closed periods, lock dates, maybe tax changes? etc prior. Also I know Europe can be a bit fussy legally.

To do this in ORM.
Disable grouping on affected journals.
Enable cancelling moves on the affected journals.
Identify affected invoices.
Cancel, reset to draft, confirm.
And in v12 it will keep the same move number but now unroll it.

**Comment by pjrobertson** [comment]
I am currently facing this same issue, I appreciate @remi-filament for filing this request and documenting your findings.

@remi-filament  - would you be able to share the SQL code (or similar) that you used for step 3 in your instructions:

> 3. Update related account_move_line : delete group line and update other lines with correct amount on each line

I'm not 100% clear on what you did here, more specifically, how do you determine the group lines and how do you work out the amount for each remaining line (e.g. manually?)

**Comment by remi-filament** [comment]
Hi @pjrobertson we did it manually (one by one...)
Group lines are easy to determine since after migration script they start with "(OLD GROUPED ITEM)" (as per https://github.com/OCA/OpenUpgrade/blob/a82a1c75d171fed2f2fccfcafb01843cb894f762/addons/account/migrations/13.0.1.1/post-migration.py#L299)
You then have other lines with amount = 0 with name mapping with invoice lines tab, you have to make these match the amounts from invoice lines !

If you have a lot of them for sure this should not be the way to go, but if you have not so many (or time to spare), you may want to give it a shot !
Good luck !

**Comment by pjrobertson** [comment]
Thanks @remi-filament - much appreciated!

I will update your steps as follows then:


1. Cancel invoice using account.move button_cancel
2. Bring back invoice to draft status account.move button_draft
3. Get the invoice (move) ID for the current invoice by looking in the URL (move_id=XXX)
4. Update related account_move_line to delete group lines: `delete from account_move_line where move_id=XXX and name like '(OLD GROUPED ITEM)%';
5. Update other account_move_line  with correct amount on each line - one by one check each line and make sure the 'amount' column matches what is in the invoice.
6. Validate invoice
7. Reconcile payments


When looking into this further, I realised that our main problem is that payment lines ('Paid on XXXXX') at the end of an invoice are split up based on the payment terms of an invoice. So if my invoice is for $100 and payment terms are 50% up front ad 50% after 3 months, then a single payment of $100 will be split into two lines. I now don't think this is an issue with the database as such, but that Odoo has changed the way they display payment lines on invoices now.

Thanks again!

**Comment by pedrobaeza** [comment]
Closing as stalled.

**Comment by jose250698** [comment]
@pjrobertson @remi-filament @pedrobaeza @legalsylvain @StefanRijnhart 

Hello! what do you think of this approach?

I tested it in V15 on a ir.cron record on a paid and unpaid customer invoices, with this approach you don't have to cancel the invoice or unreconcile the payments, just replace INVOICE_ID with actual invoice you want to test, it could be easily refactored to support multiple invoices

```
invoice = model.browse(INVOICE_ID).with_context(check_move_validity=False)

lines_to_delete = invoice.line_ids.filtered(lambda l: '(OLD GROUPED ITEM)' in l.name)
for line in lines_to_delete:
  matched_line = invoice.line_ids.filtered(
    lambda l: l.product_id == line.product_id and 
              l.quantity == line.quantity and 
              l.account_id == line.account_id and
              l.id != line.id
  )
  matched_line.write({'credit': line.credit, 'debit': line.debit})

  env.cr.execute('delete from account_move_line where id = {};'.format(line.id))
invoice._recompute_dynamic_lines(True, True)
```
