### ISSUE TITLE
[13.0 --> 14.0] account Invoice payment widget does not show payment amounts

### ISSUE THREAD

**Issue by remi-filament** [OCA/OpenUpgrade#3055]
## Module
account

## Describe the bug
After migration, when opening a paid invoice, the payment widget at the bottom shows only date of payment but not the amount.

After a bit of investigation, it is because new fields debit_amount_currency and credit_amount_currency added in v14.0 on account.partial.reconcile model are empty (these are usually filled during reconciliation with the following functions from account_move : reconcile() > _prepare_reconciliation_partials() but the old lines are not updated).

The solution should probably be to calculate these 2 fields as done in [_prepare_reconciliation_partials() function.](https://github.com/odoo/odoo/blob/077e554703b6d8a71c81fbf6783228d04e77d96f/addons/account/models/account_move.py#L4366)

As we have only 1 currency and we are not dealing with multi currencies we worked around that issue with simple SQL command (but more elaborated solution should be found for multi_currency contexts) :
```sql
update account_partial_reconcile
set 
    debit_amount_currency = amount,
    credit_amount_currency = amount
where debit_amount_currency is null;
```

## To Reproduce
**Affected versions**: migration to version 14.0

1. Get a database in v13.0
2. Create invoice and associated payments
3. Migration to v14.0
4. Check paid invoices : the amounts are not there on payment widget at the bottom (between total price and due amount)

**Expected behavior**
Display properly all payments with both dates and amounts

**Comment by remi-filament** [comment]
Split from #3050  as requested by @pedrobaeza

**Comment by pedrobaeza** [comment]
This sounds like you can do a pull request adding such SQL in the migration scripts ;)

**Comment by remi-filament** [comment]
Yes I could but I think this will not work for multi-currency environment, so I am not sure whether we should add this in script or if it should be made more generic before ?

**Comment by pedrobaeza** [comment]
You can add a `WHERE` clause for only those that match the currency, and with that, you fill proper data for a good percentage (or 100%) of the reconcilations. Put a TODO or try to develop the other case.

**Comment by remi-filament** [comment]
Good idea thanks, will do !
