### ISSUE TITLE
[13.0 --> 14.0] account incorrect account moves created for bank statement lines

### ISSUE THREAD

**Issue by remi-filament** [OCA/OpenUpgrade#3056]
## Module
account

## Describe the bug
Every account_move created for account_bank_statement_line which did not already have related account_move had 2 lines of suspense account (instead of only 1) + 1 line for bank account (as expected).
This caused all of these moves to be not balanced and therefore remained could not be validated directly without removal of 1 one the suspense account line.

This might be related to the [post-migration script fill_account_journal_payment_credit_debit_account_id() function](https://github.com/OCA/OpenUpgrade/blob/fb786b529fc460bb99334fac12ea79db63476191/openupgrade_scripts/scripts/account/14.0.1.1/post-migration.py#L394) but I am not sure...
It seems to me that suspense lines are probably created twice, since account_move_line _prepare_move_line_default_vals() function will be called twice : once in [st_line._synchronize_to_moves() line 458](https://github.com/OCA/OpenUpgrade/blob/fb786b529fc460bb99334fac12ea79db63476191/openupgrade_scripts/scripts/account/14.0.1.1/post-migration.py#L458) and once on [line 475](https://github.com/OCA/OpenUpgrade/blob/fb786b529fc460bb99334fac12ea79db63476191/openupgrade_scripts/scripts/account/14.0.1.1/post-migration.py#L475).

## To Reproduce
**Affected versions**: migration to 14.0

1. Get a v13.0 database
2. Create bank statement and leave some statement lines unreconciled (so that no related account_move would be created for these)
3. Migrate to v14.0
4. Check the account_move created during migration for these unreconciled bank statement lines

**Expected behavior**
Balanced account_moves with 1 line for bank account and 1 counterpart line with suspense account

**Comment by remi-filament** [comment]
Split from #3050 as requested by @pedrobaeza

**Comment by MiquelRForgeFlow** [comment]
Solved in https://github.com/OCA/OpenUpgrade/pull/3251.

**Comment by StefanRijnhart** [comment]
Fix merged. Thanks!
