### ISSUE TITLE
sh: /var/tmp/openupgrade/8.0/server/openerp-server: No such file or directory

### ISSUE THREAD

**Issue by masterdubs** [OCA/OpenUpgrade#308]
Each time the migrations stop with this error : 
sh: /var/tmp/openupgrade/8.0/server/openerp-server: No such file or directory

but create itself directory /var/tmp/openupgrade/8.0/

**Comment by hbrunn** [comment]
any chance `/var` (or `/var/tmp`) is mounted with `-o noexec`? If so, pass `--branch-dir` pointing to a location where you can execute files.

**Comment by masterdubs** [comment]
I try different location, chmod 777 a dir, but I have always the same error

**Comment by hbrunn** [comment]
can you run `/var/tmp/openupgrade/8.0/server/openerp-server` in a console?

**Comment by masterdubs** [comment]
I find the problem, the script has a bad command in line 313, I just remove '--single-branch' and it works perfectly

**Comment by hbrunn** [comment]
Which means you use a very old git, this parameter exists since 1.7.9: https://lkml.org/lkml/2012/3/28/418

**Comment by masterdubs** [comment]
you are right git version 1.7.9.5
