### ISSUE TITLE
[14.0] account amount_residual_currency not recomputed

### ISSUE THREAD

**Issue by remi-filament** [OCA/OpenUpgrade#3087]
## Module
account

## Describe the bug
The field amount_residual_currency is normally computed on account_move_line in [_compute_amount_residual() function](https://github.com/odoo/odoo/blob/c68e1d1c13d116bda6b91fcbbcd61a26739a9894/addons/account/models/account_move.py#L3850)

This compute depends on the currency_id field hat needs to be defined.

This currency_id existed since a while in Odoo, but is required only since v14. It is filled in [pre-migration script](https://github.com/OCA/OpenUpgrade/blob/8a5c24145c8ea11f08454273c46186ce94c1d9d6/openupgrade_scripts/scripts/account/14.0.1.1/pre-migration.py#L389), but the amount_residual_currency is not recomputed for existing lines since this change is made in SQL and not via ORM.

This causes issues when reconciling bank statement with invoices : the invoices change to Paid payment_state but you cannot see the related payment. This is because the [_prepare_reconciliation_partials() function ](https://github.com/odoo/odoo/blob/c68e1d1c13d116bda6b91fcbbcd61a26739a9894/addons/account/models/account_move.py#L4366) called from reconcile() one is using this amount_residual_currency field to complete the reconciliation. Without this field computed, the lines are not properly reconciled (it will actually not create partial_reconcile entries since exiting at lines 4430 or 4437, and afterwards not create full_reconcile)

## To Reproduce
**Affected versions**: 14.0

1. Get a version prior to v14 where currency_id is not filled in account_move_line
2. Migrate to v14.0
3. Try to reconcile a bank statement line with open invoice
4. Invoice is paid but no payment is listed

**Expected behavior**
Payment should be listed in invoice

The solution is easy : we should recompute amount_residual_currency, by running "account.move.line"._compute_amount_residual()
I could propose a PR but I am not sure where to add this, should it go to pre-migration script, in fill_account_move_line_currency_id() and be run only for the lines that were modified, or should it rather go in post-migration script ?

**Comment by pedrobaeza** [comment]
Fixed in https://github.com/OCA/OpenUpgrade/pull/3234
