### ISSUE TITLE
ImportError: cannot import name 'upgrade'

### ISSUE THREAD

**Issue by jayo2005** [OCA/OpenUpgrade#3134]
I am trying to upgrade my database from Odoo 12 to 14. I believe I have to go to 13 first and then 14 is this right?

Steps I took to upgrade from 12 to 13.

1. wget https://codeload.github.com/OCA/OpenUpgrade/zip/13.0
2. unzip 13.0
3. cd OpenUpgrade-13.0/
4. sudo nano /etc/odoo-server.conf
5. Config file looks like this 
`addons_path=/root/openupgrade/OpenUpgrade-13.0/addons`

6. cd /root/openupgrade/OpenUpgrade-13.0
7. sudo su odoo
8. `./odoo-bin --database=odoo12database --config=/etc/odoo-server.conf --update all --stop-after-init`

I get the following error when I run

```
Traceback (most recent call last):
  File "./odoo-bin", line 5, in <module>
    import odoo
  File "./odoo/__init__.py", line 109, in <module>
    from . import upgrade  # this namespace must be imported first
ImportError: cannot import name 'upgrade'


```

**Comment by legalsylvain** [comment]
Do you have this folder ?
https://github.com/OCA/OpenUpgrade/tree/13.0/odoo/upgrade

**Comment by jayo2005** [comment]
> Do you have this folder ? https://github.com/OCA/OpenUpgrade/tree/13.0/odoo/upgrade

Yes I have that folder

**Comment by legalsylvain** [comment]
Sorry. I don't understand what is the problem. 
The upgrade folder is an odoo standard folder. (See : https://github.com/odoo/odoo/tree/13.0/odoo/upgrade)
something is wrong in your deployment, but it is not a problem related to openupgrade.
