### ISSUE TITLE
[13.0] Improve account tax tags migration to repartition lines for all localizations

### ISSUE THREAD

**Issue by ddejong-therp** [OCA/OpenUpgrade#3153]
So, in the process of fixing the migration of the dutch tax tags (`account.account.tag`), I have come across multiple problems. One of them, is that because of the new accounting structure in 13.0, tags get copied to the `account.tax.repartition.line`'s. However, these lines should have one specific tag for each line.

EDIT: And that makes sense, more or less, because there isn't enough information in the `account.acount.tag` model to determine whether it was meant to be for tax lines or non-tax lines. So the migration script of `account` should not be able to apply the right tag to the right repartition line, so it just copies all of them to all lines, as a best effort I guess.

https://github.com/OCA/OpenUpgrade/pull/3146 fixes that same problem for their localization (`l10n_es`). However, because it seems to be problem that isn't specific to any localization, you could say that each localization module needs to fix this for themselves. However, I think this is a bad idea, because the problem lies in the way the structure of the `account` module changes from 12.0->13.0.

However, because each repartition line requires one of the tags, not all of them (right? correct me if I'm wrong), you need to know which tag is about VAT, and which tag is about turnover. I'm not familiar with other countries tax systems, so I can't really say if VAT and turnover tags are the 2 only tags that are relevant for everybody. Nevertheless, I think something can be done for the `account` migration that benefits most localizations.

I think determining what tags belong to what repartition lines is information that the general `account` module does not have. I'd say it is up to the localization module (`l10n_*`) to determine which tags belong to which lines.
For l10n_nl, I've made the following queries like this:
```
openupgrade.logged_query(env.cr, """
        DELETE FROM account_account_tag_account_move_line_rel r
        WHERE
            account_account_tag_id IN (
                SELECT res_id FROM ir_model_data 
                WHERE
                    model = 'account.account.tag' AND
                    module = 'l10n_nl' AND
                    name IN ('""" + "','".join(tax_tag_xmlids) + """')
            ) AND
            account_move_line_id IN (
                SELECT id FROM account_move_line
                WHERE tax_base_amount = 0
            )
    """)
openupgrade.logged_query(env.cr, """
        DELETE FROM account_account_tag_account_move_line_rel r
        WHERE
            account_account_tag_id IN (
                SELECT res_id FROM ir_model_data 
                WHERE
                    model = 'account.account.tag' AND
                    module = 'l10n_nl' AND
                    name IN ('""" + "','".join(base_tag_xmlids) + """')
            ) AND
            account_move_line_id IN (
                SELECT id FROM account_move_line
                WHERE tax_base_amount <> 0
            )
    """)
```
In here, I've compiled the xmlid's of the VAT tags in `tax_tag_xmlids` and `base_tag_xmlids` are the non-VAT tags. This seems to work for `l10n_nl`, and if there are other localizations which can resolve their problem in the same manner, I'd say maybe we should put this in a helper function of the `account` module. That way, it becomes really easy for other localizations to fix the same problem on their side.

What do you guys think?

**Comment by pedrobaeza** [comment]
Closing as stalled.

**Comment by pleirb** [comment]
How's everybody? It happens to me that when running the migration from 12 to 13 I get this error that may be related:

```
2023-07-13 01:28:05,979 1 WARNING devel odoo.addons.base.models.ir_model: Could not delete obsolete record with id: 9 of model account.account.tag
Please refer to the log message right above 
Traceback (most recent call last):
  File "/opt/odoo/custom/src/odoo/odoo/addons/base/models/ir_model.py", line 2073, in _process_end
    record.unlink()
  File "/opt/odoo/custom/src/odoo/odoo/models.py", line 3409, in unlink
    cr.execute(query, (sub_ids,))
  File "/opt/odoo/custom/src/odoo/odoo/sql_db.py", line 173, in wrapper
    return f(self, *args, **kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/sql_db.py", line 250, in execute
    res = self._obj.execute(query, params)
psycopg2.errors.ForeignKeyViolation: update or delete on table "account_account_tag" violates foreign key constraint "account_account_tag_account_move_li_account_account_tag_id_fkey" on table "account_account_tag_account_move_line_rel"
DETAIL:  Key (id)=(9) is still referenced from table "account_account_tag_account_move_line_rel".
```

To fix it after the migration that seems to be working, I run this command on the database directly to delete the relationships:

`DELETE FROM account_account_tag_account_move_line_rel WHERE account_account_tag_id = 9;`

What I'm not sure is if relevant data is deleted. The query returns thousands of deleted results, although operationally everything seems functional.

**Comment by ddejong-therp** [comment]
Do you know what localization module(s) are installed?

**Comment by pleirb** [comment]
> ¿Sabe qué módulos de localización están instalados?

I have l10n_uy installed and when I remove the module before migrating it does not give any error. What I don't know is if I suffer some kind of data loss in this process. I have read in other threads (https://github.com/OCA/OpenUpgrade/pull/3146) that the module account_chart_update can be used to correct some things, but I don't know how to use it and if it is really the solution.

**Comment by ddejong-therp** [comment]
Hey,
So the issue here is that module `l10n_uy` doesn't have a migration script yet.
The `l10n_uy` in 13.0 defines some `account.tax.report.line` data in place of what used to be  `account.account.tag`'s in 12.0.
That probably has to do with why they are being deleted.
They there should be a migration script that properly moves the records over to the new structure.

This issue right here is about some functions I've added to (hopefully) make writing the correct migration script a lot easier. But it doesn't solve it, someone has to create such a migration script for `l10n_uy`. I know nothing about taxes in Uruguay, so I can't help you there unfortunately.

**Comment by pleirb** [comment]
> account_chart_update

Thank you ! I am evaluating the possibility of removing the l10n_uy module before migrating and then installing it again. I'm not sure if I'll have data loss, but I'll try
