### ISSUE TITLE
[13.0] Improve account tax tags migration to repartition lines for all localizations 2

### ISSUE THREAD

**Issue by ddejong-therp** [OCA/OpenUpgrade#3154]
In Odoo 13.0, the `account.tax.report.line` model has been introduced. This model is responsible for generating certain `account.account.tag`'s. `l10n_nl` is using this new model for their VAT and turnover tags. So instead of having these tags defined in XML, the report lines are defined in XML and then the tags get generated from Python. On top of that, the new tags that get generated from report lines start with either a `+` or a `-`. The the tag with the right sign should be assigned to the right repartition line (`account.tax.repartition.line`).

Despite this, there is not a proper migration script to convert these old tags to new ones, for `l10n_nl`. I've made one. However, I feel this code could work for any localization that decides to move to report lines for their tags. Not all localizations are using the report lines yet, but quite a few are already.

The code I've written uses the `name` field of the old tag, and compares it against the `tag_name` field of the new report line. This happens to work for `l10n_nl`, because those who have written the module have decided to use the exact same names. Which makes sense because these names are the same names that are used on our tax forms.
However, I've checked other localization modules that happen to start using report lines in 13.0, but they don't the same names in their report lines as their old tag counterparts. So this is not necessarily an appropriate method that works for all localizations.

However, what I propose is a helper function, in the `account` module, that you give a map of what tags should be linked to what report lines, and then it converts the old tags in new tags. I believe this helper function should be in `account` due to the fact that every localization module that uses report lines will have the same issue where their old tag needs to be converted into a corresponding positive `+` or negative `-` tag.

**Comment by pedrobaeza** [comment]
This helper method should be in `openupgradelib` similar to https://github.com/OCA/openupgradelib/blob/master/openupgradelib/openupgrade_90.py#L84

**Comment by ddejong-therp** [comment]
Ah good point. Thanks.

**Comment by pedrobaeza** [comment]
Closing as stalled.
