### ISSUE TITLE
Wrong Invoice Line Link With Move Line

### ISSUE THREAD

**Issue by Murtaza-SerpentCS** [OCA/OpenUpgrade#3166]
![wrong_invoice_line_mapping](https://user-images.githubusercontent.com/52537959/156517318-f8688318-a111-4f88-b58d-2723d0d3a433.png)

**Comment by Murtaza-SerpentCS** [comment]
@pedrobaeza It critical issue we found while migration while v12 and v13

**Comment by pedrobaeza** [comment]
Sorry, but no better matching can be done with such similar data, with no product, and same label. Debit/Credit columns can't be used for matching due to precision roundings.

**Comment by Murtaza-SerpentCS** [comment]
@pedrobaeza It even not work with different lable.

**Comment by pedrobaeza** [comment]
Well, just check the conditions used to match. You are not putting even product. Any improvement to the matching algorithm that works and has no side effects is welcome.

**Comment by Murtaza-SerpentCS** [comment]
@pedrobaeza It is not necessary to have a product in every Invoice Line.
https://github.com/OCA/OpenUpgrade/blob/13.0/addons/account/migrations/13.0.1.1/post-migration.py#L235
Nothing compare for it

**Comment by pedrobaeza** [comment]
As said, if you find a better way to do the matching, please propose it.

**Comment by legalsylvain** [comment]
Hi. As it seems that this issue exists, I propose to reopen it to make it more visible : the topic is important.
(even if there is maybe no possibility to fix the issue, as pedro says).

**Comment by pedrobaeza** [comment]
There's no gain in letting opened this. It's a corner case that has no solution, and this thread is not bringing any workaround nor possible investigation lines. Please don't reopen.

**Comment by legalsylvain** [comment]
> There's no gain in letting opened this 

To make it visible, as said, and mark it as valid.

> this thread is not bringing any workaround nor possible investigation lines

Pedro, you closed this 2 minutes after the creation. It's not much.
Perhaps a little more time would allow other people (like @OCA/openupgrade-maintainers) to participate in this topic.

On my side, I would have some thoughts to bring but I have to think about it a bit. Please reconsider.

**Comment by pedrobaeza** [comment]
This has been discussed for a long in other issues. When you have something valuable to bring, we can reopen this, or maybe one of the others with more context and investigation paths.
