### ISSUE TITLE
trying to data migration from odoo 13 to odoo 14 using openupgrade

### ISSUE THREAD

**Issue by sunayana-kolekar** [OCA/OpenUpgrade#3168]
for data migration from odoo 13 to odoo 14 using openupgrade i tried below steps
1.Downloaded openupgrade 14 and copied addons of odoo14 and addons of openupgrade 13 as addons of openupgrade 14 is not ready.also odoo_bin file is not there so i take it from odoo 14
2.In configuration script path-/opt/OpenUpgrade-14.0/odoo-bin
in parameters---addons-path=/opt/OpenUpgrade-14.0/addons,/opt/OpenUpgrade-14.0/odoo/addons
-p
8079
--db_user=odoo10c
--update=all
--database=walplast_data_migration
--stop-after-init
after this I restarted pycharm service then raised following error.
i am using python 3.8
![Screenshot from 2022-03-03 18-25-45](https://user-images.githubusercontent.com/98938427/156713760-688689e1-32e8-4ea4-9552-cd83463855ce.png)

**Comment by legalsylvain** [comment]
Please follow the instruction of openupgrade.

https://oca.github.io/OpenUpgrade/migration_details.html#get-the-code-from-openupgrade-and-dependencies
