### ISSUE TITLE
Help to migrate a module with changed name

### ISSUE THREAD

**Issue by csrocha** [OCA/OpenUpgrade#320]
Hello,

I'm writting an script to upgrade a module with changed name, but the pre_migration.py script is never executed. I gess It's because it's installed with the old name then how I must to work in this cases?

Thanks,
Cristian.

**Comment by pedrobaeza** [comment]
Include your module rename in the apriori.py file and it will be done: https://github.com/OpenUpgrade/OpenUpgrade/blob/8.0/openerp/addons/openupgrade_records/lib/apriori.py#L6

**Comment by csrocha** [comment]
Sorry, I understood that module is only for analysis of clean databases. Must I install this module in the migrated database? How I do that if I use the migration.py?

**Comment by pedrobaeza** [comment]
This file is also used in the migration of the base module (although the layout is a bit weird).

**Comment by csrocha** [comment]
Thanks Pedro, but I modifty apriory.py but nothing happened (I added pdb.set_trace() to check it). Migrated.py don't install the module, but the migrated database is a result of this. Then I must install this module in the original database, I guess. That's right? That step it's not in the documentation.

**Comment by legalsylvain** [comment]
> Then I must install this module in the original database, I guess. That's right? 

I don't understand. The code that pedro mention allow to rename an installed module during an upgrade. Is your module installed (before the migration) ?

**Comment by csrocha** [comment]
@legalsylvain , I haven't installed that module in any way. My question is if I need to install it before execute the migration in the original database.

**Comment by legalsylvain** [comment]
So ... in that case, you have to install the module before upgrading, and if the name had changed between the two 2 major versions, use the @pedrobaeza's trick.

**Comment by StefanRijnhart** [comment]
@csrocha but why do you need the migration to run if you did not have the old version of the module installed?

**Comment by csrocha** [comment]
@StefanRijnhart , I have installed the old one, but not the new one, in the v7 database. Now I'm trying to install the new one (It's 8v but with old api) in the v7 database, keeping both before migration. I expect to remove the old one in the v8 server when migration has ended.

**Comment by StefanRijnhart** [comment]
Oh, please don't install the version V8 in the V7 database. Apriory.py is the correct location for module renames. It should run the migration fine if the versioned migration directory is aligned with the module version (e.g. 8.0.1.1 if the version 8 of the module has version '1.1' in its **openerp**.py). Did the version number in this file change at all from 7 to 8?
