### ISSUE TITLE
[RFC] Implement ir.config_parameter unique violation to XML-ID creation

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/OpenUpgrade#3225]
Inspired by https://github.com/odoo/odoo/pull/89389#issuecomment-1108452465

**Comment by StefanRijnhart** [comment]
Isn't this something that is rather rare? I think mail.default.from is the first case I've ever seen. Also, while the feature is generally useful from a framework perspective, isn't this something that belongs in core Odoo?

**Comment by pedrobaeza** [comment]
Well, it's not very frequent, but it can happen. Odoo is not going to add it on the framework, as it considers it something of migrations.

**Comment by pedrobaeza** [comment]
Closing as finally not a good idea at all (seen also for other unique records like res.country and so on). This should be handled manually.
