### ISSUE TITLE
[12.0 --> 13.0] Product migration

### ISSUE THREAD

**Issue by baba75** [OCA/OpenUpgrade#3230]
Hello, I got this error:
```
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "product_product_combination_unique"
DETAIL:  Key (product_tmpl_id, combination_indices)=(3596, ) already exists.
```
I read about it in previously closed issues. The fact is that I do not have such a product template id anywhere in my database. Where should I look for it to fix it?
Thank you.

**Comment by pedrobaeza** [comment]
Duplicated of #2983, and it was fixed with https://github.com/OCA/OpenUpgrade/pull/3011. You shouldn't have the update code.
