### ISSUE TITLE
Upgrade fail on product module

### ISSUE THREAD

**Issue by yomeuh** [OCA/OpenUpgrade#325]
Hi everybody
I'm trying the migration of my database from v7 to v8 but I have one error when the process manage the _product_ module:

```
2015-06-29 21:29:24,619 19389 INFO coop_last_migrated OpenUpgrade: product: loading migrations/8.0.1.1/modified_data.xml
2015-06-29 21:29:24,714 19389 ERROR coop_last_migrated openerp.sql_db: bad query:  
INSERT INTO "product_pricelist_item" ("id", "min_quantity", "base", "price_discount", "sequence", "create_uid", "write_uid", "create_date", "write_date") VALUES(nextval('product_pricelist_item_id_seq'), 0, '-1', '0.0000', 1000, 1, 1, (now() at time zone 'UTC'), (now() at time zone 'UTC')) RETURNING id

Traceback (most recent call last):
File "/var/tmp/openupgrade/8.0/server/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
IntegrityError: null value in column "price_version_id" violates not-null constraint
```

If I delete the module from my database, the migration goes to the end. **But i'd like to keep these data.**

And by the way, what about this error that do not stop the migration:

```
2015-06-29 21:28:51,575 19389 ERROR coop_last_migrated openerp.sql_db: bad query:
ALTER TABLE "mail_followers" ADD CONSTRAINT "mail_followers_mail_followers_res_partner_res_model_id_uniq" unique(res_model,res_id,partner_id)

Traceback (most recent call last):
File "/var/tmp/openupgrade/8.0/server/openerp/sql_db.py", line 234, in execute
res = self._obj.execute(query, params)
IntegrityError: could not create unique index "mail_followers_mail_followers_res_partner_res_model_id_uniq"
DETAIL: Key (res_model, res_id, partner_id)=(account.invoice, 572, 291) is duplicated.

2015-06-29 21:28:51,595 19389 WARNING coop_last_migrated openerp.models.schema: Table 'mail_followers': unable to add 'unique(res_model,res_id,partner_id)' constraint !
If you want to have it, you should update the records and execute manually:
ALTER TABLE "mail_followers" ADD CONSTRAINT "mail_followers_mail_followers_res_partner_res_model_id_uniq" unique(res_model,res_id,partner_id)
```

Thanks for your works!

**Comment by yomeuh** [comment]
Actually, I suppose the error described before is the cause the migration failed, but the log ended like this:

```
2015-06-29 21:29:24,714 19389 ERROR coop_last_migrated openerp.modules.loading: Error executing post migration script for module product
`-> procurement
   `-> stock
: 'ascii' codec can't encode character u'\xab' in position 69: ordinal not in range(128)

2015-06-29 21:29:24,716 19389 CRITICAL coop_last_migrated openerp.service.server: Failed to initialize database `coop_last_migrated`.

Traceback (most recent call last):
File "/var/tmp/openupgrade/8.0/server/openerp/service/server.py", line 919, in preload_registries
    registry = RegistryManager.new(dbname, update_module=update_module)
File "/var/tmp/openupgrade/8.0/server/openerp/modules/registry.py", line 370, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
File "/var/tmp/openupgrade/8.0/server/openerp/modules/loading.py", line 394, in load_modules
force, status, report, loaded_modules, update_module, upg_registry)
File "/var/tmp/openupgrade/8.0/server/openerp/modules/loading.py", line 286, in load_marked_modules
loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks, upg_registry=upg_registry)
File "/var/tmp/openupgrade/8.0/server/openerp/modules/loading.py", line 208, in load_module_graph
migrations.migrate_module(package, 'post')
File "/var/tmp/openupgrade/8.0/server/openerp/modules/migration.py", line 179, in migrate_module
mod.migrate(self.cr, pkg.installed_version)
File "/var/tmp/openupgrade/8.0/server/openerp/openupgrade/openupgrade.py", line 870, in wrapped_function
(module, filename, str(e).decode('utf8')))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xab' in position 69: ordinal not in range(128)
```

**Comment by StefanRijnhart** [comment]
Sorry for missing your issue. Guess I'm too late now but if you are still interested in solving this, drop a comment.

**Comment by yomeuh** [comment]
Well, even if I'm not working on it for now, I'd like having some help to finally go further with the migration.

**Comment by StefanRijnhart** [comment]
to start with the ascii error: do you know if you working in a UTF-8 locale? If not, that could explain the error. See https://pythonhosted.org/kitchen/unicode-frustrations.html#frustration-3-inconsistent-treatment-of-output (a bit below, where it actually mentions locale).

price_version_id hints at an incomplete update of the product module. It tries to add a field to a record that is present in this module's data, and that includes the missing price_version_id. The real error would have occurred earlier on, therefore.

The integrity error of the followers table is a good candidate for this. The output (account.invoice, 572, 291) hints at that it could be the case that in your 7.0 database, partner with id 291 is following invoice #572 multiple times. Could you check this on the original database?

If you are able to rerun the whole migration, please paste the full logs somewhere (pastebin etc).

**Comment by yomeuh** [comment]
Thanks for the help.
I'm working with a UTF8 locale 'fr_CA.UTF-8', but this error doesn't seem to affect the process.

I manage the duplicate key constraints in my database, it was finally pretty simple. But I can't resolve the problem on 'product_pricelist_item' which I don't understand. Even if I delete all pricelist versions, the error still happens.

Here is the [last log](http://pastebin.com/M25gWs8r) 

Thanks for your help

**Comment by yomeuh** [comment]
Migration of product module seems to fail when load_data is called in post_migration.py.
And in the xml file, there is this record:
<record id="item0" model="product.pricelist.item"><field name="sequence">1000</field>
            </record>
with no price_version_id specified...
Why is this record item0 inserted in the database?

**Comment by StefanRijnhart** [comment]
I'm baffled by this case. The offending entry in addons/product/migrations/8.0.1.1/modified_data.xml attempts to update the sequence of the pricelist item included in the product module's data entries. Apparently, its reference 'item0' cannot be resolved so that a new item is created which then has missing required fields.

The mystery is that in line 498 of the log the original data file is loaded. While the data entries are set to _noupdate_, they will still be created when they had been removed previously so the 'item0' record is pretty much guaranteed to exists when the OpenUpgrade data loading kicks in a couple of lines below. This could have been caused by errors in the load_data call for instance, but it looks alright to me and it has not been modified since I used it in my last successful migration.

Can you check to see what the _product.item0_ xmlid refers to in your ir_model_data table, and what that entry looks like in the product_pricelist_item?

**Comment by yomeuh** [comment]
Here is what it looks like in my db to migrate:

> #select id,name,module,model,res_id from ir_model_data where name like '%item0%';
>   id  | name  |  module  |         model          | res_id 
> ------+-------+----------+------------------------+--------
>  2809 | item0 | product  | product.pricelist.item |      1
>  6128 | item0 | purchase | product.pricelist.item |      2
> 
> #select id,name,price_version_id from product_pricelist_item where id=1 or id=2;
>  id |              name               | price_version_id 
> ----+---------------------------------+------------------
>   2 | Default Purchase Pricelist Line |                2

Isn't it the problem: 2 elements in ir_model_data for item0 but only one is in the product_pricelist_item table?

**Comment by StefanRijnhart** [comment]
Yes, that must be it! The record for xmlid product.item0 is missing. In earlier versions of Odoo/OpenERP the deletion of records could lead to orphaned items in this table. At update time, the noupdate record in the product data file is ignored because Odoo thinks it already exists. But when OpenUpgrade forces to load the value of a new field the migration breaks because the record does not actually exist, and the update is treated as an incomplete insert.

Try 

```
delete from ir_model_data where id = 2809;
```

And rerun the migration.
