### ISSUE TITLE
How to migrate Odoo 12 to latest version CE

### ISSUE THREAD

**Issue by ajaydoyenhub** [OCA/OpenUpgrade#3254]
I'm working on migrating Odoo 12 to the latest version of CE, I followed your doc, but It's not very clear to me. 
Actually, I'm upgrading for the first time, I don't know how to migrate the old version to the latest.

If anyone has any please help me, I would be very thankful.

Thank You

**Comment by pedrobaeza** [comment]
Please use discussions for this kind of questions, and not being more specific about a problem, nobody will be able to help you.
