### ISSUE TITLE
Lack in progress feedback on OpenUpgrade scripts

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/OpenUpgrade#326]
One of the problems I'm facing lately with the migration of large DBs is that the process hangs for very big times without no visual feedback of what is being done, because on several migration scripts there's no clue about what is being done across the multiple methods that run (only at the beginning of the script with the pre or post-script log entry), making very difficult to identify bottlenecks to optimize.

I propose to:
- Include an openupgrade decorator `@openupgrade.logging(logging)` that logs a line indicating that the method name is being executed
- Include a method that allows to slice an operation being done over an iterator in chunks of a determined size (passed by argument), to give feedback in the log once on each chunk. This way, you don't bloat the log, but control the progress of the current task and you can also estimate total times with the log timestamps. It can even being also estimated between chunks taking measures. For example:

```
Creating quants processing pickings (1-1000/192345)
Creating quants processing pickings (1001-2000/192345)
Creating quants processing pickings (2001-3000/192345)
...
```

**Comment by legalsylvain** [comment]
:+1:

**Comment by bwrsandman** [comment]
Personally, I am a big fan of the [progressbar==2.3](https://pypi.python.org/pypi/progressbar/2.2) library

**Comment by pedrobaeza** [comment]
Good option indeed!

**Comment by pedrobaeza** [comment]
I have to check https://pypi.python.org/pypi/progressbar2, because it seems to have python3 support, so that can be an option to go for the progress.
