### ISSUE TITLE
[RFC] Content of Migration Issues and use of ocabot migration command

### ISSUE THREAD

**Issue by legalsylvain** [OCA/OpenUpgrade#3288]
hi all,

In each upgrade, openupgrade maintainers are creating an issue for the migration. like this one for the V14 https://github.com/OCA/OpenUpgrade/issues/2190

### Initialization of the migration Issue for 15

I just create an issue for migration 15 here : https://github.com/OCA/OpenUpgrade/issues/3287

In my opinion, initializing the issue with the list of the all the odoo modules is redundant with the main file present here : 
https://github.com/OCA/OpenUpgrade/blob/15.0/docsource/modules140-150.rst

So I'm in favour to have an empty issue and to a line per module with PR.

What do you think ?

### use of ocabot command

Previously, maintainers has to update manually the issue to make reference to each PR. See : 

![image](https://user-images.githubusercontent.com/3407482/173932760-171b1847-ea7b-42cd-8163-1927c232444e.png)

I just made a test [here](https://github.com/OCA/OpenUpgrade/issues/3287) and [here](https://github.com/OCA/OpenUpgrade/pull/3284) and using the command ``\ocabot migration module_name`` works perfectly well. 

Advantage : 
- main migration issue is automatically updated when the PR is created
- migration PR receive the milestone 15.0
- merging PR update automatically the issue.

Do you agree that from now on we should use this command to update the main issue? 

Thanks for your comment.

**Comment by pedrobaeza** [comment]
> merging PR update automatically the issue.

This is not really true. Such feature is not developed (although very interesting of course, not only here).

OK for me to use the command.

About the list, I populate it manually. It's very easy with a text editor to make some replace to get what's needed from the RST.

**Comment by legalsylvain** [comment]
> This is not really true. Such feature is not developed (although very interesting of course, not only here).

Oh ! IYou're right. Opened an issue : https://github.com/OCA/oca-github-bot/issues/189

> About the list, I populate it manually. It's very easy with a text editor to make some replace to get what's needed from the RST.

And what about to NOT pre-populate it ? 
- the info is still in the main file ``modules140-150.rst``. So a simple link at the beginning of the issue makes the job IMO.
- I fear that some extra text like ``|del|`` or ``>`` (for rename) break the current regular expression defined [here](https://github.com/OCA/oca-github-bot/blob/master/src/oca_github_bot/tasks/migration_issue_bot.py#L41) to search the line.

**Comment by pedrobaeza** [comment]
OK for me.

**Comment by StefanRijnhart** [comment]
Mmm, maybe we can then reflect the list of open module migration PRs in modules140-150.rst as well!

**Comment by legalsylvain** [comment]
> Mmm, maybe we can then reflect the list of open module migration PRs in modules140-150.rst as well!

I'm not sure. Indeed, having all the information in the same page (and available on the documentation is great). In the other hand I think it will add extra work for commiters. I mean : 

for the time being, to propose a PR : 
- make a branch / commit changes / make a PR

With your proposal : 
- make a branch / commit changes / make a PR / Get the number of the github PR and set it in the modulesxxx.rst / commit & squach changes / Push PR again --force.

What do you think ? Did I missed something ?

**Comment by legalsylvain** [comment]
FYI I renamed the issue https://github.com/OCA/OpenUpgrade/issues/2190 to be able to call ``ocabot migration`` command for 14.0 release.
However, it does'nt seems to work. https://github.com/OCA/OpenUpgrade/pull/3326 and the bot doesn't say why.

**Comment by pedrobaeza** [comment]
Already done.
