### ISSUE TITLE
Warehouse missing types of operation

### ISSUE THREAD

**Issue by ghost** [OCA/OpenUpgrade#329]
Warehouse has a new item. This is not filled with default items. This will give you an error when making a request for quotation because the deliver to field is required.

**Comment by pedrobaeza** [comment]
Can you specify which item?

**Comment by ghost** [comment]
Hi, Yeah sorry about that, could be more descriptive. The' deliver to' field has no items. You can fix it by creating warehouse operations. This is probably new in 8. 

Purchase order
![missing deliver to](https://cloud.githubusercontent.com/assets/8478649/9154398/ad3c9c4a-3e8c-11e5-8f8b-7bb12cae2daa.png)

No warehouse operations
![warehouse operations empty](https://cloud.githubusercontent.com/assets/8478649/9154399/b34f8c1e-3e8c-11e5-909d-350b4fb7597d.png)

Regards,
Maarten

**Comment by pedrobaeza** [comment]
This is already done in current migration scripts: https://github.com/OCA/OpenUpgrade/blob/8.0/addons/stock/migrations/8.0.1.1/post-migration.py#L393, and I have just checked that it works, so I close this one.
