### ISSUE TITLE
[8.0] project_mrp -> sale_service migration no cover

### ISSUE THREAD

**Issue by rafaelbn** [OCA/OpenUpgrade#331]
If you are using in OpenERP 7 module project_mrp you will loose in v7 In model product.product field project_id. This must be migrate in v8 in model product.template to auto_create_task + project_id fields from module sale_service.

**Comment by StefanRijnhart** [comment]
While this is true, lack of coverage is already reflected in https://doc.therp.nl/openupgrade/modules70-80.html, and the analysis in https://github.com/OCA/OpenUpgrade/blob/8.0/addons/sale_service/migrations/8.0.1.0/openupgrade_analysis.txt. I hope you don't mind me closing this issue therefore.

**Comment by pedrobaeza** [comment]
And thanks to @hbrunn, this gap is also filled: https://github.com/OCA/OpenUpgrade/pull/361

**Comment by StefanRijnhart** [comment]
Thanks for noting that, @pedrobaeza. That one is now merged.

**Comment by pedrobaeza** [comment]
It lasts then https://github.com/OCA/OpenUpgrade/pull/360 for 6.0 > 6.1 migration of _project_mrp_ (and the documentation is already merged saying that it's done), so please review and merge.
