### ISSUE TITLE
[RFC] adding new decorator to enable some optional features

### ISSUE THREAD

**Issue by legalsylvain** [OCA/OpenUpgrade#3346]
Following that PR https://github.com/OCA/OpenUpgrade/pull/3330#issuecomment-1163382672 that introduce some extra log, I was thinking to have a new decorator in ``openupgrade_framework`` with that pseudo code : 

```
def enable_feature("VARIABLE_NAME"):
    # Check if VARIABLE_NAME is define as an environment variable
    # and / or if a key is present in the ``config.cfg`` like : 
    # [openupgrade]
    # VARIABLE_NAME = True
    # If  yes, write a log and call the function
    Put here the code of the decorator.
```
Then regarding #3330, we could have some functions defined like 

```
@enable_feature("track_row_changes")
def initialize_openupgrade_track_row_count():
    ....

@enable_feature("track_row_changes"):
def update_openupgrade_track_row_count():
    ....
```

This could be a common way to add extra optional features.

Any point of view ? 

There is nothing urgent about this issue. Just a question for the future that can be dealt with later.

**Comment by gdgellatly** [comment]
In my experience there is a far more common situation with OpenUpgrade. Let's call it the general case, the complex case and the simple case.

The general case is a function in the upgrade script and today if we wish to disable it we must fork. It usually tries to cover all cases at expense of optimisation. 

Lets use the 12-13 account invoice line -> account move line migration. The general case works great for short complex invoices, or invoices without repeated products. If you have many 1000 line invoices you can get a 9 day migration with even a very few invoices, say less than 10,000 if they have over 1,000 lines each and sadly in this case using all the same product.

So in this case I fork and write a new function, specific for that situation. It is orders of magnitude faster (7 days to 13 minutes) using the enterprise approach and is optimised for the case that applies to nearly all countries except some of Europe and most of South America. Now you talk to most OpenUpgrade Users they often do this. But if we could solve that without forking somehow, and allow alternative implementations of functions that would be huge, but unlike this it involves choosing/disabling as well as enabling.

So my idea would be similar, something like an experimental, or alternatives folder whereby setting in config you could choose alternate functions for migration. Of course it is no big deal for me to fork, it is the loss of the code to the project

**Comment by pedrobaeza** [comment]
Closing as stalled.
