### ISSUE TITLE
use updated URL for wkhtmltopdf downloads

### ISSUE THREAD

**Issue by ashkulz** [OCA/OpenUpgrade#336]
Hello,

wkhtmltopdf has [moved the downloads provider](https://groups.google.com/d/msg/wkhtmltopdf-general/wZwTUol3mXI/GNVeyrKDdqIJ) from SourceForge to gna.org. As mentioned in the linked message, all earlier downloads have been removed from SourceForge and you are strongly advised to migrate to the new URLs. The following files in your repository will need to be updated:
- setup/win32/static/getfiles.sh

It is recommended to either subscribe to the [mailing list](https://groups.google.com/forum/#!forum/wkhtmltopdf-general) or [Twitter feed](https://twitter.com/wkhtmltopdf) to receive updates on new releases and further changes.

Thanks,
wkhtmltopdf maintainer

**Comment by StefanRijnhart** [comment]
Thanks for warning affected projects like this!

This is a fork of Odoo for migration purposes only. Wkhtmltopdf is not needed for running the migration so I am closing this issue.
