### ISSUE TITLE
migration error windows

### ISSUE THREAD

**Issue by annemarie1991** [OCA/OpenUpgrade#337]
Hello,

I am new to this, and don't understand much about the migration process... And now I am stuck with an error. Can anyone help me?

I am trying to migrate from 7.0 to 8.0. My current database is on windows. 
When the migration is at the step: 'running migration for 8.0' i am getting the error: 
'C:...........\OpenUpgrade\8.0\server\openerp-server' is not recognized as an internal or external command, operable program or batch file. 

It doesn't work if I copy the path to the environment variables. I guess because the commant that is given is the whole path, not only the last words: openerp-server.

What can I change in migrate.py to only give openerp-server as command? 
If you have an other sollution for this: you are very welcome!

Thanks in advance,
Annemarie

**Comment by StefanRijnhart** [comment]
Hi Annemarie,

running migrate.py on Windows is not supported, I'm afraid. Even running the Odoo server itself for production purposes on Windows is not recommended, let alone that anyone in the OpenUpgrade community has ever tried a migration. My suggestion would be for you to use migrate.py on a Linux virtual machine. You can export your database from the OpenERP installation on Windows and copy it to the Linux VM, and copy the resulting upgraded database back to Windows afterwards to import in your Odoo 8 instance.
