### ISSUE TITLE
[14.0->15.0]  Migrating to v15

### ISSUE THREAD

**Issue by Robrechtc** [OCA/OpenUpgrade#3387]
Hey folks, 

I'm trying to upgrade a v14 Odoo instance to v15. I've run into the following issues: 

If I try to run the instance locally with Odoo v14 sources, the [function _raise_view_error](https://github.com/OCA/OpenUpgrade/blob/15.0/openupgrade_framework/odoo_patch/odoo/addons/base/models/ir_ui_view.py#L30) does not exist, which raises an error - this makes sense, as this function was only introduced in Odoo 15. 

If I try to run the instance locally with Odoo v15 sources, the database is invalid, which also makes sense, because the asset management was changed significantly from Odoo v14 to Odoo v15, and the ir.asset model does not exist yet. 

The openupgrade_framework using a v15 function has left me confused as to whether or not I should be running Odoo 14 or 15 when trying to migrate. I would assume I run the upgrade script on Odoo 14 and only after it's completed do I run Odoo 15, but this is not mentioned in the docs so I am unsure. 

Kind regards,
Robrecht

**Comment by legalsylvain** [comment]
Hi. 

> If I try to run the instance locally with Odoo v14 sources, the [function _raise_view_error](https://github.com/OCA/OpenUpgrade/blob/15.0/openupgrade_framework/odoo_patch/odoo/addons/base/models/ir_ui_view.py#L30) does not exist

running odoo 14 with 15 modules doesn't makes sense in Odoo.

To migrate from 14 to 15, you should run Odoo V15 with openupgrade V15 code.

Note : the V15 migration is not completed. So if you have trouble, please open a PR with fixes.

Regards.
