### ISSUE TITLE
[12.0] ==> [13.0] issue with invoices , all invoices are marked as entry account.move

### ISSUE THREAD

**Issue by bouktaibMohssin** [OCA/OpenUpgrade#3511]
after migrating the databsae from odoo12 to odoo13 , there were some issue with the invoices , the invoice are not deleted but all of them are marked as entry account.move , partner and sale orders are not linked anymore to invoice , is this a normal behaviour from openupgrade migration code ?

Odoo12

![image](https://user-images.githubusercontent.com/17483600/183409798-d763633e-5726-4f90-b87c-b646b96ac9a2.png)

![image](https://user-images.githubusercontent.com/17483600/183410221-e2a6cf21-fbf0-4547-b631-f9123a0f9eaf.png)

![image](https://user-images.githubusercontent.com/17483600/183410344-83c52621-387d-4150-9d1d-05567d1bb5bd.png)

Odoo13

![image](https://user-images.githubusercontent.com/17483600/183409869-89b46b69-6b91-4d04-8820-e06f4728e715.png)

![image](https://user-images.githubusercontent.com/17483600/183410296-97ae3e70-08c5-418d-bc7a-cc210e890b7e.png)

![image](https://user-images.githubusercontent.com/17483600/183410417-d6a9138d-4c85-43aa-ad26-8106885884b5.png)

**Comment by pedrobaeza** [comment]
You have any kind of change in your DB that makes the account entries to not be recognized as invoices linking their corresponding information.

But unless further information leading to know a possible problem with OpenUpgrade, this is not something to be handled as an issue.
