### ISSUE TITLE
8.0 : NameError: name 'openupgrade' is not defined

### ISSUE THREAD

**Issue by judewinne** [OCA/OpenUpgrade#3533]
## Module
openupgrade

## Describe the bug
OpenUpgrade/openerp-server
OpenUpgrade/openerp/openupgrade/openupgrade_tools.py", line 1, in <module>
    openupgrade.py
NameError: name 'openupgrade' is not defined

## To Reproduce
1. install openerp 8 and openupgradelib on ubuntu 20
2. launch openerp-server

What should we do to fix that?

**Comment by pedrobaeza** [comment]
It seems you are not launching correctly the OpenUpgrade server, but that's out of scope of this issue tracker.

**Comment by judewinne** [comment]
Ok but i follow all doc. How should I do that?

**Comment by pedrobaeza** [comment]
Publish a talk at Discussions and indicate all you have done with all the possible detail, and with that, people may start to figure out what the problem is.
