### ISSUE TITLE
[14.0-->15.0] Field "work_location" does not exist in model "res.users"

### ISSUE THREAD

**Issue by eguane** [OCA/OpenUpgrade#3540]
I'am testing the migration script currently done from V14 to V15

## Module
HR 

## Describe the bug
 File "/home/chris/odoo/odoo15C/odoo/tools/convert.py", line 691, in _tag_root
    raise ParseError(msg) from None  # Restart with "--log-handler odoo.tools.convert:DEBUG" for complete traceback
odoo.tools.convert.ParseError: while parsing /home/chris/odoo/odoo15C/addons/hr/views/res_users.xml:9
Error while validating view near:

                        <group>
                            <field name="employee_parent_id" attrs="{'readonly': [('can_edit', '=', False)]}"/>
                            <field name="coach_id" attrs="{'readonly': [('can_edit', '=', False)]}"/>
                        </group>
                    </group>

Field "work_location" does not exist in model "res.users"

## To Reproduce
V14 to V15

**Comment by legalsylvain** [comment]
Hi @eguane. Thanks for reporting.

on hr module : 
V14 : work_location exists, see : https://github.com/odoo/odoo/blob/14.0/addons/hr/models/res_users.py#L29
V15 : work_location_id exists : see : https://github.com/odoo/odoo/blob/15.0/addons/hr/models/res_users.py#L94

however, they are non stored fields, so no migrations scripts is required.

As v15 CI is green, I think that the migration script of ``hr`` is ok. Could you check if this bug occurs in a migration 14 -> 15 with a fresh database with hr installed ? I suspect custom changes in your views.

Closing in the meantime. Do not hesitate to reopen after further investigations.

**Comment by eguane** [comment]
> Hi @eguane. Thanks for reporting.
> 
> on hr module : V14 : work_location exists, see : https://github.com/odoo/odoo/blob/14.0/addons/hr/models/res_users.py#L29 V15 : work_location_id exists : see : https://github.com/odoo/odoo/blob/15.0/addons/hr/models/res_users.py#L94
> 
> however, they are non stored fields, so no migrations scripts is required.
> 
> As v15 CI is green, I think that the migration script of `hr` is ok. Could you check if this bug occurs in a migration 14 -> 15 with a fresh database with hr installed ? I suspect custom changes in your views.
> 
> Closing in the meantime. Do not hesitate to reopen after further investigations.

Hi, this issue is related with HR installed module. tested with a fresh install with HR module installed and the issue is still existing. Remove HR module before uprgading solve the problem.

**Comment by legalsylvain** [comment]
Hi. Thanks for your investigation. 
@MiquelRForgeFlow,  @sang250399, any idea ?

**Comment by MiquelRForgeFlow** [comment]
> Remove HR module before uprgading solve the problem.

No need. Just delete `hr.res_users_view_form_profile` record before migrating. It should work. If not, just execute the query beofre migrating:

```sql
DELETE FROM ir_ui_view iuv
USING ir_model_data imd
WHERE imd.model = 'ir.ui.view' AND imd.res_id = iuv.id AND imd.noupdate IS DISTINCT FROM TRUE
```

**Comment by feliperocha00** [comment]
> > Remove HR module before uprgading solve the problem.
> 
> No need. Just delete `hr.res_users_view_form_profile` record before migrating. It should work. If not, just execute the query beofre migrating:
> 
> ```sql
> DELETE FROM ir_ui_view iuv
> USING ir_model_data imd
> WHERE imd.model = 'ir.ui.view' AND imd.res_id = iuv.id AND imd.noupdate IS DISTINCT FROM TRUE
> ```

I'm facing the same problem, but when I try this solution, I'm getting several errors about foreign key constraint violation. 
![image](https://github.com/OCA/OpenUpgrade/assets/98479839/62c06305-ba1c-409f-bec0-047b8c07fe4f)

Any thoughts?
