### ISSUE TITLE
[14.0-->15.0] snailmail_account

### ISSUE THREAD

**Issue by eguane** [OCA/OpenUpgrade#3541]
## Module
The name of the module that has a bug.
snailmail_account

## Describe the bug
File "/home/chris/odoo/odoo15C/odoo/tools/convert.py", line 691, in _tag_root
    raise ParseError(msg) from None  # Restart with "--log-handler odoo.tools.convert:DEBUG" for complete traceback
odoo.tools.convert.ParseError: while parsing /home/chris/odoo/odoo15C/addons/snailmail_account/wizard/account_invoice_send_views.xml:4
Error while validating view near:

                    </div>
                    
                    <field name="composition_mode" invisible="1"/>
                    <field name="invoice_ids" invisible="1"/>
                    <field name="email_from" invisible="1"/>

Le champ "edi_format_ids" n'existe pas dans le modèle "account.invoice.send"

## To Reproduce
V14 to V15

1. fresh V14 database installation Belgium localisation with demo data.

**Comment by MiquelRForgeFlow** [comment]
Just delete `account_edi.account_invoice_send_inherit_account_wizard_form` record before migrating.
