### ISSUE TITLE
[14.0-->15.0]  stock_account

### ISSUE THREAD

**Issue by eguane** [OCA/OpenUpgrade#3544]
Upgrade from v14 to v 15 with just insallled database

## Module
stock_account

## Describe the bug
odoo.tools.convert.ParseError: while parsing /home/chris/odoo/odoo15C/addons/stock_account/security/stock_account_security.xml:10, somewhere inside
<record id="group_lot_on_invoice" model="res.groups">
        <field name="name">Display Serial &amp; Lot Number on Invoices</field>
        <field name="category_id" ref="base.module_category_hidden"/>
    </record>

Probably due to script migration not yet existingt

**Comment by pedrobaeza** [comment]
This module is not yet with migration scripts.
