### ISSUE TITLE
Error updating 13 --> 14 using latest scripts with base/data/ir_module_module.xml

### ISSUE THREAD

**Issue by clarkj239** [OCA/OpenUpgrade#3566]
Error using latest ([14.0.1.0.1](https://github.com/OCA/OpenUpgrade/commit/31961c5dd426394e45673a3a0647a85eb89c08f3)) 
Openupgrade script 13 --> 14 on both production DB & a freshly created demo DB:

[Odoo Openupgarde Error.txt](https://github.com/OCA/OpenUpgrade/files/9581768/Odoo.Openupgarde.Error.txt)

**Comment by StefanRijnhart** [comment]
This seems related: https://github.com/OCA/OpenUpgrade/blob/14.0/openupgrade_scripts/scripts/base/14.0.1.3/pre-migrate.py#L66-L67. In your 13.0 database, does `base.module_category_operations_timesheets` refer to a module category?

You did not include the full log. It is therefore unclear whether that pre-migration script has run. Can you check and if possible, include the full log?

**Comment by laurentolivier** [comment]
Same type of issue there migrating from 13-->14.
Error happens while loading base/data/ir_module_module.xml.
The module category manufacturing_manufacturing doesn't  exist but is called for some modules there.
 

[OpenUpgrade  module categ error.txt](https://github.com/OCA/OpenUpgrade/files/10238932/OpenUpgrade.module.categ.error.txt)

**Comment by pedrobaeza** [comment]
Closing as stalled.
