### ISSUE TITLE
UnicodeDecodeError: 'gbk' codec can't decode byte 0xa6 in position 193: illegal multibyte sequence

### ISSUE THREAD

**Issue by alanljj** [OCA/OpenUpgrade#3567]
when run
pip install git+https://github.com/OCA/openupgradelib.git@master#egg=openupgradelib
will got is error:
UnicodeDecodeError: 'gbk' codec can't decode byte 0xa6 in position 193: illegal multibyte sequence

on python 3.7.9

after change setup.py file on line 13 to:
with open('HISTORY.rst','r', encoding='UTF-8') as history_file:

problem solved.

**Comment by pedrobaeza** [comment]
Sorry, but this is not something related to the migration scripts, and there are very few details.

**Comment by legalsylvain** [comment]
@alanljj Could you make a PR against OCA/openupgradelib project ?
