### ISSUE TITLE
Migration 14.0 -> 15.0 Issue with Project, Tasks, timesheet, invoices

### ISSUE THREAD

**Issue by NICO-SOLUTIONS** [OCA/OpenUpgrade#3604]
The problem affects to the modules "project" & "timesheets" & Invoices

After upgrading a db from 14.0 to 15.0 i get the following problems.
- not able to enter project view

relevant Result:
    return field_cache[record._ids[0]]
KeyError: 11

    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: 'project.project(11,).timesheet_count'

The above exception was the direct cause of the following exception:

    raise exception.with_traceback(None) from new_cause
ValueError: Invalid field project.project.allowed_internal_user_ids in leaf ('allowed_internal_user_ids', 'in', [6])

The same happens when trying to access the timesheet or the invoice view...

ValueError: Invalid field project.project.allowed_internal_user_ids in leaf ('allowed_internal_user_ids', 'in', [6])

Simply Updating the modules doesnt help..

In additipn... it seems like i do have a problem with the payment entries, as they dont seem to be linked to a payment method. Due to this  i had to to delete all payments and unreconcile them before upgrading... Possible that this could lead to this behaviour? With the original data the logs tell me, that i have to define a payment method for my payments.... something is srewed up here...

Any hints for solving this would be highly appreciated

regards
Nils

**Comment by pedrobaeza** [comment]
The coverage of the modules with migration scripts is still low in the main branch, so the problems seems to be to migrate a DB with modules non covered. Please see such coverage in https://github.com/OCA/OpenUpgrade/blob/15.0/docsource/modules140-150.rst

**Comment by NICO-SOLUTIONS** [comment]
hey pedrobaeza,
thanks for you reply. I already chaeckd the coverage of the modules. I am trying to support the upgrade procedure but in this case i got stuck! I will dig deeper and see if i can find out whats going on...

**Comment by pedrobaeza** [comment]
It seems there's a remaining domain with `allowed_internal_user_ids` field in it.

**Comment by NICO-SOLUTIONS** [comment]
That´s what confuses me a bit...
As it is part of the project model. Which should be covered by the upgrade script right?

Checking the following now...

- payment
- sale_project_account
- sale_timesheet

**Comment by TomaszKn** [comment]
I confirm.
I'm have the same problem.

**Comment by OKT96** [comment]
hr_timesheet could also be the reason, maybe its missing here: https://github.com/OCA/OpenUpgrade/pull/3306

> That´s what confuses me a bit... As it is part of the project model. Which should be covered by the upgrade script right?
> 
> Checking the following now...
> 
> * payment
> * sale_project_account
> * sale_timesheet
