### ISSUE TITLE
[Proposal] Make deferred migration generic?

### ISSUE THREAD

**Issue by blaggacao** [OCA/OpenUpgrade#366]
# Problem

The library is useful also in many kinds of custom workflows, which are differing from the current reference case"migrate 7.0 to 8.0". Some functionality, by design, is very specific to this use case. Hacky temporal solutions can be made, but are not in favor of the assumed goal of incentivizing the use of OpenUpgrade by a wider user base.
# Proposal

At the moment, the (single) deferred migration method is called in the `loading.py` explicitly. This means that there is just one single file `deferred_80.py` linked, which additionaly is in a central location.
The proposal consists in making this functionality more generic, moving the deferred location to the standard migrations directorIES (`pkg/migration` & `base/maintenance/migrations`).
`pgk/migrations` being deferred and executed in the migrations inherent toposort order
`base/maintenance/migrations` being deferred and executed last, so execute order can be controlled better (usability).
# Votes

Votes welcome, if we should implement this func, please post your opinion. (:smile: @max3903 )

**Comment by pedrobaeza** [comment]
That adds a complicated layer for just easying migration script modularity. Deferred methods are very rare and very limited. I don't think it deserves the time. :-1:

**Comment by StefanRijnhart** [comment]
I tend to agree with Pedro here. What is your use case?

**Comment by blaggacao** [comment]
Ok, thanks for closing. I don't remember well, but I think it had to do with the merging use case, I raised once in some discussion..
