### ISSUE TITLE
Branch 9.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/OpenUpgrade#367]
Now that the data model has been freezed, we can create the 9.0 branch and get analysis file. What do you think?

**Comment by zuher83** [comment]
+1 Good idea!

**Comment by max3903** [comment]
:+1:

**Comment by StefanRijnhart** [comment]
Yes indeed. I should be able to do some work on this next week, but if you don't want to wait, go ahead!

**Comment by pedrobaeza** [comment]
I prefer you to do it as you are very used to due to the work on previous versions, but let me know if I can help.

**Comment by StefanRijnhart** [comment]
WIP here: https://github.com/StefanRijnhart/OpenUpgrade/tree/9.0-port_framework

It should be ready to start testing the remote comparison. I expect the internals of the new API to skew the analysis and needs work.

**Comment by pedrobaeza** [comment]
Looks good at first sight. Let's see if there's no problem in the detection due to new/old API.

**Comment by nostahl** [comment]
hows the odoo 9 progress for migrating from 8 to 9?

**Comment by StefanRijnhart** [comment]
@nostahl https://github.com/OCA/OpenUpgrade/pull/380 needs reviews. In that PR, a couple of follow up branches have been mentioned that add necessary changes to the analysis mechanism to deal with some details of the new API, and add the resulting analysis. From there, we can start developing the migration scripts.

**Comment by f-ewald** [comment]
@StefanRijnhart  Is there any roadmap or any time schedule?
Thanks for the great project, looking forward to it.

**Comment by StefanRijnhart** [comment]
Well, https://github.com/OCA/OpenUpgrade/pull/382 is now waiting for reviews. Then I will update the analysis branch with any recent changes in Odoo 9.0 if any, and then we can all get to work. On most of the regular contributors' parts, they will write migration scripts as per customer demand which should now still be quite low with Odoo 9.0 still maturing. I will try to get started on base and accounting sometime soon if I have time, but AFAIK not much more is planned.

**Comment by f-ewald** [comment]
Ok that sounds promising, thank you for the information.

**Comment by asimzaidi** [comment]
Any idea when upgrade form 8.0 to 9.0 community edition will be available? Is there any documentation for upgrade that I can go through? I am a developer myself but am having hard time finding any documentation on that

**Comment by mmalorni** [comment]
Hi, I have a couple developers that are available to work on this module. We could work on the contacts, projects and crm modules as a start for conversion. Anything else we can do to move forward? We plan to move to 9.0 internally ASAP. Our custom modules and dependencies are all updated to 9.0. Just need to transfer data. I would rather we use the upgrade tool than do it manually.

**Comment by pedrobaeza** [comment]
OK, thanks for the disposition. You can start developing the migration scripts comparing by yourself the differences, extracting the analysis file, or waiting that @StefanRijnhart finish his current analysis work, and come back here to propose that scripts with PRs that will be reviewed. You can find a bit information here: https://doc.therp.nl/openupgrade

**Comment by StefanRijnhart** [comment]
I'm restarting a new analysis now, because the analysis I originally prepared was from more than a month ago. You should be able to expect a PR for this by tomorrow.

**Comment by StefanRijnhart** [comment]
In creating the analysis, I encountered this problem that needs to be fixed first. https://github.com/OCA/OpenUpgrade/pull/398

**Comment by StefanRijnhart** [comment]
Thanks for the quick review of #398! Here is the analysis PR: https://github.com/OCA/OpenUpgrade/pull/399

**Comment by nostahl** [comment]
any idea how long till you could migrate opportunities / leads from odoo 8 to a new 9 server?

**Comment by pedrobaeza** [comment]
No. Nobody has expressed for now interest in doing (voluntarily) such work. If you are interested, you can assign yourself or pay someone to do it.
