### ISSUE TITLE
Obsolete modules after migration

### ISSUE THREAD

**Issue by ghost** [OCA/OpenUpgrade#368]
Hello, does anyone knows why after migrating from version 7 to 8 in the latest version obsolete modules still appear in state "no installed"?, I mean its appear as if you could install the latest version (8 in this case), I wonder how it could do to cleaning the list of modules.

**Comment by pedrobaeza** [comment]
What modules are you talking about? Anyway, you can cleanly uninstall them I think

**Comment by ghost** [comment]
Whatever module, I mean, I got "X module" and I've uninstalled it in version 7.0 because this module is obsolete in the version 8 (destination) so I not need it anymore but this module still appear in the version 8 even when I don't have the code. So I need to update the module list, I've done, I click on the button "Update module list" but the module still there.

**Comment by hbrunn** [comment]
https://github.com/OCA/server-tools/tree/8.0/database_cleanup was written for this purpose (and some others)

**Comment by ghost** [comment]
That's what I need. Thank you.
