### ISSUE TITLE
[6.1->7.0] Error if the 'warning' module is installed

### ISSUE THREAD

**Issue by sebalix** [OCA/OpenUpgrade#369]
The output:

```
ERROR bad query: INSERT INTO res_partner (name, active) VALUES(E'Administrator',true) RETURNING id
Traceback (most recent call last):
  File "/home/openerp/oerp/server/openerp/sql_db.py", line 226, in execute
    res = self._obj.execute(query, params)
IntegrityError: ERREUR:  une valeur NULL viole la contrainte NOT NULL de la colonne « purchase_warn »

2015-09-18 14:19:07,963 24769 ERROR test_61to70 openerp.sql_db: bad query: INSERT INTO res_partner (name, active) VALUES(E'Administrator',true) RETURNING id
Traceback (most recent call last):
  File "/home/openerp/oerp/server/openerp/sql_db.py", line 226, in execute
    res = self._obj.execute(query, params)
IntegrityError: ERREUR:  une valeur NULL viole la contrainte NOT NULL de la colonne « purchase_warn »
```

The `warning` module set some required fields on `res.partner` (`purchase_warn`, `picking_warn`, `sale_warn` and `invoice_warn`, with `no-message` as a default value for all of them), so the SQL query at https://github.com/OCA/OpenUpgrade/blob/7.0/openerp/addons/base/migrations/7.0.1.3/pre-migration.py#L180 fails.

**Comment by pedrobaeza** [comment]
Uhm, this has difficult solution just right now, because we can't use ORM as this a pre-migration script, and I'm not sure if we can move that part to the post part. A tricky solution for your current migration is to add in the script the corresponding values or to remove the constraints in Postgres.

**Comment by sebalix** [comment]
Yes, I'm working on a fix in the `pre-migration.py` script, I will make a PR right after.

**Comment by StefanRijnhart** [comment]
Fixed by the related PR. Thanks!
