### ISSUE TITLE
[v10 - v13] Repo Location for upgrade_analysis / openupgrade_records

### ISSUE THREAD

**Issue by hussain** [OCA/OpenUpgrade#3715]
I'm looking for the upgrade analysis module but it seems I cannot find it! 

I need it for v11 upgrade analysis of customer modules.

`openupgrade_records` module exist from v6.1 until [v9.0](https://github.com/OCA/OpenUpgrade/tree/9.0/openerp/addons/openupgrade_records)
`upgrade_analysis` module exist from [v14.0](https://github.com/OCA/server-tools/tree/14.0/upgrade_analysis) to [v15.0](https://github.com/OCA/server-tools/tree/15.0/upgrade_analysis)

**Comment by pedrobaeza** [comment]
https://github.com/OCA/OpenUpgrade/tree/10.0/odoo/addons/openupgrade_records
