### ISSUE TITLE
[11.0][HowTo] Upgrade Analysis does no pickup fields of custom module

### ISSUE THREAD

**Issue by hussain** [OCA/OpenUpgrade#3717]
I'm testing upgrade 11.0 => 15.0 for custom modules, and hit something I could not pass trough!

#### Case
I have a custom module `branch` which have its own fields and adding field `branch_id` to many odoo standard modules i.e. `res.partner`, `account.invoice`...etc to be migrated v11 => v15

#### Odoo 11
Using [openupgrade_records](https://github.com/OCA/OpenUpgrade/tree/11.0/odoo/addons/openupgrade_records) I ran "Generate Records" successfully and got records. But there is only 1 record for `branch`.

![image](https://user-images.githubusercontent.com/31601080/218269919-6321cf84-d549-4996-a633-ea312661e0eb.png)

#### Odoo 15
I did same (using [upgrade_analysis](https://github.com/OCA/server-tools/tree/15.0/upgrade_analysis)) and got all fields of `branch` module.

![image](https://user-images.githubusercontent.com/31601080/218270054-ba805b98-c91d-47c5-82cb-7de3693849fc.png)

I did connect v15.0 to v11.0 and did the analysis, and got the files written but of course it gave me everything as new.

..
I searched for the code which generates the fields for upgrade records in both `openupgrade_records` and `upgrade_analysis` to find why no fields are picked in `openupgrade_records` while they are picked in `upgrade_analysis`, but seems I could not get where the logic is in code!
I created another simple custom module with basic stuff, and same result (no fields, except 1 record in Upgrade Records).

Is there a special way to handle custom modules?

**Comment by hussain** [comment]
me and my silly mistakes!

ok, this is learning curve.

doing analysis should be in same environment of upgrade, so for v11 I used Openupgrade version to run v11 and follow the steps in documentation.

I think we need a place to document those assumptions, to give people head start.

here is what I have in mind: (donnu where to put, how to start, where to discuss to start with!)

- Environment Setup
- Upgrade Analysis (Standard Odoo, OCA, Custome modules)
- Data Integrity Tools (there are cases we know possible to do in Odoo, but data will fail during upgrade i.e. UoM Category with multiple reference UoM , or Journals with no selected payment method will fail payments migration ... etc)
- Known Issues (environment related, data related .... it is very rare to be openupgrade related)

**Comment by pedrobaeza** [comment]
This should go on the `upgrade_analysis` repository.
