### ISSUE TITLE
[13.0 --> 14.0] Coulde not displayed selected image when use ir_attachment.location to db

### ISSUE THREAD

**Issue by AungKoKoLin1997** [OCA/OpenUpgrade#3721]
Step to reproduce:

- Create database with demo in v13.0 and install sale module
- Change ir_attachment.location to db in `system parameters`
- Add new product with image or update image in existing product
- Migrate to 14.0

After migration to 14.0, the product image that are uploaded after changing `ir_attachment.location` to `db` could not be displayed. The products are that exist before changing location can show product images.

For reference,
This is the product image in 13.0.
![Screenshot from 2023-02-16 10-37-18](https://user-images.githubusercontent.com/45355704/219266146-d9757794-e478-42e8-8a45-30974ea72c59.png)

Below images are from v14.0.
![Screenshot from 2023-02-16 10-35-27](https://user-images.githubusercontent.com/45355704/219265931-d53dd219-c830-4b7d-927d-a5faf83e3fe7.png)

![Screenshot from 2023-02-16 10-33-58](https://user-images.githubusercontent.com/45355704/219265978-5624aef0-73de-4c98-9c73-049e8144f052.png)

@qrtl

**Comment by pedrobaeza** [comment]
Who use filestore in DB? I think that's pretty insane. If you come from an older version, do the conversion (there's an OCA module for that) before coming to this new versions. Anyway, that flow is not supported, although I don't see any strong reason why it fails. I don't feel also that we should cover this edge case.

**Comment by hussain** [comment]
> Who use filestore in DB?

There are customer who do! But they don't know the side-effect.
I have a project in hand v11=>v15 with filestore in DB (was then changed to files so it is mixed). First step was to convert filestore to files and applied to production. Result is +30% in performance gain and 50% reduction in (DB+files) size which results in less time for full backup (2 hours => 40 minutes).

Let the numbers speak
```log
# Filestore in DB
DB: 69 GB
Filestore: 14 GB

# Filestore in Files
DB: 11 GB
Filestore: 37 GB
```

**Comment by pedrobaeza** [comment]
Exactly, but they use it because it was the previous default. But not on v13! That's why I said that it should be converted before starting the migration (or in a middle step before getting to this new versions).

**Comment by AungKoKoLin1997** [comment]
In my background, I used the module `attachment_s3` that helps to store in s3 external storage. In v11.0, it stores all of attachments to s3 but some of small files that need to be fast access like `image_128` stored in the database since 12.0. In my case, I can adjust configuration for this module to store all of attachments in s3 or I can force to convert to files for small files. I just wanted to know there is any option for DB stored attachment migration. Thanks for your fast response and suggestion.

**Comment by pedrobaeza** [comment]
For other times, it's important to say that although the error is in the step to 14.0, your DB comes from such 11.0 version. As said, I don't think that it's worth to analyze and fix what provokes the problem, and it's better to just store in filestore before, but if you think it does, please go ahead and contribute with the patch.

I close this issue, as already discussed.
