### ISSUE TITLE
14 -> 15 Migration of CRM (meeting_count)

### ISSUE THREAD

**Issue by NICO-SOLUTIONS** [OCA/OpenUpgrade#3743]
CRM

After migration there is no access to the crm leads/opps, shwoing the error 
"UncaughtPromiseError
Uncaught Promise > While parsing modifiers for span: for modifier "invisible": Unknown field meeting_count in domain
Error: While parsing modifiers for span: for modifier "invisible": Unknown field meeting_count in domain"

**Expected behavior**
After migration the meeting_count should not block the access leads/opps.

**Additional context**
All appreances of "meeting_count" in translations needs to be replaced by "calendar_event_count".

Possible to implement it directly in the script? This would avoid changing the translations manually afterwards.

**Comment by mgielissen** [comment]
Quick fix: delete translated items with "meeting_count".

**Comment by MiquelRForgeFlow** [comment]
Remember to always pass the parameter `--i18n-overwrite` when migrating, in the `--update=all` command call.

**Comment by pedrobaeza** [comment]
I prefer to do it later once migrated, but anyway, that's the way to solve it.
