### ISSUE TITLE
duplicate key value violates unique constraint "res_country_code_uniq"

### ISSUE THREAD

**Issue by AussieScorpio** [OCA/OpenUpgrade#3755]
Attempting to migrate from Odoo 9 to Odoo 10 results in a failure attempting to insert to res_country. The record that fails to insert has a "code" of "gb", but a row already exists with a code of "GB" (uppercase). Is this potentially an issue of database collation differing from the string comparisons being done in OpenUpgrade?

**Comment by pedrobaeza** [comment]
Your country GB doesn't have the proper XML-ID for being identified as the same as the new version. You should fix this in your DB, but nothing on OpenUpgrade itself.

**Comment by AussieScorpio** [comment]
Thanks. That put me on the right track. The XML-ID was 'gb', whereas the XML for res.country in OpenUpgrade had it as 'uk' (don't know why they deviated from the standard for ISO country codes on this one; seems silly and leads to these kind of issues).
I've now been able to run the migration through without errors; now to validate it.
