### ISSUE TITLE
Model equal to empty "string" in QWeb views for migrated databases version 7 to 8

### ISSUE THREAD

**Issue by ghost** [OCA/OpenUpgrade#376]
The bases are being migrated to being a model equal to empty string in the Qweb views. Normally Odoo 8 in the new bases generate a null model for these views.

When you generate an inherited view base is null and string original base was empty and Qweb not see it as a legacy view that vacuum valid because empty is different from null.

You have to run something like this consultation to ensure that no model views remain at zero instead of empty string.
UPDATE SET ir_ui_view model = NULL WHERE type = 'Qweb' AND model = '';

The problem happens when I create a new view Qweb, this view was created with an empty string, so empty string is different than Null (model from the original view).

**Comment by StefanRijnhart** [comment]
Thanks for your suggestion. The proposed change seems simple enough. Could you propose a PR with a version of this change that allows your migration to succeed?

**Comment by pedrobaeza** [comment]
As no answer since long, I close.
