### ISSUE TITLE
Error: upgrade between v15 to v16 on enterprise build

### ISSUE THREAD

**Issue by nabilragab** [OCA/OpenUpgrade#3810]
On Odoo 15: 
the pos_coupon module is part of the community build
the pos_loyalty module is part of the enterprise build

the upgrade of an enterprise build would cause an error.

https://github.com/OCA/OpenUpgrade/blob/c19c0703455361b9c551c4b6a74ba194af19a75a/openupgrade_scripts/apriori.py#L11

**Comment by pedrobaeza** [comment]
I don't get you. `pos_loyalty` is a community module:

https://github.com/odoo/odoo/tree/16.0/addons/pos_loyalty

And anyway, OpenUpgrade 16.0 is still far from being complete.

Closing for now.

**Comment by nabilragab** [comment]
@pedrobaeza yes you are correct that is in Odoo16 not in Odoo15. So when upgrading from an enterprise version 15, the pre-migration script will crash because the module already exists in ir_module

https://github.com/odoo/enterprise/tree/15.0/pos_loyalty

**Comment by pedrobaeza** [comment]
OK, now I get you. Changed in 20034b29770513dc4b178f662c6238f88983798c for avoiding such problem, although you will need extra migration scripts if such module was installed in your DB.
