### ISSUE TITLE
Can you provide better information on how to run migration?

### ISSUE THREAD

**Issue by matzrm** [OCA/OpenUpgrade#3821]
**Is your feature request related to a problem?**
I can't understand if I have to install this modules on my old Odoo or in my new one.
Also I can't understand what is the configuration file that you speak about in the documentation.

**Describe the solution you'd like**
A clear and concise example on how to run.

**Additional context**
I wish upgrade  my odoo 14 to odoo 16. I have no custom modules installed!

**Comment by pedrobaeza** [comment]
Not possible to migrate yet to v16, and please check all the documentation and make specific questions in Discussion part, not in issues.
