### ISSUE TITLE
[DOC][RFC] Openupgradelib documentation

### ISSUE THREAD

**Issue by legalsylvain** [OCA/OpenUpgrade#3862]
Hi all.

**Current situation :** 
- Regarding openupgrade documentation ([source](https://github.com/OCA/OpenUpgrade/tree/documentation/docsource) + website : https://oca.github.io/OpenUpgrade/) 
    - includes part of the openupgradelib documentation, and show the function available in the [API section](https://oca.github.io/OpenUpgrade/API.html). 
    - As a result :  build openupgrade documentation is quite complex, (it requires to install openupgradelib, so it requires to install odoo ...)

- regarding openupgradelib documentation ([source](https://github.com/OCA/openupgradelib/tree/master/docs) + website : https://openupgradelib.readthedocs.io/
    - doesn't include the description of the openupgradelib function. (?!?)
    - it is not hosted in the same place
    - include generic text thats mention how to make a PR on github
    - has not been updated since May, 2015. see [history in docsource](https://github.com/OCA/openupgradelib/blob/master/HISTORY.rst) and [published history](https://openupgradelib.readthedocs.io/en/latest/history.html).

**Proposal :**
- refactor openupgradelib : 
    - the doc should contains the description of the function (API)
    - move into github page and deploy in a similar way as openupgrade (workflow)
 - refactor openupgrade : 
     - remove openupgradelib API from the documentation, and replace by a link to the openupgradelib.
     - simplify all the "documentation-commit"  files.

**Pro :**
- openupgradelib documentation up to date
- openupgrade documentation easier to build locally
- openpugrade doc easier to build by workflow
- each project documentation describes the project.

**Cons :**
- I don't really see it, except for a time of work that I propose to do. This being said, there may be elements that I have not taken into account...

What do you think ? @StefanRijnhart, @pedrobaeza, @MiquelRForgeFlow.

CC : @bguillot, @etobella. (Topic related to the RFQ.)

**Comment by pedrobaeza** [comment]
It seems a possibility to reduce some of the problems.

**Comment by legalsylvain** [comment]
Done.
