### ISSUE TITLE
Migrating Asset Management , Deffered expense and Deffered revenue module

### ISSUE THREAD

**Issue by shazzwazz20** [OCA/OpenUpgrade#3867]
**Is your feature request related to a problem?**
If so, please provide clear and concise description of what the problem is.

Asset model and asset data from 12.0 does not migrate to 13.0 new table structure
**Describe the solution you'd like**
OCA should add migration script for assets

**Describe alternatives you've considered**

**Additional context**
Add any other context about the feature request here.

**Comment by legalsylvain** [comment]
Hi.
Thanks for reporting.
Could you specify which "asset" module it is? is it https://github.com/OCA/account-financial-tools/tree/12.0/account_asset_management ? 

kind regards.

**Comment by pedrobaeza** [comment]
Closing as not directly related to OpenUpgrade nor answered.
