### ISSUE TITLE
[8.0] stock: Created quants doesn't have the correct date

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/OpenUpgrade#387]
Although quants are correctly recreated with current migration scripts, the date that is taken is the date when the migration is run, giving incorrect information when consulting directly this data. We can improve scripts for re-writing the date once the quant has been created taking stock.move transferred date as reference.

**Comment by rafaelbn** [comment]
After migration, the stock.move fields are:

1 - date: WRONG it take the date of the migration (year 2015)
2 - create_date: RIGHT it take the date of stock.move creation (year 2013)
3 - and in stock.quant field in_date: WRONG it take the date of the migration. (year 2015)

Attached:

![20-10-2015 16-54-35](https://cloud.githubusercontent.com/assets/8736623/10611506/b28b73bc-774c-11e5-94f3-3e7ae8dada03.png)

**Comment by pedrobaeza** [comment]
Solved in https://github.com/OCA/OpenUpgrade/pull/395

**Comment by sebalix** [comment]
I missed this one... thanks! It fixed the `stock_history` SQL view from `stock_account`.

**Comment by pedrobaeza** [comment]
@sebalix, where?

**Comment by sebalix** [comment]
I mean the PR #395, it was what I was looking for regarding the wrong dates on `stock_move` and `stock_quant` (my branch was not up-to-date, giving wrong results in the stock history).

**Comment by pedrobaeza** [comment]
Ah, OK, I close this issue then.
