### ISSUE TITLE
[11 --> 12.0] ERROR: index row size 2712 exceeds btree version 4 maximum 2704 for index "stock_picking_origin_index"

### ISSUE THREAD

**Issue by AungKoKoLin1997** [OCA/OpenUpgrade#3885]
I want to migrate my database to v11 to v15. So, I tried to migrate first to v12.0 and run migration script. I have a lot of transaction lines for stock.picking and I am stuck at stock.picking migration.

I am not sure this is related with openupgrade but I would like to hear some suggestion from community.
Here is the error message.

```
ERROR production odoo.sql_db: bad query: CREATE INDEX "stock_picking_origin_index" ON "stock_picking" ("origin")
ERROR: index row size 2712 exceeds btree version 4 maximum 2704 for index "stock_picking_origin_index"
DETAIL:  Index row references tuple (555,22) in relation "stock_picking".
HINT:  Values larger than 1/3 of a buffer page cannot be indexed.
Consider a function index of an MD5 hash of the value, or use full text indexing.
```

**Comment by legalsylvain** [comment]
Hi @AungKoKoLin1997.
I didn't know that type of error, but indeed after a quick look, it looks unrelated to openupgrade but to your postresql versions.
https://stackoverflow.com/questions/70123567/index-row-size-2712-exceeds-btree-version-4-maximum-2704-for-index-while-doing

If you find a solution, dont hesitate to put the answer here. 

Closing in the meantime.

**Comment by pedrobaeza** [comment]
You have very long texts in your `origin` field in `stock_picking`. You have to reduce them. Detect the longest ones.
