### ISSUE TITLE
[15.0 =>16.0] insert or update on table "stock_route_product" violates foreign key constraint "stock_route_product_route_id_fkey"

### ISSUE THREAD

**Issue by medaminesayadi** [OCA/OpenUpgrade#3890]
I got this error while migrating from odoo 15 to odoo 16 :

2023-05-25 09:41:57,233 24214 ERROR TEST_16 odoo.sql_db: bad query: ALTER TABLE "stock_route_product" ADD FOREIGN KEY ("route_id") REFERENCES "stock_route"("id") ON DELETE cascade
ERROR: insert or update on table "stock_route_product" violates foreign key constraint "stock_route_product_route_id_fkey"
DETAIL:  Key (route_id)=(5) is not present in table "stock_route".

Any solution to fix this bug ?

**Comment by legalsylvain** [comment]
Hi. The stock migration is not available for V16.
please, before opening issue, refer to the coverage file of the documentation, and check that the module is marked as done.
see : https://oca.github.io/OpenUpgrade/modules150-160.html

kind regards.

**Comment by Aadeelyoo** [comment]
When they are going to fix this issue? they are about to roll out v17 and have no solution for stock module migration so far for v16.

**Comment by hyjie-ts** [comment]
`from openupgradelib import openupgrade
_models_renames = [("stock.location.route", "stock.route")]
_tables_renames = [("stock_location_route", "stock_route")]


@openupgrade.migrate()
def migrate(env, version):

    openupgrade.rename_models(env.cr, _models_renames)
    openupgrade.rename_tables(env.cr, _tables_renames)`
try this in pre-migration.py

**Comment by hyjie-ts** [comment]
```
from openupgradelib import openupgrade
_models_renames = [("stock.location.route", "stock.route")]
_tables_renames = [("stock_location_route", "stock_route")]


@openupgrade.migrate()
def migrate(env, version):

    openupgrade.rename_models(env.cr, _models_renames)
    openupgrade.rename_tables(env.cr, _tables_renames)
```
try this in pre-migration.py

**Comment by MuhammadFayyaz22** [comment]
from openupgradelib import openupgrade

_models_renames = [
    ("stock.location.route", "stock.route"),
    ("stock.production.lot", "stock.lot"),
]

_tables_renames = [
    ("stock_location_route", "stock_route"),
    ("stock_production_lot", "stock_lot"),
    ("stock_location_route_categ", "stock_route_categ"),
    ("stock_location_route_packaging", "stock_route_packaging"),
    ("stock_location_route_move", "stock_route_move"),
]

_columns_renames = {
    "stock_move_line": [
        # ("product_qty", "reserved_qty"),
        # ("product_uom_qty", "reserved_uom_qty"),
    ],
    "stock_rule": [
        ("location_id", "location_dest_id"),
    ],
}
_fields_renames = [
    ("stock.move.line", "stock_move_line", "product_qty", "reserved_qty"),
    ("stock.move.line", "stock_move_line", "product_uom_qty", "reserved_uom_qty"),
    ("stock.rule", "stock_rule", "location_id", "location_dest_id"),
    ("stock.picking", "stock_picking", "move_lines", "move_ids"),
]
def _update_stock_quant_storage_category_id(env):
    openupgrade.logged_query(
        env.cr,
        """
        ALTER TABLE stock_quant
        ADD COLUMN IF NOT EXISTS storage_category_id INTEGER
        """,
    )
    openupgrade.logged_query(
        env.cr,
        """
        UPDATE stock_quant
        SET storage_category_id = stock_location.storage_category_id
        FROM stock_location
        WHERE stock_quant.location_id = stock_location.id
        """,
    )
def _update_sol_product_category_name(env):
    openupgrade.logged_query(
        env.cr,
        """
        ALTER TABLE stock_move_line
        ADD COLUMN IF NOT EXISTS product_category_name CHARACTER VARYING
        """,
    )
    openupgrade.logged_query(
        env.cr,
        """
        UPDATE stock_move_line AS sml
        SET product_category_name = category.complete_name
        FROM product_product AS product
        JOIN product_template AS product_tmpl
        ON product_tmpl.id = product.product_tmpl_id
        JOIN product_category AS category
        ON category.id = product_tmpl.categ_id
        WHERE sml.product_id = product.id
        """,
    )
def _compute_stock_location_replenish_location(env):
    openupgrade.logged_query(
        env.cr,
        """
        ALTER TABLE stock_location
        ADD COLUMN IF NOT EXISTS replenish_location BOOLEAN
        """,
    )
    openupgrade.logged_query(
        env.cr,
        """
        WITH location_info as (
            SELECT sl.id as id,
            CASE
                WHEN sl.usage = 'internal' AND sl.id = sw.lot_stock_id THEN True
                ELSE FALSE
            END as replenish_location_status
            FROM stock_location sl
            LEFT JOIN stock_warehouse sw
            ON sw.id = sl.warehouse_id
             )
        UPDATE stock_location sl
        SET replenish_location = info.replenish_location_status
        FROM location_info info
        WHERE sl.id = info.id
        """,
    )

def _update_stock_quant_package_pack_date(env):
    openupgrade.logged_query(
        env.cr,
        """
        ALTER TABLE stock_quant_package
        ADD COLUMN IF NOT EXISTS pack_date DATE
        """,
    )
    openupgrade.logged_query(
        env.cr,
        """
        UPDATE stock_quant_package
        SET pack_date = DATE(create_date)
        """,
    )
@openupgrade.migrate()
def migrate(env, version):
    openupgrade.rename_tables(env.cr, _tables_renames)
    openupgrade.rename_models(env.cr, _models_renames)
    openupgrade.rename_fields(env, _fields_renames)
    # openupgrade.rename_columns(env.cr, _columns_renames)
 

Apply this code into your stock module  pre-migrations.py file this helps me to retrieve stock data in v16

**Comment by hamadfayyad** [comment]
### Try This in pre-migration.py
~/openupgrade_scripts/scripts/stock/16.0.X.X/**pre-migration.py**



```
from openupgradelib import openupgrade

_models_renames = [
    ("stock.location.route", "stock.route"),
    ("stock.production.lot", "stock.lot"),
]

_tables_renames = [
    ("stock_location_route", "stock_route"),
    ("stock_production_lot", "stock_lot"),
    ("stock_location_route_categ", "stock_route_categ"),
    ("stock_location_route_packaging", "stock_route_packaging"),
    ("stock_location_route_move", "stock_route_move"),
]

_fields_renames = [
    ("stock.move.line", "stock_move_line", "product_qty", "reserved_qty"),
    ("stock.move.line", "stock_move_line", "product_uom_qty", "reserved_uom_qty"),
    ("stock.rule", "stock_rule", "location_id", "location_dest_id"),
    ("stock.picking", "stock_picking", "move_lines", "move_ids"),
]


def _update_stock_quant_storage_category_id(env):
    openupgrade.logged_query(
        env.cr,
        """
        ALTER TABLE stock_quant
            ADD COLUMN IF NOT EXISTS storage_category_id INTEGER
        """,
    )
    openupgrade.logged_query(
        env.cr,
        """
        UPDATE stock_quant
            SET storage_category_id = stock_location.storage_category_id
        FROM stock_location
        WHERE stock_quant.location_id = stock_location.id
        """,
    )


def _update_sol_product_category_name(env):
    openupgrade.logged_query(
        env.cr,
        """
        ALTER TABLE stock_move_line
            ADD COLUMN IF NOT EXISTS product_category_name CHARACTER VARYING
        """,
    )
    openupgrade.logged_query(
        env.cr,
        """
        UPDATE stock_move_line AS sml
            SET product_category_name = category.complete_name
        FROM product_product AS product
        JOIN product_template AS product_tmpl
            ON product_tmpl.id = product.product_tmpl_id
        JOIN product_category AS category
            ON category.id = product_tmpl.categ_id
        WHERE sml.product_id = product.id
        """,
    )


def _compute_stock_location_replenish_location(env):
    openupgrade.logged_query(
        env.cr,
        """
        ALTER TABLE stock_location
            ADD COLUMN IF NOT EXISTS replenish_location BOOLEAN
        """,
    )

    openupgrade.logged_query(
        env.cr,
        """
        UPDATE stock_location sl
            SET replenish_location = False
        WHERE sl.usage != 'internal'
        """,
    )

    openupgrade.logged_query(
        env.cr,
        """
        UPDATE stock_location sl
            SET replenish_location = True
        FROM stock_warehouse sw
        WHERE sl.usage = 'internal' AND sl.id = sw.lot_stock_id
        """,
    )

    openupgrade.logged_query(
        env.cr,
        """
        UPDATE stock_location sl
            SET replenish_location = True
        FROM stock_warehouse_orderpoint point
        WHERE sl.id = point.location_id
        """,
    )


def _update_stock_quant_package_pack_date(env):
    openupgrade.logged_query(
        env.cr,
        """
        ALTER TABLE stock_quant_package
            ADD COLUMN IF NOT EXISTS pack_date DATE
        """,
    )
    openupgrade.logged_query(
        env.cr,
        """
        UPDATE stock_quant_package
            SET pack_date = DATE(create_date)
        """,
    )


@openupgrade.migrate()
def migrate(env, version):
    openupgrade.rename_models(env.cr, _models_renames)
    openupgrade.rename_tables(env.cr, _tables_renames)
    openupgrade.rename_fields(env, _fields_renames)
    _update_stock_quant_storage_category_id(env)
    _update_stock_quant_package_pack_date(env)
    _update_sol_product_category_name(env)
    _compute_stock_location_replenish_location(env)
```
