### ISSUE TITLE
Merge Modules in  database migration 5.0 to 8.0

### ISSUE THREAD

**Issue by synconics** [OCA/OpenUpgrade#391]
Hello  All,

I am trying to write migration scripts for v5 - v8 database migration with some my custom module.
I want to do database analysis for my modules. But I am confuse how to do that with changed module name in targeted version.
I have modules A,B,C and D in v5 and all are merged into module E in v8.
Now for clear database analysis what i have to do?
I know the basic steps for db analysis. But not aware about change module name and merge modules.
Please guide me.

Thanks in advance.

**Comment by pedrobaeza** [comment]
I don't recommend you to do that. Go step by step, and reuse what is done. I have migrated databases from 4.2 to 8.0 without problem, going this way.

**Comment by StefanRijnhart** [comment]
Agree with @pedrobaeza but at some step you will have to merge these modules.

I would choose one of the modules (let's say, _A_) to rename to _E_ by adding this combo to https://github.com/OCA/OpenUpgrade/blob/8.0/openerp/addons/openupgrade_records/lib/apriori.py.

Modify your data structure as any other migration script in the _E_ module. Be sure to rename any XMLID from B, C and D to E.

After the migration, uninstall B, C, and D with or without the database_cleanup module from https://github.com/oca/server-tools

**Comment by pedrobaeza** [comment]
You can also check https://github.com/OCA/openupgradelib/pull/13 for a mechanism (not yet approved) to merge modules.

**Comment by synconics** [comment]
Thank you so much @pedrobaeza  and @StefanRijnhart for your support. 
I understand now the scenario which you explain.
