### ISSUE TITLE
 raise Exception(_('Module loading %s failed: file %s could not be processed:\n %s') % (module, fname, warning_msg)) Exception: Module loading mahmoud_market failed: file mahmoud_market\security/ir.model.access.csv could not be processed:  No matching record found for external id 'Model_market' in field 'Model' Missing required value for the field 'Model' (model_id)

### ISSUE THREAD

**Issue by mahmoud-homsi** [OCA/OpenUpgrade#3927]
<odoo>
    <data>
        
        <record id="view_market_form" model="ir.ui.view">
            <field name="name">mahmoud_market.form</field>
            <field name="model">sale.order</field>
            <field name="inherit_id" ref="sale.view_order_form"/>
            <field name="arch" type="xml">
                <data>
                    <field name="header" string="Header" attrs="{'readonly': [('state', '!=', 'draft')]}"/>
                </data>
            </field>
        </record>
    </data>
</odoo>

id,name,model_id:id,group_id:id,perm_read,perm_write,perm_create,perm_unlink
access_market_manager,market.manager,market.py,base.group_user,1,1,1,1

from odoo import fields, models

class Market(models.Model):
    _inherit = 'sale.order'
    header = fields.Char(string='Header')

what could be the error

**Comment by pedrobaeza** [comment]
This has nothing to do with OpenUpgrade.
