### ISSUE TITLE
By when we odoo15 to Odoo 16 migration script would be ready for testing?

### ISSUE THREAD

**Issue by shazzwazz20** [OCA/OpenUpgrade#3929]
By when we odoo15 to Odoo 16 migration script would be ready ?
Especially looking for Inventory management migration script due to lot of changes in structure from 15 to 16.

**Comment by pedrobaeza** [comment]
Check in #3681 the progress of the covered modules. It depends on your installed modules. No planned deadline, as it's a voluntary work. If you want to speed up, fund the development of any module migration script.
