### ISSUE TITLE
[8.0] Mark 'process' and 'account_report_company' modules to remove in regular migration

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/OpenUpgrade#394]
Both modules has dissapeared on v8, one - process - because is not maintain anymore (but also doesn't have any problem uninstalling it), and the other because it's already integrated in core.

I think the best is to uninstall both in the regular migration, instead of having to uninstall them manually afterwards. What do you think?

Can this be achieved in base module?

**Comment by StefanRijnhart** [comment]
This would also remove any modules that deped on them which are not available in the module path at that point, which could lead to data loss. Consider that you can migrate just the core modules using the OpenUpgrade distribution, and then migrate some 3rd party module that carries its own migration script (if necessary) afterwards on a regular edition of Odoo.

**Comment by pedrobaeza** [comment]
We can mark them on the very end. I don't remember now the name of the method that is executed at the end of the migration, but there.

**Comment by StefanRijnhart** [comment]
No, I mean in a next run. So removing them at the end of the original run does not help.

**Comment by pedrobaeza** [comment]
Well, the account_report_company module has been integrated in the account module, so a proper module migration should remove that dependency. process can be other case, but at least I would do it for the first one.

**Comment by StefanRijnhart** [comment]
It's not about the modules themselves, it is about the modules that might depend on them. Removing the core modules will remove those as well.

**Comment by pedrobaeza** [comment]
Well, we have entered in a loop, hehe. I was talking about the special case of `report_company`, but no matter. We can continue doing the same way as now.
