### ISSUE TITLE
Migrade 8.0 to 9.0

### ISSUE THREAD

**Issue by dany-lopez-silttec** [OCA/OpenUpgrade#396]
Hello

I try to use the tool for migrate to odoo 9.0 from 8.0

In 'migration.log' file:

... openerp.sql_db: Programming error: column "transient" does not exist

And, when I try to login in my migrate database:
... openerp.modules.module: module email_template: module not found
... openerp.modules.module: module website_report: module not found
... openerp.modules.module: module web_tests: module not found
... openerp.modules.module: module account_check_writing: module not found
... openerp.modules.module: module im_chat: module not found
... openerp.modules.module: module account_chart: module not found
... openerp.modules.module: module edi: module not found
... openerp.modules.module: module web_graph: module not found
... openerp.modules.module: module web_gantt: module not found
... openerp.modules.module: module web_kanban_sparkline: module not found
... openerp.modules.module: module share: module not found

**Comment by pedrobaeza** [comment]
OpenUpgrade for v9 is not yet available. Check https://github.com/OCA/OpenUpgrade/issues/367

**Comment by m3asmi** [comment]
I got the issue too:
```
... openerp.modules.module: module email_template: module not found
... openerp.modules.module: module website_report: module not found
... openerp.modules.module: module web_tests: module not found
... openerp.modules.module: module account_check_writing: module not found
... openerp.modules.module: module im_chat: module not found
... openerp.modules.module: module account_chart: module not found
... openerp.modules.module: module edi: module not found
... openerp.modules.module: module web_graph: module not found
... openerp.modules.module: module web_gantt: module not found
... openerp.modules.module: module web_kanban_sparkline: module not found
... openerp.modules.module: module share: module not found
```
