### ISSUE TITLE
Missing DEL entries in analysis file

### ISSUE THREAD

**Issue by alexis-via** [OCA/OpenUpgrade#40]
Here is the scenario of the bug:
- in openerp 6.1, there is an osv.osv object "document.storage" with several fields (cf addons-61/document/document_storage.py)
- in openerp 7.0, there is still an osv.osv object "document.storage", but without _columns (cf addons-70/document/document.py ; it is because document.storage is deprecated)

When you look at the file openupgrade-addons-70/document/migrations/7.0.2.1/openupgrade_analysis.txt you should see DEL entries for the columns of document.storage... but there are no such entries !

**Comment by pedrobaeza** [comment]
@StefanRijnhart, is this solved with your latest changes to the analyzer?

**Comment by StefanRijnhart** [comment]
No. I suspect that the analysis doesn't do field deltas on models that have no fields at all. I can't think of a lot of other cases of models without any fields in Odoo, so it's a cornercase I can live with.

**Comment by hbrunn** [comment]
closing as of https://github.com/OCA/OpenUpgrade/issues/40#issuecomment-199191123
