### ISSUE TITLE
setting PYTHONPATH fails in migration.py script when PYTHONPATH is undefined

### ISSUE THREAD

**Issue by yucer** [OCA/OpenUpgrade#401]
In line 337 of `migration.py` we have:

``` python
os.environ['PYTHONPATH'] = ':'.join([
    openupgradelib, os.environ.get('PYTHONPATH')])
```

but that fails when PATHONPATH is not previously setted up in the os enviroment. Maybe ..?

``` python
os.environ['PYTHONPATH'] = ':'.join([
    openupgradelib, os.environ.get('PYTHONPATH', '')])
```

**Comment by StefanRijnhart** [comment]
That must be a regression of today's merge of https://github.com/OCA/OpenUpgrade/pull/397. Your solution looks reasonable. Could you prepare a PR?

**Comment by yucer** [comment]
That would be my first contribution to a github project. There is some link
indicating how to do it?

**Comment by hbrunn** [comment]
@yucer https://odoo-community.org/page/code

I think your solution is fine, so I leave the PR to you as an exercise ;-)

**Comment by yucer** [comment]
Thanks !

I'm waiting for the CLA approval. So you can fix it if you need it soon.
