### ISSUE TITLE
[8.0] Header and Footer are missing

### ISSUE THREAD

**Issue by ikus060** [OCA/OpenUpgrade#403]
After upgrading from 7.0 to 8.0, my customer header and footer (defined as RML header & footer in Compagnies settings) are missing from invoice report. I don't see any error in logs.

I've try the following
1. Remove my customer invoice report module.
2. Upgrade `report`module
3. Set System Parameter `report.url` = `http://127.0.0.1:8069`

![image](https://cloud.githubusercontent.com/assets/921251/11324822/3ca77f5a-910b-11e5-851d-76dc40461e38.png)
- Running on Debian Jessie (amd64)
- wkhtmltopdf (0.12.1-2) -- installed from Debian packages.

**Comment by pedrobaeza** [comment]
New version doesn't use RML header and footer, but QWeb. You need to redefine your reports and customize again the headers and footers.

**Comment by ikus060** [comment]
Ok. Make sense. I still have few quesrtions.
1. If QWeb is the way to go, why is section `Configuration (RML)` still exists in Companies settings ?
![image](https://cloud.githubusercontent.com/assets/921251/11337511/9254bffc-91bb-11e5-9aab-aa78b2497bf8.png)
2. Also, the preview Header/Footer is still working and display my header and footer has appropriate.
1. Where / How do I change the header and footer for QWeb ?
2. I've create a new `demo` database. Header and footer are still missing. I was expecting this to work by default.

![image](https://cloud.githubusercontent.com/assets/921251/11337588/17765538-91bc-11e5-9ad1-2f8985c38ac5.png)

**Comment by pedrobaeza** [comment]
The section is for your custom RML reports that you want to keep (it's deprecated, but not removed). The other issue is something with your deployment.
