### ISSUE TITLE
[9.0]column "transient" does not exist

### ISSUE THREAD

**Issue by jas-odoo** [OCA/OpenUpgrade#408]
It is the very first error i will get after migrating 8 to 9.Actually i am knowing the reason that transient column does not exists.But migration script cannot make column 'transient'?

Programming error: column "transient" does not exist
LINE 1: select model, transient from ir_model where state='manual'

Can i have to makie that column manually or any other issue?
Please guide me

**Comment by pedrobaeza** [comment]
Please check the WIP https://github.com/OCA/OpenUpgrade/pull/405.

It's also interesting that you coordinate with the rest of people working in the migration in https://github.com/OCA/OpenUpgrade/issues/400
