### ISSUE TITLE
Error Odoo 13 to 14 upgrade Failed to load server-wide module `openupgrade_framework`.

### ISSUE THREAD

**Issue by abrunos** [OCA/OpenUpgrade#4118]
## Module

server_wide_modules = web,openupgrade_framework

## Describe the bug

Unfortunately, we couldn't upgrade the Odoo 13 instance to Odoo 14.

There are errors when we try to run the upgrade script:

CRITICAL ? odoo.modules.module: Couldn't load module openupgrade_framework
CRITICAL ? odoo.modules.module: type object 'IrModelSelection' has no attribute '_process_ondelete'
ERROR ? odoo.service.server: Failed to load server-wide module `openupgrade_framework`.
python3: Python/compile.c:3021: compiler_nameop: Assertion `!_PyUnicode_EqualToASCIIString(name, "None") && !_PyUnicode_EqualToASCIIString(name, "True") && !_PyUnicode_EqualToASCIIString(name, "False")' failed.
Aborted (core dumped)

We double-checked the Odoo configuration, and there is a line:

server_wide_modules = web,openupgrade_framework

For some reason, the openupgrade framework module is not detected.

## To Reproduce
Oddo 13 to 14
The odoo_13 user has permission to access the module files:

ls -alh /opt/odoo13/odoo_13/odoo/addons/openupgrade_framework/

total 48K
drwxr-xr-x   6 odoo_13 odoo_13 4.0K Sep  1 04:32 .
drwxr-xr-x 336 odoo_13 odoo_13  12K Sep  1 04:45 ..
-rw-rw-r--   1 odoo_13 odoo_13  485 Sep  1 04:05 __init__.py
-rw-rw-r--   1 odoo_13 odoo_13  745 Sep  1 04:05 __manifest__.py
drwxr-xr-x   4 odoo_13 odoo_13 4.0K Sep  1 04:32 odoo_patch
drwxrwxr-x   2 odoo_13 odoo_13 4.0K Sep  1 04:32 __pycache__
drwxr-xr-x   2 odoo_13 odoo_13 4.0K Sep  1 04:05 readme
-rw-rw-r--   1 odoo_13 odoo_13 6.7K Sep  1 04:05 README.rst
drwxr-xr-x   3 odoo_13 odoo_13 4.0K Sep  1 04:05 static

This is from the Odoo configuration file:

server_wide_modules = web,openupgrade_framework

**Comment by pedrobaeza** [comment]
You must use Odoo 14 for migrating to Odoo 14 with OpenUpgrade, not 13.

**Comment by abrunos** [comment]
Tia will try it
