### ISSUE TITLE
Missing field conversion of ir_* models and other

### ISSUE THREAD

**Issue by mholthausen** [OCA/OpenUpgrade#4123]
## Model
ir_*

## Describe the bug
When running the migration from odoo15 to odoo16 database I get an error concerning several fields in the ir_*-models and other relations with missing fields because they aren't migrated into jsonb fields

## To Reproduce
**Affected versions**:
15.0, 16.0

1. Install fresh odoo 15
2. Run migration with OpenUpgrade to version 16
3. The database selector says, database my be incompatible
4. When trying to open the login form and login you get errors in the log about "unknown operators" (`-->`)

```
ir_model:name
ir_model_fields:field_description
ir_model_fields:help
ir_module_module:shortdesc
ir_module_module:summary
ir_module_module:description
ir_ui_view:arch_db
res_groups:name
mail_message_subtype:name
mail_message_subtype:description
```

missing columns:
```
res_company:active
res_partner:company_registry
```

**Expected behavior**
The fields are converted into the needed datatype format (from character varying into jsonb)

**Additional context**
odoo and upgrade was run within docker-compose

**Comment by legalsylvain** [comment]
which version of odoo and openupgrade are you using ?

**Comment by mholthausen** [comment]
It is odoo 15 that should go to odoo 16 and I tried it with OpenUpgrade from branch `16.0`.

**Comment by legalsylvain** [comment]
Hi. to upgrade from 15.0 to 16.0 you have to use odoo 16 and openupgrade 16.0

please refer to the documentation : https://oca.github.io/OpenUpgrade/intro.html

thanks !
