### ISSUE TITLE
[15.0 =>16.0] insert or update on table "stock_route_product" violates foreign key constraint "stock_route_product_route_id_fkey"

### ISSUE THREAD

**Issue by Aadeelyoo** [OCA/OpenUpgrade#4154]
I got this error while migrating from odoo 15 to odoo 16 :

2023-05-25 09:41:57,233 24214 ERROR TEST_16 odoo.sql_db: bad query: ALTER TABLE "stock_route_product" ADD FOREIGN KEY ("route_id") REFERENCES "stock_route"("id") ON DELETE cascade
ERROR: insert or update on table "stock_route_product" violates foreign key constraint "stock_route_product_route_id_fkey"
DETAIL: Key (route_id)=(5) is not present in table "stock_route".

Any solution to fix this bug ?

**Comment by pedrobaeza** [comment]
Please don't duplicate things. The proposed migration scripts are in https://github.com/OCA/OpenUpgrade/pull/3966

If you want to speed up the development, please fund contributors to do it.

**Comment by Aadeelyoo** [comment]
I am ready to fund. please share the procedure?

**Comment by pedrobaeza** [comment]
That's great. You can go through OCA https://odoo-community.org/about/openupgrade, or write directly to one of the contributors to make the work. Just ask to dump back here the results.
