### ISSUE TITLE
How to deal with specific OCA repo?

### ISSUE THREAD

**Issue by mileo** [OCA/OpenUpgrade#416]
Hi,

Recently i'm working in the migration of account-fical-rule 7.0 -> 8.0 in this fork:

https://github.com/odoo-brazil/account-fiscal-rule/commits/8.0.2.0
https://github.com/odoo-brazil/account-fiscal-rule/commit/b133c6176b6e3aca8b601c792dd707eaba1acd6e
https://github.com/odoo-brazil/account-fiscal-rule/commit/158fa584768eaae7a82fe22214287a4648ed9eb8

But openupgrade lib was add as dependency, can i make a pr to original repo?

Thanks in advance

**Comment by pedrobaeza** [comment]
openupgradelib can be added as a new python dependency as any other python library. Please follow the conventions about it (add it in the manifest and protect possible general imports, which it's not the case). You can make a PR with this in the account-fiscal-rule repository, not here, for the final target version (8.0). People upgrading from 7.0 to 8.0 will take 8.0 repo, include it on OpenUpgrade addons-path, and benefit from these migration scripts.
