### ISSUE TITLE
I have done the procedure correctly, in the web script there is nothing to convert the fields report_header from text to html thats why i get this error.

### ISSUE THREAD

**Issue by Jny-z** [OCA/OpenUpgrade#4162]
I have done the procedure correctly, in the web script there is nothing to convert the fields report_header from text to html thats why i get this error.

_Originally posted by @Jny-z in https://github.com/OCA/OpenUpgrade/issues/4142#issuecomment-1763740732_

**Comment by pedrobaeza** [comment]
That has nothing to do. The error was issued from Odoo itself due to inconsistency in related fields types. Please stop putting issues if you are not adding anything useful to determine a real issue, and not something of your process itself. You have discussions for asking for help.
