### ISSUE TITLE
Migrated Data not in Views but Exist in Database

### ISSUE THREAD

**Issue by MuhammadFayyazq125** [OCA/OpenUpgrade#4165]
Greetings,
   I have Migrated database from v15 - v16 successfully but I am unable to view records of Chart of Account Types and account.move.line records as I found the records in postgress but unable to view from front. Anyone knows the solution or reason.

## Module
account (account.move.line model)

**Comment by legalsylvain** [comment]
please avoid duplicated issue.

**Comment by MuhammadFayyazq125** [comment]
ok it is uploaded by mistake

**Comment by MuhammadFayyazq125** [comment]
can you please help me out of this issue? @legalsylvain

**Comment by legalsylvain** [comment]
Hi. As said in other place. Account module is not migrated. If you want your migration work, you can pay people to do the work, contribute, or wait.
kind regards.
