### ISSUE TITLE
account move line data is not showing

### ISSUE THREAD

**Issue by MuhammadFayyazq125** [OCA/OpenUpgrade#4166]
Greetings all,
     I have Migrated my database from v15 - v16 and it goes successfully but unable to visible account.move.line records as these records are existing is database I verified it from postgress but don't know what could be the reason that it is not visible in views

account (account.move.line)

**Comment by legalsylvain** [comment]
Hi.
Account module is not migrated yet. 

You can take a look on the openupgrade documentation, specially module coverage : https://oca.github.io/OpenUpgrade/modules150-160.html

regards.
