### ISSUE TITLE
module 'openupgradelib.openupgrade' has no attribute 'get_model2table'

### ISSUE THREAD

**Issue by kamel27hk** [OCA/OpenUpgrade#4195]
## Module
Base module migration

## Describe the bug
When i try to excute the script of migration, it stop and show me this error:
module 'openupgradelib.openupgrade' has no attribute 'get_model2table'
in the script from odoo14 to odoo15, it worked like a charme

## To Reproduce
**Affected versions**: odoo15 to odoo16 migration

**Comment by pedrobaeza** [comment]
Use latest source code.
