### ISSUE TITLE
Error migration V7 to V8

### ISSUE THREAD

**Issue by iagit** [OCA/OpenUpgrade#421]
Hello,

I have the following message error in my migration.log file :

```
IntegrityError: insert or update on table "res_country_res_country_group_rel" violates foreign key constraint "res_country_res_country_group_rel_res_country_id_fkey"

DETAIL: Key (res_country_id)=(23) is not present in table "res_country".

```

Can you help me ?

Thank you,

**Comment by pedrobaeza** [comment]
In any moment in the DB, you remove one country (and maybe recreate it). You have to fix that via SQL manually, removing the entry on the table.
