### ISSUE TITLE
addons/document/content_index.py should use python-magic instead of non-portable file -b --mime

### ISSUE THREAD

**Issue by ghost** [OCA/OpenUpgrade#422]
Had a ton of the following sort of messages running on SunOS:
    file: illegal option -- mime 
    usage: file [-bdh] [-M mfile] [-m mfile] [-f ffile] file ...
       file [-bdh] [-M mfile] [-m mfile] -f ffile
       file -i [-bh] [-f ffile] file ...
       file -i [-bh] -f ffile
       file -c [-d] [-M mfile] [-m mfile]

Seems more appropriate to use python-magic instead of Popen 'file' to get the mime-type.

**Comment by dreispt** [comment]
That sounds like an upstream issue. Consider opening an Issue on odoo/odoo.

**Comment by StefanRijnhart** [comment]
@dreispt is right, this project only covers additional functionality to standard Odoo, concerning migrations.
