### ISSUE TITLE
Accounting Invoice display_type is only assigning product to all products 

### ISSUE THREAD

**Issue by MuhammadFayyaz22** [OCA/OpenUpgrade#4220]
I am Currently Migrating v15 to v16 community Edition where I Identified an issue over Invoice Lines is that 
stock Interim (Delivered) has also the display_type product  and even Cost Of Good sold has display_type product and in old version it was not showing these info in invoice lines

**Comment by pedrobaeza** [comment]
That's something that should be done in `stock_account`, which is still not merged, so closing. It has been noted in the PR though.

**Comment by MuhammadFayyaz22** [comment]
okay but I wonder that we now have odoo17 and we are still stuck in the migration of v16 how could we continue to odoo17?

**Comment by pedrobaeza** [comment]
You can fund some people or the OCA to speed the development.

**Comment by MuhammadFayyaz22** [comment]
> You can fund some people or the OCA to speed the development.

I fund myself to solve this problem as of now I did some changes on account and stock module so right now I am able to migrate my account module and i verified that now everything is working fine and also stock module so am i allowed to upload my changes,

**Comment by pedrobaeza** [comment]
Great, then comment in the opened PRs about the needed changes. I still think the change should go to `stock_account`, not `account` module.

**Comment by MuhammadFayyaz22** [comment]
ok but I need PRs github URL?

**Comment by MuhammadFayyaz22** [comment]
right Now I modified OCA but here I am unable to push the code currrently just committed in OCA

**Comment by pedrobaeza** [comment]
You can suggest the change in https://github.com/OCA/OpenUpgrade/pull/3971
