### ISSUE TITLE
Migrate Odoo CRM DB from V6 to V8 

### ISSUE THREAD

**Issue by ronozoro** [OCA/OpenUpgrade#423]
I'm trying to migrate my db form v6 to v8 but i face some problems i knew from the docs that to migrate my DB from v6 to v8 i have to migrate it to v7 first and what i was trying untill this error comes up
I have downloaded migrate.py from here :
https://github.com/OCA/OpenUpgrade/blob/8.0/scripts/migrate.py
 and run this command :+1:  
python migrate.py --config=[openerp-server.conf] --database=[kamel] --run-migrations=7.0 but i always got an error:

No user found in configuration 

and here is my openerp-server.conf:

[options]
; This is the password that allows database operations:
admin_passwd = admin
db_host = localhost
db_port = 5432
db_user = odoo
db_password = odoo
addons_path = /Users/mostafa/Documents/odoo-develop/odoo8/addons,/Users/mostafa/Documents/odoo-develop/net2do_work,/Users/mostafa/Documents/odoo-develop/more_net2do,/Users/mostafa/Documents/odoo-develop/freelance_work,/Users/mostafa/Documents/odoo-develop/custom_addons
pg_path= /usr/local/bin

**Comment by andreiboyanov** [comment]
What are the square brackets ([openerp-server.conf]) meant for? 
Do you have the openerp-server.conf in bthe same directory as migrate.py?

**Comment by ronozoro** [comment]
yes and i added it's content to the post.

**Comment by pedrobaeza** [comment]
As already said, don't put between brackets the parameters:

```
python migrate.py --config=openerp-server.conf --database=kamel --run-migrations=7.0
```

**Comment by ronozoro** [comment]
i did and the error changed now :

Traceback (most recent call last):
  File "migrate.py", line 341, in <module>
    db_name = copy_database(conn_parms)
  File "migrate.py", line 25, in copy_database
    conn = psycopg2.connect(**conn_parms)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/psycopg2/**init**.py", line 164, in connect
    conn = _connect(dsn, connection_factory=connection_factory, async=async)
psycopg2.OperationalError: FATAL:  database "kamel" does not exist

My db and my conf are in the same directory ,,, my database should be .dump or .zip ?is there any difference?

**Comment by pedrobaeza** [comment]
The database should be directly in Postgres as a regular database. The error is self-explanatory, so please investigate a bit before writing here, or you will leave us exhausted and reluctant for answering the real problems.

**Comment by ronozoro** [comment]
Solved ,, Many Thanks,
Sorry For Disturb :)
