### ISSUE TITLE
[13.0] Error in apriori

### ISSUE THREAD

**Issue by Lukwos** [OCA/OpenUpgrade#4247]
There is an error in this commit : https://github.com/OCA/OpenUpgrade/commit/8d44dea88cbb1aaa3cbf133058ce0eac34fb7967

The new line in apriori is in the rename_module section and must be in the merged_module section

**Comment by Lukwos** [comment]
@robinkeunen

**Comment by pedrobaeza** [comment]
You are right. Fixed in ae58fbf438d9d0ae02bd92ff906bb6d4dae3b7c6

Robin, it's important to check the difference between both dictionaries.

**Comment by robinkeunen** [comment]
Alright, noted. Thank you for the quick fix !
