### ISSUE TITLE
[15.0] hr_expense: wrong amount update to 0.0 for some expense journal items

### ISSUE THREAD

**Issue by dalonsod** [OCA/OpenUpgrade#4251]
Hello,

I've recently found that seems to be a problem with journal entries that belong to expenses. A lot of journal items amounts were set to `0.0`, and every journal entry amount as well.

I've debugged and found this: starting from v15, as journal entries are now similar to invoices, when creating journal items, some of those items are marked as "excluded from invoice tab":

https://github.com/odoo/odoo/blob/15.0/addons/hr_expense/models/hr_expense.py#L618

In v14 this is different, as a pure "entry" journal entry.

This difference is not taken in account during migration AFAIK. Journal entries are recomputed in order to update payment status:

https://github.com/OCA/OpenUpgrade/blob/15.0/openupgrade_scripts/scripts/hr_expense/15.0.2.0/post-migration.py#L24

and that method, since now expenses journal entries are processed as invoices, sets total amount to 0:

https://github.com/odoo/odoo/blob/15.0/addons/account/models/account_move.py#L1525-L1530

that also set journal items amount to 0 if such journal entry have only two items:

https://github.com/odoo/odoo/blob/15.0/addons/account/models/account_move.py#L1593-L1607

This could be an important issue IMO, maybe easy to be detected before in other migrations, so I made an in-depth review if I've lost something in my configuration (I'm making a v11 to v15 migration, not starting from v14), but everything seems to be fine. @hbrunn @legalsylvain @pedrobaeza what do you think, is it a genuine bug or a wrong local configuration?

If it's finally a migration bug, I'll made a PR. What could be the best approach, adding to pre or post migration script a SQL properly setting `exclude_from_invoice_tab` for destination expense journal items? Which could be the exact identification method for them within the journal entry?

Thanks in advance!

**Comment by pedrobaeza** [comment]
So your proposal is to put `exclude_from_invoice_tab` to True? You should do it before the code that set the amounts to 0.

**Comment by dalonsod** [comment]
That's right, e.g. for a journal entry with two items, one of them should be set `exclude_from_invoice_tab` to `True`, leaving the other one unset or `False`. This could be achieved in post-migration before `_compute_amount()`, or within pre-migration.

**Comment by pedrobaeza** [comment]
Go ahead then

**Comment by dalonsod** [comment]
Open #4253

**Comment by pedrobaeza** [comment]
Fixed in #4386
