### ISSUE TITLE
[16.0][account] minor: aml quantity should be False instead of 1.0 for tax lines and payment term lines in v16

### ISSUE THREAD

**Issue by rvalyi** [OCA/OpenUpgrade#4275]
the account.move.line quantity field should now be False for tax lines and payment term lines in v16. I spotted the change while adapting the tests of l10n_br_account for v16. This can be seen here for instance: 

- https://github.com/odoo/odoo/blob/16.0/addons/account/tests/test_account_move_out_invoice.py#L69
- https://github.com/odoo/odoo/blob/16.0/addons/account/tests/test_account_move_out_invoice.py#L107

I have seen that nothing is done to adapt this quantity field in the account pre or post migration scripts and I have seen we still have quantity = 1.0 for these lines on a production database that I migrated.

## Module
account

## Describe the bug
the account.move.line quantity field should be False for tax lines and payment term lines in v16.
**It is not clear if there is any real functional impact** (in some report for instance).

## To Reproduce
**Affected versions**: 16,0

1.  migrate a v15 database to v16 and search the quantity field in tax or payment term lines, for instance with: `select name, quantity, create_date from account_move_line where name ilike '%VAT%';`

**Expected behavior**
quantity should now be False for tax and payment term lines in v16.
I guess we should add some SQL UPDATE for this in the pre-migration or post-migration script.

**Comment by pedrobaeza** [comment]
Are you sure that in v15 `account` module, the quantity is set to 1 in section/notes lines?

**Comment by rvalyi** [comment]
> Are you sure that in v15 `account` module, the quantity is set to 1 in section/notes lines?

yes, as you can see here https://github.com/odoo/odoo/blob/15.0/addons%2Faccount%2Ftests%2Ftest_account_move_out_invoice.py in v15 it still 1.0 as in v14. The change occured with v16. Again I think it is better to follow that change in the migration but I didn't find any real functional impact of this change yet.

**Comment by pedrobaeza** [comment]
I have just queried a real DB, and your assertion is not correct:

![Selección_023](https://github.com/OCA/OpenUpgrade/assets/7165771/a0014ec2-522a-49fa-ada7-8d1f0aaff62c)

**Comment by rvalyi** [comment]
@pedrobaeza it's not about the line notes nor the note sections it is about the aml carrying the taxes or the payment terms, remember these are the auto generated lines from the hidden "account items" tab, not the invoice_line_ids.
Change your where criteria to match them and you will see the 1.0 quantity (can be where credit > 0 for customer ibvoices).

**Comment by pedrobaeza** [comment]
Oh, sorry, my bad. I read bad about which lines. Indeed, they are filled with quantity = 1.0. One simple SQL may serve for tax lines:

```sql
UPDATE account_move_line SET quantity = 0 WHERE tax_line_id IS NOT NULL
```

**Comment by pedrobaeza** [comment]
@rvalyi do you make the PR then?

**Comment by rvalyi** [comment]
> @rvalyi do you make the PR then?

for tax lines it is just as easy as you proposed. As for payment lines I found no easy solution (didn't think much about it either). Not sure fixing only the tax lines will make any difference for now...

I guess if some report will sum qty over all lines without filter it might behave differently if we have these old 1 qty instead of False. Any idea for the payment lines? If we have it I'll do the PR...

**Comment by pedrobaeza** [comment]
The criteria is those with an AR/AP account belonging to a move with move_type of an invoice.

**Comment by rvalyi** [comment]
> The criteria is those with an AR/AP account belonging to a move with move_type of an invoice.

stupid me, I didn't think about combining these two criteria. Indeed! Will propose a PR then.

**Comment by pjrobertson** [comment]
@rvalyi - did you put together a PR or do you still have the SQL/code you used to fix this? Would really appreciate your help on this!

**Comment by pedrobaeza** [comment]
Done in #4421

**Comment by pjrobertson** [comment]
🚀 wow! Thank you @pedrobaeza amazing!

**Comment by rvalyi** [comment]
sorry guys, was on my roadmap but couldn't dive into it yet (I had no SQL, just spotted the issue while migrated a module). Thank you @pedrobaeza for the script.
