### ISSUE TITLE
Attribute Error: 'module' object has no attribute 'symlink'

### ISSUE THREAD

**Issue by ayesaitis** [OCA/OpenUpgrade#428]
Running on windows server.  I get this error as soon as the script starts.  Attempting to migrate from 8.0 to 9.0.

linking server\addons to D:\opentemp\9.0\addons
Traceback (most recent call last):
  File "C:\Python27\migrate9.py", line 318, in <module>
    os.symlink(addon_config['url'],
AttributeError: 'module' object has no attribute 'symlink'

**Comment by pedrobaeza** [comment]
Migration to 9.0 is not yet possible, because it's not completed, and it must be done in Linux. Please follow progressions on the open issue: https://github.com/OCA/OpenUpgrade/issues/400
