### ISSUE TITLE
Migration 6.1 -> 7.0 - comparison configuration Error

### ISSUE THREAD

**Issue by scigghia** [OCA/OpenUpgrade#429]
Hi,
i'm following instructions on this page: https://doc.therp.nl/openupgrade/analyse.html 
but after setup of the two instances, I get this error on target (7.0) server in wizard "comparison configuration"

../server/openerp/addons/openupgrade_records/lib/compare.py", line 216, in compare_sets
    if (column['isfunction'] or column['isrelated'] or
KeyError: 'isrelated'

**Comment by StefanRijnhart** [comment]
Sorry, comparisons between 6.1 and 7.0 are not supported until you port https://github.com/OCA/OpenUpgrade/pull/384 to 6.1. Or you could revert this change locally in your 7.0.
