### ISSUE TITLE
Migration continue don't run migration scripts

### ISSUE THREAD

**Issue by voronind** [OCA/OpenUpgrade#4298]
If I run migration from 13 to 14 with `-u all` option, it works good. If it fails and I want to continue migration I run same command without `-u all` option and odoo don't run `pre` and `post` scripts.

Is it OK? Is there way for step-by-step migration?

**Comment by pedrobaeza** [comment]
You should reset the DB and start from the beginning if you want a correct whole migration.

**Comment by voronind** [comment]
> You should reset the DB and start from the beginning if you want a correct whole migration.

I don't want correct whole migration. I want to continue migration. I will run whole migration later.

**Comment by pedrobaeza** [comment]
Migration scripts are run just once.

**Comment by voronind** [comment]
> Migration scripts are run just once.

If module update fails we need to run migrations again. In 13 version running without `-u all` option works. It continue migration and run migration scripts again.

**Comment by pedrobaeza** [comment]
The same for 14, but only once per module fully updated.
