### ISSUE TITLE
1 Vote For VirtualBox Distro

### ISSUE THREAD

**Issue by jpstaub** [OCA/OpenUpgrade#441]
First off:
Thanks to the developers who have put hard work into OpenUpgrade. I would be nowhere as far as open OpenERP database migration is concerned without it.

Second:
My skill with computers is second (maybe third) rate. I am certain I am not alone based on the solutions I found on-line to solve the problems encountered while upgrading a database of interest using OpenUpgrade.

Third:
Perhaps it would be worthwhile to distro the upgrade process inside a Virtual Machine (VM) for operation inside a service like VirtualBox given the vast number of variables that stand between an inexperienced operator (people like me) and a successful database migration.

I understand a VirtualBox type solution is akin to setting a nail with a pile driver. But a good VM running inside a known entity like VirtualBox seems like it would save a lot of time and effort for developers and users alike. I'd be happy to pass on my own VM solution only it's probably so poorly implemented it would be more harmful than helpful.

All the best,
Jake Staub

**Comment by pedrobaeza** [comment]
You already have a script that download all the needed stuff, so I don't see this as a need and will split efforts in the project.

:-1: for this

**Comment by StefanRijnhart** [comment]
Thank you for your interest in the project. There are all kinds of ways in which an Odoo instance can be built and deployed from source, and in all of those ways you just have to substitute the OpenUpgrade repository for the Odoo one, and include openupgradelib. For my own purposes, I use buildout but you can use any architecture you like. If you want to work with Virtualbox, maybe you can look at provisioning a Vagrant box with the Odoo ansible script here: https://github.com/osiell/ansible-odoo?

If anyone wants to bring anything useful that needs to be included into the project repositories or documentation we are surely interested, but for now this is a hugely understaffed project, so I don't think this will be undertaken by the current regular contributors. I will therefore close this issue, but feel free to follow up or post other concrete issues on the project.

**Comment by dreispt** [comment]
Hi @jpstaub, 

Bitnami has a VM ready to use: https://bitnami.com/stack/odoo/virtual-machine
Turnkey Linux also: https://www.turnkeylinux.org/odoo
Is this what you were thinking of?

Anyway, the OpenUpgrade is quite technical, and I'm not sure a non-developer can make much progress in that particular OCA project.

**Comment by jpstaub** [comment]
Thanks for the responses. 

After working with Docker yesterday I can see something like Docker would be a better way to go if there were desire to go. 

“…the OpenUpgrade is quite technical…”
Very true. I’ve spent more than 100 hours attempting to generate a meaningful output. 

Here’s the thing: All of my time to this point has been consumed replicating an environment that permits OpenUpgrade to run. Not that I’m sophisticated enough to contribute in a meaningful way to the development of OpenUpgrade to an insider looking out, but the possibility that I would with the time spent on environmental replication was completely eliminated. I am contributing to my own development as a computer user but not in the development of the software I’m interested in using in large part in response to the amount of development time it takes to simply arrive at a system that will run. Additionally, soliciting support from developers to solve environmental problems is a drain both ways. 

That aside, it’s fundamentally disturbing to see how troublesome it is to migrate database information to comply with Odoo architectural changes brought on by Odoo itself. Makes me want to stick to metal working machines built in the ’40’s.

Stuff it NSA,
Jake

**Comment by StefanRijnhart** [comment]
Thanks for sharing your opinion. I particularly agree with your last point of course. Again, IMHO the bottleneck currently is not the deployment but the module/version coverage. Even if we smoothen out the environment issue, there is still a lot that can go wrong during a migration. Maybe it is a lack of confidence on my side that I don't want to make it look too easy to perform the migration, because it may not be easy at all? Then again, migrations that only concern covered modules can be run flawlessly in less than an hour. There is also the funding issue: apart from spending 100 hours of their time trying to install Odoo from source using OpenUpgrade branches to run their migration, there is always the option to support the project by hiring any known OCA contributor to run their migration for them, which is likely to lead to new contributions to the project.

**Comment by jpstaub** [comment]
Just wanted to say thanks for putting OCA out in the world. It ended up helping me restore a 7.0 database that was plagued with functional problems. In other words, I migrated from 7.0 to 7.0 to correct the problems that were inherent in a database that OpenERP7 would no longer open. The repaired database works like a charm now. I don’t know enough about OpenERP to know where the trouble was. Suffice it to say, there’s no way I could have done it without OCA. 

I’ve also managed to migrate the OpenERP Demo database from 7.0 to 8.0 but the migration produces a few warnings in the log file. I was wondering if there’s an example database available that produces a clean log file when migrated. A clean migration would help build confidence in the migration method and system. 

Finally, is there a way to donate to the OCA project?

Best wishes,
Jake

**Comment by elicoidal** [comment]
@jpstaub Thanks a lot for your praises and we are happy to see that the OCA is useful in your project.

You can contribute in many ways depending on your budget:
- Become a member of the association (50EUR): https://odoo-community.org/page/website.Membership
- Donate any suitable number (starting from 50EUR): https://odoo-community.org/shop
- become a sponsor of the OCA (starting from 1000EUR): https://odoo-community.org/page/become-a-sponsor

And of course you can spread the word, contribute and review in Github, which we also highly value :)
