### ISSUE TITLE
7.0 to 8.0 migrate error. 'module' object has no attribute 'one2many'

### ISSUE THREAD

**Issue by cewolf2002** [OCA/OpenUpgrade#444]
Please Help.
We tried to migrate our 7.0 database to 8.0.
But always stop here.
I tried to compare database between this one and another 7.0 database but no difference.

Server running ubuntu 12.04.5
All modules are already up-to-date.
And openerp's version is 20160222

error message
  File "/var/tmp/openupgrade/8.0/addons/stock/migrations/8.0.1.1/post-migration.py", line 496, in migrate_stock_warehouse_orderpoint
    openupgrade.get_legacy_name('procurement_id'))
  File "/var/tmp/openupgrade/8.0/server/openerp/openupgrade/openupgrade.py", line 616, in m2o_to_x2m
    elif isinstance(model._columns[field], (openerp.fields.one2many,
AttributeError: 'module' object has no attribute 'one2many'

Full log:
http://pastebin.com/yty41hEE

**Comment by pedrobaeza** [comment]
You're running an outdated OpenUpgrade version without openupgradelib. You have to update it and install openupgradelib

**Comment by cewolf2002** [comment]
Thanks :+1:
