### ISSUE TITLE
Problem in config root path when migrating database to v5 - v8

### ISSUE THREAD

**Issue by synconics** [OCA/OpenUpgrade#445]
Hello,

I am trying to migrate database from v5 to v6.
python migrate.py --config=/home/haresh/chini_data/openerp-server11.conf --database=oasis_new --run-migrations=6.0

Addons path in my config file:

addons_path= /var/tmp/openupgrade/6.0/addons

But at the time of migration system automatically takes another config root path. Don't know why?

config root path:::::::: /usr/local/lib/python2.7/dist-packages/odoo-8.0-py2.7.egg/openerp

 rtp:::::::: /usr/local/lib/python2.7/dist-packages/odoo-8.0-py2.7.egg/openerp

Please explain me why this happening?

**Comment by StefanRijnhart** [comment]
I don't install Odoo globally on my systems, but I image that if you do, you may get interference from globally available executables or import paths. I would recommend to perform the migration on a aystem that does not have a globally installed Odoo.
