### ISSUE TITLE
Migration from OpenERP 6.1 to Odoo 8.0

### ISSUE THREAD

**Issue by dywen69** [OCA/OpenUpgrade#447]
Hello everybody,

i'm currently in trouble doing a migration from openerp 6.1 to Odoo 8.0. To do that i've tried to make a direct migration with --run-migrations=7.0,8.0 option but can't make it work. So i've tried another way and make a dump of my 6.1 database, restore it on a 7.0 openerp and tried to make first a 7.0 upgrade.

I've installed some packages : git, python-pip, python-bzrlib. With pip i've installed : openerp-client-lib, decorator, requests, pyPdf, passlib.

After that i connect into openerp user and make a git clone of the last OpenUpgrade branch into my home folder.

And launch the python migrate.py --config=/etc/openerp-server.conf --database=cytoomigration --run-migrations=7.0 command.

The result : 

linking server/addons to /var/tmp/openupgrade/7.0/addons
getting git://github.com/OpenUpgrade/OpenUpgrade.git
error: unknown option `single-branch'
usage: git clone [options] [--] <repo> [<dir>]

```
-v, --verbose         be more verbose
-q, --quiet           be more quiet
--progress            force progress reporting
-n, --no-checkout     don't create a checkout
--bare                create a bare repository
--mirror              create a mirror repository (implies bare)
-l, --local           to clone from a local repository
--no-hardlinks        don't use local hardlinks, always copy
-s, --shared          setup as shared repository
--recursive           initialize submodules in the clone
--recurse-submodules  initialize submodules in the clone
--template <template-directory>
                      directory from which templates will be used
--reference <repo>    reference repository
-o, --origin <name>   use <name> instead of 'origin' to track upstream
-b, --branch <branch>
                      checkout <branch> instead of the remote's HEAD
-u, --upload-pack <path>
                      path to git-upload-pack on the remote
--depth <depth>       create a shallow clone of that depth
--separate-git-dir <gitdir>
                      separate git dir from working tree
-c, --config <key=value>
                      set config inside the new repository
```

error: unknown option `single-branch'
usage: git clone [options] [--] <repo> [<dir>]

```
-v, --verbose         be more verbose
-q, --quiet           be more quiet
--progress            force progress reporting
-n, --no-checkout     don't create a checkout
--bare                create a bare repository
--mirror              create a mirror repository (implies bare)
-l, --local           to clone from a local repository
--no-hardlinks        don't use local hardlinks, always copy
-s, --shared          setup as shared repository
--recursive           initialize submodules in the clone
--recurse-submodules  initialize submodules in the clone
--template <template-directory>
                      directory from which templates will be used
--reference <repo>    reference repository
-o, --origin <name>   use <name> instead of 'origin' to track upstream
-b, --branch <branch>
                      checkout <branch> instead of the remote's HEAD
-u, --upload-pack <path>
                      path to git-upload-pack on the remote
--depth <depth>       create a shallow clone of that depth
--separate-git-dir <gitdir>
                      separate git dir from working tree
-c, --config <key=value>
                      set config inside the new repository
```

copying database cytoomigration to cytoomigration_migrated...
Copying the database using 'with template'
Failed, fallback on creating empty database + loading a dump
running migration for 7.0
sh: 1: /var/tmp/openupgrade/7.0/server/openerp-server: not found

I've no log for the OpenUpgrade migration.log, there is a new cytoomigration_migrated database created but when i want to connect on the login page, i've an openerp server error : 
  File "/opt/openerp/v7/server/openerp/sql_db.py", line 226, in execute
    res = self._obj.execute(query, params)
ProgrammingError: column res_users.login_date does not exist
LINE 1: SELECT res_users."menu_id",res_users."login_date",res_users....

Don't know what to do....

If anybody can help me, is there someone that i could bring my database dump and that could make a 6.1 to 8.0 migration for me please...

**Comment by hbrunn** [comment]
the error message says you git is too old to understand the parameter. Update git and try your original commandline, everything you tried afterwards cannot work. And you also need to `pip install openupgradelib`.

**Comment by dywen69** [comment]
Thank you very much for that, it helps me a lot!!!!

I'm currently resolving some python import missing, hope that it should work soon!!!

**Comment by dywen69** [comment]
I've some question about a working way to do it. I've on 6.1 machine and a 8.0 machine. 
I want to know if have to make the OpenUpgrade migration on the 6.1 machine, specifying the 6.1 openerp-server.conf and after dump the migrated database to restore it on the 8.0 machine? 
Or i've to dump the original 6.1 database, restore it on the 8.0 machine and make the OpenUpgrade migration specifying the 8.0 odoo-server.conf?

Thank for your help!

**Comment by pedrobaeza** [comment]
You can't migrate to 8.0. You have to first migrate to 7.0, and then to 8.0, and you always use the target version of OpenUpgrade to migrate (in 6.1 DB, you use 7.0)

**Comment by dywen69** [comment]
I think i've missed something. Could you please tell me if i'm right?

First on the 6.1 openerp machine, i've to use the 7.0 branch of OpenUpgrade with the 6.1 openerp-server.conf file.

Then when it done, i've to use the 8.0 branch of OpenUpgrade with the 6.1 openerp-server.conf file and after dump the database and restore it on my 8.0 odoo machine.

Is that correct?

**Comment by pedrobaeza** [comment]
No, you have to use the 6.1 DB. The conf file is created from scratch specially for the migration, pointing to OpenUpgrade addons + custom 7.0 addons path.

**Comment by dywen69** [comment]
So i make the all two migration process (the first from 6.1 to 7.0, and the second from 7.0 to 8.0), on the same 6.1 machine? Using first the original 6.1 DB and after the 6.1to 7.0 migrated DB? 

And when all the migration process is done, i've to dump the last migrated 8.0 DB and restore it on an 8.0 odoo machine?

**Comment by pedrobaeza** [comment]
You can do the migrations in the machine you want, while you have the OpenUpgrade branch version + the DB + the conf in it.

**Comment by dywen69** [comment]
Just to be sure:
migration 6.1 to 7.0 : OpenUpgrade 7.0 branch + original 6.1 DB + original 6.1 openerp-server.conf
migration 7.0 to 8.0 : OpenUpgrade 8.0 branch + migrated DB + original 6.1 openerp-server.conf

Is it all correct?

**Comment by pedrobaeza** [comment]
Again no: the openerp-server.conf is something you have to make totally new for each migration (one for 7.0, and another for 8.0). The conf only have to content the addons_path for OpenUpgrade addons.

**Comment by pedrobaeza** [comment]
I'm going to close this, because this is not an OpenUpgrade issue, but some kind of functional support, and as you can understand, this is not something that we can do for free extensively.
