### ISSUE TITLE
[9.0] OpenUpgrade execute invoices workflow

### ISSUE THREAD

**Issue by esousy** [OCA/OpenUpgrade#448]
OpenUpgrade 'OU' execute invoices workflow while recomputing computed fields, 
So, when the invoice is paid by this auto workflow,  OU tries to mark the purchase or sale orders as done, even if those modules are not loaded yet.

```
return self.models[model_name]
```

KeyError: u'purchase.order'

the source of this issue in this line added for version 9 in module.py
    if obj_list:
        obj_list[0].recompute(cr, openerp.SUPERUSER_ID, {})

**Comment by StefanRijnhart** [comment]
Yes, this is an issue that can be addressed by an OpenUpgrade method to disable the related workflow triggers temporarily. But you mention version 9, and the account module is not yet covered in this version so you may have bigger problems that just that.

**Comment by esousy** [comment]
Thanks for your reply,
what are the modules already covered by version 9?

**Comment by StefanRijnhart** [comment]
Just base. https://github.com/OCA/OpenUpgrade/issues/400
