### ISSUE TITLE
Unable Upgrade: How to upgrade from Odoo 16 to Odoo 17 ?

### ISSUE THREAD

**Issue by rathorrupam** [OCA/OpenUpgrade#4493]
Hi everyone,

I want to migrate my V16 database to V17, I'm encountering some difficulties.

Steps taken to migrate from Odoo 16 to Odoo 17:

I restored my V16 database to a V17 version
 I downloaded the openupgrade_scripts module
 I created a migration_scripts folder, adding the openupgrade_scripts module, and then added the path to my addons.
I installed the openupgradelib package
and called my instance with the command: ./odoo-bin --database=DEMO-MIGRATION --upgrade-path=/mnt/extra-addons/migration_scripts/openupgrade_scripts/scripts
mistake: 
	​Usage: odoo-bin server [options] 

	​odoo-bin server: error: option --upgrade-path: the path '/mnt/extra- ​ ​ ​	​	​	​	​	​addons/migration_scripts/openupgrade_scripts/scripts' is not a valid upgrade  ​directory

I tried the second option:

[options]

upgrade_path = /mnt/extra-addons/migration_scripts/openupgrade_scripts/scripts

I have followed the recommendations given here 👇

https://github.com/OCA/OpenUpgrade/tree/17.0/openupgrade_scripts#:~:text=%5Boptions%5D%0Aupgrade_path%20%3D%20/PATH_TO_openupgrade_scripts_MODULE/scripts/

There's no error, but my database hasn't been migrated

Am I missing something?

Thank you for your help and suggestions**

**Comment by rathorrupam** [comment]
@rvalyi @ovnicraft @pniederlag @azmeuk @

**Comment by pedrobaeza** [comment]
OpenUpgrade v17 is not yet ready. You can follow its progress at https://github.com/OCA/OpenUpgrade/issues/4124
