### ISSUE TITLE
[16.0] After DB migration account resequence failing

### ISSUE THREAD

**Issue by ljimenezsidoo** [OCA/OpenUpgrade#4498]
After complete a migration from 11.0/12.0 to 16.0 the account functionality resequence is not working when select multiple invoices.
currently occurs in two different databases

## Module
account

## Describe the bug
Resequence functionality change the name of the invoice to '/'
This change should not raise this constraint _check_unique_sequence_number but it is happening.
In both instances with all custom modules installed but fresh db is not happening

## To Reproduce
**Affected versions**: 16.0

1. Complete migration from 11.0/12.0 to 16.0 with openupgrade
2. Select multiple posted invoices and try to resequence
![image](https://github.com/OCA/OpenUpgrade/assets/14888212/b4150938-7aa5-40af-9ab8-e91fee8a91d7)

**Expected behavior**
Select multiple posted invoices and try to resequence.
After launching the process the invoice names should be updated without throw exceptions.

**Comment by pedrobaeza** [comment]
This is because OpenUpgrade is not changing previous sequences, and there are overlapped numbers in your DB. You must check it and decide what to do, but that's out of the scope of OpenUpgrade, so closing.
