### ISSUE TITLE
Different options in reconciliation models

### ISSUE THREAD

**Issue by GrmnTUK** [OCA/OpenUpgrade#4569]
## Module
Billing (I don't know if it is another module that interferes, I have tried to compare it with the modules installed in the two versions)
## Describe the bug
Hello, I have an odoo 16 that has been migrated from odoo 14, passing through odoo 15 until reaching odoo 16, the issue is that in the Billing module, specifically in the Configuration > Reconciliation models section, the options that appear if I compare with a clean installation of odoo 16 they are different.

## To Reproduce
Odoo 16, migrated from Odoo 14 to Odoo 15 to Odoo 16

1. Billing
2. Configuration
3. Accounting entries

**Expected behavior**

- What I get (Odoo 16 migrated)

Create a mismatch manually by clicking the button.
Suggest counterpart values.
Match existing invoices

- What I get in Odoo 16 (installed from 0)
Button to generate a counterpart entry
Rule to suggest a contra entry
Invoice matching rule

![image](https://github.com/user-attachments/assets/801436e2-2c09-4251-8685-a85ab5c1c01e)
![image](https://github.com/user-attachments/assets/7914859a-a667-4bee-a21d-ebcafdfc0b39)

NOTE: I have already tried to run a "odoo -u all"

**Comment by legalsylvain** [comment]
Hi @GrmnTUK. Could you rename title and content of your issue in english ? 
thanks !

**Comment by GrmnTUK** [comment]
> Hi @GrmnTUK. Could you rename title and content of your issue in english ? thanks !

Done!

**Comment by pedrobaeza** [comment]
It seems you haven't loaded Spanish language overwriting terms.

**Comment by GrmnTUK** [comment]
I have refreshed the translations and it now appears correctly. Thanks @pedrobaeza!!
