### ISSUE TITLE
NameError: name 'bzrlib' is not defined

### ISSUE THREAD

**Issue by albin-john** [OCA/OpenUpgrade#461]
Traceback (most recent call last):
  File "migrate.py", line 249, in <module>
    bzrlib.plugin.load_plugins()
NameError: name 'bzrlib' is not defined

**Comment by pedrobaeza** [comment]
You have to install that library (`sudo apt-get install python-bzrlib` in Debian+derivatives, `sudo pip install bzrlib` in general).

**Comment by albin-john** [comment]
Thank you very much @pedrobaeza
