### ISSUE TITLE
9.0 docs

### ISSUE THREAD

**Issue by hbrunn** [OCA/OpenUpgrade#463]
Is it by purpose that 9.0's doc directory is empty? https://github.com/OCA/OpenUpgrade/tree/9.0/openerp/openupgrade/doc

Or is this a glitch from the initial OpenUpgrade-import?

(the reason I ask is that I'm busy estimating the work load for a migration project, and for the ones where's nothing to do, I think it's a nice thing to write 'Nothing to do' there at once)

**Comment by hbrunn** [comment]
@StefanRijnhart any idea?

**Comment by StefanRijnhart** [comment]
The docs have not been moved there and are still maintained in 8.0. Migration needs to be coordinated with Therp as they host the documentation. Moving the docs between branches is trivial, but preparing the build environment is a little more complex as I remember. It would be great if you could have a look and give a go to move the docs to 9.0.

**Comment by pedrobaeza** [comment]
We can take the occasion to try to leave on each version the document about their module coverage to help the maintenance when new modules are migrated. This is not easy task to do directly with the RST compiler, as pointed by @StefanRijnhart, but maybe we can gather the corresponding files for each version and compile all together in a script.

**Comment by hbrunn** [comment]
@StefanRijnhart @pedrobaeza good point leaving a version's module coverage in the respective branch. The script proposed in #464 https://github.com/OCA/OpenUpgrade/compare/9.0...hbrunn:9.0-doc?expand=1#diff-08d4ec7cbf6f53396c7a4e38e949d00fR1 is used to generate https://doc.therp.nl/openupgrade-test, so if we merge this, I can simply switch the main documentation to this one

**Comment by pedrobaeza** [comment]
As a PR has been proposed in https://github.com/OCA/OpenUpgrade/pull/464, I close this issue and we can continue any discussion there (this is to avoid opened issues that are not closed when PR is merged).
