### ISSUE TITLE
[hr_recruitement]sql constraint hr_job_hired_employee_check 

### ISSUE THREAD

**Issue by flotho** [OCA/OpenUpgrade#4679]
While upgrading to 15.0 I have this SQL issue :
```
 ligne de la relation « hr_job » viole la contrainte de vérification « hr_job_hired_employee_check »
```
I'm looking for the constraint in database and it's present. 
Unfortunately, I didn't succeed in finding the definition in python for `hired_employee_check` neither as sql_constraints nor in another file.
Any help would be appreciated to spot the part of the code so that I can adapt the scripts.
Regards

**Comment by pedrobaeza** [comment]
If the DB is older and you have migrated previously, it may be a leftover of old migrations.

**Comment by flotho** [comment]
thanks @pedrobaeza , (facepalm) for me, I've checked the wrong previous database !!
