### ISSUE TITLE
[15.0]l10n_fr fail on update_taxes_from_templates

### ISSUE THREAD

**Issue by flotho** [OCA/OpenUpgrade#4683]
## Module
l10n_fr

## Describe the bug

Coming from v14 with history of 10.0 .
While upgrading the v15,  this method is called https://github.com/OCA/OCB/blob/15.0/addons/l10n_fr/migrations/2.1/post-migrate_update_taxes.py#L6 in the OCB basecode .

The message thrown is `Invoice and credit note repartition should have at least one tax repartition line` coming from https://github.com/OCA/OCB/blob/15.0/addons/account/models/account_tax.py#L194 

## To Reproduce
**Affected versions**:

15.0

**Expected behavior**

No issue

**Additional context**

Coming from v14 with history of 10.0 .
I'm not sure how to handle this, any advice would be appreciated.
Regards

**Comment by pedrobaeza** [comment]
Not related to OpenUpgrade, but to Odoo.

**Comment by flotho** [comment]
you're right
