### ISSUE TITLE
Product qty is lost when migrating to odoo v7 -> v9.

### ISSUE THREAD

**Issue by synconics** [OCA/OpenUpgrade#472]
Hello,

I am trying to migrate database v7 to v9.
After migrating i found that qty_available, incoming_aty, outgoing_qty, virtual_available fields are empty on product form. and stock. quants are also missing from database.

I dont found any solution for fix it. please guide me.

**Comment by legalsylvain** [comment]
Please, could you mention if the information is lost during the migration between 7 to 8 or between 8 to 9.

regards.

**Comment by synconics** [comment]
Hello,
Migration was successfully done and all product data is migrated but some fields like qty_available, incoming_qty, virtual_available, virtual_available are empty.

And also stock.quants are missing from database.

**Comment by legalsylvain** [comment]
this is quite weird. Could you retry just doing a 7 to 8 migration and check the result ?
kind regards.

**Comment by pedrobaeza** [comment]
You have an outdated version of OpenUpgrade without stock migration scripts.

**Comment by StefanRijnhart** [comment]
Well, stock is not yet supported in 9.0 so there is not much we can say about a migration to 9.0. Indeed, check the results of 8.0 first. If the results are faulty there as well, paste your full debug log of the migration in a pastebin and refer here.
