### ISSUE TITLE
CSS messed up after migration

### ISSUE THREAD

**Issue by karlis-dreizis** [OCA/OpenUpgrade#474]
I tried to migrate an empty v8 db to a v9 using the migrate.py script and using the manual method. It generally worked. 

Everything seem just fine in on openupgrades server, but for some reason on the 9.0 and master branch the css resource path is messed up. 

/website/static/src/less**/web.assets_backend**/import_bootstrap.less.css    <-- 9.0 |  returns 404
/web/static/src/less**/web.assets_backend**/...
/mail/static/src/less**/web.assets_backend**/... etc

vs

/website/static/src/less/import_bootstrap.less.css   <-- openupgrade
/web/static/src/less/import_bootstrap.less.css... etc

I tried but with no results
- making a virtualenv from v9 requirements.txt - no change
- -u all after the migration on openupgrade and on v9.0

If anyone has any clue where to look or how to resolve this problem I would appreciate any pointers.

**Comment by StefanRijnhart** [comment]
No migration is yet possible for 9.0. See https://doc.therp.nl/openupgrade/modules80-90.html.

**Comment by karlis-dreizis** [comment]
That being the state of things. Would you recommend going down the path of sql scripts or trying to get openupgrade to workable state? Or maybe there are other alternatives?

I read the doc, some of the issues, pull requests and I understand that everything still way in the early days of development. Yet I saw some individuals repos have migration scripts that cover at least a subset of module . https://github.com/microcom/OpenUpgrade/tree/9.0-base

And based on this the base is reported as ported or at least partially https://github.com/OCA/OpenUpgrade/issues/400

**Comment by pedrobaeza** [comment]
Yes, this is progressing, but slowly yet. You can contribute in any moment making PRs for the missing parts. It's a great challenge, but very satisfying if you get it.

**Comment by hbrunn** [comment]
and please try to persuade people who already wrote migration scripts to offer them here. It would be a pity to have to duplicate the work.
