### ISSUE TITLE
Can we migrate v7 db to v9 db? how ?

### ISSUE THREAD

**Issue by synconics** [OCA/OpenUpgrade#476]
Hello,
As i found we can migrate v7 to v8 but I dont found any proper steps to migrate v7 to v9.
Is there any solution available?

Thanks

**Comment by pedrobaeza** [comment]
No, there isn't. The migration to v9 is not yet finished. Track the progress in https://github.com/OCA/OpenUpgrade/issues/400.

Anyway, when ready, you must migrate from v7 to v8, and then from v8 to v9, but not directly.
