### ISSUE TITLE
[6.1 project_mrp] procurement_order: sale_id column does not exist

### ISSUE THREAD

**Issue by ghost** [OCA/OpenUpgrade#477]
Dear all,

First i would like to congratulate you for your efforts to build a community. 
While migrating my old 6.04 database to OpenERP 6.1, the migration script stopped:

select t.id, t.project_id, po.sale_id from project_task t join procurement_order po on t.procurement_id=po.id where po.sale_id is not null

Programming error: ERREUR:  column po.sale_id does not exist

The error is located in https://github.com/OCA/OpenUpgrade/blob/6.1/addons/project_mrp/migrations/6.1.1.0/post-migrate.py#L28

Table procurement_order (without constraint) is :
CREATE TABLE procurement_order
(
  id serial NOT NULL,
  create_uid integer,
  create_date timestamp without time zone,
  write_date timestamp without time zone,
  write_uid integer,
  origin character varying(64), -- Source Document
  product_uos_qty double precision, -- UoS Quantity
  product_uom integer NOT NULL, -- Product UoM
  product_uos integer, -- Product UoS
  product_qty double precision NOT NULL, -- Quantity
  procure_method character varying(16) NOT NULL, -- Procurement Method
  message character varying(64), -- Latest error
  location_id integer NOT NULL, -- Location
  move_id integer, -- Reservation
  product_id integer NOT NULL, -- Product
  priority character varying(16) NOT NULL, -- Priority
  name character varying(64) NOT NULL, -- Reason
  date_planned timestamp without time zone NOT NULL, -- Scheduled date
  close_move boolean NOT NULL, -- Close Move at end
  company_id integer NOT NULL, -- Company
  date_close timestamp without time zone, -- Date Closed
  note text, -- Note
  state character varying(16) NOT NULL, -- State
  purchase_id integer, -- Purchase Order
  task_id integer, -- Task
  bom_id integer, -- BoM
  requisition_id integer-- Latest Requisition)

The correct SQL query **_could be**_

select t.id, t.project_id, po.id from project_task t join procurement_order po on t.procurement_id=po.id where po.id is not null

as this is a JOIN and there is no po.sale_id in the table.

Many thanks.
Kellogs

**Comment by StefanRijnhart** [comment]
Well, thank you for your interest in OpenUpgrade!

The code looks wrong to me indeed. I cannot find this sale_id on the procurement_order in the 6.0 data model. Instead, there is a procurement_id on the sale_order_line. It seems that procurement's new field sale_line_id in 6.1, and the related field on project_task that refers to it can simply be calculated by taking the reverse of this field. @hbrunn, any clues?

**Comment by hbrunn** [comment]
I can't remember how this came back then, and verify this is wrong, so a PR to fix this would be a good thing

**Comment by pedrobaeza** [comment]
Closing this as very old. If someone comes again with this, it can be reopened.
