### ISSUE TITLE
Tedious upgrade mechanism : an alternative, Drupal upgrade mechanism

### ISSUE THREAD

**Issue by ghost** [OCA/OpenUpgrade#480]
Dear all,

OpenERP aka OdooS***\* upgrade mechanism seems tedious. I have using Drupal for years and its upgrade mechanism is barely simple and unbreakable, regarding developers follow guidelines:

Each module includes a property returning major version and minor version and dependencies.
It also includes SQL code to upgrade the module to any version (but no downgrades).

Therefore, when you upgrade modules and core, the upgrade code is already included in the platform and no additional tool is needed. It is also very well tested by the community which is upgrading all the time.

IMHO OpenERP should lean on a similar mechanism.

This also has a very good consequence : users know that they are able to upgrade at any time, so they don't have to rely on paid service from a provider offering support. In other words, Drupal is well designed, OpenERP upgrade is not.

Besides, this does not stop me from using OpenUpgrade, the only alternative and thanks for developing it.

Kind regards,
Kellogs

**Comment by pedrobaeza** [comment]
There's no such possibility, as Odoo doesn't integrate the upgrade mechanism in their core (it's a paid service), so mechanisms like this are needed.

**Comment by ghost** [comment]
As OCA is now a free community, you should be able to open a ticket somewhere to indicate this is something that we should think about, as a needed feature and then write a collaborative Spec. 

Where can I add a feature request for such a feature? IMHO this would be less work to add a native upgrade mechanism rather than work on OpenUpgrade, which seems to be a lot of work.
