### ISSUE TITLE
[6.1] Third-party module marked as upgradable after migration but is not installed

### ISSUE THREAD

**Issue by ghost** [OCA/OpenUpgrade#481]
Dear all,

After migrating 6.04 to 6.1 nearly without error, I stumbled upon this issue:

The following packages are marked as "upgradable" but are not installed in OpenERP addons directory:
account_3rd_party_generat : to upgrade
account_fstr : to upgrade
account_report : to upgrade
base_report_creator : to upgrade
base_scheduler_creator : to upgrade
currency_rate_update : to upgrade
intrastat_base : to upgrade
invoice_cn23 : to upgrade
l10n_fr_intrastat_product : to upgrade
nan_product_pack : to upgrade
report_aeroo : to upgrade
report_aeroo_printscreen : to upgrade
report_aeroo_sample : to upgrade
smsclient : to upgrade

Now I would like to remove those missing modules from OpenERP schema, but I cannot.

How can I proceed to remove those modules? The problem is that some core features in OpenERP are now broken.

Kind regards, 
Kellogs

**Comment by ghost** [comment]
OK, I read in another post that I should use server-tools to purge the schema. Unfortunately, this feature is supported only from 7.0 onwards. So I probably need to migrate to 7.0 or 8.0 and then purge.

Kind regards,
Kellogs

**Comment by ghost** [comment]
Closing issue as migrating to 7.0 or 8.0 is the answer.

**Comment by ghost** [comment]
I removed the original modules from OpenERP and performed a new migration. And it worked like a charm (except other minor issues). You cannot migrate third-party modules.

**Comment by pedrobaeza** [comment]
You can migrate them if you have the proper modules in the target version, and providing the proper migrations scripts if needed.
