### ISSUE TITLE
[6.1] to [7.0]: account journal duplicate

### ISSUE THREAD

**Issue by ghost** [OCA/OpenUpgrade#483]
When migrating from 6.1 to 7.0, OpenUpgrade tries to create new sequences, and this fails because of sequence name being unique:

insert into "ir_sequence_type" (id,"code","name",create_uid,create_date,write_uid,write_date) values (45,'account.journal','Account Journal',1,(now() at time zone 'UTC'),1,(now() at time zone 'UTC'))
fails because of unique constraint on code.

Here is the log:
2016-04-27 10:44:27,172 9917 INFO xxxx_61_migrated openerp.modules.loading: module account_sequence: loading account_sequence_data.xml
2016-04-27 10:44:27,191 9917 ERROR xxxxx_61_migrated openerp.sql_db: bad query: insert into "ir_sequence_type" (id,"code","name",create_uid,create_date,write_uid,write_date) values (45,'account.journal','Account Journal',1,(now() at time zone 'UTC'),1,(now() at time zone 'UTC'))
Traceback (most recent call last):
  File "/var/tmp/openupgrade/7.0/server/openerp/sql_db.py", line 226, in execute
    res = self._obj.execute(query, params)
IntegrityError: ERREUR:  la valeur d'une clé dupliquée rompt la contrainte unique « ir_sequence_type_code_unique »
DÉTAIL : La clé « (code)=(account.journal) » existe déjà.

Kind regards,
Kellogs

**Comment by ghost** [comment]
This is not a journal duplicate, rather a problem of sequence migration.

**Comment by pedrobaeza** [comment]
No, it's a problem that you have manipulated the 6.1 database, removing XML-ID references in any way (for example, removing records and then recreating them by hand), and thus the migration tries to create them again, so you have to solve these problems in your DB, It's not an OpenUpgrade business.

**Comment by ghost** [comment]
No I did not manipulate records by hand, removing XML-ID references. I am now using the 6.1 database in OpenERP 6.1 and it works like a charm. Please reopen and rename sequence migration problem.

If you understand the problem in more details, please comment and indicate how to fix.

**Comment by pedrobaeza** [comment]
I don't think so. I have migrated several 6.0 > 6.1 databases without that problem. In any case, just remove the offending record that exists in the DB to let the process to continue.

**Comment by ghost** [comment]
Thank you for this quick answer.

The table involved is : account_sequence_data
These are the different balances names, I cannot remove them and let OpenUpgrade recreate them.

In my 6.1 database the same record exists with ir_sequence_type.id=6
SELECT \* FROM _sequence_type WHERE id=6
"6";1;"2011-02-03 01:32:19.03693";"";;"account.journal";"Account Journal"

The query fails as it tries to insert a duplicate on code:
insert into "ir_sequence_type" (id,"code","name",create_uid,create_date,write_uid,write_date) values (45,'account.journal','Account Journal',1,(now() at time zone 'UTC'),1,(now() at time zone 'UTC'))

I suspect there is something wrong with trying to recreate a records which already exists.

Where should I try to remove this in the migration code?

**Comment by pedrobaeza** [comment]
If it exists in your DB, you should check that there's a record in the ir_model_data with the same name as the new XML that points to this record in the res_id column.

**Comment by ghost** [comment]
The error is located here:
2016-04-27 21:34:57,441 20026 ERROR xxxx_61_migrated openerp.tools.convert: Parse error in /var/tmp/openupgrade/7.0/addons/account_sequence/account_sequence_data.xml:7:

I will try to remove account_sequence module in the 6.1 database and migrate. I can always reimplement account_sequence afterwards.

**Comment by ghost** [comment]
I could remove account_sequence module. Not a major issue as this is not a core module and can be reinstalled afterwards. Please note that upgrading account_sequence module is buggy.

I will come back later on this issue to investigate the 61 database.

Many thanks for your help.

**Comment by pedrobaeza** [comment]
account_sequence module migration is not covered yet: https://doc.therp.nl/openupgrade/modules60-61.html

**Comment by ghost** [comment]
My fault, this is my first migration. I will come back and commit a solution for account_sequence afterwards. I would like to learn how to use Openupgrade with the idea of implementing it within OCB. Thanks for your help.

**Comment by ghost** [comment]
I added this feature request: https://github.com/OCA/OpenUpgrade/issues/485

Many thanks for your time and help.
