### ISSUE TITLE
[all] Feature request: warn users about non-supported modules

### ISSUE THREAD

**Issue by ghost** [OCA/OpenUpgrade#485]
i.e. module-coverage should handeled inside OpenUpgrade.

This would be nice to warn users during execution of Openupgrade about non-supported modules. 
Inside OpenUpgrade, there should be a property returning the level of migration and it should be displayed in the log. The list of modules can be stored in GIT. 

So users can perform a quick review reading the logs only.

Presently, users need to connect to:
https://doc.therp.nl/openupgrade/status.html#module-coverage

I spent hours trying to migrate a 6.1 database to 7.0 (no problem I am learning) before understanding that some modules could not be migrated (account_sequence).

**Comment by pedrobaeza** [comment]
You already have this list in https://doc.therp.nl/openupgrade/modules60-61.html. I already saw you this one. And in the header of the OpenUpgrade project in GitHub, you have the link to this documentation.

**Comment by ghost** [comment]
I agree with you, but for automation purpose, the list of supported modules should be handled inside Openupgrade. When reviewing the log, it saves a lot of time.

Please keep this issue open, I may pick it up myself.

Migrating OCB between revisions is the most important issue IMHO. There are dozens of hosting services and if want to impose OCB, it has to upgrade smoothly.

**Comment by pedrobaeza** [comment]
What do you mean by log?

**Comment by StefanRijnhart** [comment]
Actually, it would be great to have it as a feature.

**Comment by legalsylvain** [comment]
I'm interested to work on it. How do you imagine this log ? What I can imagine is the following : 
at the beginning of OpenUpgrade, run a routine that analyse each installed module, and display : 
- name of the current module, 
- current state and current version
- exist in the next version : Y / N
- renamed in the next version : N / the name of the new module. (based on [this file](https://github.com/OCA/OpenUpgrade/blob/9.0/openerp/addons/openupgrade_records/lib/apriori.py))
- state of the migration work based based on [this files](https://github.com/OCA/OpenUpgrade/blob/9.0/openerp/openupgrade/doc/source/modules80-90.rst)

Alternatively, we could imagine one or two news keys in the manifest of each module : 
- 'migration_state': 'to_analyse', 'nothing_to_do', 'done', 'wip'
- 'new_name': False (or the name of the new module)

CC : @StefanRijnhart, @pedrobaeza.

kind regards.

**Comment by pedrobaeza** [comment]
As this has not been materialized (and I think that it's very difficult to be done), I close this issue. If someone wants to revisit this topic later, he/she can open a new issue/PR about it.
