### ISSUE TITLE
Problems upgrading a bare bones 7.0 database

### ISSUE THREAD

**Issue by IJOL** [OCA/OpenUpgrade#508]
While doing what i suppoussed should be a ·easy· upgrade process just to try it, i get this error on migrate log:

2016-06-13 15:50:58,465 20491 ERROR acesticker_migrated openerp.addons.base.ir.ir_ui_view: El elemento '<group name="status" version="7.0">' no puede ser localizado en la vista padre

Error de contexto:
Vista `product.product.form`
[view_id: 222, xml_id: product.product_normal_form_view, model: product.product, parent_id: 240]
2016-06-13 15:50:58,465 20491 CRITICAL acesticker_migrated openerp.service.server: Failed to initialize database `acesticker_migrated`.
Traceback (most recent call last):
  File "/var/tmp/openupgrade/8.0/server/openerp/service/server.py", line 929, in preload_registries
    registry = RegistryManager.new(dbname, update_module=update_module)
  File "/var/tmp/openupgrade/8.0/server/openerp/modules/registry.py", line 370, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/var/tmp/openupgrade/8.0/server/openerp/modules/loading.py", line 483, in load_modules
    if not Views._validate_custom_views(cr, SUPERUSER_ID, model):
  File "/var/tmp/openupgrade/8.0/server/openerp/api.py", line 268, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/var/tmp/openupgrade/8.0/server/openerp/addons/base/ir/ir_ui_view.py", line 1133, in _validate_custom_views
    return self._check_xml(cr, uid, ids, context=context)
  File "/var/tmp/openupgrade/8.0/server/openerp/api.py", line 268, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/var/tmp/openupgrade/8.0/server/openerp/addons/base/ir/ir_ui_view.py", line 197, in _check_xml
    view_def = self.read_combined(cr, uid, view.id, ['arch'], context=context)
  File "/var/tmp/openupgrade/8.0/server/openerp/api.py", line 268, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/var/tmp/openupgrade/8.0/server/openerp/addons/base/ir/ir_ui_view.py", line 561, in read_combined
    cr, uid, arch_tree, view_arch, parent_view['id'], context=context)
  File "/var/tmp/openupgrade/8.0/server/openerp/api.py", line 268, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/var/tmp/openupgrade/8.0/server/openerp/addons/base/ir/ir_ui_view.py", line 498, in apply_inheritance_specs
    self.raise_view_error(cr, uid, _("Element '%s' cannot be located in parent view") % tag, inherit_id, context=context)
  File "/var/tmp/openupgrade/8.0/server/openerp/api.py", line 268, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/var/tmp/openupgrade/8.0/server/openerp/addons/base/ir/ir_ui_view.py", line 383, in raise_view_error
    raise AttributeError(message)
AttributeError: El elemento '<group name="status" version="7.0">' no puede ser localizado en la vista padre

Error de contexto:
Vista `product.product.form`
[view_id: 222, xml_id: product.product_normal_form_view, model: product.product, parent_id: 240]
2016-06-13 15:50:58,467 20491 INFO acesticker_migrated openerp.service.server: Initiating shutdown
2016-06-13 15:50:58,467 20491 INFO acesticker_migrated openerp.service.server: Hit CTRL-C again or send a second signal to force the shutdown.
2016-06-13 15:50:58,467 20491 DEBUG acesticker_migrated openerp.service.server: current thread: <_MainThread(MainThread, started 140240162830144)>
2016-06-13 15:50:58,467 20491 DEBUG acesticker_migrated openerp.service.server: process <_MainThread(MainThread, started 140240162830144)> (False)
2016-06-13 15:50:58,467 20491 DEBUG acesticker_migrated openerp.service.server: process <Thread(openerp.addons.bus.bus.Bus, started daemon 140239909750528)> (True)
2016-06-13 15:50:58,467 20491 DEBUG acesticker_migrated openerp.service.server: --

**Comment by hbrunn** [comment]
when posting logs, set your system language to English next time, not everybody speaks Spanish. Openupgrade should ignore most view related errors, but this one looks different. Post the architecture of view with ids 222, 240 in the database to be migrated

**Comment by IJOL** [comment]
Hmmn, everybody should know Spanish by now, we are taking the world by storm.... :)  I's a joke obviously, but i take the point we'll try to post them at least gtranslated, because of my big ignorance, how in the hell i could change the language of logs?... ( dont be afraid me colleagues are doing some frantic gogling to get know it )

I'm posting here  the arch of the 2 views involved from the database to be translated ( not the remain of the upgrade the *_migrated one )  first the 240 one (the parent):

``` xml
<?xml version="1.0"?>
<form string="Product Template" version="7.0">
                    <label for="name" class="oe_edit_only"/>
                    <h1><field name="name"/></h1>
                    <label for="categ_id" class="oe_edit_only"/>
                    <h2><field name="categ_id"/></h2>
                    <notebook>
                        <page string="Information">
                        <group>
                            <group string="Product Type">
                                <field name="sale_ok"/>
                            </group>
                            <group string="Procurement">
                                <field name="type"/>
                            </group>

                            <group string="Base Prices">
                                <field name="list_price"/>
                                <field name="standard_price" attrs="{'readonly':[('cost_method','=','average')]}"/>
                                <field name="cost_method"/>
                            </group>

                            <group string="Weights">
                                <field digits="(14, 3)" name="volume" attrs="{'readonly':[('type','=','service')]}"/>
                                <field digits="(14, 3)" name="weight" attrs="{'readonly':[('type','=','service')]}"/>
                                <field digits="(14, 3)" name="weight_net" attrs="{'readonly':[('type','=','service')]}"/>
                            </group> 

                            <group name="status" string="Status">
                                <field name="categ_id"/>
                                <field name="state"/>
                                <field name="product_manager"/>
                            </group>

                            <group name="uom" string="Unit of Measure">
                                <field name="uom_id" on_change="onchange_uom(uom_id,uom_po_id)" groups="product.group_uom"/>
                                <field name="uom_po_id"/>
                            </group>

                            <group name="uos" groups="product.group_uom" string="Second Unit of Measure">
                                <field name="uos_id"/>
                                <field name="uos_coeff"/>
                                <field name="mes_type"/>
                            </group>
                        </group>
                        </page>
                        <page string="Procurement &amp; Locations">
                            <group>
                                <group name="delay" string="Delays">
                                    <label for="produce_delay"/>
                                    <div>
                                        <field name="produce_delay" class="oe_inline"/> days
                                    </div>
                                    <field name="warranty"/>
                                </group>
                            </group>

                        </page>
                        <page string="Suppliers">
                            <field name="seller_ids"/>
                        </page>
                        <page string="Descriptions">
                            <separator string="Internal Description"/>
                            <field name="description"/>
                            <separator string="Sale Description"/>
                            <field name="description_sale"/>
                            <separator string="Purchase Description"/>
                            <field name="description_purchase"/>
                        </page>
                    </notebook>
                </form>
```

## the 222 ( the heir)

``` xml
<?xml version="1.0"?>
<form string="Product" version="7.0">
                    <sheet>
                        <field name="image_medium" widget="image" class="oe_avatar oe_left"/>
                        <div class="oe_title">
                            <div class="oe_edit_only">
                                <label for="name" string="Product Name"/>
                            </div>
                            <h1>
                                <field name="name"/>
                            </h1>
                            <label for="categ_id" class="oe_edit_only"/>
                            <h2><field name="categ_id"/></h2>
                            <div name="options" groups="base.group_user">
                                <field name="sale_ok"/>
                                <label for="sale_ok"/>
                            </div>
                        </div>
                        <div class="oe_right oe_button_box" name="buttons">
                        </div>
                        <notebook>
                            <page string="Information">
                                <group>
                                    <group>
                                        <field name="type"/>
                                        <field name="uom_id" on_change="onchange_uom(uom_id,uom_po_id)" groups="product.group_uom"/>
                                        <field name="list_price"/>
                                    </group>
                                    <group>
                                        <field name="default_code"/>
                                        <label for="ean13"/>
                                        <div name="ean">
                                            <field name="ean13" placeholder="e.g. 5901234123457"/>
                                        </div>
                                    </group>
                                    <group>
                                        <field groups="product.group_product_variant" name="variants"/>
                                        <field name="price_margin" groups="product.group_product_variant"/>
                                        <field name="price_extra" groups="product.group_product_variant"/>
                                    </group>
                                </group>
                                <field name="description" placeholder="describe the product characteristics..."/>
                            </page>
                            <page string="Procurements" groups="base.group_user">
                                <group name="procurement">
                                    <group name="general">
                                        <field name="cost_method" groups="product.group_costing_method"/>
                                        <field name="standard_price" attrs="{'readonly':[('cost_method','=','average')]}"/>
                                    </group>
                                    <group name="procurement_uom" groups="product.group_uom" string="Purchase">
                                        <field name="uom_po_id"/>
                                    </group>
                                </group>
                                <separator string="Description for Suppliers"/>
                                <field name="description_purchase" placeholder="This note will be displayed on requests for quotation..."/>
                            </page>
                            <page string="Inventory" groups="base.group_user">
                                <group name="inventory">
                                    <group name="status" string="Status">
                                        <field name="state"/>
                                        <field name="product_manager"/>
                                    </group>
                                    <group name="Weights" groups="product.group_stock_packaging" string="Weights">
                                        <field digits="(14, 3)" name="volume" attrs="{'readonly':[('type','=','service')]}"/>
                                        <field name="weight" attrs="{'readonly':[('type','=','service')]}"/>
                                        <field name="weight_net" attrs="{'readonly':[('type','=','service')]}"/>
                                    </group>
                                </group>
                            </page>
                            <page string="Sales" attrs="{'invisible':[('sale_ok','=',False)]}">
                                <group name="sale">
                                    <group string="Sale Conditions">
                                        <label for="warranty"/>
                                        <div>
                                            <field name="warranty" class="oe_inline"/> months
                                        </div>
                                    </group>
                                    <group groups="product.group_uos" string="Unit of Measure">
                                        <field name="uos_id"/>
                                        <field name="uos_coeff"/>
                                        <field name="mes_type"/>
                                    </group>
                                </group>
                                <field name="packaging" groups="product.group_stock_packaging">
                                    <form string="Packaging" version="7.0">
                                        <group col="4">
                                            <field name="ean"/>
                                            <field name="sequence" invisible="1"/>
                                            <newline/>
                                            <field name="qty"/>
                                            <field name="ul"/>
                                            <field name="weight_ul"/>
                                            <separator colspan="4" string="Palletization"/>
                                            <field name="ul_qty"/>
                                            <field name="rows"/>
                                            <field name="weight"/>
                                            <separator colspan="4" string="Pallet Dimension"/>
                                            <field name="height"/>
                                            <field name="width"/>
                                            <field name="length"/>
                                        </group>
                                        <separator colspan="4" string="Description"/>
                                        <field name="name"/>
                                    </form>
                                </field>
                                <separator string="Description for Quotations"/>
                                <field name="description_sale" placeholder="note to be displayed on quotations..."/>
                            </page>
                        </notebook>
                    </sheet>
                    <div class="oe_chatter">
                        <field name="message_follower_ids" widget="mail_followers"/>
                        <field name="message_ids" widget="mail_thread"/>
                    </div>
                </form>
```

**Comment by hbrunn** [comment]
note that github comments are markdown, I fixed the syntax for you. Before, it was unreadable. For the logs in english: Start your server with `LANG=en ./openerp-server etc`

**Comment by hbrunn** [comment]
what you posted as architecture of view 222 looks pretty much like the standard view (https://github.com/OCA/OCB/blob/7.0/addons/product/product_view.xml#L54), and should not inherit from anything. Clear out the `inherit_id` column for this record and try again.

**Comment by IJOL** [comment]
Gosh, In my original database, this 2 views have inherit_id empty.... but in the migrated one.. they do have inherit_id in the 222, it seems basic form for product.product the 240 is the form for product.template, should i post archs for that views  from the migrated database?

**Comment by hbrunn** [comment]
try if this helps. But probably we need your full migration log.

**Comment by IJOL** [comment]
HI, thank for help, the complete migration log is on [https://dl.dropboxusercontent.com/u/58666391/migration.log](https://dl.dropboxusercontent.com/u/58666391/migration.log),

Let me Know if you need translation from Spanish, i'm trying to get the migrate.py to change Locale, so i'll be slow on english logs...

**Comment by hbrunn** [comment]
aha. Search for a view that has `<group name="status" version="7.0">` in it's arch, this one is probably the culprit.

**Comment by IJOL** [comment]
The search you suggested find nothing in db, but in the migrated database the arch for the product.template, is the one in xmlid product_normal_form_view in product.view.xml, and thus group name="status" couldnt be found, logical, but how end that arch there?

**Comment by hbrunn** [comment]
there must be a view that contains this. It is normalized XML though, so what is precisely in the database can be somewhat different. Read through all view architectures for product.product, one of them should contain the snippet.

**Comment by IJOL** [comment]
I think i've found something, in the view with name "product.normal.procurement.locations.inherit", which inherits from product.product_normal_form_view ( my 222 id view ) , this view is part of stock module..

**Comment by IJOL** [comment]
Hola:

Finally deleting the view product.normal.procurement.locations.inherit in module stock, did the trick, so i was able to end OpenUpgrade process, so many thanks..

But i'm eager to contribute a solution for the problem i've found is that possible?  

Why i need to do that in my test db?

**Comment by hbrunn** [comment]
you could research why this view was not deleted by the standard migration mechanism as it should have been. Probably that's a problem with your exact installation, not a general one. Maybe the view's entry in ir_model_data was deleted at some point, which is why is was not cleaned up? Or if there's an inheriting custom view, this also blocks deleting it.
