### ISSUE TITLE
Optimistic merge flow in OpenUpgrade

### ISSUE THREAD

**Issue by StefanRijnhart** [OCA/OpenUpgrade#511]
Dear @OCA/openupgrade-maintainers, @OCA/core-maintainers,

in collaboration with @hbrunn I would like to continue the discussion of the Optimistic merge flow in OpenUpgrade. As layed out by Hintjens in his blog and his youtube talk, a single reviewer should be able to merge everything that does not break tests and is not trollishly bad (or merge with the option of reverting it again). Instead of reviewing, I expect the current maintainers to submit fixes on the merged code. These fixes are proposed as a PR, and merged optimistically as well.

Then, when we want a release, we fix what we think needs fixing and tag a commit.

I wanted to ask you all if you can agree with this experiment, and if you think it would make sense to have separate unstable and release branches for each version.

In the terms as above, what I think is happening here https://github.com/OCA/OpenUpgrade/pull/509 is that Holger has opened up an unstable branch, merged all the open PRs optimistically and is now preparing a release with his fixes. The only difference is that we don't know if the PRs failed the tests because the tests did not exist yet.

Please let us know your opinion.

**Comment by hbrunn** [comment]
I would love to work this way in OpenUpgrade

**Comment by pedrobaeza** [comment]
OK, let's try then.

**Comment by max3903** [comment]
+1

[image: Ursa Information Systems]
_Maxime Chambreuil__Project Manager / Consultant_

Ursa Information Systems
1450 W Guadalupe Road, Suite 132
Gilbert, Arizona, 85233
- Office:     1-855-URSA ERP x 710                 1-855-877 2377 x 710
  Mobile:   1-602-427-5632*

**Comment by StefanRijnhart** [comment]
OK, based on your preliminary support I merged #509 optimistically!

**Comment by StefanRijnhart** [comment]
Do we want a develop/unstable branch to merge into, or just tag releases on the main branch?

**Comment by pedrobaeza** [comment]
I have switched default branch to 9.0 now that the focus is there.

**Comment by pedrobaeza** [comment]
Let's simplify using tags.

**Comment by StefanRijnhart** [comment]
I'll use tags like ou9.0.1.0, with the prefix disambiguating from upstream tags.

**Comment by pedrobaeza** [comment]
OK, but do we use 4 or 5 digits notation?

**Comment by StefanRijnhart** [comment]
I'm thinking a major and a minor release digit suffices for us?

**Comment by pedrobaeza** [comment]
OK, it's for being consistent with the rest of the OCA, but the meaning of "needs migration" here is a bit ironic :stuck_out_tongue_winking_eye:, so let's go with 2 digits.

**Comment by StefanRijnhart** [comment]
;-) we now have release tags on all branches https://github.com/OCA/OpenUpgrade/releases
