### ISSUE TITLE
Hosting the test databases

### ISSUE THREAD

**Issue by StefanRijnhart** [OCA/OpenUpgrade#514]
@hbrunn I created a release on Github for the databases. Please add them here: 
https://github.com/OCA/OpenUpgrade/releases/edit/databases

You can then refer to them in Travis like this:
https://github.com/OCA/OpenUpgrade/releases/download/databases/8.0.psql

Unfortunately, I had to create a dummy branch to link the release to but I clarified this in the branch' README.

**Comment by hbrunn** [comment]
good idea! I changed the URL in https://github.com/OCA/OpenUpgrade/pull/515.

Did you consider using pages instead of releases? https://pages.github.com - we might also take this occasion to move doc.therp.nl/openupgrade there

**Comment by StefanRijnhart** [comment]
Well, could have used any git repository and then download as raw, but I am fundamentally against version control on these files.
