### ISSUE TITLE
Add Jordi Ballester as a PSC

### ISSUE THREAD

**Issue by StefanRijnhart** [OCA/OpenUpgrade#539]
Asking @OCA/openupgrade-maintainers for their approval to add @jbeficent to this team. He has managed to get some funding for the 9.0 edition, and is mobilizing a team with Therp and me to write and review migration scripts. We would find it useful if he could be given permissions to assign people and labels to issues and PRs, and to edit https://github.com/OCA/OpenUpgrade/issues/400 to track progress. He would need to be a member of the team in order to to so.

Please provide your opinion.

Thanks,
Stefan.

**Comment by hbrunn** [comment]
:+1:

**Comment by hbrunn** [comment]
I don't think @OCA-git-bot and @oca-transbot are going to reply, so that's it. I'm still a pending member as I see right now, could out confirm my membership?

**Comment by pedrobaeza** [comment]
:+1: I'll add both in OCA instance

**Comment by StefanRijnhart** [comment]
cc @OCA/board 

Well, I have the permissions in the odoo-community database so I will add you.

@legalsylvain, @pedrobaeza may I propose that you be member of the OpenUpgrade PSC?

**Comment by StefanRijnhart** [comment]
Ah thanks @pedrobaeza for your support.

**Comment by pedrobaeza** [comment]
Done. Next OCA sync will add them on GitHub

**Comment by legalsylvain** [comment]
:+1:
