### ISSUE TITLE
migration of crm.case.section.parent_id  from v8 to v9

### ISSUE THREAD

**Issue by yucer** [OCA/OpenUpgrade#550]
I understand that OpenUpgrade will not migrate this field from v8 because the hierarchical sales team doesn't exist in sales_team module of v9. Am I right ?

Mi question is: Is this feature implemented by another module so that we can install it to migrate the field info ?

I was looking for the commit that removes the field, but I didn't found it.  The module analysis doesn't says that the field should be erased. Which is the reason for that?

**Comment by pedrobaeza** [comment]
Maybe the analysis was done before this change. If you miss a feature, you can implement by yourself in a module. Regular behavior is to not drop removed columns, so when installing your new module in v9, you'll get all your old data.
