### ISSUE TITLE
[9.0] [crm] Conversion of next actions in leads to crm.activity

### ISSUE THREAD

**Issue by JordiBForgeFlow** [OCA/OpenUpgrade#571]
In 8.0 the crm.lead model contains the fields 'title_action' and 'date_action'.

![image](https://cloud.githubusercontent.com/assets/7683926/17140388/994cf9ba-5348-11e6-97ce-b1072146113b.png)

In v9 the fields are migrated, but they are being hidden because there's no next_activity_id. See https://github.com/odoo/odoo/blob/9.0/addons/crm/crm_lead_view.xml#L495

See:
![image](https://cloud.githubusercontent.com/assets/7683926/17140510/0adb02f2-5349-11e6-9247-d37e5fc8d3fb.png)

I suggest to add as default Next Activity = Task (crm_activity_data_meeting).

**Comment by pedrobaeza** [comment]
@jbeficent are you going to work on this? If not, I think it can be closed.

**Comment by pedrobaeza** [comment]
Closing as no answer

**Comment by JordiBForgeFlow** [comment]
Sorry, not planning to work on it
