### ISSUE TITLE
[9.0][analytic] Analytic accounts of type='view' should be deleted

### ISSUE THREAD

**Issue by JordiBForgeFlow** [OCA/OpenUpgrade#578]
Impacted versions: 9.0

Steps to reproduce:
Migrate a database in 8.0 with module 'analytic' installed.

Current behavior:
The analytic accounts of type 'view' are migrated to analytic accounts with tag 'view'.

Expected behavior:
These analytic accounts will not be used anymore in v9. 

Instead, the child analytic accounts may incorporate a tag with the name of the old analytic account.
In case of parent analytic accounts that are not of type 'view' a tag should also be created and assigned downwards to all the children down the hierarchy.

Video/Screenshot link (optional):

V8:
![image](https://cloud.githubusercontent.com/assets/7683926/17205890/444ac184-54ad-11e6-9625-d8b11e691c12.png)

V9:
![image](https://cloud.githubusercontent.com/assets/7683926/17205896/4d1b1fe8-54ad-11e6-811b-40e157f2ad40.png)

**Comment by pedrobaeza** [comment]
Is this still relevant?

**Comment by JordiBForgeFlow** [comment]
Yes

**Comment by pedrobaeza** [comment]
OK, Isn't better to convert them to tags?

**Comment by pedrobaeza** [comment]
With new module account_analytic_parent, they shouldn't get removed. Maybe hidden meanwhile.

**Comment by pedrobaeza** [comment]
@jbeficent definitively, we can't delete the views. I have hidden them with a consistent logic to be rescued later in #1010, so I merge that PR, closing this issue, and I'll make another migration script to _account_analytic_parent_ restoring parent views.
