### ISSUE TITLE
Freeze 9.0 for release

### ISSUE THREAD

**Issue by StefanRijnhart** [OCA/OpenUpgrade#589]
Hi @OCA/openupgrade-maintainers,

I'd like to do a release of 9.0. Because of the quick turnaround (kudos @hbrunn!) I'd like to freeze the branch and only apply bugfixing PRs (I have submitted 2 of those) in the next couple of days. Any other fixes are still welcome as well, of course. The maintainer to fix the last of the open bugfixes can tag release ou9.0.2.0 and then the freeze is lifted again.

Thanks,
Stefan.

**Comment by StefanRijnhart** [comment]
BTW to clarify, an OpenUpgrade release is not supposed to be super stable, but it is a mark that someone (me in this case) has gone through all the code that was optimistically merged since the last release. I'd like us to do releases more often, because there was a lot of code to review this time but fortunately the quality was very good.

**Comment by pedrobaeza** [comment]
Although I'm not yet participating too much on 9.0, it seems to me a good idea.

:+1:

**Comment by hbrunn** [comment]
done, so closing this

**Comment by StefanRijnhart** [comment]
@hbrunn thanks, but did you push the tag?

**Comment by hbrunn** [comment]
no. I didn't even create one because I mixed this up with 9.0.1.0. Thanks for the reminder, now it's fixed
