### ISSUE TITLE
Analysis work file. Detect changes to XML data records with noupdate="1" 

### ISSUE THREAD

**Issue by JordiBForgeFlow** [OCA/OpenUpgrade#590]
Would be nice if the openupgrade analysis tool would be able to detect data records with noupdate="1" that exist across two versions, where there are changes in the data. This would trigger the need to use openupgrade.load_data to force the reload of the correct data for the newer version. For example: https://github.com/OCA/OpenUpgrade/pull/586.

**Comment by StefanRijnhart** [comment]
We could run https://github.com/OCA/OpenUpgrade/blob/8.0/scripts/compare_noupdate_xml_records.py for each module and store the results in migrations/x.x.x.x/noupdate_changes.analysis. After a review, the result could be renamed and loaded in a migration script.

**Comment by JordiBForgeFlow** [comment]
That could be a great thing from a usability perspective. You will quickly know what modules require attention, instead of having to run the script for each module.

**Comment by pedrobaeza** [comment]
But can this be achieved with current openupgrade_records mechanism where we communicate with the other Odoo server through XML-RPC?

**Comment by pedrobaeza** [comment]
Any news on this?

**Comment by pedrobaeza** [comment]
This has been achieved already in #1086 and #1092
