### ISSUE TITLE
[7.0 -> 8.0] Issue with l10_es module post-migration script

### ISSUE THREAD

**Issue by marcosligero** [OCA/OpenUpgrade#609]
We have just detected that if installing the last revisions of the i10n_es modules on a 7.x instance and performing a DB update on OpenERP server the account_types mappings are being performed already, so migrating to 8.0 crashes.

Here is the approach that we have used just in case it could be helpful to update on the code. Changing map_account_types function would solve the issue. File attached.

Cheers to everyone! This is our first time and our first post here at Github 😄 
[post-migration.py.zip](https://github.com/OCA/OpenUpgrade/files/402264/post-migration.py.zip)

**Comment by StefanRijnhart** [comment]
Hi @marcosligero thank you for your input and welcome to GitHub! We would love to receive your change in a Github PR. This involves for you to fork this project, make your changes in your local branch and push them to your own fork. From this branch in the Github interface, create the PR.

**Comment by pedrobaeza** [comment]
No issue on my side, so I close.
