### ISSUE TITLE
No user found in configuration when attempting to run

### ISSUE THREAD

**Issue by cartertech** [OCA/OpenUpgrade#616]
Impacted versions: 9.0

Steps to reproduce: I am trying to migrate an Odoo 8.0 database to version 9.0 using the migrate.py script. While running, I receive an error that "No user found in configuration". My Odoo configuration file is OK so I do not understand why this error is coming up.

Config file attached.
[openerp.txt](https://github.com/OCA/OpenUpgrade/files/408184/openerp.txt)

**Comment by cartertech** [comment]
Moved the file to the same folder as migrate.py instead of using the full path and it resolved the issue

**Comment by daudakhtar** [comment]
is it able to migrate my custom module data from erp7 to odoo 11???
