### ISSUE TITLE
Migrate.py uses unsynced versions of openupgradelib and OpenUpgrade

### ISSUE THREAD

**Issue by Sekiltoyai** [OCA/OpenUpgrade#617]
Migrate.py depends on:
- an openupgradelib from pip install, as stated in the following reply:
  https://github.com/OCA/OpenUpgrade/issues/362
- an OpenUpgrade from github (latest commit automatically downloaded by the script)

In some cases, the openupgradelib provided by pip install is out of sync with the OpenUpgrade provided by github, causing execution errors.

Example:
- Up to date openupgradelib from pip: version 1.1.2 (version from 2016-06-13)
- Up to date OpenUpgrade from github: commit 77b271a7eae3c8af2b0ddbc2a41625eaa721be04
- Execution error: "TypeError: migrate() got an unexpected keyword argument 'use_env'"
- Explanation: Commit 9223ea774bd2044f8b889297a1a4e2479bcbc453 (OpenUpgrade) depends on commit c4b7b29cc2208de325aa7d5b6d572d3c4d06fa8c (openupgradelib)

Impacted versions: all versions

Steps to reproduce:
Download and execute the migrate.py script.

Current behavior:
OpenUpgrade is rolling released, while openupgradelib is version released

Expected behavior:
A migration script with both OpenUpgrade and openupgradelib rolling released, or both OpenUpgrade and openupgradelib version released

**Comment by pedrobaeza** [comment]
That's not true since https://github.com/OCA/OpenUpgrade/pull/397

**Comment by Sekiltoyai** [comment]
This pull request have been pulled in branch 8.0 but not in branch 9.0.
The migrate.py file refered in the online documentation (https://doc.therp.nl/openupgrade/migrate.py.html) is the one from HEAD (branch 9.0).

**Comment by pedrobaeza** [comment]
@hbrunn, it was not used the same logic in 9.0?

**Comment by hbrunn** [comment]
this was merged after we created the 9.0 branch, so passing them over was simply forgotten after the 9.0 branch was made HEAD. Fixed in https://github.com/OCA/OpenUpgrade/pull/620
