### ISSUE TITLE
[9.0][CRM] CRM.Stage not converted properly

### ISSUE THREAD

**Issue by mmalorni** [OCA/OpenUpgrade#630]
Impacted versions: 9.0

Steps to reproduce: Migrate to 9.0 with opportunity stages added to the default ones.

Current behavior: After the migration, when you filter the opportunities and some kanban columns are left empty they disappear and when you open a form they do not appear as a Stage you can move the opportunity to.

Expected behavior:  All the opportunity stages should be displayed at all time for their Sales Team and when opening the form the buttons should be displayed to move the opportunity to any stage.

Video/Screenshot link (optional):

It looks like it is the table crm_team_stage_rel that is not filled properly.

**Comment by pedrobaeza** [comment]
Is this still happening?

**Comment by pedrobaeza** [comment]
No answer, so I close.
