### ISSUE TITLE
 Error: "Module openerp was already imported from..."

### ISSUE THREAD

**Issue by jeanabreu** [OCA/OpenUpgrade#642]
# When I tried to migrate to Odoo 8, I get this error:

copying database testing_db to testing_db_migrated...
Copying the database using 'with template'
Failed, fallback on creating empty database + loading a dump
running migration for 8.0
/usr/lib/python2.7/dist-packages/babel/**init**.py:33: UserWarning: Module openerp was already imported from /var/tmp/openupgrade/8.0/server/openerp/**init**.pyc, but /usr/lib/pymodules/python2.7 is being added to sys.path
#   from pkg_resources import get_distribution, ResolutionError

Please, Any idea about?

**Comment by pedrobaeza** [comment]
This doesn't proceed here, and I recommend you not to spam all mailing lists and projects if you want to receive a proper answer.
