### ISSUE TITLE
Rename of module account_check_writing to account_check_printing has no effect

### ISSUE THREAD

**Issue by NL66278** [OCA/OpenUpgrade#646]
Impacted versions: migration of 8.0 to 9.0

Steps to reproduce: Run migration script on a database with account_check_writing installed

Current behavior: Module account_check_writing (which no longer exists) will have status 'to upgrade'. module account_check_printing will be uninstalled

Expected behavior: Module account_check_printing having status installed and module account_check_writing deleted from list of modules (table ir_module_module). Migration scripts in account_check_printing should be called.

The rename of account_check_writing to account_check_printing is listed in openerp/addons/openupgrade_records/lib/apriori.py renamed_modules. But that does not seem to have any effect.

**Comment by pedrobaeza** [comment]
For other renamings, I haven't got any problem, so I'm not sure if something went bad in your migration that unrolled the change or what...

**Comment by NL66278** [comment]
@pedrobaeza Is this for 8.0 to 9.0? Strangely enough I did not find any logic to actually process the renaming at all. Only in the analysis. But I might have looked at the wrong places...

**Comment by StefanRijnhart** [comment]
Closing, as fix is merged
