### ISSUE TITLE
[8.0 -> 9.0] Key (channel_id)=(2) is not present in table "mail_channel".

### ISSUE THREAD

**Issue by cewolf2002** [OCA/OpenUpgrade#658]
Please Help.
We tried to migrate our Version 8.0 database to 9.0.
But always stop here.
I searched database but can not find table "mail_channel"

Server running ubuntu 14.04.5
All modules are already up-to-date.
And odoo version is 20161106

Full log:
http://pastebin.com/rFU4vBig

**Comment by cewolf2002** [comment]
I checked database, table mail_group, email_template, mail_group_res_group_rel not rename to mail_channel, mail_template, mail_channel_res_group_rel
Is there any way to fix it?

**Comment by hbrunn** [comment]
check if there's any mail follower in your original database with res_model='mail.channel', and delete those

**Comment by cewolf2002** [comment]
I excuted select \* from mail_followers where res_model = 'mail.channel' and no record.

**Comment by hbrunn** [comment]
do the same with mail.group. If there comes out a group res_id which doesn't exist, delete those records

**Comment by cewolf2002** [comment]
Issue solved after deleting records with res_model = 'mail.group'.
Thanks for your help.

Another question.
http://pastebin.com/ArY7qTPF

Would you know why Openupgrade use so much time to excute next line between line 2017 and 2018? (14 hours)
2016-11-07 09:44:51,004 21436 DEBUG GAPL_migrated OpenUpgrade: 1 rows affected
2016-11-07 23:32:21,538 21436 DEBUG GAPL_migrated OpenUpgrade: Running

Is there anything wrong in my database?

**Comment by hbrunn** [comment]
nothing wrong, this is a part of the account migration which is painfully slow. https://github.com/OCA/OpenUpgrade/pull/634 contains an attempt to speed things up.

Closing this as the original issue is solved
