### ISSUE TITLE
Anyone see anything obvious in my log that is failing my migration

### ISSUE THREAD

**Issue by cliffkujala** [OCA/OpenUpgrade#659]
Impacted versions: 
9.0

Steps to reproduce: 
I followed this ( http://www.patrikdufresne.com/fr/migration-odoo-8/ ) step by step tutorial with a little more detail on how to use the migrate.py script.  It is in french but Google did a good job translating it for me.  The biggest help was the fact that this tutorial pointed out to me that the migrate script gets ran on the Target version of Odoo.  I kept running it on the original version, and the script wasn't working at all.

Current behavior:
If I go straight from a backup of my live working v8 database, there are errors all over the place, and the migrated database won't even fire up in v9 after Migration. It just goes to a Server500 error when you select it from the database manager in v9.  I tickered around, and cleaned up some unneeded apps/modules, and got the database to at least migrate to a point where it would start and run.  However many things were wrong, and I would get traceback errors.  Most specifically on the Partners.  Anytime I would try to view a list of partners, or open a partner I would get a Traceback referencing res_partner_opt_out_search

Expected behavior:
Nice happy migration to v9 with no errors or database corruption ;-)

Pastbin from migration.log
http://pastebin.com/wUBfp5iU

**Comment by pedrobaeza** [comment]
You should check the full log of your migration and see the possible errors in there.

**Comment by hbrunn** [comment]
OpenUpgrade doesn't clean up deprecated/unavailable modules, and those usually leave behing views which cause trouble. It's out of scope for OpenUpgrade to do something about this, but we have https://github.com/OCA/server-tools/tree/9.0/database_cleanup for this job. Install this in your migrated database and purge those modules, then you should be fine

**Comment by hbrunn** [comment]
wait, your log is very clear about this: "Error while validating constraint. You cannot have a receivable/payable account that is not reconciliable. (account code: 201)" - the migration doesn't finish successfully. Fix your accounts in 8 and rerun the migration.
