### ISSUE TITLE
Requiered essential addons to upgrade

### ISSUE THREAD

**Issue by roberto-barreiro** [OCA/OpenUpgrade#661]
Impacted versions: 8.0

Steps to reproduce: Uninstall all addons not suportted for 8.0 to 9.0 migration

I tryed to uninstall all modules not supported by OpenUpgrade successfully, except the following modules:

edi, procurement, web_kanban_gauge, web_kanban_sparkline

If I try to uninstall anyone of these modules, another modules supported by openupgrade like crm, sale or purchase, are going to be removed.

**Comment by hbrunn** [comment]
why would you want to uninstall those modules in the first place? The standard procedure is to keep them and purge them with https://github.com/OCA/server-tools/tree/9.0/database_cleanup afterwards

**Comment by roberto-barreiro** [comment]
Thank you for your answer, I have not seen that step in the openupgrade documentation.

**Comment by hbrunn** [comment]
your PR to update the documentation is welcome
