### ISSUE TITLE
mrp migration script is incomplete

### ISSUE THREAD

**Issue by arthru** [OCA/OpenUpgrade#67]
Mrp post migration script is incomplete with missing lines : https://github.com/OpenUpgrade/OpenUpgrade/pull/63/files#diff-42f221718256b2641dc5ed5e21576f9bR11

@gurneyalex did you forget to send changes ?

**Comment by arthru** [comment]
The PR bringing that is #63

**Comment by StefanRijnhart** [comment]
Closing this as per last comment

**Comment by gurneyalex** [comment]
It is a partial migration of stuff which moved from product to mrp. 

Don't tackle mrp until procurement and stock are migrated.

**Comment by StefanRijnhart** [comment]
Sure, we just fixed the syntax error to make pep-bot happy.
