### ISSUE TITLE
Migration scripts for v10: status

### ISSUE THREAD

**Issue by BzMB** [OCA/OpenUpgrade#683]
Hi,

First of all, thanks for all your work on that topic.

We have a openerp (7.0) project/db to migrate to the 10 community version, with a few custom module.

1) v10 script status
wget https://raw.githubusercontent.com/OCA/OpenUpgrade/HEAD/scripts/migrate.py
try to execute:
python migrate.py --config=xxx.server.conf --database=xxx --run-migrations=10.0

What's the status of the "migrate.py" scripts for the v10?

2)
Do you suggest to run first in that way?
python migrate.py --config=xxx.server.conf --database=xxx --run-migrations=8.0,9.0

Thanks in advance

**Comment by pedrobaeza** [comment]
There isn't anything yet for migrating to v10. You should know also that you need to migrate through all versions: 7.0 > 8.0 > 9.0 > 10.0, which will imply for sure a very deep knowledge of Odoo and OpenUpgrade to handle possible errors.
