### ISSUE TITLE
odoo-bin: not found

### ISSUE THREAD

**Issue by Whytehorse** [OCA/OpenUpgrade#686]
I'm getting the following error when migrating from 8.0 to 10.0:
sh: 1: /var/tmp/openupgrade/10.0/server/odoo-bin: not found
I upgraded from 8 to 9 with no problems and then from 9 to 10 I get that error. I did ls the directory and the file is not there.

Impacted versions: 8.0, 9.0

Steps to reproduce:
`python migrate.py --config=/etc/odoo/openerp-server.conf --database=production --run-migrations=10.0
`
Current behavior:
```
From git://github.com/OpenUpgrade/OpenUpgrade
 * branch            10.0       -> FETCH_HEAD
Already up-to-date.
From https://github.com/OCA/openupgradelib
 * branch            master     -> FETCH_HEAD
Already up-to-date.
copying database production to production_migrated...
Copying the database using 'with template'
running migration for 10.0
sh: 1: /var/tmp/openupgrade/10.0/server/odoo-bin: not found
```

Expected behavior:
running migration for 10.0

**Comment by E-HO** [comment]
See https://doc.therp.nl/openupgrade/ , no migration for V10.
