### ISSUE TITLE
How can I contribute to improve the docs?

### ISSUE THREAD

**Issue by dreispt** [OCA/OpenUpgrade#687]
Can you please point me to the source for the docs?

**Comment by pedrobaeza** [comment]
https://github.com/OCA/OpenUpgrade/tree/9.0/openerp/openupgrade/doc/source. We haven't switched to 10.0 version docs, although the branch exists, but we can cherry-pick the commits improving the doc.

**Comment by dreispt** [comment]
Thanks!
