### ISSUE TITLE
[8.0] File Attachments do not show in interface 

### ISSUE THREAD

**Issue by ghost** [OCA/OpenUpgrade#689]
Impacted versions:
upgrade from v7 to v8

Steps to reproduce:
- do upgrade from v7 to v8
- check if file can be downloaded from product form view, or stock form view

Current behavior:
- file is not available in v8

Expected behavior:
- file is available

To find attachments odoo checks for model name (res_model) and item id (res_id) in ir_attachment table. Because in the new version the model name has changed the correct attachments are not found.

The following sql code fixes these issues:

UPDATE 
  ir_attachment
SET 
  res_model = 'product.template'
WHERE 
  res_model = 'product.product'

UPDATE 
  ir_attachment
SET 
  res_model = 'stock.picking'
WHERE 
  res_model = 'stock.picking.out'

UPDATE 
  ir_attachment
SET 
  res_model = 'stock.picking'
WHERE 
  res_model = 'stock.picking.in'

**Comment by ghost** [comment]
Rather new to this. Just signed CLA, I have a fix and could make a pull request for changes if this is wanted.

**Comment by pedrobaeza** [comment]
Please make the PR. I'm not sure about the switch from product.template to product.product. Some people will see at product menu, and some other people will look at product variant menu. What about duplicating the attachment record as Salomonian solution? If the attachment is in file store, it won't duplicate the space. I don't know if there's any side effect for making this trick though.

**Comment by ghost** [comment]
Ok I have done a pull request for the stock part as this is more straightforward. I will look into the duplication part for products when I have a little more time. Thanks for the input

**Comment by pedrobaeza** [comment]
Closing as it was handled on the PR.
