### ISSUE TITLE
error after migrate  8.0 > 9.0

### ISSUE THREAD

**Issue by m3asmi** [OCA/OpenUpgrade#701]
Impacted versions:_9.0_  
Steps to reproduce: migrate from **8.0 -> 9.0**
Current behavior: 
```
The field 'default_section_id' doesn't exist
Vue res.users.groups
[view_id: 156, xml_id: base.user_groups_view, model: res.users, parent_id: 153]
None" while parsing /opt/odoo/odoo9/addons/account/security/account_security.xml:5, near
<record id="group_account_invoice" model="res.groups">
        <field name="name">Billing</field>
        <field name="category_id" ref="base.module_category_accounting_and_finance"/>
        <field name="users" eval="[(4, ref('base.user_root'))]"/>
        <field name="implied_ids" eval="[(4, ref('base.group_user'))]"/>
    </record>
```

**Comment by pedrobaeza** [comment]
That's any security rule that you have customized that uses field `default_section_id`

**Comment by m3asmi** [comment]
@pedrobaeza no there is no cosumized uses of that field

**Comment by pedrobaeza** [comment]
Well, standard migration is working perfectly. I have done one this weekend. Anyway, find the rule with that field and remove it before migrating.

**Comment by m3asmi** [comment]
@pedrobaeza  the migration been done well 
but I get that error when I do --update all on odoo 9.0 !!!

**Comment by pedrobaeza** [comment]
I have said a security rule, but it's a view the one that contains the non-existing field. Just remove it or uninstall the affected module.
