### ISSUE TITLE
Unable to complete upgrade 8.0 to 9.0

### ISSUE THREAD

**Issue by kvdb** [OCA/OpenUpgrade#723]
Ran the migration script (from todays master). It worked through a lot of tables successfully, but then got stuck. Log that contains the error towards the end: http://pastebin.com/Y0nW3edX

I wonder if it has to do with OCA modules I have installed.
Perhaps anyone recognizes the error and can provide a hint.

**Comment by pedrobaeza** [comment]
The error you have attached is not important, as it's a not null constraint. Put full log or give more details.

**Comment by kvdb** [comment]
So line 182 is not really a problem? What you saw in the pastebin is the final part of the log. After that, nothing is logged anymore. It takes about 5 to 10 minutes for the migration script to complete (it doesn't provide any output on the console or log during that time, so I can only assume it went fine). When I run odoo 9 with the migrated database, I can login, but get a lot of errors for css files that are not found. Perhaps that has nothing to do with the migration?
I reverted to odoo 8 for now, but I can retry if you think a full log would help.

**Comment by pedrobaeza** [comment]
Have you restored properly the BD copying the filestore?

**Comment by pedrobaeza** [comment]
Closing as no response
