### ISSUE TITLE
[8.0] stock migration very slow

### ISSUE THREAD

**Issue by legalsylvain** [OCA/OpenUpgrade#724]
Impacted versions: 8.0

Steps to reproduce:
Using a Database with 2.000.000 stock moves, trying to openupgrade it from 7.0 to 8.0. During script migration, in the [quant generation script](https://github.com/OCA/OpenUpgrade/blob/8.0/addons/stock/migrations/8.0.1.1/post-migration.py#L934), the process is very slow. 
10.000 stock move managed in 25 minutes. So, full quants generation will take 5.000 minutes. (3,5 days). That is quite annoying. 

The server is dedicated for the migration with a not so bad hardware : 
- RAM : 32 GO
- HD : SSD
- Processor : [Intel Xeon E3-1245 v5](https://www.cpubenchmark.net/cpu.php?cpu=Intel+Xeon+E3-1245+v5+%40+3.50GHz&id=2674) @ 3,5 GHz
* Cpu Benchmark Note : 10.350. (but just one is used for Odoo). so the real note is more ~2.000
* No of Cores: 4 (2 logical cores per physical)

What I tried 
* Set a higher value for shared_buffers value in the ./postgresql.conf file. (128 MB -> 10 GO) --> Bad result. (longer process)
* Set a higher value for limit_memory_hard et limit_memory_soft. (~600MB -> 10 GO) --> no result.

Odoo settings : (quite simple)
- multi company. (~25)
- one warehouse per company
- one internal location by warehouse
- no product lots management

~I was asking me if it's possible to create only one global quant per product in this configuration. I'll loose maybe some features based on history... In a generic way, I could add extra keys in the update process like -u all --stock-migration-simple-or-whatever, and make some conditionnal migration script.~
--> Dummy remarks. Talked with @sebastienbeau. This solution will not work because quants should exist in external customers location too.

Do you have some ideas for optimizations ? I'm ready to work on that but I'm not a quant expert, so any advice is welcome.
CC : @pedrobaeza, @StefanRijnhart. 

Did you faced duration problems with databases with similar size ?

**Comment by pedrobaeza** [comment]
It was optimized here with reasonable results: https://github.com/OCA/OpenUpgrade/pull/469.

Do you have the last OpenUpgrade version?

**Comment by legalsylvain** [comment]
Hi @pedrobaeza .

Thanks for your quick answer. Yes I'm using 8.0 HEAD version. The last commit is [this one](https://github.com/OCA/OpenUpgrade/commit/3058fc09c161580f7049a6e3e62522d6e6b0791b) from @jbeficent .

**Comment by pedrobaeza** [comment]
Well, then he should answer if there's room for more improvement.

**Comment by legalsylvain** [comment]
@pedrobaeza. could you share migration duration and stock move quantity for some databases you open-upgraded ? I'd like to identify if I have configuration problem, or if it's an OpenUpgrade limitation.

@akretion last customer : 
- migration done from 6.1 -> 8.0.
- database with 250.000 stock.move
- global duration : 1,5 day.
- @jbeficent [optimization](https://github.com/OCA/OpenUpgrade/commit/3058fc09c161580f7049a6e3e62522d6e6b0791b) : included.

**Comment by pedrobaeza** [comment]
I don't have right now statistics, because I did my 8.0 migrations a long time ago (some even without optimization). Jordi should give you more accurate details.

**Comment by hbrunn** [comment]
the DB I'm currently working on has ~190k moves, there the stock migration part costs 5 hours. On a somewhat unrelated note, I'm working at the moment on the recomputation of some sale fields in #710, and what I noticed there is that recomputations are a non-linear enterprise. It might be that this piece of code grows quadratic too, that's something you should be able to measure by migrating only some small representative fraction of your moves. From there, you can decide if it's more promising to look for bugs (the quadratic case) or simple speed optimizations (the linear case)

**Comment by legalsylvain** [comment]
Hi @hbrunn Thanks a lot for your PoV. Is your server configuration very better that the one I described ? or is it something similar.
 ~190k moves in 5 hours is > 10 stock move per second. (ignoring other processes). (My stats is 6 per second). So similar result.
I'll try to work on treating stock move product per product. (still ordered by date). I guess I can win some time because of ORM cache optimization. (_move_assign and _move_done func access to uom, ...) Not sure if it's a good idea. But well.

Thanks for your feedback. 
CC @sebastienbeau

**Comment by hbrunn** [comment]
the specs are worse than your example, it's VPS4 from http://www.cloudvps.com/virtual-private-server/linux-vps - so you're probably on less than 50% throughput for a comparable machine. This lets me guess there's some quadraticness going on here too.
I'd suggest you to extract the relevant code to some script and measure it's performance, that's a lot more effective to look at than the same code within the whole openupgrade environment. I use something quite similar to https://gist.github.com/hbrunn/c7f7fbab47261475772c for the optimization I'm busy with

**Comment by legalsylvain** [comment]
@hbrunn. Thanks a lot again. I'll take a look on your gist script.

Another way to reduce duration time could be to use multi processes. (if available). For consistency, I guess that OpenUpgrade should not be run in a multi worker context, but we could imagine, in a specific function (like quants generation), to run quants generation dispatched on many processes.

Do you think it could be interesting ? If yes, any sample of multi processes implementation in python 2.7 is welcome.

Regards.

**Comment by pedrobaeza** [comment]
The problem in parallelization is that you need to keep the order in the operations for the same product, so it's not very easy to develop it.

**Comment by legalsylvain** [comment]
I was thinking, (I'm working on it), in a first optimization, to run quants process, order by product (and prod lot) then date. (for the time being, only this is only by date). Ref : [WIP work](https://github.com/grap/OpenUpgrade/commit/171ebda42687670e2b097c1be44a2baee900b895#diff-c016f55f80a2042f93830629c1f7bfb5R986)
I guess that for a single product / prodlot tuple, generating quants based on ordered associated moves will not have bad side effect. (and *maybe* will reduce time, because of cache optimization).

**Comment by JordiBForgeFlow** [comment]
@legalsylvain We optimized the search, and for us we improve from more than 5 days to about 1 day, for about 250.000 moves. At the time it was a success for us, but it is clear that it's not the case for you. Also, it's important that the current approach is compatible with perpetual inventory. So no new journal entries should be created. This should be considered in any approach.

**Comment by sebastienbeau** [comment]
Hi after some discution with Nhomar, he told me that he have done that work for migrating quant using SQL request. Maybe it will be good to have it in OpenUpgrade https://github.com/Vauxoo/sql_migration

**Comment by pedrobaeza** [comment]
Closing this as there's now a PR
