### ISSUE TITLE
Migration 8.0 to 9.0 stops after account_bank_statement_line

### ISSUE THREAD

**Issue by Hans-0** [OCA/OpenUpgrade#725]
Impacted versions:
openupgrade odoo8 to odoo9
Steps to reproduce:
running script migrate.py
Current behavior:
migrate.py script doesn't complete migrationprocess.
For several days now, I try to migrate my odoo8 database to a odoo9 database.
After sometime (15 min) the process stops after running the  account_bank_statement_line table. Witch in my case has  8840 rows affected.
The migration script doesn't continue, so after one hour II cut off the process (ctrl-C).
Please find enclosed the migrationlog of to days attempt
[migration.txt](https://github.com/OCA/OpenUpgrade/files/695973/migration.txt)

.

**Comment by pedrobaeza** [comment]
This is because you have a lot of moves. For an speed optimization, see #634 or #663
