### ISSUE TITLE
[9.0] base: Images are lost

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/OpenUpgrade#726]
On a migration from v8 to v9, all images in fields.Binary are lost (example: image field on res.users). This can be due to the change of these fields to attachment mode.

**Comment by pedrobaeza** [comment]
@hbrunn @NL66278 @jbeficent have you seen this problem?

**Comment by JordiBForgeFlow** [comment]
@pedrobaeza I just experienced this problem 2 days ago, but did not realize that this was a consequence of the migration. So, it's a valid issue.

**Comment by pedrobaeza** [comment]
FYI I'm working all this morning in this. Almost completed...

**Comment by pedrobaeza** [comment]
The fix is a two step solution:

* openupgradelib method: https://github.com/OCA/openupgradelib/pull/66
* OpenUpgrade patch: https://github.com/OCA/OpenUpgrade/pull/745

**Comment by yajo** [comment]
Then is this closed now?

**Comment by pedrobaeza** [comment]
Yes!
