### ISSUE TITLE
[8.0] sales_team error (relation "crm_case_section" does not exist)

### ISSUE THREAD

**Issue by legalsylvain** [OCA/OpenUpgrade#729]
Impacted versions: 8.0 (target upgrade version)

Steps to reproduce:
* install a fresh V7.0 database, -i point_of_sale,purchase. (i guess that less module is sufficient, but not tested)
* upgrade to V8.0

Current behavior:
* During the migration, sales_team (new 8.0 module is installed by [dependencies](https://github.com/OCA/OpenUpgrade/blob/8.0/addons/sales_team/__openerp__.py#L32)).
* sales_team migration is executed.
* an error is raised :

        error in migration script OpenUpgrade/addons/sales_team/migrations/8.0.1.0/pre-migration.py: 
        relation "crm_case_section" does not exist
        LINE 1: UPDATE crm_case_section SET code = '_DM' WHERE code = 'DM'

Expected behavior:
No error.

Analyse & Solution:
Part of the crm migration should be executed early. That's why part of the code is in sales_team. But migration should include test to know if crm is installed.

**Comment by pedrobaeza** [comment]
If you're going to make a PR, better to not open 2 things: put the issue report on the PR itself.
