### ISSUE TITLE
Upgrade from OpenERP 7.0 to Odoo 8.0

### ISSUE THREAD

**Issue by franklee628** [OCA/OpenUpgrade#734]
Tried with python migrate.py --config=/etc/openerp/openerp-server.conf --database=test_data --run-migrations=8.0

Outcome: No user found in configuration

=====================================================================

Tried with sudo python migrate.py --config=/etc/openerp/openerp-server.conf --database=test_data --run-migrations=8.0

Outcome: Copying the database using 'with template'
Failed, fallback on creating empty database + loading a dump
pg_restore: WARNING:  hash indexes are not WAL-logged and their use is discouraged
running migration for 8.0
Running as user 'root' is a security risk, aborting.

=====================================================================

I have tried to Google every possible keywords but won't find a solution. I've tried to check the openerp-server.conf file and it's as followings:

[options]
; This is the password that allows database operations:
admin_passwd = admin
db_host = False
db_port = False
db_user = openerp
db_password = openerp
addons_path = /usr/lib/python2.7/dist-packages/openerp/addons

Could anybody give a hint or help? Much appreciated.

**Comment by franklee628** [comment]
I've found these line within the migrate.py file:

> conn_parms = {}
for parm in ('host', 'port', 'user', 'password'):
    db_parm = 'db_' + parm
    if config.has_option('options', db_parm):
        conn_parms[parm] = config.get('options', db_parm)

> if 'user' not in conn_parms:
    print 'No user found in configuration'
    sys.exit()

Is that means I will have to define a user somewhere in openerp-server.conf?

**Comment by legalsylvain** [comment]
Hi. There is no difference between odoo and openupgrade.
you have to run openupgrade with the same user as you run odoo.
So your problem is not related to openupgrade.

I don't know your setting, but if you have some odoo user dedicated, you could use something like 
sudo su odoo -c "python migrate.py --config=...."

kind regards.
