### ISSUE TITLE
[9.0][product] product.supplierinfo not correctly migrated

### ISSUE THREAD

**Issue by JordiBForgeFlow** [OCA/OpenUpgrade#739]
Impacted versions: 9.0

Steps to reproduce:
Migrate a database that contains supplier pricelists in v8

Current behavior:
Cannot access to supplier pricelists in v9. The model in v9 to maintain supplier pricelists is the product.supplierinfo

Expected behavior:
There needs to be a conversion so that the supplier pricelists are converted to product.supplierinfo

Video/Screenshot link (optional):

**Comment by JordiBForgeFlow** [comment]
@NL66278 @hbrunn Do you think you could help me on this?

**Comment by hbrunn** [comment]
I would hope so. You've come up often with important corner cases lately, do you see any possibility to share your real world database in an anonymized fashion? Note that the `anonymization` addon is not up to privacy requirements.

**Comment by JordiBForgeFlow** [comment]
Fixed in https://github.com/OCA/OpenUpgrade/pull/747
