### ISSUE TITLE
[9.0] Migration of the CRM phonecalls sends emails

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/OpenUpgrade#741]
When converting crm.phonecall objects to chatter messages, followers that are subscribed to this message type are notified by mail. We have to disable this notification or create it by SQL.

Who did this script? @jbeficent? @hbrunn?

**Comment by hbrunn** [comment]
Me. While I think it's a questionable practice to run migrations in an environment where the code can contact the outside world at all, if we want to prevent people from shooting in their own foot, I'd propose to handle this centrally in `ir.mail.server#send_email`. But there's no chance in hell to prevent some other plugins from doing requests to some webshop sync instance or whatever, so it still stands that the safest way to do this is in an isolated environment.

**Comment by pedrobaeza** [comment]
Yeah, you're right. Now with our Docker image (https://github.com/Tecnativa/docker-odoo-base) we have handled that deactivating mail proxy. Closing this issue.
