### ISSUE TITLE
[9.0][account_check_printing] Journals with flag 'Allow check writing' should default outbound payment method 'check'

### ISSUE THREAD

**Issue by JordiBForgeFlow** [OCA/OpenUpgrade#742]
Impacted versions: 9.0

Steps to reproduce:
8.0 DB with module 'account_check_writing' installed.
Define a journal "Check Writing" with flag 'Allow check writing' activated.

Current behavior:
The journal cannot be used in supplier payments using checks, in v9

Expected behavior:
The method 'Check' should be activated in the journal:

The journal should appear in the list of of allowed payment methods when a payment is created.

Video/Screenshot link (optional):

v8:
![image](https://cloud.githubusercontent.com/assets/7683926/22163127/d90aaab2-df51-11e6-8245-648a4f8627ce.png)

v9:
![image](https://cloud.githubusercontent.com/assets/7683926/22163057/9dbf39f0-df51-11e6-94ca-8b3da9ddb32d.png)

**Comment by StefanRijnhart** [comment]
Closing as @pedrobaeza's fix was merged.
