### ISSUE TITLE
[9.0][account_voucher] No link between payments and invoices in migrated account.payment records

### ISSUE THREAD

**Issue by JordiBForgeFlow** [OCA/OpenUpgrade#744]
Impacted versions: 9.0

Steps to reproduce:
In 8.0, with module 'account_voucher' installed, create a payment for an invoice using a voucher.

Current behavior:
When the database is migrated the field invoice_ids of account.payment is empty

Expected behavior:
The migration script of 'account_voucher' should include a routine to migrate the table `account_invoice_payment_rel`

**Comment by JordiBForgeFlow** [comment]
@NL66278 I need your help on this one.

**Comment by NL66278** [comment]
@jbeficent I hope to be able to do this next week.

**Comment by NL66278** [comment]
@jbeficent Should be working with this PR: https://github.com/OCA/OpenUpgrade/pull/762

**Comment by JordiBForgeFlow** [comment]
Thanks!! Will test right now

**Comment by pedrobaeza** [comment]
Closing as the PR was merged.
