### ISSUE TITLE
Migrate Odoo v9 to v10 - enhancement

### ISSUE THREAD

**Issue by ArthurBorsboom** [OCA/OpenUpgrade#751]
Is there an automated upgrade script available or in a Work in Progress for Odoo v9 to v10?

**Comment by pedrobaeza** [comment]
No, there isn't any progress on v10 migration yet

**Comment by ArthurBorsboom** [comment]
That is shame. Any future plans?

**Comment by pedrobaeza** [comment]
Well, as soon as someone start contributing or any other open initiative, but nothing defined.

**Comment by ArthurBorsboom** [comment]
Got it. Thanks!
