### ISSUE TITLE
Migration odoo 8 to 9

### ISSUE THREAD

**Issue by camilozuluaga** [OCA/OpenUpgrade#761]
Hello friends, good day to all and in advance thanks for the attention paid.

What happens is the following I am doing the migration with the commands that are followed in the official guide of "open ugrade", the migration at data level is working correctly since the database is populated with such data, but at At the moment of installing modules I get the following xml error.

"2017-02-14 15:13:44,410 6748 INFO ghgh openerp.addons.base.ir.ir_translation: module account: loading translation file (es) for language es_ES
2017-02-14 15:13:44,440 6748 INFO ghgh openerp.tools.translate: loading C:\Program Files (x86)\Odoo 9.0-20160923\server\openerp\addons\account\i18n\es.po
2017-02-14 15:13:49,323 6748 INFO ghgh openerp.addons.base.ir.ir_ui_view: El elemento '<xpath expr="//div[@name='buttons']">' no puede ser localizado en la vista padre

Error de contexto:
Vista `partner.view.button.journal_item_count`
[view_id: 492, xml_id: account.partner_view_button_journal_item_count, model: res.partner, parent_id: 126]".

I would like to know what can be done there, or how can I solve the problem.

I hope to have a timely response.
<img width="942" alt="d" src="https://cloud.githubusercontent.com/assets/2817796/22939445/b1b72be8-f2ac-11e6-8f3c-8f722656912b.PNG">

**Comment by legalsylvain** [comment]
Could you try to make an update all (with a no openupgrade version = Odoo or OCB) before installing new module ? i guess it should solve your problem.

**Comment by camilozuluaga** [comment]
Friend you can give me a training to do this, the training will be for and is to help us with the migration.

**Comment by ovnicraft** [comment]
@legalsylvain i have the same issuea after migration i run -u all, but i dont get it when you say: (with a no openupgrade version = Odoo or OCB)
