### ISSUE TITLE
 Training migration odoo 8 to odoo 9

### ISSUE THREAD

**Issue by camilozuluaga** [OCA/OpenUpgrade#763]
Hello friends, good morning, I would like to know who knows about the topic to do the migration of odoo v8 to v9, is to hire a consultant group of developers who need someone with experience to do so many thanks. If you are interested leave me your data. Or something we can contact.

**Comment by ldibarbora** [comment]
Hello Juan , i'm a consultant in a software company with focus in Odoo
development, also we are Odoo partners . We have experience in migration
projects from OpenERP 7 to Odoo 9.
  If you are interested contact our sale and technical representative:
hernanbroun@elepeservicios.com.ar.

Regards

Ing. Leonardo Dibarbora
elepe servicios srlwww.elepeservicios.com.ar
Viamonte 638 2do. Piso Of. B
2000 - Rosario - Argentina
Te./Fax: (0054-341) 4853806


2017-02-15 18:44 GMT-03:00 juan camilo zuluaga serna <
notifications@github.com>:
