### ISSUE TITLE
[9.0] operations not created for pickings where qty has been reserved but not transferred

### ISSUE THREAD

**Issue by JordiBForgeFlow** [OCA/OpenUpgrade#765]
Impacted versions: 9.0

Steps to reproduce:
In 8.0
* Install module 'stock'
* Create a delivery order, and ensure availability to transfer, but do not transfer yet

![image](https://cloud.githubusercontent.com/assets/7683926/23074183/5672ef36-f538-11e6-9e1c-9c0ef1de5f7e.png)
* Migrate to v9

Current behavior:
After the migration the  operations are not created:
![image](https://cloud.githubusercontent.com/assets/7683926/23074206/6d3afccc-f538-11e6-91ff-9aeea226777e.png)

Only after the user presses the button 'Recompute' in the picking will it re-create the operations.
![image](https://cloud.githubusercontent.com/assets/7683926/23074248/9bf82080-f538-11e6-9df8-d59ce54f94b0.png)

Expected behavior:

The migration script should create all operations, so that the target state does not require any further manual action from the user.

**Comment by pedrobaeza** [comment]
Closing as there's a PR solving it: #766
