### ISSUE TITLE
[8.0] Share module should warn about users previously not in share group

### ISSUE THREAD

**Issue by StefanRijnhart** [OCA/OpenUpgrade#77]
Something interesting changed in the share module. The share group is not a manual setting anymore, but consists in 8.0 of every user that is not in base.group_user.

It would be nice if the migration scripts for the share module could warn about users that are not in the share group in 7.0 but not in group_user either.

**Comment by legalsylvain** [comment]
Agree.

**Comment by pedrobaeza** [comment]
Any news about this?

**Comment by StefanRijnhart** [comment]
Nope ;-)

**Comment by pedrobaeza** [comment]
Closing as this one is not too much relevant nowadays and there's no PR.
