### ISSUE TITLE
Access Error when sending message to other Odoo user (8 -> 9)

### ISSUE THREAD

**Issue by mgielissen** [OCA/OpenUpgrade#774]
After upgrading from 8 to 9 this error pops up when sending a message to another Odoo user with the chatbox. 

Steps to reproduce:

- Choose New Message on topmenu
- Type a letter in To: field
- Click on a name

```
The requested operation cannot be completed due to security restrictions. Please contact your system administrator.

(Document type: mail.channel, Operation: read) 
```

**Comment by pedrobaeza** [comment]
This is fixed here: https://github.com/OCA/OpenUpgrade/pull/797

**Comment by mgielissen** [comment]
Thanks, To fix a already migrated database:

Remove (double entry) "Mail.group: access only public and joined groups" under Settings/Record Rules
