### ISSUE TITLE
after restoring database that was migrated from version 8 to 9 the web login paged had an error

### ISSUE THREAD

**Issue by Dager7** [OCA/OpenUpgrade#778]
Impacted versions: 9.0

Steps to reproduce:
 1. use migration script to migrate fro version 8 of odoo to version 9
 2. dump the migrated database using this code  
      pg_dump --no-owner --format=custom DBNAME > newdbname.dump
 3. restore db.dump file on odoo 9
Current behavior:
unable to login
Expected behavior:
the web login should be operational 
Video/Screenshot link (optional):
![zxcorp login error](https://cloud.githubusercontent.com/assets/26226807/24016681/06e23b86-0a85-11e7-989e-aa52b2599826.png)
![zxcorp server errors shown in ubuntu terminal](https://cloud.githubusercontent.com/assets/26226807/24016891/c066501a-0a85-11e7-854a-79c6b0a3ed1b.png)
![zxcorp server errors shown in ubuntu terminal2](https://cloud.githubusercontent.com/assets/26226807/24016890/c0642da8-0a85-11e7-9d60-62e09c14b7d4.png)
![zxcorp server errors shown in ubuntu terminal3](https://cloud.githubusercontent.com/assets/26226807/24016892/c066b5be-0a85-11e7-9da9-19cadbac93d5.png)

![zxcorp server errors shown in ubuntu terminal4](https://cloud.githubusercontent.com/assets/26226807/24017060/7547f02e-0a86-11e7-957c-2380dcf98438.png)
![zxcorp server errors shown in ubuntu terminal5](https://cloud.githubusercontent.com/assets/26226807/24017058/75445900-0a86-11e7-8462-c441e27c694e.png)
![zxcorp server errors shown in ubuntu terminal6](https://cloud.githubusercontent.com/assets/26226807/24017059/754490f0-0a86-11e7-9b2c-4165a1576bcd.png)

**Comment by pedrobaeza** [comment]
For sure something was not correct on the migration or the environment you have set, but this is not an issue itself. Please check logs and if you have a real specific issue, create a new one talking about it.
