### ISSUE TITLE
[9.0] Partner, Product, HR_Employee images was lost

### ISSUE THREAD

**Issue by cewolf2002** [OCA/OpenUpgrade#781]
Hi, all.
I installed latest openupgrade and openupgradelib.
After migrating our database from 8.0 to 9.0.
I noticed Partner, Product, HR_Employee images was lost.

This pull request should resolved this issue.
https://github.com/OCA/OpenUpgrade/pull/745/files

But I checked
column image, image_medium, image_small was not found in Product_Template , hr_employee, res_partner

How should I solve this issue?

**Comment by pedrobaeza** [comment]
This is already solved, so you shouldn't have latest code.
