### ISSUE TITLE
CAN SOMEONE PLEASE PROVIDE A CLEAR EXPLANATION

### ISSUE THREAD

**Issue by Dager7** [OCA/OpenUpgrade#787]
I want to migrate from odoo 8 to odoo 9
Do i just run the migrate.py script? Because that didn't seem to work although i did not receive any errors.

After running migrate.py i made a dump of the _migrated database then tried to restore on odoo 9 
PLEASE HELP.  -_____-
![restore_error](https://cloud.githubusercontent.com/assets/26226807/24570226/49006bd0-1662-11e7-9918-33740a70238f.png)

**Comment by pedrobaeza** [comment]
Sorry, but this is for notifying issues, not to ask for help. See the documentation (https://doc.therp.nl/openupgrade/) or experiment by yourself with enough Odoo knowledge.
