### ISSUE TITLE
logged_query function call failing with TypeError

### ISSUE THREAD

**Issue by red15** [OCA/OpenUpgrade#79]
It seems I'm having an error when it's trying to convert the project priorities.

The call to logged_query I have has these arguments:

```
query = "UPDATE project_task SET priority = %(new)s WHERE openupgrade_legacy_8_0_priority = %(old)s"
args = {'table': 'project_task', 'old': '4', 'target': 'priority', 'new': '0', 'source': 'openupgrade_legacy_8_0_priority'}
```

Then I get a TypeError on the log.debug()

https://github.com/OpenUpgrade/OpenUpgrade/blob/8.0/openerp/openupgrade/openupgrade.py#L409

Which contains:

```
cr.execute(query, args)
logger.debug('Running %s', query % tuple(args))
logger.debug('%s rows affected', cr.rowcount)
return cr.rowcount
```

Which I can totally understand because tuple() on a dict only returns the key values.
Should we not instead simply be calling

```
cr.execute(query, args)
logger.debug('Running %s', query % args)
logger.debug('%s rows affected', cr.rowcount)
return cr.rowcount
```

Or am I totally missing out on something here ? Changing this seemed to fix my problem, I have not ran another full migration with it though.

**Comment by red15** [comment]
Fixing this myself in https://github.com/Bubbles-IT/OpenUpgrade/tree/8.0-project expect a pull request soon.

**Comment by StefanRijnhart** [comment]
Closing this as your fix for this has been merged some time ago.
