### ISSUE TITLE
[9.0] [account] Migration of taxes in account move lines

### ISSUE THREAD

**Issue by JordiBForgeFlow** [OCA/OpenUpgrade#806]
The migration scripts currently do not consider the migration of the taxes. I had to to a post migration fix for a customer, but still needs to be adjusted in the migration script.

**Comment by pedrobaeza** [comment]
I'm going to develop this gap

**Comment by pedrobaeza** [comment]
@jbeficent please validate the PR for merging it and close this issue.

**Comment by pedrobaeza** [comment]
We can close this one after the merging.
