### ISSUE TITLE
Published documentation not correct

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/OpenUpgrade#807]
If you go to https://doc.therp.nl/openupgrade/modules80-90.html, there isn't any list. This should be due to an incorrect linking of all pages.

**Comment by pedrobaeza** [comment]
Is there any solution for this then?

**Comment by hbrunn** [comment]
https://github.com/OCA/OpenUpgrade/pull/810 - we just need to merge this and I have to update the generation script on our server afterwards
