### ISSUE TITLE
Possibly the dumbest question ever - order of running migration/restoring db

### ISSUE THREAD

**Issue by bigmillz** [OCA/OpenUpgrade#818]
Impacted versions: 10.0

Steps to reproduce:
1. Setup Openupgrade per instructions
2. Run migrate.py script
3.???

Hi everyone - I'm stuck on the most basic thing ever. Do I restore my 9.0 db into Odoo 10.0 and then run migrate.py on it, or do I run migrate.py on the dump file and then restore into Odoo?

Because I tried running migrate.py on the .zip (and .sql) files, and it won't take them under the database= parameter. However, Odoo 10.0 won't accept my 9.0 file, and thus I can't pass the name of the unrestored db to migrate.py.

Thanks :)

**Comment by hbrunn** [comment]
0. read the [documentation](https://doc.therp.nl/openupgrade/) which is pointed to at several places, try things, and ask questions with a description of what you tried, what you expected and what the error messages are.
But from the way you phrase this I think you should hire somebody.
