### ISSUE TITLE
procurement / wms migration

### ISSUE THREAD

**Issue by gurneyalex** [OCA/OpenUpgrade#82]
I'm creating an issue for this for traceability. 

I started doing preliminary work on procurement during the code sprint (https://github.com/gurneyalex/OpenUpgrade/compare/procurement_v8). Ongoing project is currently preventing me from working on this topic, and I'll be on vacation during most of July. 

I hope I'll be able to resume work on this issue in August, but if someone else wishes to move on, please do so.

**Comment by diellenne** [comment]
Hi,

we are going to finish the implementation of the scripts for 'product' and 'procurement'.
if all goes as planned we should finish before august 2014.

Regards.

**Comment by pegonzalezs** [comment]
Hi @gurneyalex,

first of all thank you for your work. What do you think about the note (Internal Notes) field?. We think that it could be added at the end of the External Note (name). Putting in between a slash or some small string.

Did you already think about it?.
Thank you.

**Comment by StefanRijnhart** [comment]
After a long journey, procurement is now for review in #121. Closing this issue.
