### ISSUE TITLE
Migration Buildout Error on second step 

### ISSUE THREAD

**Issue by lord-enzo** [OCA/OpenUpgrade#827]
Impacted versions: 9.0

Steps to reproduce: When using the buildout to get to v10.0, on the second step: `bin/buildout

Current behavior: scripts throws an error:

```
fatal: Couldn't find remote ref 9.0-base
While:
  Installing openupgrade9.
Unexpected end of command stream
```
[...]
```
CalledProcessError: Command '['git', 'pull', '--no-edit', 'https://github.com/microcom/openupgrade.git', '9.0-base']' returned non-zero exit status 1
```

Expected behavior: Finishing to get to the next step

**Comment by pedrobaeza** [comment]
Buildout is not a supported method (it was only a test). Anyway, the error is clear: that branch is not correct as it was only a test (9.0-base).

**Comment by lord-enzo** [comment]
So, I guess there's no way to migrate to 10.0? I can't find any other way...

**Comment by pedrobaeza** [comment]
Yes, there is. Just run the OU server with the -u all switch.

**Comment by pedrobaeza** [comment]
And check if the modules are covered. Anyway, this is not something easy to perform to any non-experienced Odoo integrator.
