### ISSUE TITLE
Error migrating 8.0->9.0

### ISSUE THREAD

**Issue by ovnicraft** [OCA/OpenUpgrade#835]
Impacted versions:
9.0

Steps to reproduce:
After run migrate.py without output errors
Run odoo.py with addons-path, -d migrated_db -u all

Current behavior:
Error: https://gist.github.com/ovnicraft/af052ccb85fe1baff00aa94288bace28

Expected behavior:
Update module

**Comment by pedrobaeza** [comment]
What I see is that you have modified website views and now they don't load. My advise:

Change all the website views to noupdate=0 for doing the migration.

**Comment by ovnicraft** [comment]
All my modules has install: False, so if you see the xml in load is from website module, so i will try your advice.
