### ISSUE TITLE
ONESTEiN Contribution

### ISSUE THREAD

**Issue by diellenne** [OCA/OpenUpgrade#84]
In order to accelerate the development and increase the coverage of OpenUpgrade v8 in the next few days our team will start to contribute to the project: in particular, we would like to complete as soon as possible the following modules:
- account
- delivery
- mail
- mrp
- portal
- portal_sale
- procurement
- product
- purchase
- report_intrastat
- sale
- sale_stock
- stock

Concerning the modules that are already in progress, we would like to hear from everyone who is actually working on these in order to share the missing work; for the others I will update the wikipage with our planning as soon as possible.

**Comment by legalsylvain** [comment]
Hi, 

Glad to see that you're interested by this project. Yes, the wiki is not very up to date. Com' on guys, plz update the list with the current state! (@arthru, ccomb, c2c, @StefanRijnhart, ...)

Do you have some questions about how OpenUpgrade works, or how to contribute ?
Don't hesitate to ask.

About the list of your module you want to cover, the most important work is in 'stock & co' for the 7.0 -> 8.0 migration. Plz, see this post #82  and contact Alexandre if you want more information about the changes.

Regards.

**Comment by diellenne** [comment]
Thank you,

about OpenUpgrade we know how to use it. We started migrating some small modules and we felt quite comfortable with the process.

About the contribution, as ONESTEiN we are now starting to be involved in the effective contribution to the Odoo ecosystem; for now we forked the OpenUpgrade project and we are going to take it as a basis to start working on the missing modules; so we will make our pull-requests to merge the code in the 'official' OpenUpgrade from our fork. For all the information related to the progress and the technical discussions we will refer directly to the pages of the main project. Do you think that might be a good way to work? 

Regards,
D

**Comment by diellenne** [comment]
Hi,

I updated the 'planned migrations' wikipage with the modules that we are going to migrate by september 2014.

@legalsylvain: I saw that for some of these you had already planned the migration for 2015 ... I reinserted them in the table assigned to us but, if you want to collaborate, we would be glad to work with you in the implementation of the scripts. 

Regards.

**Comment by plaes** [comment]
@diellenne Will you have a public branch of your efforts? I would really like to cooperate with `mrp` and `stock` modules.

**Comment by diellenne** [comment]
@plaes I'm glad that you want to cooperate with us to improve OpenUpgrade faster. We landed on GitHub as onseteinbv just from a little so we are trying to organize our repositories in the best way to share our work.
Right now if you want to work with us we have our OpenUpgrade fork (https://github.com/onesteinbv/OpenUpgrade) and we are implementing the scrips for procurement and stock on the branch stock-v8-migration; If for you is ok you could fork it and start working with our team on stock or independetly on mrp...What do you think about? 

Gr,
D

**Comment by plaes** [comment]
I've yet to figure out the way to get the analyze part running successfully, failing in the 
_Generate Records_ part with cryptic `duplicate tax code error`.

And my current migration efforts fail with following error:

```
openerp.sql_db: Programming error: column stock_warehouse.mto_pull_id does not exist
LINE 1: SELECT stock_warehouse."mto_pull_id",stock_warehouse."code",...
               ^
, in query SELECT stock_warehouse."mto_pull_id",stock_warehouse."code",stock_warehouse."lot_stock_id",stock_warehouse."default_resupply_wh_id",stock_warehouse."wh_pack_stock_loc_id",stock_warehouse."pack_type_id",stock_warehouse."reception_route_id",stock_warehouse."pick_type_id",stock_warehouse."crossdock_route_id",stock_warehouse."delivery_route_id",stock_warehouse."partner_id",stock_warehouse."name",stock_warehouse."wh_qc_stock_loc_id",stock_warehouse."wh_output_stock_loc_id",stock_warehouse."in_type_id",stock_warehouse."company_id",stock_warehouse."out_type_id",stock_warehouse."int_type_id",stock_warehouse."wh_input_stock_loc_id",stock_warehouse."delivery_steps",stock_warehouse."reception_steps",stock_warehouse."view_location_id",stock_warehouse."resupply_from_wh",stock_warehouse.id FROM "stock_warehouse" WHERE stock_warehouse.id IN %s ORDER BY id
```

**Comment by pankk** [comment]
@plaes It seems the problem lies with the function that sets the default for location_id. As a temporary work-around you could set the value in the _defaults dict for location_id in stock_inventory to False.

**Comment by plaes** [comment]
OK, after a somewhat long hiatus, I got some work done in my https://github.com/plaes/OpenUpgrade/commits/wip-mrp branch which is based on onestein's stock migration branch. It will be rebased and I'll probably amend the 'Various hacks...' commit when need arises.

**Comment by diellenne** [comment]
Hi @plaes , @pankk has completed your work on 'mrp' on our fork (https://github.com/onesteinbv/OpenUpgrade) in the brach os-dev.
In that branch there are also the migration scripts for the module that we proposed to work on https://github.com/OpenUpgrade/OpenUpgrade/wiki/Planned-migrations.

**Comment by plaes** [comment]
Yup, I saw that..

How do you guys handle the broken xml stuff (views, model and field data) which is stored in the database? This part is still real magic for me, though I tried to write a small script (pull #91) to detect some of the discrepancies.

**Comment by pankk** [comment]
@plaes This differs; in depth functional knowledge is required to see what should be done with the data.

**Comment by ghost** [comment]
Hello, my name is Ronald Rubí and I am team manager in ClearCorp (Costa Rica).
We have begun to use the branch of OpenUpgrade, however some modules like 'stock' not are in oficial version. Reviewing this issue, we see that you are working on this, so I would like to know the status of it. We are ready to collaborate on this project.

**Comment by pedrobaeza** [comment]
Hi, Ronald, you can check current PRs (pull requests) - https://github.com/OpenUpgrade/OpenUpgrade/pulls - to review them, or create a new one with the migration scripts you have done. Currently, there is a proposition for stock module migration here: https://github.com/OpenUpgrade/OpenUpgrade/pull/125.

**Comment by ghost** [comment]
Thanks, Pedro!

**Comment by diellenne** [comment]
Hi everybody!
Just want to say that I'm sorry to not been so active in the review of our work during the last weeks...it was a really busy period for us.
In the next days I will be travelling so I will not be really active, but my colleague @pankk will reserve some time to help you and try to speed up the merging.

Cheers!

**Comment by pedrobaeza** [comment]
Thanks, Diego. Any help will be welcome.

Regards.

**Comment by StefanRijnhart** [comment]
Currently working on review and test. I'm closing this chit chat now ;-)
