### ISSUE TITLE
Travis misbehaving on PR's

### ISSUE THREAD

**Issue by NL66278** [OCA/OpenUpgrade#852]
I notice Travis loading non existing files (not existing in 10.0) and giving errors. No idea what is going on...

**Comment by hbrunn** [comment]
can you link which lines in travis you mean?

**Comment by pedrobaeza** [comment]
This is what I have pointed out that $TRAVIS_COMMIT variable is not correct on rebasing or forced push operations. The only solution is to close the PR and open again for having Travis correctly informed.
