### ISSUE TITLE
Where is branch 7.0?

### ISSUE THREAD

**Issue by dreispt** [OCA/OpenUpgrade#89]
My local repo tell me there was a 7.0 branch:

```
a4605f1 Merge pull request #23 from hbrunn/7.0-lp1311076
```

But I can't find it in the branch list.

**Comment by pedrobaeza** [comment]
I think it was in the project, but then it was removed to keep it at Launchpad. I think we can consider to bring it to GitHub too.

Regards.

**Comment by dreispt** [comment]
That's unexpected. Is there a reason for OpenUpgrade to branches to have a different setup from OCA ones? IMO it would be best to keep all branches either on LP or on GH.

**Comment by pedrobaeza** [comment]
Well, I don't know the exact reasons. Perhaps @StefanRijnhart can say.

**Comment by bwrsandman** [comment]
:+1: to bring all the branches over, I heard you can setup lp to fetch changes from github

**Comment by pedrobaeza** [comment]
Doing the tracking of the migration in #137, so I close this.
