### ISSUE TITLE
[9.0] Use of the environment doesn't work?

### ISSUE THREAD

**Issue by ecino** [OCA/OpenUpgrade#915]
Impacted versions: 9.0

Steps to reproduce: 
Make a migration script using @openupgrade.migrate(use_env=True) decorator
Call env.ref('module.xml_id') function or env['model'].search() and it doesn't work.

Current behavior:
For instance, calling `env['res.partner'].search([('ref', '=', '123')])`
{ValueError}Invalid field 'ref' in leaf "<osv.ExtendedLeaf: ('ref', '=', 'lsv') on res_partner (ctx: )>"

Expected behavior:
Find a res.partner record.

**Comment by hbrunn** [comment]
this report would belong into https://github.com/OCA/OpenUpgradelib, but this looks like a different problem. You should post more code on what you're doing, and at which state (pre/post migration) for which module

**Comment by ecino** [comment]
Oops, I didn't realize I post it on the wrong repo. Sorry, I will post it there.
