### ISSUE TITLE
[9.0] Could not get content for /im_chat/static/......

### ISSUE THREAD

**Issue by cor9003** [OCA/OpenUpgrade#931]
Hello, after migrated the verion 8 to 9 with script migration.py, after restore database migrated I can login in version 9.0 but  I get the following messages:

Could not get content for /im_chat/static/src/css/im_commons.css defined in bundle 'web_assets_backend'
Could not get content for /im_chat/static/src/css/im_chat.css defined in bundle 'web_assets_backend'
Could not get content for /web_grantt/static/src/css/grantt.css defined in bundle 'web_assets_backend'
Could not get content for /base_setup/static/src/css/base_setup.css defined in bundle 'web_assets_backend'
Could not get content for /web_graph/static/src/css/graph.css defined in bundle 'web_assets_backend'

Some are modules not longer used in 9.0
Also thought to use the database cleanup module but not have access to modules screen for this message in the top 

Any idea of to solve this ?

Thanks

**Comment by pedrobaeza** [comment]
Update all the modules with regular Odoo.

**Comment by imaralux** [comment]
Same issue here event after upgrading, even after upgrading with flag --update=all. The source database is blank, so it's basic case.

**Comment by imaralux** [comment]
Fixed as follows:
from psql command-line : UPDATE ir_module_module SET state = 'to remove' WHERE name = 'im_chat';
then launch with --update=all

**Comment by imaralux** [comment]
Easier option : Uninstall module im_chat from v8 BEFORE upgrade. That does the trick.
