### ISSUE TITLE
[10.0] error try to login on migrated db

### ISSUE THREAD

**Issue by ovnicraft** [OCA/OpenUpgrade#936]
Impacted versions: 10.0 

Steps to reproduce:

* Migrate db to 10.0
* Run `-u all`
* in browser, select db and enter user:passwd, enter

Current behavior:

https://gist.github.com/ovnicraft/93314eff1bf8f92e227e1d88d2919f49

Expected behavior:

render the  system

Video/Screenshot link (optional):

**Comment by ovnicraft** [comment]
This error is caused by im_odoo_support module view is not removed from db in migration process, i understand this caused by module was removed, any hint to include some migration method and delete the view ? @pedrobaeza

**Comment by pedrobaeza** [comment]
Use `update_module_names` method with merge_modules=True.
