### ISSUE TITLE
[0.8 to 0.9] Key (name)=(account_analytic_distribution) already exists.

### ISSUE THREAD

**Issue by fanha99** [OCA/OpenUpgrade#953]
Hi all,

I'm using migrate.py to upgrade my database from 8.0 to 9.0.

the script is force stop, and the final line in the log is:

odoo@ubuntu:~/odoo-dev$ tail -f /var/tmp/openupgrade/migration.log
    cr.execute(query, args)
  File "/var/tmp/openupgrade/9.0/server/openerp/sql_db.py", line 141, in wrapper
    return f(self, *args, **kwargs)
  File "/var/tmp/openupgrade/9.0/server/openerp/sql_db.py", line 220, in execute
    res = self._obj.execute(query, params)
IntegrityError: duplicate key value violates unique constraint "ir_module_module_name_uniq"
DETAIL:  Key (name)=(account_analytic_distribution) already exists.

what did I wrong? or I am missing any steps?

thanks for reading, regards

**Comment by pedrobaeza** [comment]
But that's because you already have a module in v8 with the name of `account_analytic_distribution`. Remove that module from the list in v8 and all will go correct.
