### ISSUE TITLE
Base core field 'sequence' for res.company error

### ISSUE THREAD

**Issue by ghost** [OCA/OpenUpgrade#963]
I migrated database using script from 8 to 10. and manual migrate all custom modules.
But when i try to login in migrated database it gives error that res.company has no field 'sequence'

I notice it is new field in odoo10 it is not exist in odoo 8.

Also i try from command line to upgrade base module but it gives error like 

Exception: Module loading base failed: file base/res/res.lang.csv could not be processed:
 duplicate key value violates unique constraint "res_lang_name_key"
DETAIL:  Key (name)=(Chinese (CN) / \u7b80\u4f53\u4e2d\u6587) already exists.

duplicate key value violates unique constraint "res_lang_name_key"
DETAIL:  Key (name)=(Chinese (TW) / \u6b63\u9ad4\u5b57) already exists.

duplicate key value violates unique constraint "res_lang_name_key"
DETAIL:  Key (name)=(Japanese / \u65e5\u672c\u8a9e) already exists.

duplicate key value violates unique constraint "res_lang_name_key"
DETAIL:  Key (name)=(Korean (KP) / \ud55c\uad6d\uc5b4 (KP)) already exists.

How to solve this ?

**Comment by pedrobaeza** [comment]
You need to solve the problems with the languages and then all it's supposed to go alright. That problem is because your languages doesn't have the correct XML-IDs in your old DB. You need to fix this, which is technical, but this is not supposed to be a non-technical tool.

**Comment by ghost** [comment]
But i am not manual added language record. its automatically generated when i added method from settings. how to correct it  ? can you please give me some idea.

Thanks.

**Comment by pedrobaeza** [comment]
Sorry, but this is not for teaching Odoo structure. I can quickly say you that XML-IDs are stores on ir.model.data table, but the rest it's up to you.
