### ISSUE TITLE
Error migrating to 8.0

### ISSUE THREAD

**Issue by ffurlanetto** [OCA/OpenUpgrade#97]
2014-08-26 11:13:04,144 16889 INFO ffurlanetto_migrated openerp.modules.loading: module base: loading base_data.xml
2014-08-26 11:13:04,329 16889 ERROR ffurlanetto_migrated openerp.addons.base.ir.ir_ui_view: Field `menu_id` does not exist

Error context:
View `res.users.groups`
[view_id: 159, xml_id: base.user_groups_view, model: res.users, parent_id: 156]
2014-08-26 11:13:04,397 16889 ERROR ffurlanetto_migrated openerp.addons.base.ir.ir_ui_view: Field `menu_id` does not exist

Error context:
View `res.users.groups`
[view_id: 159, xml_id: base.user_groups_view, model: res.users, parent_id: 156]

**Comment by ffurlanetto** [comment]
There is also related bugs in launchpad 
https://answers.launchpad.net/openupgrade-server/+question/253039
and severals messages about this issue (launchpad too)

**Comment by cysnake4713** [comment]
I have the same problem!!! do you find way to fix it?  @ffurlanetto

**Comment by lebanonsky** [comment]
I am stuck with this bug as well. The question in launchpad is closed, so I cannot see if some one has sovled the problem.

**Comment by legalsylvain** [comment]
Hi, 

Can you detail which modules was installed on your database V7 ? 

Regards.

**Comment by lebanonsky** [comment]
These are the modules I have in the migrated installation:
"base.module_mail" 
"base.module_project" 
"base.module_hr" 
"base.module_hr_timesheet" 
"base.module_hr_timesheet_sheet" 
"base.module_hr_holidays" 
"base.module_analytic" 
"base.module_auth_signup" 
"base.module_base" 
"base.module_base_action_rule" 
"base.module_base_calendar" 
"base.module_base_import" 
"base.module_base_setup" 
"base.module_base_status" 
"base.module_board" 
"base.module_decimal_precision" 
"base.module_document" 
"base.module_document_page" 
"base.module_email_template" 
"base.module_fetchmail" 
"base.module_hr_attendance" 
"base.module_hr_contract" 
"base.module_knowledge" 
"base.module_process" 
"base.module_product" 
"base.module_resource" 
"base.module_web" 
"base.module_web_calendar" 
"base.module_web_gantt" 
"base.module_web_graph" 
"base.module_web_kanban" 
"base.module_web_tests" 
"base.module_web_view_editor" 

But I tried also with clean install with demo data and even with out it. All came up with the same error.

**Comment by lebanonsky** [comment]
Markdown maybe ate some of the error code...

Field `menu_id` does not exist

Error context:
View `res.users.groups`
[view_id: 159, xml_id: base.user_groups_view, model: res.users, parent_id: 156]" while parsing /var/tmp/openupgrade/8.0/server/openerp/addons/base/base_data.xml:88, near

record id="group_portal" model="res.groups"
            field name="name" Portal /field
            field name="comment" Portal members have specific access rights (such as record rules and restricted menus).
                They usually do not belong to the usual OpenERP groups. /field
        /record

**Comment by NaScha** [comment]
I am facing the same problem when trying to migrate from v7 to v8. Any hints how to proceed?

**Comment by StefanRijnhart** [comment]
These entries are created in stock_data.yml which should be loaded during a succesful migration of the stock module. Note that the stock module is not covered yet by the leading 8.0 branch of OpenUpgrade. You can try to merge the proposal https://github.com/OpenUpgrade/OpenUpgrade/pull/94 in your tree and try again. In any case, check the log file for errors during the upgrade.

**Comment by lebanonsky** [comment]
Thank you for the advice. Applied the pull but still got the same error when trying to migrate a empty installation with NO extra modules installed.

**Comment by pankk** [comment]
A temporary(!) workaround is to change your openerp/addons/base/__openerp__.py and move the 'res/res_users_view.xml', in the data list to the top of the data list.

**Comment by lebanonsky** [comment]
thanks pankk - that cleared that error but ended up with a new one...

**Comment by NaScha** [comment]
Could anybody please post the git command to merge proposal #94 into the current 8.0 tree? Have not been so familiar with that yet...

**Comment by hbrunn** [comment]
Those errors should be fixed by #111
