### ISSUE TITLE
migrate.py - connect without password

### ISSUE THREAD

**Issue by ferdiga** [OCA/OpenUpgrade#98]
psycopg2 will connect using a Unix socket in the same manner as psql. 
When you specify a HOST, psycopg2 will connect with TCP/IP, which requires a password.

--- a/scripts/migrate.py
+++ b/scripts/migrate.py
@@ -20,6 +20,9 @@ def copy_database(conn_parms):
     db_new = '%s_migrated' % conn_parms['database']
     print('copying database %(db_old)s to %(db_new)s...' % {'db_old': db_old,
                                                             'db_new': db_new})
-    if conn_parms['host'] == 'False':
-    ....del conn_parms['host'] 
-    ....del conn_parms['port'] 
  
   conn = psycopg2.connect(**conn_parms)
   conn.set_isolation_level(psycopg2.extensions.ISOLATION_LEVEL_AUTOCOMMIT)
   cur = conn.cursor()

**Comment by ferdiga** [comment]
sorry I can not attach the patch and do not know yet to handle git

**Comment by legalsylvain** [comment]
Hi! 
Can you better do a Pull Request ? It will be more easy to review and to merge.
Regards.

**Comment by ferdiga** [comment]
done
