### ISSUE TITLE
Odoo looking for filestore files that never existed after 9->10 migration

### ISSUE THREAD

**Issue by bigmillz** [OCA/OpenUpgrade#983]
Impacted versions: 10.0

Steps to reproduce:
1. Migrated database from 9 to 10 successfully
2. Copied filestore from old 9 server to test 10 server
3. Ran Odoo 10, selected migrated db

Current behavior:
`odoo-server.log` showing several errors about missing filestore files such as:

```
IOError: [Errno 2] No such file or directory: u'/odoo/.local/share/Odoo/filestore/odoo-test/f3/f3f11e52a3ead336749157f46e1c8d8a07de8b61'
2017-07-31 18:42:10,936 1887 INFO odoo-test odoo.addons.base.ir.ir_attachment: _read_file reading /odoo/.local/share/Odoo/filestore/odoo-test/45/45$

```

**Comment by pedrobaeza** [comment]
This is because you haven't copied your v9 filestore first before starting the migration. It's not a problem of OpenUpgrade itself, but the way you perform the migration.

**Comment by sebastienhasa** [comment]
> This is because you haven't copied your v9 filestore first before starting the migration. It's not a problem of OpenUpgrade itself, but the way you perform the migration.

Do you need to import the filestore before doing migration or providing it with your migrated database is enough?
