### ISSUE TITLE
[10.0] error migrating stock module

### ISSUE THREAD

**Issue by ovnicraft** [OCA/OpenUpgrade#984]
Impacted versions: 10.0

Steps to reproduce:

run `odoo.py --addons-path=addons -u all -d db2migrate`

Current behavior:
Cant find data by ref
Error: https://gist.github.com/ovnicraft/4df61fade38bf7058cbb932af67a843d

Expected behavior:
Migration runs ok.

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
This is because you removed in your DB that picking type, which is expected to be found.

**Comment by ovnicraft** [comment]
Type when is loading gives duplicated key.

**Comment by pedrobaeza** [comment]
I don't think so if you did it well.
